star-whale/starwhale

- client/starwhale/api/_impl/service.py
- example/PennFudanPed/pfp/evaluator.py
> chore(example): model serving demo for pfp

- client/starwhale/api/_impl/service.py
- check if the `wait` function exists
- use async call
> chore(sdk): refine hijacked js when using gradio

- .gitignore
- README.md
- client/requirements-dev.txt
- example/datasets/sdk/dataset-sdk.ipynb
- code: https://colab.research.google.com/github/tianweidut/starwhale/blob/doc%2Fdataset-notebooks/example/datasets/sdk/dataset-sdk.ipynb
- run example:https://colab.research.google.com/drive/1xbLxRJwsZ1_gDO707cmSud9Up_huwah0
> example(dataset): add jupyter notebook for dataset sdk

- docs/sidebars.js
> chore(doc): add server admin config to sidebar

- server/controller/src/test/java/ai/starwhale/mlops/schedule/k8s/K8sJobTemplateTest.java
> fix(ci): remove useless import

- console/src/domain/model/components/CreateOnlineEvalForm.tsx
- console/src/domain/model/schemas/model.tsx
- console/src/domain/setting/components/FlatResourceSelector.tsx
- console/src/domain/setting/components/ResourceSelector.tsx
- console/src/i18n/locales.ts
- console/src/pages/Project/OnlineEval.tsx
relates to #1709
https://user-images.githubusercontent.com/3217223/212052341-a4048027-4869-4661-8c88-e55e6357e4d3.mp4
> feat(console): support resource request in online eval page

- console/package.json
- console/src/domain/model/components/CreateOnlineEvalForm.tsx
- console/src/pages/Project/OnlineEval.tsx
https://user-images.githubusercontent.com/3217223/212275541-e8fe1bc2-cd0a-4470-8a4d-6fbd72ca6cdb.mp4
> chore(console): support model switching in online eval

- docs/i18n/zh/docusaurus-plugin-content-docs/current/tutorials/nmt.md
> doc(example): fix wrong link addr in nmt

- example/cifar10/cifar/evaluator.py
> chore(example): serving handler for cifar10

- example/nmt/nmt/evaluator.py
> chore(example): serving handler for nmt

- example/text_cls_AG_NEWS/tcan/evaluator.py
> chore(example): serving handler for ag news

- docs/docs/img/examples/ucf101-eval.png
- docs/docs/tutorials/ucf101.md
- docs/i18n/zh/docusaurus-plugin-content-docs/current/tutorials/ucf101.md
- docs/sidebars.js
> chore(doc): add example doc for ucf101

- console/.eslintignore
- console/packages/starwhale-core/src/datastore/filter.ts
- console/packages/starwhale-core/src/datastore/hooks/useFetchDatastore.ts
- console/packages/starwhale-ui/src/GridTable/GridTable.tsx
- console/packages/starwhale-ui/src/GridTable/hooks/useDatastoreColumns.tsx
- console/packages/starwhale-ui/src/Search/FilterRenderer.tsx
- console/packages/starwhale-ui/src/Search/Search.tsx
- console/packages/starwhale-ui/src/Transfer/Transfer.tsx
- console/packages/starwhale-ui/src/base/data-table/config-query.tsx
- console/packages/starwhale-ui/src/base/data-table/data-custom-table.tsx
- console/packages/starwhale-ui/src/base/data-table/stateful-data-table.tsx
- console/src/domain/project/components/ProjectForm.tsx
- console/src/pages/Dataset/DatasetOverviewLayout.tsx
- console/src/pages/Dataset/DatasetVersionOverviewFiles.tsx
- console/src/pages/Evaluation/EvaluationListCard.tsx
- console/src/pages/Evaluation/EvaluationListCompare.tsx
- console/src/pages/Evaluation/EvaluationWidgetResults.tsx
- console/vite.config.ts
> fix(console): search bar be smoother, and bugs when sync config

- console/src/pages/Dataset/DatasetVersionOverviewFiles.tsx
> fix(console): dataset missing records

- .github/workflows/release.yml
Fix the broken release workflow: https://github.com/star-whale/starwhale/actions/runs/4041588527/jobs/6948310315
> fix(docker): fix release workflows when building console with gradio

- console/src/pages/Project/OnlineEval.tsx
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/ModelServingService.java
- server/controller/src/main/java/ai/starwhale/mlops/schedule/k8s/K8sJobTemplate.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/job/ModelServingServiceTest.java
- server/controller/src/test/java/ai/starwhale/mlops/schedule/k8s/K8sJobTemplateTest.java
- Fix the "Please fill in all fields" warning when `Advance` is not enabled in console.
- resource pool starts to take effect.
> chore(controller): online eval resource pool implementation

- server/controller/src/main/java/ai/starwhale/mlops/domain/model/ModelService.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/model/ModelServiceTest.java
file pull support using project id
> fix(controller): file pull support using project id

- server/controller/src/main/java/ai/starwhale/mlops/api/DatasetApi.java
- server/controller/src/main/java/ai/starwhale/mlops/api/EnvApi.java
- server/controller/src/main/java/ai/starwhale/mlops/api/EvaluationApi.java
- server/controller/src/main/java/ai/starwhale/mlops/api/JobApi.java
- server/controller/src/main/java/ai/starwhale/mlops/api/LogApi.java
- server/controller/src/main/java/ai/starwhale/mlops/api/ModelApi.java
- server/controller/src/main/java/ai/starwhale/mlops/api/ObjectStoreApi.java
- server/controller/src/main/java/ai/starwhale/mlops/api/PanelApi.java
- server/controller/src/main/java/ai/starwhale/mlops/api/ProjectApi.java
- server/controller/src/main/java/ai/starwhale/mlops/api/RuntimeApi.java
- server/controller/src/main/java/ai/starwhale/mlops/api/SystemApi.java
- server/controller/src/main/java/ai/starwhale/mlops/api/TrashApi.java
- server/controller/src/main/java/ai/starwhale/mlops/api/UserApi.java
> chore(controller): optimize swagger annotations of api

- docs/docs/tutorials/ag_news.md
- docs/i18n/zh/docusaurus-plugin-content-docs/current/tutorials/ag_news.md
- docs/i18n/zh/docusaurus-plugin-content-docs/current/tutorials/cifar10.md
- docs/i18n/zh/docusaurus-plugin-content-docs/current/tutorials/mnist.md
- docs/i18n/zh/docusaurus-plugin-content-docs/current/tutorials/nmt.md
- docs/i18n/zh/docusaurus-plugin-content-docs/current/tutorials/pfp.md
- docs/i18n/zh/docusaurus-plugin-content-docs/current/tutorials/speech.md
> chore(doc):update tutorials' doc

- README.md
- docs/docs/guides/install/helm-charts.md
- docs/docs/quickstart/on-premises.md
- docs/i18n/zh/docusaurus-plugin-content-docs/current/guides/install/helm-charts.md
- docs/i18n/zh/docusaurus-plugin-content-docs/current/quickstart/on-premises.md
> doc(helm): update cloud install docs for docker registry

- client/.coveragerc
- client/starwhale/api/_impl/dataset/model.py
- client/starwhale/api/_impl/model.py
- client/starwhale/base/view.py
- client/starwhale/cli/board/board.py
- client/starwhale/cli/board/project_tree.py
- client/starwhale/cli/board/widgets.py
- client/starwhale/version.py
- client/tests/utils/test_common.py
> chore(client): tune import with TYPE_CHECKING flag

- example/datasets/sdk/dataset-sdk.ipynb
> example(dataset): modify jupyter example

- example/datasets/cityscapes/disparity/README.md
- example/datasets/cityscapes/disparity/dataset.py
- example/datasets/cityscapes/disparity/example.py
add cityscapes_disparity dataset
> (dataset): add cityscapes_disparity dataset

- client/tests/sdk/test_dataset.py
> chore(test): fix dataset test for unexpected .dataset_tmp dir in the code tree

- scripts/e2e_test/start_test.sh
remove proxy in E2E test before client test  temporarily to make e2e test pass
longrun solution https://github.com/star-whale/starwhale/issues/1820
> chore(test): remove proxy in E2E test before client test 

- server/checkstyle.xml
- server/controller/src/main/java/ai/starwhale/mlops/datastore/ColumnSchema.java
- server/controller/src/main/java/ai/starwhale/mlops/datastore/DataStore.java
- server/controller/src/main/java/ai/starwhale/mlops/datastore/DataStoreScanRequest.java
- server/controller/src/main/java/ai/starwhale/mlops/datastore/MemoryTable.java
- server/controller/src/main/java/ai/starwhale/mlops/datastore/RecordResult.java
- server/controller/src/main/java/ai/starwhale/mlops/datastore/TableSchema.java
- server/controller/src/main/java/ai/starwhale/mlops/datastore/impl/MemoryRecord.java
- server/controller/src/main/java/ai/starwhale/mlops/datastore/impl/MemoryTableImpl.java
- server/controller/src/main/java/ai/starwhale/mlops/datastore/parquet/SwParquetWriterBuilder.java
- server/controller/src/main/java/ai/starwhale/mlops/datastore/parquet/SwReadSupport.java
- server/controller/src/main/java/ai/starwhale/mlops/datastore/parquet/SwWriteSupport.java
- server/controller/src/main/protobuf/wal.proto
- server/controller/src/test/java/ai/starwhale/mlops/datastore/TableSchemaTest.java
- server/controller/src/test/java/ai/starwhale/mlops/datastore/impl/MemoryTableImplTest.java
- server/controller/src/test/java/ai/starwhale/mlops/datastore/parquet/ParquetReadWriteTest.java
> feat(datestore): naive version implementation, add records timestamp

- client/starwhale/cli/__init__.py
- client/starwhale/cli/assistance/broker.py
- client/starwhale/cli/assistance/cli.py
- client/starwhale/cli/assistance/common.py
- client/starwhale/cli/assistance/host.py
- client/starwhale/cli/assistance/remote.py
- client/tests/cli/assistance/test_broker.py
- client/tests/cli/assistance/test_common.py
- client/tests/cli/assistance/test_host.py
- client/tests/cli/assistance/test_remote.py
> feat(client): support remote assistance

- server/controller/src/main/java/ai/starwhale/mlops/schedule/k8s/K8sClient.java
- server/controller/src/main/java/ai/starwhale/mlops/schedule/k8s/ResourceEventHolder.java
- server/controller/src/main/resources/application.yaml
- server/controller/src/test/java/ai/starwhale/mlops/schedule/k8s/ResourceEventHolderTest.java
Support collecting resource events
- Pod
- Deployment
- Job
- Statefulset
> feat(controller): support collecting resource events

- example/transformer/cifar100/README.md
- example/transformer/cifar100/code/evaluator.py
- example/transformer/cifar100/download_model.py
- example/transformer/cifar100/model.yaml
- example/transformer/cifar100/requirements.txt
add hugging face transformer Ahmed9275/Vit-Cifar100 example
> example(model): add hugging face transformer Ahmed9275/Vit-Cifar100 example

- client/starwhale/core/dataset/type.py
- client/tests/sdk/test_dataset.py
- example/datasets/kitti/object_bird/README.md
- example/datasets/kitti/object_bird/dataset.py
- example/datasets/kitti/object_bird/example.py
- example/datasets/kitti/object_bird/requirements.txt
add kitti-object-birds dataset example
> example(dataset): add kitti-object-birds dataset example

- client/starwhale/api/_impl/data_store.py
- client/starwhale/api/_impl/wrapper.py
- client/starwhale/core/dataset/copy.py
- client/tests/core/test_eval.py
- client/tests/sdk/test_data_store.py
- client/tests/sdk/test_dataset.py
- client/tests/sdk/test_dataset_sdk.py
- client/tests/sdk/test_loader.py
- client/tests/sdk/test_wrapper.py
- server/controller/src/main/java/ai/starwhale/mlops/domain/dataset/index/datastore/DataStoreTableNameHelper.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/dataset/upload/DatasetUploader.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/model/ModelService.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/runtime/RuntimeService.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/storage/StoragePathCoordinator.java
- server/controller/src/test/java/ai/starwhale/mlops/JobMockHolder.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/model/ModelServiceTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/storage/StoragePathCoordinatorTest.java
1. closes #1808 
2. fix wrong storage path
> fix(controller):unified paths to use project id

- console/packages/starwhale-core/src/datastore/hooks/useFetchDatastore.ts
- console/packages/starwhale-core/src/store/store.ts
- console/packages/starwhale-core/src/widget/withWidgetDynamicProps.tsx
- console/packages/starwhale-ui/src/GridTable/GridTable.tsx
- console/packages/starwhale-ui/src/GridTable/types.ts
- console/packages/starwhale-ui/src/Search/FilterRenderer.tsx
- console/packages/starwhale-ui/src/base/data-table/inner-table-element.tsx
- console/packages/starwhale-ui/src/base/data-table/stateful-data-table.tsx
- console/packages/starwhale-ui/src/base/data-table/store.ts
- console/packages/starwhale-ui/src/base/data-table/types.tsx
- console/packages/starwhale-ui/src/base/data-table/view/useCurrentView.tsx
- console/packages/starwhale-widgets/src/PanelTableWidget/component/Table.tsx
- console/packages/starwhale-widgets/src/PanelTableWidget/index.tsx
- console/src/pages/Evaluation/EvaluationListCard.tsx
- console/src/pages/Evaluation/EvaluationWidgetResults.tsx
* all runs with full columns showing status update
* optimize summary ui
> update(console): add panel query api, optimize in view load status

- client/starwhale/cli/assistance/Dockerfile
> chore(client): Add Dockerfile for assistance broker

- console/packages/starwhale-core/src/datastore/hooks/useDatastoreTables.tsx
- console/src/components/Editor/index.tsx
- console/src/pages/Evaluation/EvaluationListCard.tsx
- console/src/pages/Evaluation/EvaluationResults.tsx
- console/src/pages/Evaluation/EvaluationWidgetResults.tsx
- console/src/pages/Model/ModelOverviewLayout.tsx
> update(console): use projectId for table query

- console/src/components/Viewer/ImageViewer.tsx
> fix(console): image data empty when cros error

- scripts/e2e_test/start_test.sh
> chore(e2e): ignore controller service check command non-zero exit for e2e script

- example/ucf101/Makefile
> fix(example): fix make error

- console/src/components/Viewer/ImageViewer.tsx
> fix(console): support dataset without shape attribute

- scripts/publish/image_sync.sh
- docker-registry.starwhale.cn  tag list: https://docker-registry.starwhale.cn/v2/star-whale/starwhale/tags/list
> bug(release): add cuda11.5 into the docker image sync list

- example/notebooks/quickstart-standalone.ipynb
> chore(example): add COLUMNS env for eval output in the jupyter notebook

- console/package.json
- console/packages/starwhale-ui/src/AutoResizer/GridResizer.tsx
- console/packages/starwhale-ui/src/base/data-table/view/useCurrentView.tsx
- console/src/components/Card/index.module.scss
- console/src/components/Card/index.tsx
- console/src/pages/Evaluation/EvaluationListCard.tsx
- console/vite.config.ts
- console/yarn.lock
> update(console): set wrapper height to make sure resizer not null

- docs/src/css/custom.scss
> update(docs): use default monospaced fonts

- console/src/domain/runtime/services/runtime.ts
Related to https://github.com/star-whale/starwhale/pull/1621/files#diff-5e98722277942e2c1292594f7717994c589c796bf138661afcd6dad91cee7fc1R165
> fix(console): update runtime version fetch param name

- README.md
- docs/docs/quickstart/standalone.md
- docs/i18n/zh/docusaurus-plugin-content-docs/current/quickstart/standalone.md
- example/notebooks/quickstart-standalone.ipynb
> chore(doc): tune git clone command in the docs

- server/controller/src/main/java/ai/starwhale/mlops/api/LogApi.java
> fix(controller): fix task offline emoji not show error

- docker/charts/README.md
- docker/charts/templates/controller-deployment.yaml
- docker/charts/values.minikube.cn.yaml
- docker/charts/values.minikube.global.yaml
- docker/charts/values.yaml
- docker/compose/compose.yaml
- docs/docs/guides/install/helm-charts.md
- docs/i18n/zh/docusaurus-plugin-content-docs/current/guides/install/helm-charts.md
- scripts/e2e_test/start_test.sh
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/split/JobSpliteratorEvaluation.java
- server/controller/src/main/resources/application.yaml
`taskSplitSize` argument is useless.
> chore(charts): remove useless taskSplitSize argument in charts

- server/controller/src/main/java/ai/starwhale/mlops/api/UserApi.java
- server/controller/src/main/java/ai/starwhale/mlops/api/UserController.java
- server/controller/src/main/java/ai/starwhale/mlops/api/protocol/user/RoleVo.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/project/ProjectService.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/user/UserService.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/user/bo/Role.java
- server/controller/src/test/java/ai/starwhale/mlops/api/UserControllerTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/project/ProjectServiceTest.java
> fix(controller): fix bug with getting current user roles & e2e

- server/controller/src/main/java/ai/starwhale/mlops/api/DatasetApi.java
- server/controller/src/main/java/ai/starwhale/mlops/api/JobApi.java
- server/controller/src/main/java/ai/starwhale/mlops/api/ModelApi.java
- server/controller/src/main/java/ai/starwhale/mlops/api/RuntimeApi.java
- server/controller/src/main/java/ai/starwhale/mlops/api/TrashApi.java
> chore(controller): add remove permission to project maintainer

- server/controller/src/main/java/ai/starwhale/mlops/domain/task/status/TaskStatus.java
- server/controller/src/main/java/ai/starwhale/mlops/reporting/ReportedTask.java
- server/controller/src/main/java/ai/starwhale/mlops/schedule/k8s/JobEventHandler.java
- server/controller/src/main/java/ai/starwhale/mlops/schedule/k8s/PodEventHandler.java
- server/controller/src/test/java/ai/starwhale/mlops/reporting/TaskStatusReceiverImpTest.java
- server/controller/src/test/java/ai/starwhale/mlops/schedule/k8s/JobEventHandlerTest.java
update job status accord with k8s spec
a fix for :
- https://github.com/star-whale/starwhale/issues/1881
- https://github.com/star-whale/starwhale/issues/1860
> fix(controller): update job status accord with k8s spec

- docker/Dockerfile.server
tune controller jvm max heap size
> fix(controller): tune controller jvm max heap size

- console/src/domain/job/schemas/task.tsx
- console/src/i18n/locales.ts
- console/src/pages/Job/JobTasks.tsx
- console/src/pages/Job/TaskListCard.tsx
- server/controller/src/main/java/ai/starwhale/mlops/api/protocol/task/TaskVo.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/step/mapper/StepMapper.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/task/TaskService.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/task/converter/TaskConverter.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/task/TaskConverterTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/task/TaskServiceTest.java
make task info on task page richer
> chore(controller): make task info on task page richer

- .github/workflows/docs.yaml
- .github/workflows/release.yml
- .gitignore
- docs/Makefile
- docs/docusaurus.config.js
- docs/i18n/zh/docusaurus-plugin-content-docs/current.json
depends on: https://github.com/star-whale/starwhale/pull/1864
related issue: https://github.com/star-whale/starwhale/issues/1384
> enhance(doc): support doc versioning

- console/packages/starwhale-ui/src/Viewer/ImageViewer.tsx
> fix(console): coco with _show control

- server/controller/src/main/java/ai/starwhale/mlops/domain/task/status/watchers/log/CancellableTaskLogK8sCollector.java
> fix(controller): realtime log gibberish

- server/controller/src/main/java/ai/starwhale/mlops/api/JobApi.java
- server/controller/src/main/java/ai/starwhale/mlops/api/JobController.java
- server/controller/src/main/java/ai/starwhale/mlops/api/protocol/job/RuntimeSuggestionVo.java
- server/controller/src/main/java/ai/starwhale/mlops/api/protocol/runtime/RuntimeVersionVo.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/RuntimeSuggestionService.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/runtime/converter/RuntimeVersionConverter.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/runtime/mapper/RuntimeVersionMapper.java
- server/controller/src/main/resources/db/migration/v0_3_2/V0_3_2_011__add_runtime_version_index.sql
- server/controller/src/test/java/ai/starwhale/mlops/api/JobControllerTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/job/RuntimeSuggestionServiceTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/runtime/mapper/RuntimeVersionMapperTest.java
Add `/job/suggestion/runtime` API for getting the suggestion runtime list
- response the last used runtime if the model version is set (prefer using the online eval version)
- response the latest runtime in the project otherwise
demo 
```bash
curl -s 'https://example.com/api/v1/job/suggestion/runtime?projectId=1' | jq
```
```json
{
"data": {
"runtimes": [
{
"id": "1",
"name": "pn2olwnom7cml3pc545744fg7pfcpbsl6rb4h4i4",
"tag": null,
"alias": "v1",
"meta": "artifacts:\n  dependencies:\n  - dependencies/requirements.txt\n  - dependencies/requirements-sw-lock.txt\n  files: []\n  runtime_yaml: runtime.yaml\n  wheels: []\nbase_image: ghcr.io/star-whale/starwhale:latest\nbuild:\n  os: Linux\n  sw_version: 0.0.0.dev0\nconfigs:\n  conda:\n    channels:\n …
```
> feat(controller): add runtime suggestion api

- console/packages/starwhale-ui/src/Button/Button.tsx
- console/src/i18n/locales.ts
- console/src/pages/Project/ProjectListCard.tsx
> feat(console): add name confirm before project remove

- console/packages/starwhale-ui/src/Viewer/TextViewer.tsx
> fix(console): show content directly in TextViewer

- docker/Makefile
> fix(docker): fix wrong base image of the server

- client/tests/sdk/test_loader.py
issues:
- https://github.com/star-whale/starwhale/actions/runs/4342147697/jobs/7582628881
- https://github.com/star-whale/starwhale/actions/runs/4360458815/jobs/7623387115
> chore(test): make dataset loader test stable on the unordered rows

- README.md
- client/starwhale/core/model/model.py
- client/tests/data/model.yaml
- client/tests/data/model/model.yaml
- docs/docs/guides/model.md
- docs/docs/tutorials/ag_news.md
- docs/docs/tutorials/cifar10.md
- docs/docs/tutorials/mnist.md
- docs/docs/tutorials/nmt.md
- docs/i18n/zh/docusaurus-plugin-content-docs/current/guides/model.md
- example/mnist/custom_model.yaml
- example/mnist/model.yaml
- scripts/example/model.yaml
depends on: https://github.com/star-whale/starwhale/pull/1906
> chore(client): remove useless config field in the model.yaml

- client/starwhale/core/model/model.py
- client/tests/data/model.yaml
- client/tests/data/model/model.yaml
- docs/docs/guides/model.md
- docs/docs/tutorials/ag_news.md
- docs/i18n/zh/docusaurus-plugin-content-docs/current/guides/model.md
Related PRs: 
- https://github.com/star-whale/starwhale/pull/1933
- https://github.com/star-whale/starwhale/pull/1906
For Starwhale Model Package:
- `run.exclude_pkg_data` -> `.swignore` file
- `run.pkg_data` -> Default includes all files
> chore(client): remove useless pkg_data/exclude_pkg_data field in the model.yaml

- .github/workflows/release.yml
related: https://github.com/star-whale/starwhale/actions/runs/4411284434/jobs/7729649620
> hotfix(doc): add tag for doc versioning

- .github/workflows/release.yml
> hotfix(doc): fix docs copy path typo

- .github/workflows/release.yml
> chore(doc): update doc release action for github pages publish

- server/controller/src/main/java/ai/starwhale/mlops/domain/system/agent/AgentCache.java
> fix(controller): agent save error when report empty node

- server/controller/src/main/resources/template/image-build.yaml
> chore(controller): rename cmd's tag in the image build job yaml

- client/starwhale/api/_impl/dataset/builder.py
- client/starwhale/api/_impl/dataset/loader.py
- client/starwhale/api/_impl/evaluation.py
- client/starwhale/core/dataset/model.py
- client/starwhale/core/dataset/tabular.py
- client/tests/core/test_dataset.py
- client/tests/sdk/test_dataset.py
- client/tests/sdk/test_evaluation.py
- client/tests/sdk/test_loader.py
- preorder pr: https://github.com/star-whale/starwhale/pull/1943
- refactor: replace `data` with `features`. Please review [b43b20](https://github.com/star-whale/starwhale/commit/b43b20c6ef5bd2c55250be4ec813fc75a502f4b5) commit. 
> chore(dataset): refactor TabularRow `data` to `features` field

- console/src/pages/Dataset/DatasetVersionListCard.tsx
> update(console): fix button ui

- console/packages/starwhale-core/src/widget/WidgetRenderTree.tsx
- console/packages/starwhale-core/src/widget/hooks/useRestoreState.tsx
- console/src/domain/model/services/modelVersion.ts
- console/src/pages/Evaluation/EvaluationWidgetResults.tsx
- It shows the default layout without any user custom settings or model-builtin setting
- It will show the user custom setting if exists
- It will not show the model-builtin setting when no user custom setting by default (TBD) @lijing-susan @weijie00123 
https://user-images.githubusercontent.com/3217223/225245638-1269d6e3-a4e2-44fa-8762-68bfacdeb488.mp4
> feat(console): support showing the model builtin layout

- console/packages/starwhale-widgets/src/PanelTableWidget/index.tsx
> fix(console): loop rerender when panel loading

- server/controller/src/main/java/ai/starwhale/mlops/api/ErrorController.java
- server/controller/src/main/java/ai/starwhale/mlops/configuration/ResourceConfiguration.java
- server/controller/src/main/java/ai/starwhale/mlops/configuration/security/AdminSecurityConfiguration.java
- server/controller/src/main/java/ai/starwhale/mlops/configuration/security/SecurityConfiguration.java
- server/controller/src/main/resources/application.yaml
link issue: https://github.com/codecentric/spring-boot-admin/issues/1545
> fix(controller): admin server conflict with sw index page

- console/packages/starwhale-core/src/types/index.ts
- console/packages/starwhale-core/src/widget/WidgetRenderer.tsx
- console/src/domain/panel/utils.ts
- console/src/pages/Evaluation/EvaluationWidgetResults.tsx
demo config and the render result.
```json
{
"layouts": [
{
"title": "model builtin layout",
"panels": [
{
"title": "tables for datastore",
"charts": [
{
"type": "table",
"table": "confusion_matrix/binarylabel"
},
{
"type": "table",
"table": "results"
}
]
},
{
"title": "charts",
"height": "400",
"charts": [
{
"type": "roc_auc",
"table": "roc_auc/1",
"x": "tpr",
"y": "fpr",
"title": "roc auc for label 1"
},
{
"type": "confusion_matrix",
"table": "confusion_matrix/binarylabel",
"title": "confusion matrix"
}
]
}
]
}
]
}
```
> feat(console): support simplified version of layout settings

- client/starwhale/core/job/task.py
> fix(client): fix unclosed file warning in model eval

- server/controller/src/main/java/ai/starwhale/mlops/api/DataStoreController.java
- server/controller/src/main/java/ai/starwhale/mlops/datastore/DataStore.java
- server/controller/src/main/java/ai/starwhale/mlops/datastore/MemoryTable.java
- server/controller/src/main/java/ai/starwhale/mlops/datastore/impl/MemoryTableImpl.java
`update` api of data store returns the revision
> chore(controller): update api of data store returns the revision

- .github/workflows/docs.yaml
- .github/workflows/release.yml
related pr: https://github.com/star-whale/starwhale/pull/1862
> chore(doc): remove the useless keep_files config for doc release ci

- docs/docs/what-is-starwhale.md
- docs/docusaurus.config.js
- docs/i18n/zh/docusaurus-plugin-content-docs/current/what-is-starwhale.md
- docs/src/pages/index.js
> chore(docs): set what-is-starwhale's routing path to the root

- console/src/pages/BaseSubLayout.tsx
> fix(console): sidebar invisible in admin page

- client/starwhale/api/_impl/dataset/model.py
- client/tests/sdk/test_dataset_sdk.py
- depends on: https://github.com/star-whale/starwhale/pull/1973
- changes:  
- Depending on whether dataset commit or not, providing `uri`, `committed_version`, `changed` properties
- refactor the internal __core_dataset usage
> feat(dataset): provide `uri`, `committed_version`, `changed` properties for SDK Dataset

- client/starwhale/api/_impl/dataset/loader.py
- client/starwhale/api/_impl/dataset/model.py
- client/tests/sdk/test_dataset_sdk.py
- depends on: https://github.com/star-whale/starwhale/pull/1973
> chore(dataset):  sdk dataset head use internal data loader

- client/starwhale/api/_impl/dataset/model.py
- client/tests/sdk/test_dataset_sdk.py
- example/datasets/caltech_101/dataset.py
- example/datasets/celeba/dataset.py
- example/datasets/cityscapes/3dcarbox/dataset.py
- example/datasets/cityscapes/disparity/dataset.py
- example/datasets/cityscapes/fine/dataset.py
- example/datasets/cityscapes/person_bbox/dataset.py
- example/datasets/country211/dataset.py
- example/datasets/culane/dataset.py
- example/datasets/dtd/dataset.py
- example/datasets/eurosat/dataset.py
- example/datasets/fer2013/dataset.py
- example/datasets/flickr8k/dataset.py
- example/datasets/gtsrb/dataset.py
- example/datasets/iNaturalist/dataset.py
- example/datasets/kitti/lane/dataset.py
- example/datasets/kitti/object_bird/dataset.py
- example/datasets/lfw/dataset.py
- example/datasets/oxfordIIITPet/dataset.py
- example/datasets/sbd/dataset.py
- example/datasets/sintel/dataset.py
- example/datasets/stanford_cars/dataset.py
- example/datasets/svhn/dataset.py
- example/datasets/wider_face/dataset.py
- depends on:  please commit [5038f4](https://github.com/star-whale/starwhale/pull/1998/commits/5038f4dc6d61f139b265c1bd5ab4eff562b82f4a)
- https://github.com/star-whale/starwhale/pull/1994 
- changes:
- remove dataset `create` argument in python sdk
- update dataset examples
> chore(dataset): remove dataset `create` argument in python sdk

- scripts/publish/image_sync.sh
use regctl to copy images which support multi arch. https://github.com/regclient/regclient/blob/main/docs/regctl.md#registry-commands
1. image sync: ![image](https://user-images.githubusercontent.com/24869618/227140043-89899cec-9504-4bbf-8ef7-1f3f6c52e097.png)
2. docker manifest inspect homepage-bj.intra.starwhale.ai:5000/star-whale/starwhale:0.2.2rc3 --insecure         
```json
{
"schemaVersion": 2,
"mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
"manifests": [
{
"mediaType": "application/vnd.docker.distribution.manifest.v2+json",
"size": 3043,
"digest": "sha256:127ce78a91221fde7e58a29b7ec2d03b676d078e612e1c42efc3abf51f87eef6",
"platform": {
"architecture": "arm64",
"os": "linux"
}
},
{
"mediaType": "application/vnd.docker.distribution.manifest.v2+json",
"size": …
```
> chore(script):support multi arch for image sync

- client/Makefile
- console/Makefile
Introduced by #2012
- Install required dev tools for building UI
- Add env to prevent oom when building js
> fix(client): install console related dev tool for building ui

- client/starwhale/api/_impl/data_store.py
> chore(client): batch put data store records

- console/package.json
- console/packages/starwhale-ui/src/base/data-table/store.ts
- console/packages/starwhale-ui/src/base/data-table/types.tsx
- console/packages/starwhale-ui/src/base/data-table/view/useCurrentView.tsx
- console/src/domain/job/components/JobStatus.tsx
- console/src/domain/panel/utils.ts
- console/src/i18n/locales.ts
- console/src/pages/Evaluation/EvaluationListCard.tsx
- console/src/pages/Evaluation/EvaluationListCompare.tsx
- console/src/pages/Evaluation/EvaluationWidgetResults.tsx
- docker/Makefile
Fix the issue where the UCF video type cannot be displayed due to an error.
Add "status" label UI to the evaluation list and details.
Fix the issue where the table in the panel does not display after a query.
Fix the deployment script.
> fix(console): UCF video display error, add status label UI to evaluation, display table after query in panel, and fix deployment script.

- client/starwhale/api/_impl/data_store.py
- client/tests/sdk/test_data_store.py
- client/tests/sdk/test_dataset.py
- client/tests/sdk/test_dataset_sdk.py
DataStore protocol support revision (scan and query)
> feat(datastore): datastore api support revision

- console/Makefile
- docker/Makefile
- scripts/publish/pub.sh
add fault tolerance for gradio build
> tune(e2e): add fault tolerance for gradio build

- client/starwhale/core/dataset/cli.py
- client/starwhale/core/eval/cli.py
- client/starwhale/core/model/cli.py
- client/starwhale/core/runtime/cli.py
- update cli project option doc
- replace `--project` with `--evaluation-project` in the `swcli model eval` command.
> chore(client): update cli `--project` option doc

- console/Makefile
- docker/Makefile
> fix(ci): fix gradio build error

- console/src/domain/project/components/VisitSelector.tsx
- console/src/domain/project/hooks/useFetchProjects.ts
- console/src/domain/project/services/project.ts
- console/src/hooks/usePage.ts
- console/src/i18n/locales.ts
- console/src/pages/Project/ProjectListCard.tsx
> feat(console): project sort by visit type and new project card

- example/PennFudanPed/pfp/dataset.py
- example/datasets/caltech_101/dataset.py
- example/datasets/coco/dataset.py
> bug(example): fix dataset examples for the localfs link issue

- console/packages/starwhale-ui/src/DynamicSelector/Selector.tsx
- console/packages/starwhale-ui/src/Tree/Tree.tsx
- console/packages/starwhale-ui/src/Tree/hooks/useTreeDataLoader.tsx
- console/packages/starwhale-ui/src/Tree/hooks/useTreeDataSelection.tsx
- console/packages/starwhale-ui/src/Tree/types.ts
- console/packages/starwhale-ui/src/base/tree-view/tree-view.tsx
- console/src/domain/dataset/components/DatasetLabel.tsx
- console/src/domain/dataset/components/DatasetTreeSelector.tsx
> fix(console): dataset selector filter error and make select default tree node when filter exsits with arrow keyboard

- client/starwhale/api/_impl/data_store.py
- client/starwhale/api/_impl/dataset/builder/mapping_builder.py
- client/starwhale/api/_impl/dataset/loader.py
- client/starwhale/api/_impl/dataset/model.py
- client/starwhale/api/_impl/wrapper.py
- client/starwhale/core/dataset/copy.py
- client/starwhale/core/dataset/model.py
- client/starwhale/core/dataset/tabular.py
- client/tests/sdk/test_dataset.py
- client/tests/sdk/test_dataset_sdk.py
- related: #1940 
- depends on:
- https://github.com/star-whale/starwhale/pull/2001
- https://github.com/star-whale/starwhale/pull/2016
- https://github.com/star-whale/starwhale/pull/2021
> feat(dataset): dataset sdk supports to use datastore revision for builder and loader

- console/packages/starwhale-core/src/datastore/hooks/useFetchDatastore.ts
- console/packages/starwhale-ui/src/Viewer/DatasetViewer.tsx
- console/src/domain/dataset/utils.ts
- console/src/pages/Dataset/DatasetVersionOverviewFiles.tsx
> update(console): adapt the API to the dataset revision version

- client/setup.py
- client/starwhale/api/_impl/data_store.py
- client/tests/sdk/test_data_store.py
support merging local file with memory table
> feat(datastore): support merging local file with memory table

- client/starwhale/api/_impl/data_store.py
- client/tests/sdk/test_data_store.py
Store diff only in the data store
> chore(client): store diff only in the data store

- scripts/client_test/cli_test.py
> fix(e2e): fix e2e script error

- example/LLM/chatglm6b/README.md
- example/LLM/chatglm6b/code/evaluator.py
- example/LLM/chatglm6b/download_model.py
- example/LLM/chatglm6b/model.yaml
- example/LLM/chatglm6b/requirements.txt
> example(model): chatglm6b

- scripts/e2e_test/start_test.sh
> fix(e2e): fix e2e won't fail

- client/starwhale/core/dataset/type.py
- client/tests/sdk/test_dataset.py
> bug(dataset): fix drop fp in the dataset build processing

- example/datasets/LLM/KQApro/README.md
- example/datasets/LLM/KQApro/dataset.py
- example/datasets/LLM/KQApro/example.py
> example(dataset): add KQApro Dataset

- example/datasets/LLM/GrailQA_v1.0/README.md
- example/datasets/LLM/GrailQA_v1.0/dataset.py
- example/datasets/LLM/GrailQA_v1.0/example.py
> example(dataset): add GrailQA_v1.0 Dataset

- example/datasets/LLM/webQSP/README.md
- example/datasets/LLM/webQSP/dataset.py
- example/datasets/LLM/webQSP/example.py
add WebQuestions Semantic Parses Dataset
> example(dataset): add WebQuestions Semantic Parses Dataset

- example/datasets/LLM/ComplexWebQuestions/README.md
- example/datasets/LLM/ComplexWebQuestions/dataset.py
- example/datasets/LLM/ComplexWebQuestions/example.py
> example(dataset): add ComplexWebQuestions Dataset

- example/datasets/LLM/QALD-9/README.md
- example/datasets/LLM/QALD-9/dataset.py
- example/datasets/LLM/QALD-9/example.py
> example(dataset): add QALD-9 Dataset

- console/src/domain/dataset/components/DatasetLabel.tsx
- console/src/domain/job/components/JobForm.tsx
- console/src/domain/model/components/ModelLabel.tsx
- console/src/domain/runtime/components/RuntimeLabel.tsx
> fix(console): handler editable status not sync

- client/starwhale/api/_impl/job.py
- client/starwhale/core/job/dag.py
- client/starwhale/core/job/step.py
- client/tests/core/test_job.py
- client/tests/sdk/test_job.py
> bug(model): fix generate dag bug for more than one out degree case

- server/controller/src/main/java/ai/starwhale/mlops/api/DataStoreController.java
- server/controller/src/main/java/ai/starwhale/mlops/api/protocol/datastore/RecordListVo.java
- server/controller/src/main/java/ai/starwhale/mlops/datastore/ColumnHintsDesc.java
- server/controller/src/main/java/ai/starwhale/mlops/datastore/ColumnStatistics.java
- server/controller/src/main/java/ai/starwhale/mlops/datastore/DataStore.java
- server/controller/src/main/java/ai/starwhale/mlops/datastore/MemoryTable.java
- server/controller/src/main/java/ai/starwhale/mlops/datastore/RecordList.java
- server/controller/src/main/java/ai/starwhale/mlops/datastore/impl/MemoryTableImpl.java
- server/controller/src/test/java/ai/starwhale/mlops/api/DataStoreControllerTest.java
- server/controller/src/test/java/ai/starwhale/mlops/datastore/DataStoreTest.java
- server/controller/src/test/java/ai/starwhale/mlops/datastore/exporter/RecordsExporterCsvTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/dataset/dataloader/ReadRangeTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/job/storage/JobRepoTest.java
> feature(datastore): return column hints for query and scan

- scripts/e2e_test/remove_test_env.sh
- scripts/e2e_test/start_test.sh
> chore(e2e): keep mysql and minio when e2e success

- console/packages/starwhale-core/src/dataset/hooks/useDatasets.tsx
- console/packages/starwhale-core/src/dataset/types.ts
- console/packages/starwhale-core/src/datastore/hooks/useDatastore.tsx
- console/packages/starwhale-core/src/datastore/hooks/useDatastoreTables.tsx
- console/packages/starwhale-core/src/datastore/hooks/useFetchDatastore.ts
- console/packages/starwhale-core/src/datastore/hooks/useParseDatastore.ts
- console/packages/starwhale-core/src/datastore/schemas/datastore.tsx
- console/packages/starwhale-core/src/datastore/services/datastore.ts
- console/packages/starwhale-core/src/datastore/types.ts
- console/packages/starwhale-core/src/widget/withWidgetDynamicProps.tsx
- console/packages/starwhale-ui/src/GridTable/hooks/useDatastoreColumns.tsx
- console/packages/starwhale-ui/src/Search/Search.tsx
- console/packages/starwhale-ui/src/base/data-table/types.tsx
- console/packages/starwhale-widgets/src/PanelConfusionMatrixWidget/index.tsx
- console/packages/starwhale-widgets/src/PanelTableWidget/index.tsx
- console/src/__generated__/MySuperbApi.ts
- console/src/pages/Dataset/DatasetOverviewLayout.tsx
- console/src/pages/Evaluation/EvaluationListCard.tsx
- console/src/pages/Evaluation/EvaluationListCompare.tsx
- console/src/pages/Evaluation/EvaluationWidgetResults.tsx
- console/src/utils/datetime.ts
- console/swagger.json
> hotfix(console): use columnHints for type, use ignoreNonExistingTable as default  

- .github/workflows/e2e-test.yml
- client/Makefile
- client/starwhale/core/project/cli.py
- scripts/client_test/cli_test.py
- scripts/client_test/cli_test.sh
- scripts/client_test/step_specs/step_spec_cpu_mini.yaml
- scripts/e2e_test/start_test.sh
- scripts/example/model.yaml
- scripts/example/src/dataset.py
- scripts/example/src/evaluator.py
- 35min -> 10min
- enhance points:
- adjust the sequence of the steps to increase the parallelism
- Use minikube docker daemon to store images directly,  bye nexus docker registry.
- Simplify the example code
> enhance(e2e): tune e2e speed

- client/starwhale/api/_impl/evaluation.py
- client/tests/sdk/test_job.py
> enhance(sdk): remove predict/evaluate decorator use limits

- server/controller/src/main/java/ai/starwhale/mlops/api/JobController.java
- server/controller/src/main/java/ai/starwhale/mlops/api/protocol/job/JobRequest.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/JobService.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/spec/JobSpecParser.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/model/bo/ModelVersion.java
- server/controller/src/test/java/ai/starwhale/mlops/api/JobControllerTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/job/JobServiceTest.java
> feat(controller): add handler parameter for job create api

- server/controller/src/main/java/ai/starwhale/mlops/domain/job/JobService.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/job/JobServiceTest.java
> chore(controller): limit parameters for job create api

- server/controller/src/main/java/ai/starwhale/mlops/domain/runtime/RuntimeService.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/system/resourcepool/bo/ResourcePool.java
- server/controller/src/main/java/ai/starwhale/mlops/schedule/k8s/K8sJobTemplate.java
- server/controller/src/main/java/ai/starwhale/mlops/schedule/k8s/K8sTaskScheduler.java
- server/controller/src/test/java/ai/starwhale/mlops/schedule/k8s/K8sJobTemplateTest.java
- server/controller/src/test/java/ai/starwhale/mlops/schedule/k8s/K8sTaskSchedulerTest.java
> chore(controller): add metadata for annotation in resource pool

- scripts/client_test/update_controller_setting.sh
- server/controller/src/main/java/ai/starwhale/mlops/domain/system/SystemSettingService.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/system/resourcepool/bo/Resource.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/system/resourcepool/bo/ResourcePool.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/job/ModelServingServiceTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/system/SystemSettingServiceTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/system/resourcepool/bo/ResourcePoolTest.java
1. set default resource pool in e2e
2. throw exceptions when valid resouces and runtimeResource
> chore(controller): set default resource pool in e2e

- console/src/domain/runtime/schemas/runtimeVersion.tsx
- console/src/domain/runtime/services/runtimeVersion.ts
- console/src/i18n/locales.ts
- console/src/pages/Runtime/RuntimeListCard.tsx
- console/src/pages/Runtime/RuntimeVersionListCard.tsx
- server/controller/src/main/java/ai/starwhale/mlops/domain/bundle/BundleManager.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/runtime/RuntimeService.java
- server/controller/src/main/resources/template/image-build.yaml
- server/controller/src/test/java/ai/starwhale/mlops/domain/runtime/RuntimeServiceTest.java
1. add image build button at console
2. fix build bug with swcli runtime info
3. fix image version typo
demo: http://ib.pre.intra.starwhale.ai/projects/1/runtimes
> feat(console): add image build button

- example/speech_command/sc/evaluator.py
> bug(example): fix speech command example to device typo

- console/packages/starwhale-ui/src/GridTable/GridTable.tsx
- console/packages/starwhale-ui/src/GridTable/components/ConfigViews/ConfigViewEdit.tsx
- console/packages/starwhale-ui/src/GridTable/components/ConfigViews/ConfigViews.tsx
- console/packages/starwhale-ui/src/GridTable/hooks/useGridData.ts
- console/packages/starwhale-ui/src/GridTable/types.ts
> hotfix(console): gets columns as function in case of format by store

- client/scripts/sw-docker-entrypoint
- client/starwhale/base/store.py
- client/starwhale/base/uri.py
- client/starwhale/core/model/cli.py
- client/starwhale/core/model/model.py
- client/starwhale/core/model/store.py
- client/starwhale/core/model/view.py
- client/starwhale/core/runtime/process.py
- client/starwhale/core/runtime/store.py
- client/tests/core/test_model.py
- scripts/client_test/cli_test.py
- scripts/client_test/cmds/artifacts_cmd.py
- depend on: https://github.com/star-whale/starwhale/pull/2121
> feat(client): support starwhale model package to embed starwhale runtime

- server/controller/src/main/java/ai/starwhale/mlops/domain/runtime/RuntimeRegistryListener.java
> chore(controller): ignore not found code when delete secret

- client/starwhale/core/model/cli.py
> bug(client): fix model serve default yaml issue

- server/controller/src/main/java/ai/starwhale/mlops/api/protocol/runtime/RuntimeVersionVo.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/runtime/converter/RuntimeVersionConverter.java
> fix(controller): return property of built image from api

- scripts/client_test/cli_test.py
- scripts/client_test/cmds/artifacts_cmd.py
> chore(e2e): use model run command for e2e test

- server/controller/src/main/java/ai/starwhale/mlops/schedule/k8s/K8sTaskScheduler.java
Add job info in pod annotations
> chore(controller): add job info in pod annotations

- example/LLM/alpaca-lora-7b/README.md
> example(model): add tloen/alpaca-lora example

- server/controller/src/main/java/ai/starwhale/mlops/domain/dataset/mapper/DatasetVersionMapper.java
> bug(server): fix dataset update sql error

- server/controller/src/main/java/ai/starwhale/mlops/api/SystemApi.java
- server/controller/src/main/java/ai/starwhale/mlops/api/SystemController.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/system/SystemService.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/system/SystemSettingService.java
- server/controller/src/test/java/ai/starwhale/mlops/api/SystemControllerTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/system/SystemSettingServiceTest.java
> chore(controller): add resource pool update api

- server/controller/src/main/java/ai/starwhale/mlops/schedule/k8s/K8sTaskScheduler.java
- server/controller/src/test/java/ai/starwhale/mlops/schedule/k8s/K8sTaskSchedulerTest.java
> chore(controller): add project id into meta

- console/packages/starwhale-core/src/datastore/hooks/useDatastoreMixedSchema.tsx
- console/src/pages/Dataset/DatasetVersionOverviewFiles.tsx
> hotfix(console): disable decode cache, for records with uncertain unique key

- console/src/domain/job/components/JobForm.tsx
> hotfix(console): step & editor status sync error

- client/starwhale/core/runtime/process.py
- client/tests/core/test_runtime_process.py
- scripts/client_test/cli_test.py
- scripts/example/runtime_conda.yaml
- use conda run to run a command in the specified environment
- add conda runtime test for github e2e
> hotfix(runtime): fix runtime conda activate typo

- client/starwhale/base/scheduler/task.py
> chore(client): remove warning log when use event loop in thread pool

- client/requirements-install.txt
> chore(client): fix urllib3 version

- client/starwhale/base/bundle.py
- client/starwhale/base/view.py
- client/starwhale/core/dataset/cli.py
- client/starwhale/core/dataset/model.py
- client/starwhale/core/dataset/view.py
- client/tests/core/test_dataset.py
- client/tests/core/test_eval.py
- client/tests/sdk/test_dataset_sdk.py
- docs/docs/reference/swcli/dataset.md
- docs/i18n/zh/docusaurus-plugin-content-docs/current/reference/swcli/dataset.md
[![asciicast](https://asciinema.org/a/580693.svg)](https://asciinema.org/a/580693)
> enhance(client): simpify dataset info command with auto complete latest version

- server/controller/src/main/java/ai/starwhale/mlops/domain/model/ModelService.java
> fix(controller): unexpect file stream closed

- console/packages/starwhale-ui/src/DatePicker/DatePicker.tsx
- console/packages/starwhale-ui/src/DatePicker/index.tsx
- console/packages/starwhale-ui/src/theme/index.ts
- console/src/utils/datetime.ts
> feat(console): datepicker ui

- client/starwhale/core/runtime/process.py
- client/tests/core/test_runtime_process.py
> chore(runtime): runtime process live stream output for conda mode

- client/starwhale/core/model/cli.py
- client/tests/core/test_model.py
> bug(client): fix workdir path name resolve issue

- console/packages/starwhale-core/src/widget/withWidgetDynamicProps.tsx
- console/packages/starwhale-ui/src/GridTable/GridCombineTable.tsx
- console/packages/starwhale-ui/src/GridTable/components/ToolBar/index.tsx
- console/packages/starwhale-ui/src/GridTable/hooks/useGrid.ts
- console/packages/starwhale-ui/src/GridTable/hooks/useGridData.ts
- console/packages/starwhale-ui/src/GridTable/hooks/useGridQuery.tsx
- console/packages/starwhale-ui/src/GridTable/store/store.ts
- console/packages/starwhale-ui/src/base/data-table/headers/headers.tsx
- console/src/pages/Dataset/DatasetVersionOverviewFiles.tsx
> fix(console): columns transfer invisible not showing, parse bytes in panel

- scripts/client_test/cli_test.py
- scripts/client_test/cmds/job_cmd.py
- scripts/e2e_test/start_test.sh
> hotfix(e2e): tune e2e for the useless check

- client/starwhale/core/runtime/cli.py
- client/starwhale/core/runtime/model.py
- client/starwhale/utils/venv.py
- client/tests/core/test_runtime.py
- example/mnist/model2.yaml
- scripts/example/runtime_conda.yaml
- issue:https://github.com/star-whale/starwhale/issues/2156
- test case:
- [![asciicast](https://asciinema.org/a/581147.svg)](https://asciinema.org/a/581147)
> enhance(runtime): make conda export for URL for pip packages installed from git

- .github/workflows/release-base.yml
- docker/Makefile
> chore(ci): fix base and nodejs image rebuild issue

- .github/workflows/release-base.yml
> chore(ci): disable release image build on push event

- client/scripts/sw-docker-entrypoint
- client/starwhale/base/type.py
- client/starwhale/core/model/cli.py
- client/starwhale/core/model/model.py
- client/starwhale/core/model/view.py
- client/starwhale/utils/fs.py
- client/tests/core/test_model.py
[![asciicast](https://asciinema.org/a/582365.svg)](https://asciinema.org/a/582365)
> enhance(model): provide snapshot for model run

- .github/workflows/client.yaml
- .github/workflows/e2e-test.yml
- client/starwhale/core/runtime/model.py
- client/starwhale/utils/progress.py
- client/starwhale/utils/venv.py
- client/tests/core/test_runtime.py
- scripts/client_test/cli_test.py
- scripts/client_test/cli_test.sh
- scripts/example/runtime_conda.yaml
- fix conda runtime e2e test: use the local starwhale wheel package
- fix conda env update prunes the conda install packages
> chore(e2e): fix conda runtime e2e test

- client/starwhale/core/model/model.py
- client/tests/core/test_model.py
- scripts/example/src/evaluator.py
- depends on: https://github.com/star-whale/starwhale/pull/2186
- changes:
- change current workdir for model run
- add e2e test case
> enhance(model): change current workdir to snapshot dir for model run command

- client/starwhale/core/model/cli.py
- client/starwhale/core/model/model.py
- client/starwhale/core/model/view.py
- client/starwhale/utils/fs.py
- client/tests/core/test_model.py
depends on: https://github.com/star-whale/starwhale/pull/2175
> feat(mode): add `model extract` command

- client/tests/sdk/test_job.py
> chore(client): add test case for needs on normal function

- server/controller/src/main/java/ai/starwhale/mlops/schedule/k8s/PodEventHandler.java
- server/controller/src/test/java/ai/starwhale/mlops/schedule/k8s/PodEventHandlerTest.java
> chore(controller): make status as running when pod condition contains PodScheduled

- docs/docs/instances/server/project.md
> Project.md

- scripts/client_test/cli_test.py
> hotfix(ci): fix handler name typo for examples

- server/controller/src/main/java/ai/starwhale/mlops/datastore/ColumnHintsDesc.java
- server/controller/src/main/java/ai/starwhale/mlops/datastore/ColumnStatistics.java
- server/controller/src/main/java/ai/starwhale/mlops/datastore/DataStore.java
- server/controller/src/main/java/ai/starwhale/mlops/datastore/MemoryTable.java
- server/controller/src/main/java/ai/starwhale/mlops/datastore/impl/MemoryTableImpl.java
- server/controller/src/main/java/ai/starwhale/mlops/datastore/type/ListValue.java
- server/controller/src/main/java/ai/starwhale/mlops/datastore/type/MapValue.java
- server/controller/src/main/java/ai/starwhale/mlops/datastore/type/TupleValue.java
- server/controller/src/test/java/ai/starwhale/mlops/api/DataStoreControllerTest.java
- server/controller/src/test/java/ai/starwhale/mlops/datastore/DataStoreTest.java
- server/controller/src/test/java/ai/starwhale/mlops/datastore/type/BaseValueTest.java
> feature(datastore): add column value hints for query and scan

- server/controller/src/main/java/ai/starwhale/mlops/datastore/ColumnSchema.java
- server/controller/src/test/java/ai/starwhale/mlops/datastore/TableSchemaTest.java
- server/controller/src/test/java/ai/starwhale/mlops/datastore/impl/MemoryTableImplTest.java
```
java.lang.NullPointerException: null                                                                                                                            
at ai.starwhale.mlops.datastore.Wal$ColumnSchema$Builder.setColumnName(Wal.java:1052) ~[classes!/:0.1.0-SNAPSHOT]                                       
at ai.starwhale.mlops.datastore.ColumnSchema.toWal(ColumnSchema.java:156) ~[classes!/:0.1.0-SNAPSHOT]                                                   
at ai.starwhale.mlops.datastore.ColumnSchema.getDiff(ColumnSchema.java:184) ~[classes!/:0.1.0-SNAPSHOT]                                                 
at ai.starwhale.mlops.datastore.ColumnSchema.getDiff(ColumnSchema.java:193) ~[classes!/:0.1.0-SNAPSHOT] …
```
> fix(datastore): fix NPE when updating type of list element

- client/starwhale/api/_impl/evaluation.py
Improve the robustness of the PipelineHandler initialization function.
> chore(SDK): add kwargs for PipelineHandler init

- client/starwhale/api/_impl/model.py
- client/starwhale/base/blob/store.py
- client/starwhale/core/model/cli.py
- client/starwhale/core/model/model.py
- client/starwhale/core/model/view.py
- client/tests/base/test_store.py
- client/tests/core/test_model.py
> enhance(client): model build ignore venv and python cache files by default

- client/starwhale/api/_impl/data_store.py
- client/starwhale/api/_impl/dataset/model.py
- client/tests/sdk/test_data_store.py
- client/tests/sdk/test_dataset.py
- client/tests/sdk/test_dataset_sdk.py
- server/controller/src/main/java/ai/starwhale/mlops/api/protocol/datastore/ScanTableRequest.java
- server/controller/src/test/java/ai/starwhale/mlops/api/DataStoreControllerTest.java
> chore(datastore): encodeWithType set to true by default

- README.md
- client/starwhale/api/_impl/evaluation.py
- client/starwhale/api/_impl/wrapper.py
- client/starwhale/base/type.py
- client/tests/sdk/test_evaluation.py
- client/tests/sdk/test_job.py
- client/tests/sdk/test_wrapper.py
- docs/docs/examples/ucf101.md
- docs/i18n/zh/docusaurus-plugin-content-docs/current/evaluation/api/sdk.md
- docs/i18n/zh/docusaurus-plugin-content-docs/current/examples/pfp.md
- docs/i18n/zh/docusaurus-plugin-content-docs/current/examples/speech.md
- docs/i18n/zh/docusaurus-plugin-content-docs/current/examples/ucf101.md
- example/LLM/bard/text_cls/code/evaluator.py
- example/LLM/chat-gpt/text_cls/code/evaluator.py
- example/PennFudanPed/pfp/evaluator.py
- example/cifar10/cifar/evaluator.py
- example/imageNet-ft/imagenet/pipeline.py
- example/mnist/mnist/evaluator.py
- example/mnist/mnist/plain_evaluator.py
- example/nmt/nmt/evaluator.py
- example/speech_command/sc/evaluator.py
- example/text_cls_AG_NEWS/tcan/evaluator.py
- example/transformer/ag_news/code/evaluator.py
- example/transformer/cifar100/code/evaluator.py
- example/ucf101/ucf101/evaluator.py
- scripts/example/src/evaluator.py
- `plain` and `pickle` modes for ppl result logging
- use the more brief word for ppl_results and update examples
> enhance(sdk): support multi modes for predict result logging

- server/storage-access-layer/src/main/java/ai/starwhale/mlops/storage/StorageAccessService.java
- server/storage-access-layer/src/main/java/ai/starwhale/mlops/storage/aliyun/StorageAccessServiceAliyun.java
- server/storage-access-layer/src/main/java/ai/starwhale/mlops/storage/autofit/CompatibleStorageAccessService.java
- server/storage-access-layer/src/main/java/ai/starwhale/mlops/storage/autofit/fs/CompatibleStorageAccessServiceFile.java
- server/storage-access-layer/src/main/java/ai/starwhale/mlops/storage/autofit/s3/CompatibleStorageAccessServiceS3Like.java
- server/storage-access-layer/src/main/java/ai/starwhale/mlops/storage/fs/StorageAccessServiceFile.java
- server/storage-access-layer/src/main/java/ai/starwhale/mlops/storage/memory/StorageAccessServiceMemory.java
- server/storage-access-layer/src/main/java/ai/starwhale/mlops/storage/minio/StorageAccessServiceMinio.java
- server/storage-access-layer/src/main/java/ai/starwhale/mlops/storage/s3/StorageAccessServiceS3.java
- server/storage-access-layer/src/test/java/ai/starwhale/mlops/storage/aliyun/StorageAccessServiceAliyunTest.java
- server/storage-access-layer/src/test/java/ai/starwhale/mlops/storage/fs/StorageAccessServiceFileTest.java
- server/storage-access-layer/src/test/java/ai/starwhale/mlops/storage/minio/StorageAccessServiceMinioTest.java
- server/storage-access-layer/src/test/java/ai/starwhale/mlops/storage/s3/StorageAccessServiceS3Test.java
> feat(storage): support presigned url with put method

- client/starwhale/base/scheduler/step.py
- client/starwhale/core/model/model.py
- client/starwhale/utils/debug.py
- example/mnist/mnist/plain_evaluator.py
- example/nmt/nmt/evaluator.py
[![asciicast](https://asciinema.org/a/583846.svg)](https://asciinema.org/a/583846)
> enhance(client): tune model run output for runnable handlers

- client/starwhale/api/_impl/evaluation.py
- client/starwhale/api/_impl/job.py
- client/tests/sdk/test_job.py
- example/LLM/bard/text_cls/code/evaluator.py
- example/LLM/chat-gpt/chat/code/evaluator.py
- example/LLM/chat-gpt/text_cls/code/evaluator.py
- example/PennFudanPed/pfp/evaluator.py
- example/speech_command/sc/evaluator.py
> chore(sdk): set predict replicas default to 1

- client/starwhale/api/_impl/data_store.py
- client/starwhale/base/bundle_copy.py
> chore(datastore): batch put records with unknown type

- client/starwhale/api/_impl/evaluation.py
- client/tests/sdk/test_evaluation.py
- scripts/example/src/evaluator.py
related: https://github.com/star-whale/starwhale/issues/2203
> enhance(sdk): add more info into external for predict function

- client/starwhale/core/runtime/model.py
- client/starwhale/core/runtime/process.py
- client/tests/core/test_model.py
- client/tests/core/test_runtime.py
- client/tests/core/test_runtime_process.py
> enhance(client): tune runtime activate for the broken restore

- server/controller/src/main/java/ai/starwhale/mlops/domain/task/status/watchers/TaskWatcherForSchedule.java
- server/controller/src/main/java/ai/starwhale/mlops/schedule/SwTaskScheduler.java
- server/controller/src/main/java/ai/starwhale/mlops/schedule/k8s/K8sTaskScheduler.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/job/JobUpdateHelperTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/task/TaskWatcherForScheduleTest.java
> fix: canceled task is not released immediately

- server/controller/src/test/java/ai/starwhale/mlops/domain/dataset/DatasetUploaderTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/storage/TestHashNamedObjectStore.java
- server/storage-access-layer/src/main/java/ai/starwhale/mlops/storage/StorageAccessService.java
- server/storage-access-layer/src/main/java/ai/starwhale/mlops/storage/StorageObjectInfo.java
- server/storage-access-layer/src/main/java/ai/starwhale/mlops/storage/aliyun/StorageAccessServiceAliyun.java
- server/storage-access-layer/src/main/java/ai/starwhale/mlops/storage/autofit/fs/CompatibleStorageAccessServiceFile.java
- server/storage-access-layer/src/main/java/ai/starwhale/mlops/storage/autofit/s3/CompatibleStorageAccessServiceS3Like.java
- server/storage-access-layer/src/main/java/ai/starwhale/mlops/storage/fs/StorageAccessServiceFile.java
- server/storage-access-layer/src/main/java/ai/starwhale/mlops/storage/memory/StorageAccessServiceMemory.java
- server/storage-access-layer/src/main/java/ai/starwhale/mlops/storage/minio/StorageAccessServiceMinio.java
- server/storage-access-layer/src/main/java/ai/starwhale/mlops/storage/s3/StorageAccessServiceS3.java
- server/storage-access-layer/src/test/java/ai/starwhale/mlops/storage/StorageAccessServiceTest.java
> feat(storage): add a head method that returns md5sum

- client/starwhale/api/_impl/evaluation.py
- scripts/example/src/dataset.py
- scripts/example/src/evaluator.py
> bug(sdk): fix predict log plain mode error

- client/starwhale/api/_impl/data_store.py
- client/starwhale/web/data_store.py
- client/tests/web/test_server.py
> fix(client): wrong column hints response in local data store web api

- client/starwhale/api/_impl/evaluation.py
- client/tests/sdk/test_evaluation.py
- scripts/example/src/evaluator.py
> bug(sdk): fix predict inspect with decorators issue

- client/starwhale/api/_impl/evaluation.py
- docker/Dockerfile.starwhale
- example/runtime/pytorch-e2e/runtime-3-10.yaml
- example/runtime/pytorch-e2e/runtime-3-7.yaml
- example/runtime/pytorch-e2e/runtime-3-8.yaml
- example/runtime/pytorch-e2e/runtime-3-9.yaml
- scripts/client_test/cli_test.py
> chore(e2e): simplfy e2e test cases

- example/PennFudanPed/pfp/evaluator.py
> hotfix(example): workaround pfp bbox type issue

- server/controller/src/main/java/ai/starwhale/mlops/api/RuntimeApi.java
- server/controller/src/main/java/ai/starwhale/mlops/api/RuntimeController.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/ModelServingService.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/spec/ModelServingSpec.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/spec/RunConfig.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/runtime/RuntimeService.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/job/ModelServingServiceTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/runtime/RuntimeServiceTest.java
> feat: add env support when running online evaluation and runtime dockerized

- client/tests/web/test_server.py
> chore(ci):fix ut typo for useless owner

- client/starwhale/core/model/cli.py
> fix(client): model run with --runtime error when model has packaged rt

- client/starwhale/base/bundle_copy.py
- client/starwhale/base/cloud.py
- client/starwhale/core/dataset/copy.py
> fix(client): fix project param when copy to remote

- client/scripts/sw-docker-entrypoint
> chore(client): simplify entrypoint logic

- example/LLM/chatglm6b/evaluator.py
> chore(ci): fix chatglm6b code format

- client/starwhale/base/uri/exceptions.py
- client/starwhale/base/uri/resource.py
- client/tests/base/uri/test_resource.py
> chore(client): use resource name when resolving version

- client/starwhale/base/uri/resource.py
- client/starwhale/core/model/model.py
- client/tests/base/uri/test_resource.py
- client/tests/core/test_model.py
- console/src/domain/job/components/JobForm.tsx
- scripts/client_test/cli_test.py
- server/controller/src/main/java/ai/starwhale/mlops/api/protocol/dataset/DatasetInfoVo.java
- server/controller/src/main/java/ai/starwhale/mlops/api/protocol/model/ModelInfoVo.java
- server/controller/src/main/java/ai/starwhale/mlops/api/protocol/runtime/RuntimeInfoVo.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/dataset/DatasetService.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/model/ModelService.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/runtime/RuntimeDao.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/runtime/RuntimeService.java
**changes** :
The model run on **server** cmd:
`swcli model run -u mnist/version/123456 -d mnist/version/223456 -r mnist/version/323456`
**TODOS** #2250 
1. use version's prefix to find artifact
2. guess artifact by version only(without name)
> fix(artifacts): Artifacts unique problem with versionName

- console/packages/starwhale-core/src/datastore/hooks/useDatastorePage.tsx
- console/packages/starwhale-core/src/datastore/hooks/useDatastoreQueryParams.tsx
- console/packages/starwhale-core/src/datastore/hooks/useFetchDatastoreByTable.tsx
- console/packages/starwhale-core/src/datastore/hooks/useFetchDatastoreByTables.tsx
- console/packages/starwhale-core/src/datastore/types.ts
- console/packages/starwhale-core/src/datastore/utils.ts
- console/packages/starwhale-core/src/form/WidgetFormModal.tsx
- console/packages/starwhale-core/src/form/WidgetPreviewModal.tsx
- console/packages/starwhale-core/src/widget/withWidgetDynamicProps.tsx
- console/packages/starwhale-ui/src/GridDatastoreTable/hooks/useDatastoreColumns.tsx
- console/packages/starwhale-ui/src/GridTable/GridCombineTable.tsx
- console/packages/starwhale-ui/src/GridTable/GridTable.tsx
- console/packages/starwhale-ui/src/GridTable/components/Pagination/AutoPagination.tsx
- console/packages/starwhale-ui/src/GridTable/components/Pagination/index.tsx
- console/packages/starwhale-ui/src/GridTable/components/Query/ConfigQuery.tsx
- console/packages/starwhale-ui/src/GridTable/store/StoreUpdater/index.tsx
- console/packages/starwhale-ui/src/GridTable/store/store.ts
- console/packages/starwhale-ui/src/GridTable/types.ts
- console/packages/starwhale-ui/tsconfig.json
- console/src/domain/job/components/JobForm.tsx
- console/src/domain/model/components/ModelTreeSelector.tsx
- console/src/pages/Dataset/DatasetOverviewLayout.tsx
- console/src/pages/Dataset/DatasetVersionOverviewFiles.tsx
- console/src/pages/Evaluation/EvaluationListCard.tsx
- console/src/pages/Evaluation/EvaluationListResult.tsx
* update: ignore columns with prefix in result details
* update: support row height
> refactor(console): grid table support pagination, auto increase and cached max page

- server/controller/src/main/java/ai/starwhale/mlops/api/ModelApi.java
> chore(controller): add guest for model file get api

- server/controller/src/main/java/ai/starwhale/mlops/configuration/RunTimeProperties.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/runtime/RuntimeService.java
- server/controller/src/main/resources/application.yaml
- server/controller/src/test/java/ai/starwhale/mlops/domain/runtime/RuntimeServiceTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/system/SystemSettingServiceTest.java
- server/controller/src/test/java/ai/starwhale/mlops/schedule/k8s/K8sTaskSchedulerTest.java
> chore(controller): config the base image for the job of image build

- server/controller/src/main/java/ai/starwhale/mlops/api/DatasetController.java
- server/controller/src/main/java/ai/starwhale/mlops/api/protocol/dataset/dataloader/DataConsumptionRequest.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/dataset/dataloader/DataLoader.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/dataset/dataloader/DataReadManager.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/dataset/dataloader/DataReadRequest.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/dataset/dataloader/ReadMode.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/dataset/dataloader/dao/DataReadLogDao.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/dataset/dataloader/mapper/DataReadLogMapper.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/dataset/dataloader/MultiConsumerTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/dataset/dataloader/ReadRangeTest.java
Dataset consumtion Message Delivery Semantics, change to at least once
> fix(controller): dataset consume error when process occur exception

- server/controller/src/main/java/ai/starwhale/mlops/schedule/k8s/K8sTaskScheduler.java
- server/controller/src/test/java/ai/starwhale/mlops/schedule/k8s/K8sTaskSchedulerTest.java
> fix(controller): jobs can not use gpu even if the default is set in pool

- server/storage-access-layer/src/main/java/ai/starwhale/mlops/storage/aliyun/StorageAccessServiceAliyun.java
- server/storage-access-layer/src/main/java/ai/starwhale/mlops/storage/s3/StorageAccessServiceS3.java
- server/storage-access-layer/src/test/java/ai/starwhale/mlops/storage/StorageAccessServiceTest.java
> fix(controlller): throw ioexception when get unexist object in oss

- console/Makefile
- scripts/e2e_test/start_test.sh
> fix(console): e2e wrong console proxy

- client/starwhale/utils/venv.py
- client/tests/core/test_runtime.py
> bug(client): fix runtime lock for local wheel pattern

- console/playwright/playwright.config.ts
> update(console): disable multi worker for e2e tests should have certain order

- example/LLM/belle-bloom/runtime_conda.yaml
- example/LLM/belle-bloom/sw.py
- use venv runtime as the default runtime
- handle dataset name pattern
> example(LLM): update example belle-bloom for runtime and dataset ingest

- client/starwhale/base/cloud.py
- server/controller/src/main/java/ai/starwhale/mlops/domain/model/ModelService.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/model/ModelServiceTest.java
https://github.com/star-whale/starwhale/assets/3217223/c10adad1-0f7b-4386-8a7d-1384f13ee3e5
> enhance(client): model download support progress and speed

- client/starwhale/base/uri/resource.py
- client/tests/base/uri/test_resource.py
- client/tests/sdk/test_dataset.py
- client/tests/sdk/test_loader.py
> fix(client): copy remote rc without version fail

- console/playwright/tests/admin-setting.spec.ts
- console/playwright/tests/auth.setup.ts
- console/playwright/tests/config.ts
- example/mnist/Makefile
> optimize(e2e): remove test dep / wait for auth token 

- console/playwright/playwright.config.ts
- console/playwright/tests/admin-setting.spec.ts
- console/playwright/tests/auth.setup.ts
- console/playwright/tests/config.ts
> update(e2e): dynamic create user for admin, disable fullyParallel for tests in single file

- server/controller/src/main/java/ai/starwhale/mlops/configuration/DockerSetting.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/runtime/RuntimeRegistryListener.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/runtime/RuntimeService.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/system/listener/DockerSettingListener.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/runtime/RuntimeRegistryListenerTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/runtime/RuntimeServiceTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/system/SystemSettingServiceTest.java
> fix(controller): image build support separate registry url

- example/LLM/bloom/.swignore
- example/LLM/bloom/download_model.py
- example/LLM/bloom/mt0xxl.py
- example/LLM/bloom/runtime.yaml
> example: add bloom mt0xxl 11B model ppl

- console/src/api/const.ts
- console/src/i18n/locales.ts
- console/src/pages/Runtime/RuntimeListCard.tsx
- console/src/pages/Runtime/RuntimeVersionListCard.tsx
demo: http://ib2.pre.intra.starwhale.ai/projects/1/runtimes/1
> chore(console): optimise image build button

- client/starwhale/utils/venv.py
- client/tests/core/test_runtime.py
> chore(client): make conda log verbose following with swcli verbose level

- server/controller/src/test/java/ai/starwhale/mlops/backup/db/MysqlBackupServiceTest.java
> fix(controller): prevent flyway migration from failing

- client/scripts/sw-docker-entrypoint
- docker/Dockerfile.starwhale
- server/controller/src/main/java/ai/starwhale/mlops/schedule/k8s/K8sTaskScheduler.java
- server/controller/src/test/java/ai/starwhale/mlops/schedule/k8s/K8sTaskSchedulerTest.java
> feat: debug mode with preinstalled code server use job version as ault password

- server/controller/src/main/java/ai/starwhale/mlops/configuration/RunTimeProperties.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/runtime/RuntimeService.java
- server/controller/src/main/resources/application.yaml
- server/controller/src/test/java/ai/starwhale/mlops/domain/runtime/RuntimeServiceTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/system/SystemSettingServiceTest.java
- server/controller/src/test/java/ai/starwhale/mlops/schedule/k8s/K8sTaskSchedulerTest.java
> fix(controller): support node select for image build

- console/packages/starwhale-ui/src/AutoResizer/GridResizerVertical.tsx
- console/packages/starwhale-ui/src/GridTable/components/ConfigColumns/ConfigColumns.tsx
- console/packages/starwhale-ui/src/Transfer/Transfer.tsx
- console/packages/starwhale-ui/src/Transfer/TransferList.tsx
- console/packages/starwhale-ui/src/Viewer/AudioViewer.tsx
> update(console): audio width 0 in grid table, config column overflow hidden, etc

- client/starwhale/core/model/cli.py
- client/starwhale/core/model/store.py
- client/starwhale/core/model/view.py
- client/starwhale/core/runtime/store.py
- client/starwhale/utils/config.py
- client/tests/core/test_model.py
- client/tests/core/test_runtime.py
- related pr:  https://github.com/star-whale/starwhale/pull/2305
- changes:
- standalone supports docker settings with .config
- fix model run in-container typos
> feat(client): standalone supports docker settings with .config

- server/controller/src/main/java/ai/starwhale/mlops/api/JobController.java
- server/controller/src/main/java/ai/starwhale/mlops/configuration/FeaturesProperties.java
- server/controller/src/test/java/ai/starwhale/mlops/api/JobControllerTest.java
> chore(controller): job pause and resume can be disabled

- server/controller/src/main/java/ai/starwhale/mlops/domain/job/JobService.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/converter/JobBoConverter.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/split/JobSpliteratorImpl.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/step/StepConverter.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/step/bo/Step.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/step/mapper/StepMapper.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/step/po/StepEntity.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/system/resourcepool/bo/ResourcePool.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/task/TaskService.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/task/converter/TaskConverter.java
- server/controller/src/main/java/ai/starwhale/mlops/schedule/k8s/K8sTaskScheduler.java
- server/controller/src/main/resources/db/migration/v0_4_0/V0_4_0_003__update_step.sql
- server/controller/src/test/java/ai/starwhale/mlops/domain/job/JobBoConverterTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/job/JobServiceTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/job/JobSpliteratorImplTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/system/resourcepool/bo/ResourcePoolTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/task/TaskServiceTest.java
- server/controller/src/test/java/ai/starwhale/mlops/schedule/k8s/K8sTaskSchedulerTest.java
- Spilt job to step when creating
- Save the resource pool snapshot in step info
> chore(controller): save resource pool detail into step info

- client/starwhale/api/_impl/experiment.py
- client/starwhale/base/view.py
- client/tests/sdk/test_job.py
- scripts/client_test/cli_test.py
- scripts/example/src/sdk_model_build.py
> bug(client): fix fine_tune decorator search errors

- console/src/components/LogViewer/LogViewer.tsx
- console/src/pages/Job/JobTasks.tsx
- console/src/routes.tsx
> fix(console): ws log not showing default, optimize ui

- server/controller/src/main/java/ai/starwhale/mlops/api/JobApi.java
- server/controller/src/main/java/ai/starwhale/mlops/api/JobController.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/task/TaskService.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/task/mapper/TaskMapper.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/task/TaskServiceTest.java
> feat(controller): add task get api

- server/controller/src/test/java/ai/starwhale/mlops/domain/task/TaskServiceTest.java
> fix(controller): task ut error with resource null

- example/LLM/bloom/bloom/bloom.py
- example/LLM/bloom/bloom/download_model.py
> example(LLM): add bigscience/bloom model

- example/datasets/LLM/openassistant-guanaco/README.md
- example/datasets/LLM/openassistant-guanaco/dataset.py
> example(dataset): add openassistant guanaco dataset

- server/controller/src/main/java/ai/starwhale/mlops/domain/task/converter/TaskBoConverter.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/task/converter/TaskConverter.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/task/po/TaskEntity.java
> fix(controller): start end time of task always be -1

- console/vite.config.ts
> fix(console): fix console build issue

- console/src/pages/Job/JobTasks.tsx
> update(console): only show current log remove log cache that viewed

- console/playwright/tests/admin-project.spec.ts
> fix(console): e2e sync with console

- console/src/api/ApiHeader.tsx
- console/src/components/Header/index.tsx
> fix(console): prevent showing error msg when log in

- server/controller/src/main/java/ai/starwhale/mlops/domain/job/JobService.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/job/JobServiceTest.java
> fix(controller): set dev_way to null when dev mode is false

- client/starwhale/api/_impl/job.py
- client/starwhale/base/scheduler/step.py
- client/starwhale/base/scheduler/task.py
- client/starwhale/core/model/model.py
- client/tests/core/test_model.py
- client/tests/sdk/test_job.py
- client/tests/sdk/test_model.py
- example/mnist/mnist/custom_evaluator.py
> enhance(client): add internal model handler for api

- example/LLM/vicuna/.gitignore
- example/LLM/vicuna/build.py
- example/LLM/vicuna/evaluation.py
- example/LLM/vicuna/utils.py
- build model package:
- model evaluation:
- model online evaluation:
- build runtime:
> example(LLM): add vicuna 7B/13B examples

- example/LLM/llama/.gitignore
- example/LLM/llama/README.md
- example/LLM/llama/build.py
- example/LLM/llama/evaluation.py
- example/LLM/llama/finetune.py
- example/LLM/llama/runtime.yaml
- example/LLM/llama/utils.py
1. Build Starwhale Model for base llama model.
3. Evaluate base llama model.
5. Fine-tune base llama model with QLoRA and build a new Starwhale Model Package.
7. Evaluate fine-tuned llama model.
8. Fine-tune fine-tuned llama model and build a new Starwhale Model Package.
9. Evaluate and fine-tune the step 5 output.
> example(LLM): add llama model evaluation and finetune example

- server/controller/src/main/java/ai/starwhale/mlops/api/JobController.java
- server/controller/src/main/java/ai/starwhale/mlops/api/protocol/job/JobRequest.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/JobDao.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/JobService.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/bo/Job.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/converter/JobBoConverter.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/po/JobEntity.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/po/JobFlattenEntity.java
- server/controller/src/main/resources/db/migration/v0_4_0/V0_4_0_005__add_job_release_tm.sql
- server/controller/src/main/resources/mapper/JobMapper.xml
- server/controller/src/test/java/ai/starwhale/mlops/api/JobControllerTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/job/JobServiceTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/job/mapper/JobMapperTest.java
- Auto-cancel the jobs which reach the `auto release time`
- Add `timeToLiveInSec`  param in JobCreate api cc @waynelwz
> enhance(controller): job support auto release

- example/PennFudanPed/pfp/evaluator.py
- example/cifar10/cifar/evaluator.py
- example/nmt/nmt/evaluator.py
- example/speech_command/sc/evaluator.py
- example/text_cls_AG_NEWS/tcan/evaluator.py
- example/ucf101/ucf101/evaluator.py
> fix(client): make model serving of the examples work

- server/controller/src/main/java/ai/starwhale/mlops/domain/task/status/watchers/TaskWatcherForPersist.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/task/TaskWatcherForPersistTest.java
> fix(controller): start time may be empty if job failed directly

- example/LLM/vicuna/README.md
- example/LLM/vicuna/runtime.yaml
> example(LLM): add readme and runtime.yaml for vicuna example

- scripts/e2e_test/start_test.sh
> chore(ci): remove scale controller to zero for daily e2e test

- server/controller/src/main/java/ai/starwhale/mlops/domain/job/status/JobStatusMachine.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/task/status/TaskStatusMachine.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/job/JobUpdateHelperTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/task/TaskWatcherForJobStatusTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/task/WatchableTaskTest.java
> fix(controller): job status is running after cancel the task in preparing status

- server/controller/src/main/java/ai/starwhale/mlops/api/protocol/job/JobVo.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/converter/JobConverter.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/spec/StepSpec.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/job/converter/JobConverterTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/job/spec/JobSpecTest.java
JobVo add `exposedLinks` field
cc @waynelwz
> chore(controller): add exposed links in job list

- example/LLM/musicgen/.gitignore
- example/LLM/musicgen/build.py
- example/LLM/musicgen/dataset.py
- example/LLM/musicgen/evaluation.py
- example/LLM/musicgen/runtime.yaml
- example/LLM/musicgen/utils.py
- cloud resources:
- dataset: https://cloud.starwhale.cn/projects/23/datasets/61/versions/89/files
- model: https://cloud.starwhale.cn/projects/23/models/28
- runtime:  https://cloud.starwhale.cn/projects/23/runtimes/23/versions/60/overview
- cloud evaluation:
- https://cloud.starwhale.cn/projects/23/evaluations/206/results  
- muscigen mini dataset:
- model run for standalone
> example(LLM): add musicgen example

- server/controller/src/main/java/ai/starwhale/mlops/domain/task/status/WatchableTask.java
Fix issue that can not get the IP of the running task when generating the exposed links
cc @waynelwz
> fix(controller): exposed links is empty

- server/controller/src/main/java/ai/starwhale/mlops/api/JobApi.java
- server/controller/src/main/java/ai/starwhale/mlops/api/JobController.java
- server/controller/src/main/java/ai/starwhale/mlops/api/protocol/job/ExecRequest.java
- server/controller/src/main/java/ai/starwhale/mlops/api/protocol/job/ExecResponse.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/JobService.java
- server/controller/src/main/java/ai/starwhale/mlops/schedule/k8s/K8sClient.java
- server/controller/src/main/java/ai/starwhale/mlops/schedule/k8s/K8sTaskScheduler.java
- server/controller/src/test/java/ai/starwhale/mlops/api/JobControllerTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/job/JobServiceTest.java
- server/controller/src/test/java/ai/starwhale/mlops/schedule/k8s/K8sTaskSchedulerTest.java
> enhance(controller): support executing cmd in running task

- client/starwhale/core/runtime/model.py
- client/tests/core/test_runtime.py
> chore(runtime): raise exception for the unsupport dependencies in the runtime.yaml

- console/packages/starwhale-ui/src/IconFont/index.tsx
- console/src/api/WithAuth.tsx
- console/src/api/const.ts
- console/src/domain/job/components/ExecutorForm.tsx
- console/src/domain/job/schemas/job.tsx
- console/src/domain/job/services/job.ts
- console/src/i18n/locales.ts
- console/src/pages/Job/TaskListCard.tsx
Related to #2370
cc @lijing-susan @weijie00123
> enhance(console): add ui for executing cmd in running task

- example/LLM/belle-bloom/sw.py
> example(LLM): fix belle example git checkout the specified version issue

- client/Makefile
- client/setup.py
> chore(client): split gradio to the extra

- .github/workflows/e2e-test.yml
- scripts/e2e_test/start_test.sh
> chore(ci): add controller debug logs when e2e was failed

- client/starwhale/__init__.py
- client/starwhale/utils/debug.py
> chore(client): tune traceback max_frames setting by the verbose argument

- example/runtime/pytorch-e2e/requirements.txt
> chore(ci): add gradio req for e2e examples

- client/starwhale/api/_impl/dataset/model.py
- client/starwhale/core/dataset/cli.py
- client/starwhale/core/dataset/model.py
- client/starwhale/core/dataset/view.py
- client/tests/core/test_dataset.py
- client/tests/sdk/test_dataset_sdk.py
[![asciicast](https://asciinema.org/a/592535.svg)](https://asciinema.org/a/592535)
> feat(dataset): support `--overwrite`/`--patch` for swcli dataset build

- client/starwhale/core/model/copy.py
- client/tests/base/test_copy.py
- server/controller/src/main/java/ai/starwhale/mlops/api/protocol/model/CreateModelVersionRequest.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/model/ModelService.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/model/ModelServiceTest.java
> bugfix: 1. add force support for model copy; 2. add timeout and retries for http client

- console/.eslintrc.js
- console/src/api/WithAuth.tsx
- console/src/domain/job/schemas/job.tsx
- console/src/domain/model/components/ModelTreeSelector.tsx
- console/src/domain/model/schemas/model.tsx
- console/src/domain/model/schemas/modelVersion.tsx
- console/src/i18n/locales.ts
- console/src/pages/Job/JobListCard.tsx
- console/src/pages/Model/ModelListCard.tsx
> feat: online-eval workflow by job

- client/starwhale/core/model/copy.py
> chore(client): remove useless assert blob size for model copy

- server/controller/src/main/java/ai/starwhale/mlops/domain/blob/BlobService.java
- server/storage-access-layer/src/main/java/ai/starwhale/mlops/storage/StorageAccessService.java
- server/storage-access-layer/src/main/java/ai/starwhale/mlops/storage/aliyun/StorageAccessServiceAliyun.java
- server/storage-access-layer/src/main/java/ai/starwhale/mlops/storage/autofit/CompatibleStorageAccessService.java
- server/storage-access-layer/src/main/java/ai/starwhale/mlops/storage/autofit/fs/CompatibleStorageAccessServiceFile.java
- server/storage-access-layer/src/main/java/ai/starwhale/mlops/storage/autofit/s3/CompatibleStorageAccessServiceS3Like.java
- server/storage-access-layer/src/main/java/ai/starwhale/mlops/storage/fs/StorageAccessServiceFile.java
- server/storage-access-layer/src/main/java/ai/starwhale/mlops/storage/memory/StorageAccessServiceMemory.java
- server/storage-access-layer/src/main/java/ai/starwhale/mlops/storage/minio/StorageAccessServiceMinio.java
- server/storage-access-layer/src/main/java/ai/starwhale/mlops/storage/s3/StorageAccessServiceS3.java
- server/storage-access-layer/src/test/java/ai/starwhale/mlops/storage/aliyun/StorageAccessServiceAliyunTest.java
- server/storage-access-layer/src/test/java/ai/starwhale/mlops/storage/fs/StorageAccessServiceFileTest.java
- server/storage-access-layer/src/test/java/ai/starwhale/mlops/storage/minio/StorageAccessServiceMinioTest.java
- server/storage-access-layer/src/test/java/ai/starwhale/mlops/storage/s3/StorageAccessServiceS3Test.java
> bugfix(storage): add Content-Type for signed put url

- client/starwhale/core/model/model.py
> bug(client): skip model list for the empty manifest/digest info

- console/packages/starwhale-ui/src/Tree/Tree.tsx
- console/packages/starwhale-ui/src/Tree/hooks/useTreeDataSelection.tsx
- console/packages/starwhale-ui/src/utils/index.ts
- console/src/domain/model/components/ModelLabel.tsx
- console/src/domain/model/components/ModelTreeSelector.tsx
- console/src/domain/model/hooks/useFetchModelVersionFiles.ts
- console/src/domain/model/hooks/useModelFiles.ts
- console/src/domain/model/schemas/model.tsx
- console/src/domain/model/schemas/modelVersion.tsx
- console/src/domain/model/services/modelVersion.ts
- console/src/domain/runtime/components/RuntimeLabel.tsx
- console/src/domain/runtime/components/RuntimeTreeSelector.tsx
- console/src/pages/Model/ModelOverviewLayout.tsx
- console/src/pages/Model/ModelVersionLayout.tsx
- console/src/pages/Model/ModelVersionListCard.tsx
- console/src/pages/Model/ModelVersionOverview.tsx
- console/src/pages/Model/ModelVersionOverviewFiles.tsx
fix: model/runtime tree selector search not work
> feat(console): new model api load model files step by step, support shared model

- server/controller/src/main/java/ai/starwhale/mlops/api/protocol/model/ModelInfoVo.java
- server/controller/src/main/java/ai/starwhale/mlops/api/protocol/model/ModelVersionVo.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/model/ModelService.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/model/converter/ModelVersionVoConverter.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/model/po/ModelVersionEntity.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/model/ModelVersionConverterTest.java
> fix(controller): make the property of 'shared' in model version to show

- server/controller/src/main/java/ai/starwhale/mlops/domain/job/converter/JobConverter.java
> fix(controller): pinned time NPE

- client/starwhale/base/bundle_copy.py
- client/starwhale/core/model/copy.py
> bugfix(client): add the "force" parameter for model uploading

- scripts/client_test/cmds/artifacts_cmd.py
> chore(ci): add verbose for e2e cmd output

- console/packages/starwhale-core/src/dataset/utils.ts
- console/packages/starwhale-core/src/form/WidgetPreviewModal.tsx
- console/packages/starwhale-ui/src/GridTable/GridCompareTable.tsx
- console/src/components/Editor/FullTablesEditor.tsx
> fix(console): store not reset when tables changed / compare num error / widget preview error 

- console/packages/starwhale-ui/src/GridDatastoreTable/components/Preview.tsx
- console/packages/starwhale-ui/src/Viewer/DataViewer.tsx
- console/packages/starwhale-ui/src/Viewer/TextViewer.tsx
> optimize(console): grid cell preview pre view with work wrap

- console/packages/starwhale-ui/src/Tooltip/Tooltip.tsx
- console/src/api/ApiHeader.tsx
- console/src/domain/model/hooks/useModelFiles.ts
- console/src/domain/model/services/modelVersion.ts
- console/src/domain/user/services/user.ts
- console/src/pages/Evaluation/EvaluationWidgetResults.tsx
- console/src/pages/Model/ModelVersionOverviewFiles.tsx
- console/src/pages/Project/OnlineEval.tsx
> feat(console): use slient config disable error toaster, update model file load api and tree interactive

- console/packages/starwhale-ui/src/Tooltip/Tooltip.tsx
- console/src/api/ApiHeader.tsx
- console/src/components/Table/index.tsx
- console/src/pages/Job/JobListCard.tsx
> update(console): job pin ui

- README.md
- docker/charts/templates/NOTES.txt
- docker/charts/templates/controller-deployment.yaml
- docker/charts/templates/controller-ingress.yaml
- docker/charts/templates/minio.yaml
> bug(ci): fix e2e release charts typo

- console/playwright/tests/admin-project.spec.ts
> bug(ci): fix console e2e typo

- console/src/pages/Runtime/RuntimeListCard.tsx
> update(console): use runtime version time for list time

- console/src/api/const.ts
- console/src/pages/Project/ProjectSidebar.tsx
> update(console): hide trash menu to none role

- example/LLM/belle-bloom/README.md
- example/LLM/belle-bloom/runtime.yaml
- example/LLM/belle-bloom/runtime_conda.yaml
- example/LLM/belle-bloom/sw.py
- example/LLM/guanaco/runtime.yaml
- example/LLM/llama/runtime.yaml
- example/LLM/vicuna/runtime.yaml
> example(LLM): update llm examples runtime req version

- console/src/api/const.ts
- console/src/pages/Job/JobListCard.tsx
> chore(console): auth for pin and unpin

- console/packages/starwhale-ui/src/base/data-table/cells/cell-placement.tsx
- console/packages/starwhale-ui/src/base/data-table/data-custom-table.tsx
- console/packages/starwhale-ui/src/base/data-table/headers/header.tsx
- console/packages/starwhale-ui/src/base/data-table/inner-table-element.tsx
> update(console): grid support optimized background without trigger full cell render

- console/src/pages/Job/JobTasks.tsx
> update(console): combine task logs with online & offline

- server/controller/src/main/java/ai/starwhale/mlops/domain/blob/BlobCacheConfig.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/blob/BlobServiceConfig.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/blob/BlobServiceImpl.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/blob/CachedBlobService.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/blob/BlobServiceImplTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/blob/CachedBlobServiceTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/model/ModelServiceTest.java
- server/storage-access-layer/src/main/java/ai/starwhale/mlops/storage/s3/S3Config.java
> feat(controller): add blob cache support for controller

- console/src/domain/model/services/modelVersion.ts
> fix(console): model file load with no parse for json

- server/controller/src/main/java/ai/starwhale/mlops/schedule/k8s/JobEventHandler.java
> fix(controller): task status changed canceled when success

- client/setup.py
- client/starwhale/base/cloud_blob_cache.py
- client/starwhale/core/model/copy.py
- client/tests/base/test_cloud_blob_cache.py
- client/tests/base/test_copy.py
> feat(client): support blob cache in model copy

- server/controller/src/main/java/ai/starwhale/mlops/domain/task/status/watchers/TaskWatcherForSchedule.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/task/TaskWatcherForScheduleTest.java
> fix(controller): can not stop the workload after cancelling

- server/controller/src/main/java/ai/starwhale/mlops/api/RuntimeApi.java
> fix(controller): allow guest accessing the runtime

- docker/Dockerfile.base
- docker/Makefile
> chore(docker): add base os dependencies for stable diffusion environment

- console/src/domain/dataset/components/DatasetTreeSelector.tsx
- console/src/domain/model/components/ModelTreeSelector.tsx
- console/src/domain/runtime/components/RuntimeTreeSelector.tsx
> fix(console): route to the original project of the shared resource

- console/package.json
- console/packages/starwhale-ui/src/GridDatastoreTable/components/Preview.tsx
- console/packages/starwhale-ui/src/JSONView/JSONView.tsx
- console/packages/starwhale-ui/src/JSONView/index.tsx
- console/src/components/Indicator/SummaryIndicator.tsx
- console/src/pages/Dataset/DatasetVersionOverviewMeta.tsx
- console/src/pages/Runtime/RuntimeVersionOverviewMeta.tsx
- console/src/styles/_global.scss
- console/yarn.lock
[Screencast from 2023年07月05日 17时08分07秒.webm](https://github.com/star-whale/starwhale/assets/100347187/63cab5ea-2f46-4905-a9f0-14e0b98fad29)
> update(console): improve json preview with copy/expand/lazy/ui optimze

- client/starwhale/base/scheduler/__init__.py
- client/tests/sdk/test_job.py
error: https://cloud.starwhale.cn/projects/12/evaluations/309/tasks
> hotfix(client): fix model run override task num does not work issue

- console/src/domain/job/components/JobForm.tsx
- console/src/domain/model/schemas/modelVersion.tsx
- console/src/pages/Admin/SystemSettings.tsx
> feat(console): support job step with need_dataset, system setting full height

- client/starwhale/api/_impl/evaluation.py
- client/tests/sdk/test_evaluation.py
> chore(client): add duration_seconds for ppl result

- example/LLM/bloom/bloom/bloom.py
- example/LLM/bloom/mt0.py
- example/LLM/chatglm6b/evaluator.py
- example/LLM/chatglm6b/requirements.txt
- example/LLM/chatglm6b/runtime.yaml
add chatbot for chatglm and mt0
> add chatbot for chatglm and mt0

- client/starwhale/api/_impl/evaluation.py
- client/starwhale/api/_impl/experiment.py
- client/starwhale/api/_impl/job.py
- client/starwhale/base/scheduler/step.py
- client/starwhale/base/scheduler/task.py
- client/tests/core/test_model.py
- client/tests/sdk/test_job.py
- client/tests/sdk/test_model.py
- console/src/domain/job/components/JobForm.tsx
- console/src/domain/model/schemas/modelVersion.tsx
- server/controller/src/main/java/ai/starwhale/mlops/api/protocol/job/JobRequest.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/JobService.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/spec/StepSpec.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/job/spec/JobSpecTest.java
related: https://github.com/star-whale/starwhale/pull/2463
> feat(client):  add 'require_dataset' for job handler

- console/src/domain/job/components/JobStatus.tsx
- console/src/domain/job/schemas/job.tsx
- console/src/i18n/locales.ts
Related to https://github.com/star-whale/starwhale/pull/2416/files#diff-168b8e90871a72f0deb5b02ae4a89683cf0c5388cd87584f7f703da81ca47f48R342
> chore(console): add cancelling in job status

- scripts/client_test/cli_test.py
- scripts/client_test/cmds/artifacts_cmd.py
- scripts/client_test/cmds/base/common.py
- scripts/client_test/cmds/base/invoke.py
- scripts/client_test/cmds/instance_cmd.py
- scripts/client_test/cmds/job_cmd.py
- scripts/client_test/cmds/project_cmd.py
https://github.com/star-whale/starwhale/actions/runs/5463781705/jobs/9961832330
a lots of log will be appended into a python list, this will lead memory leak. The pr will fix https://github.com/star-whale/starwhale/pull/2462 memory leak issue.
> enhance(ci): support more invoke funtions to simply e2e output

- console/packages/starwhale-core/src/types/index.ts
- console/packages/starwhale-core/src/widget/withWidgetDynamicProps.tsx
- console/packages/starwhale-widgets/src/PanelTableWidget/index.tsx
> feat(console): support panel table pagination

- client/starwhale/base/type.py
- client/starwhale/core/runtime/model.py
- client/tests/core/test_runtime.py
- example/runtime/pytorch-e2e/runtime-3-10.yaml
- example/runtime/pytorch-e2e/runtime-3-7.yaml
- example/runtime/pytorch-e2e/runtime-3-8.yaml
- example/runtime/pytorch-e2e/runtime-3-9.yaml
- example/runtime/pytorch-e2e/runtime.yaml
- scripts/example/runtime.yaml
- scripts/example/runtime_conda.yaml
- scripts/example/src/evaluator.py
> feat(runtime): support run commands in the runtime.yaml

- console/src/main.tsx
> update(console): support  init lang by location

- console/src/pages/Project/ProjectSidebar.tsx
> update(console): project menu order

- console/package.json
- console/packages/starwhale-ui/src/DynamicSelector/StyledComponent.tsx
- console/src/domain/project/components/ProjectForm.tsx
- console/src/pages/Project/OnlineEval.tsx
- console/yarn.lock
> update: upgrade vite avoid vulnerabilities

- server/controller/src/main/java/ai/starwhale/mlops/domain/task/status/watchers/log/TaskLogK8sCollector.java
- server/controller/src/main/java/ai/starwhale/mlops/schedule/k8s/JobEventHandler.java
- server/controller/src/main/java/ai/starwhale/mlops/schedule/k8s/K8sClient.java
- server/controller/src/main/resources/db/migration/v0_4_0/V0_4_0_009__task_fail_reason_type.sql
- server/controller/src/test/java/ai/starwhale/mlops/schedule/k8s/JobEventHandlerTest.java
> chore(controller): prefer using pod failed reason

- client/starwhale/base/cloud_blob_cache.py
- client/starwhale/core/model/copy.py
> feat(client): switch to round-robin for blob cache server selection

- console/packages/starwhale-core/src/dataset/utils.ts
- console/packages/starwhale-ui/src/GridDatastoreTable/hooks/useDatastoreColumns.tsx
- console/packages/starwhale-ui/src/JSONView/JSONView.tsx
- console/packages/starwhale-ui/src/Tooltip/Tooltip.tsx
- console/packages/starwhale-ui/src/Viewer/DataViewer.tsx
- console/packages/starwhale-ui/src/Viewer/ImageViewer.tsx
- console/packages/starwhale-ui/src/Viewer/TextViewer.tsx
- console/packages/starwhale-ui/src/Viewer/ZoomWrapper.tsx
- console/src/styles/_global.scss
> update(console): optimize grid viewer support complex data, more user friendly interactive

- server/controller/src/main/java/ai/starwhale/mlops/domain/job/JobService.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/job/JobServiceTest.java
> fix(controller): search built-in runtime by model project id

- console/playwright/tests/admin-project.spec.ts
> fix(console): unstable e2e when check checkbox

- console/src/components/Divider.tsx
- console/src/domain/job/components/JobForm.tsx
- console/src/domain/job/schemas/job.tsx
- console/src/i18n/locales.ts
> feat(console): support auto release

- server/controller/src/main/java/ai/starwhale/mlops/domain/model/Model.java
> fix(controller): set project id for model BO

- console/packages/starwhale-core/src/datastore/hooks/useDatastoreMixedSchema.tsx
- console/packages/starwhale-core/src/datastore/utils.ts
- console/packages/starwhale-core/src/utils/useCachedMap.tsx
- console/src/components/Card/index.module.scss
- console/src/components/Table/index.tsx
- console/src/pages/BaseLayout.tsx
- console/src/pages/Evaluation/EvaluationListCard.tsx
- console/src/pages/Job/JobListCard.tsx
> update(console): table list content same with viewport to avoid scroll be blocking, add useCached hook

- server/controller/src/main/java/ai/starwhale/mlops/api/EvaluationApi.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/evaluation/EvaluationService.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/evaluation/mapper/ViewConfigMapper.java
- server/controller/src/main/resources/db/migration/v0_4_0/V0_4_0_010__update_view_config.sql
- server/controller/src/test/java/ai/starwhale/mlops/domain/evaluation/EvaluationServiceTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/evaluation/mapper/ViewConfigMapperTest.java
> chore(controller): make view config in eval project scope

- client/starwhale/api/_impl/data_store.py
- client/tests/sdk/test_data_store.py
```
[2023-07-11 16:35:05.153743] 🐦 |TRACE| update table project/16/dataset/OpenOrca/_current/meta, 13 records
[2023-07-11 16:35:18.495791] 🐦 |TRACE| update table project/16/dataset/OpenOrca/_current/meta, 2139 records
[2023-07-11 16:35:18.932409] 🐦 |TRACE| update table project/16/dataset/OpenOrca/_current/meta, 4678 records
[2023-07-11 16:35:19.482208] 🐦 |TRACE| update table project/16/dataset/OpenOrca/_current/meta, 5542 records
[2023-07-11 16:35:20.118198] 🐦 |TRACE| update table project/16/dataset/OpenOrca/_current/meta, 6354 records
[2023-07-11 16:35:21.141299] 🐦 |TRACE| update table project/16/dataset/OpenOrca/_current/meta, 11001 records
[2023-07-11 16:35:23.079573] 🐦 |TRACE| update table project/16/dataset/OpenOrca/_current/meta, 20879 records
[2023-07-11 16:35:26.782620] 🐦 |TRACE| …
```
> chore(client): add max_batch_size for update_table in tablewriter

- client/starwhale/api/_impl/dataset/builder/mapping_builder.py
- client/starwhale/core/dataset/type.py
- before:
- after:
https://cloud.starwhale.cn/projects/starwhale:public/datasets/25/versions/155/files
> bug(dataset): clear Text._content for datastore

- console/src/pages/Dataset/DatasetVersionOverview.tsx
- console/src/pages/Model/ModelVersionOverview.tsx
- console/src/pages/Runtime/RuntimeVersionOverview.tsx
> chore(console): disable sharing resource in private project

- client/scripts/sw-docker-entrypoint
- server/controller/src/main/java/ai/starwhale/mlops/configuration/RunTimeProperties.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/system/SystemSetting.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/system/SystemSettingService.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/system/listener/RunTimePropertiesListener.java
- server/controller/src/main/java/ai/starwhale/mlops/schedule/k8s/K8sTaskScheduler.java
- server/controller/src/main/resources/application.yaml
- server/controller/src/test/java/ai/starwhale/mlops/domain/runtime/RuntimeServiceTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/system/SystemSettingServiceTest.java
- server/controller/src/test/java/ai/starwhale/mlops/schedule/k8s/K8sTaskSchedulerTest.java
directly wirte the conda setting to .condarc from controller
example:
```yaml
condaSetting: |
channels:
- defaults
show_channel_urls: true
default_channels:
- http://nexus.starwhale.ai/repository/anaconda/main
- http://nexus.starwhale.ai/repository/anaconda/r
- http://nexus.starwhale.ai/repository/anaconda/msys2
custom_channels:
conda-forge: http://nexus.starwhale.ai/repository/conda-cloud
nvidia: http://nexus.starwhale.ai/repository/conda-cloud
ssl_verify: false
default_threads: 10
```
> controller: add conda config to system setting

- example/text_cls_AG_NEWS/tcan/evaluator.py
- example/transformer/ag_news/code/evaluator.py
- related pr: https://github.com/star-whale/starwhale/pull/2498
- error message:
> hotfix(example): fix ag_news example evaluation typo

- client/requirements-dev.txt
- client/starwhale/base/bundle_copy.py
- client/starwhale/core/model/copy.py
- client/starwhale/proto_gen/model_package_storage_pb2.py
- client/starwhale/proto_gen/model_package_storage_pb2.pyi
- client/tests/base/test_copy.py
- server/controller/src/main/java/ai/starwhale/mlops/domain/model/ModelService.java
- server/controller/src/main/protobuf/model_package_storage.proto
- server/controller/src/test/java/ai/starwhale/mlops/domain/model/ModelServiceTest.java
> feat: add symlink & hardlink support for model packages

- console/packages/starwhale-ui/src/Viewer/DataViewer.tsx
> update(console): data viewer support text with link

- client/starwhale/core/runtime/model.py
- client/tests/core/test_runtime.py
- example runtime.yaml
```
name: basicsr
mode: venv
api_version: 1.1
dependencies:
- pip:
- torch
- numpy
- cython
- basicsr==1.4.2 
environment:
arch: noarch
os: ubuntu:20.04
cuda: 11.4
```
- runtime build with auto-lock:
[![asciicast](https://asciinema.org/a/596696.svg)](https://asciinema.org/a/596696) 
- runtime restore:
[![asciicast](https://asciinema.org/a/596702.svg)](https://asciinema.org/a/596702)
> feat(runtime): auto ingest some known libs pip setup_requires for preparing

- server/controller/src/main/java/ai/starwhale/mlops/domain/blob/CachedBlobService.java
- server/pom.xml
- server/storage-access-layer/pom.xml
- server/storage-access-layer/src/main/java/ai/starwhale/mlops/storage/autofit/CompatibleStorageAccessService.java
- server/storage-access-layer/src/main/java/ai/starwhale/mlops/storage/autofit/qcloud/CompatibleStorageAccessServiceBuilderQcloud.java
- server/storage-access-layer/src/main/java/ai/starwhale/mlops/storage/autofit/s3/CompatibleStorageAccessServiceS3Like.java
- server/storage-access-layer/src/main/java/ai/starwhale/mlops/storage/configuration/StorageAccessConfig.java
- server/storage-access-layer/src/main/java/ai/starwhale/mlops/storage/qcloud/StorageAccessServiceQcloud.java
- server/storage-access-layer/src/test/java/ai/starwhale/mlops/storage/qcloud/StorageAccessServiceQcloudTest.java
> enhance(controller): support tencent oss offical sdk

- console/packages/starwhale-ui/src/GridTable/GridCompareTable.tsx
- console/src/pages/Evaluation/EvaluationListResult.tsx
> fix(console): eval result compare title & pinkey missing

- console/packages/starwhale-ui/src/Button/Button.tsx
- console/packages/starwhale-ui/src/Tooltip/Tooltip.tsx
- console/src/components/Header/index.tsx
- console/src/i18n/locales.ts
- console/src/pages/Job/JobListCard.tsx
> update(console): pin status color / copyright / button focus etc

- console/packages/starwhale-ui/src/Upload/DraggerUpload.tsx
> fix(console): prevent 403 when file upload to oss

- client/starwhale/api/_impl/job.py
- client/tests/sdk/test_job.py
> fix(sdk): set require_ds to true when use pipeline handler

- example/stable-diffusion/txt2img/runtime.yaml
> chore(example): add docker image field in sd demo

- client/starwhale/base/cloud_blob_cache.py
> bugfix(client): roundrobin does not work for blobs

- server/controller/src/main/java/ai/starwhale/mlops/domain/filestorage/FileStorageService.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/filestorage/FileStorageServiceTest.java
> chore(controller): use the same oss schema with server

- server/controller/src/main/java/ai/starwhale/mlops/schedule/k8s/K8sTaskScheduler.java
- server/controller/src/test/java/ai/starwhale/mlops/schedule/k8s/K8sTaskSchedulerTest.java
> fix(controller): the job is deleted even if exception occurs when collecting logs

- README.md
- console/src/consts/index.ts
> chore(doc): refresh doc links

- server/controller/src/main/java/ai/starwhale/mlops/domain/dataset/DatasetService.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/dataset/DatasetServiceTest.java
> fix(controller): datasetName compare use equals function 

- README.md
- docker/charts/templates/NOTES.txt
- example/mnist/dataset.yaml
- example/notebooks/quickstart-standalone.ipynb
- example/runtime/pytorch-cn-mirror/requirements.txt
- example/runtime/pytorch/requirements.txt
> hotfix(example): fix the readme and quickstart examples outdated issue

- README.md
> chore(doc): add doc for minikube share access

- example/runtime/pytorch-cn-mirror/requirements.txt
- example/runtime/pytorch-e2e/requirements.txt
- example/runtime/pytorch/requirements.txt
- issue: 
- example: https://cloud.starwhale.cn/projects/12/evaluations/482/tasks   for speech command
> chore(example): upgrade pytorch version for examples

- console/src/api/const.ts
- console/src/pages/Dataset/DatasetListCard.tsx
> update(console): auth of  dataset build list

- example/notebooks/dataset-sdk.ipynb
> bug(example): fix dataset ipynb typo

- console/package.json
- console/packages/starwhale-ui/src/Markdown/Markdown.tsx
- console/packages/starwhale-ui/src/Markdown/index.tsx
- console/packages/starwhale-ui/src/Markdown/markdown.css
- console/src/domain/model/hooks/useCurrentModelFile.ts
- console/src/pages/Model/ModelOverviewLayout.tsx
- console/src/pages/Model/ModelReadmeOverview.tsx
- console/src/routes.tsx
- console/yarn.lock
> feat(console): support model readme preview

- server/controller/src/main/java/ai/starwhale/mlops/configuration/security/ProjectDetectionFilter.java
- server/controller/src/main/java/ai/starwhale/mlops/configuration/security/ProjectNameExtractorDataStoreMixed.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/bundle/base/BundleEntity.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/bundle/base/HasProjectId.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/bundle/tag/HasTagWrapper.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/dataset/DatasetDao.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/dataset/mapper/DatasetMapper.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/JobDao.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/model/ModelDao.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/model/mapper/ModelMapper.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/runtime/RuntimeDao.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/runtime/mapper/RuntimeMapper.java
- server/controller/src/test/java/ai/starwhale/mlops/api/config/ProjectNameExtractorDataStoreMixedTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/bundle/BundleManagerTest.java
> fix(controller): prevent accessing the rc not in the project

- server/controller/src/main/java/ai/starwhale/mlops/datastore/exporter/RecordsExporterCsv.java
- server/controller/src/test/java/ai/starwhale/mlops/datastore/exporter/RecordsExporterCsvTest.java
fix the bug caused by default charset shifting along with runtime environment
> fix(controller): fix charset bug for export csv

- .github/workflows/release.yml
> bug(ci): fix release.yaml needs typo

- console/index.html
- console/packages/starwhale-core/src/widget/WidgetFactory.tsx
- console/packages/starwhale-core/src/widget/WidgetRenderTree.tsx
- console/vite.config.ts
> update(console): widget full reload to module reload in vite hmr 、 baidu analytics

- docker/charts/templates/NOTES.txt
- docker/charts/templates/controller-deployment.yaml
- docker/charts/values.yaml
- scripts/e2e_test/start_test.sh
- scripts/publish/pub.sh
> chore(chart):update chart desc and server image tag in e2e

- server/controller/src/main/java/ai/starwhale/mlops/datastore/exporter/RecordsExporterCsv.java
- server/controller/src/test/java/ai/starwhale/mlops/datastore/exporter/RecordsExporterCsvTest.java
> feat(controller): add header for exported csv

- server/controller/src/main/java/ai/starwhale/mlops/configuration/security/ProjectNameExtractorDataStoreMixed.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/bundle/BundleAccessor.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/dataset/DatasetDao.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/dataset/mapper/DatasetMapper.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/JobDao.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/model/ModelDao.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/model/mapper/ModelMapper.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/runtime/RuntimeDao.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/runtime/mapper/RuntimeMapper.java
- server/controller/src/test/java/ai/starwhale/mlops/api/config/ProjectNameExtractorDataStoreMixedTest.java
> fix(controller): do not validate the resource with name in filter

- client/starwhale/core/job/cli.py
- client/starwhale/core/model/cli.py
- client/starwhale/core/runtime/cli.py
> bug(client): fix commands help typo

- docker/Dockerfile.dataset_build
- docker/Makefile
> chore(docker): add Dockerfile for dataset build image

- client/starwhale/consts/__init__.py
- client/starwhale/core/runtime/model.py
- client/tests/core/test_runtime.py
- docker/Makefile
> bug(client): fix base/cuda image typo

- server/controller/src/main/java/ai/starwhale/mlops/domain/model/mapper/ModelVersionMapper.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/model/mapper/ModelVersionMapperTest.java
> fix(controller): make model size works

- console/src/domain/job/components/JobForm.tsx
> update(console): remove modify check when rerun

- console/src/domain/job/schemas/task.tsx
- console/src/pages/Job/TaskListCard.tsx
> chore(console): show web handler links in task list view

- server/controller/src/main/java/ai/starwhale/mlops/api/protocol/task/TaskVo.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/converter/JobConverter.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/spec/JobSpecParser.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/spec/StepSpec.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/split/JobSpliteratorImpl.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/step/mapper/StepMapper.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/step/po/StepEntity.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/task/converter/TaskConverter.java
- server/controller/src/main/resources/db/migration/v0_4_0/V0_4_0_013__add_step_meta.sql
- server/controller/src/test/java/ai/starwhale/mlops/domain/job/spec/JobSpecTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/job/spec/StepSpecTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/job/step/mapper/StepMapperTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/task/TaskConverterTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/task/TaskServiceTest.java
> chore(controller): support exposed link in task list api

- example/LLM/llama/finetune.py
> example(LLM): disable save checkpoint for llama finetune

- console/src/components/LogViewer/LogViewer.tsx
> update(console): control render rate avoid user interactive blocking, cached component

- client/starwhale/base/uri/resource.py
- client/tests/base/uri/test_resource.py
> chore(client): Support `Resourse.refine` for the user's tags in the standalone instance

- example/LLM/llama/finetune.py
> example(LLM): fix llama finetune build model modules typo

- client/starwhale/__init__.py
- client/starwhale/api/_impl/instance.py
- client/starwhale/api/instance.py
- client/starwhale/core/instance/view.py
- client/starwhale/utils/config.py
- client/tests/sdk/test_instance.py
> feat(sdk): add `login` and `logout` sdk

- console/src/pages/Model/ModelListCard.tsx
- server/controller/src/main/java/ai/starwhale/mlops/api/protocol/model/ModelVo.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/model/ModelService.java
> chore(console): link to the latest version in model list

- server/controller/src/main/java/ai/starwhale/mlops/domain/dataset/mapper/DatasetMapper.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/dataset/mapper/DatasetVersionMapper.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/model/mapper/ModelMapper.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/model/mapper/ModelVersionMapper.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/runtime/mapper/RuntimeMapper.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/runtime/mapper/RuntimeVersionMapper.java
- server/controller/src/main/resources/db/migration/v0_4_0/V0_4_0_012__add_constraint_for_resource.sql
- server/controller/src/main/resources/db/migration/v0_4_0/V0_4_0_014__add_constraint_for_resource.sql
- server/controller/src/test/java/ai/starwhale/mlops/domain/dataset/mapper/DatasetMapperTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/model/mapper/ModelMapperTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/runtime/mapper/RuntimeMapperTest.java
> fix(controller): add constraint(UK) for resource entity

- server/controller/src/main/java/ai/starwhale/mlops/api/protocol/job/JobVo.java
- server/controller/src/main/java/ai/starwhale/mlops/api/protocol/model/ModelVo.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/dataset/DatasetDao.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/dataset/DatasetService.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/JobService.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/converter/JobConverter.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/model/ModelService.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/runtime/RuntimeService.java
- server/controller/src/main/resources/mapper/JobMapper.xml
- server/controller/src/test/java/ai/starwhale/mlops/domain/dataset/DatasetServiceTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/job/JobServiceTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/job/converter/JobConverterTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/job/mapper/JobMapperTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/runtime/RuntimeServiceTest.java
> chore(controller): add more detail info for job api

- console/src/api/ApiHeader.tsx
- console/src/components/Alias.tsx
- console/src/domain/base/schemas/resource.tsx
- console/src/domain/base/utils/alias.ts
- console/src/domain/dataset/components/DatasetLabel.tsx
- console/src/domain/dataset/components/DatasetTreeSelector.tsx
- console/src/domain/dataset/services/datasetVersion.ts
- console/src/domain/model/services/modelVersion.ts
- console/src/domain/runtime/services/runtimeVersion.ts
- console/src/i18n/locales.ts
- console/src/pages/Dataset/DatasetListCard.tsx
- console/src/pages/Dataset/DatasetVersionListCard.tsx
- console/src/pages/Model/ModelVersionListCard.tsx
- console/src/pages/Runtime/RuntimeListCard.tsx
- console/src/pages/Runtime/RuntimeVersionListCard.tsx
Related to #2569 #2581 
https://github.com/star-whale/starwhale/assets/3217223/e7391aa3-55f4-4fa2-ab2c-d6bfd7de3513
> enhance(console): support custom tag

- client/starwhale/api/_impl/dataset/model.py
- client/starwhale/api/_impl/model.py
- client/starwhale/base/bundle.py
- client/starwhale/base/tag.py
- client/starwhale/core/dataset/cli.py
- client/starwhale/core/dataset/model.py
- client/starwhale/core/dataset/view.py
- client/starwhale/core/model/cli.py
- client/starwhale/core/model/model.py
- client/starwhale/core/model/view.py
- client/starwhale/core/runtime/cli.py
- client/starwhale/core/runtime/model.py
- client/starwhale/core/runtime/view.py
- client/tests/base/test_tag.py
- client/tests/core/test_dataset.py
- client/tests/core/test_model.py
- client/tests/core/test_runtime.py
- client/tests/sdk/test_dataset_sdk.py
- scripts/client_test/cli_test.py
- scripts/client_test/cmds/artifacts_cmd.py
- scripts/example/runtime.yaml
> feat(client): support `--tag` argument for model/runtime/dataset build

- client/starwhale/api/_impl/dataset/model.py
- client/starwhale/base/bundle.py
- client/starwhale/base/cloud.py
- client/starwhale/base/tag.py
- client/starwhale/base/view.py
- client/starwhale/core/dataset/cli.py
- client/starwhale/core/dataset/model.py
- client/starwhale/core/dataset/view.py
- client/starwhale/core/model/cli.py
- client/starwhale/core/model/model.py
- client/starwhale/core/model/view.py
- client/starwhale/core/runtime/cli.py
- client/starwhale/core/runtime/model.py
- client/starwhale/core/runtime/view.py
- client/tests/core/test_model.py
- depends on: https://github.com/star-whale/starwhale/pull/2569
> feat(client): support `swcli model/dataset/runtime tag` for the server instance

- server/controller/src/main/java/ai/starwhale/mlops/domain/model/ModelService.java
> fix(controller): fix the missing function call

- docker/charts/templates/minio.yaml
> bug(charts): fix minio svc name typo

- client/starwhale/api/_impl/dataset/model.py
- client/starwhale/base/bundle_copy.py
- client/starwhale/base/cloud.py
- client/starwhale/base/tag.py
- client/starwhale/core/dataset/cli.py
- client/starwhale/core/dataset/copy.py
- client/starwhale/core/dataset/model.py
- client/starwhale/core/dataset/view.py
- client/starwhale/core/model/cli.py
- client/starwhale/core/model/model.py
- client/starwhale/core/model/view.py
- client/starwhale/core/runtime/cli.py
- client/starwhale/core/runtime/model.py
- client/starwhale/core/runtime/view.py
- client/tests/base/test_copy.py
- client/tests/base/test_tag.py
- client/tests/core/test_model.py
- client/tests/sdk/test_dataset.py
- client/tests/sdk/test_dataset_sdk.py
depends on: 
- https://github.com/star-whale/starwhale/pull/2580
- https://github.com/star-whale/starwhale/pull/2569
- https://github.com/star-whale/starwhale/pull/2581
> feat(client):  support copy with tags for model/runtime/dataset

- scripts/apitest/pytest/test_dataset.py
- scripts/apitest/pytest/test_model.py
- scripts/apitest/pytest/test_runtime.py
- scripts/e2e_test/start_test.sh
related pr: https://github.com/star-whale/starwhale/pull/2569
error message:
> bug(ci): fix server api test typo for tag api

- scripts/apitest/pytest/test_dataset.py
- scripts/apitest/pytest/test_model.py
- scripts/apitest/pytest/test_runtime.py
> bug(ci): fix tag check in the api test

- console/src/domain/job/components/FormFieldDevMode.tsx
- console/src/domain/job/components/FormFieldModel.tsx
- console/src/domain/job/components/FormFieldRuntime.tsx
- console/src/domain/job/components/JobForm.tsx
https://github.com/star-whale/starwhale/assets/3217223/95a79038-8c4e-41c0-b4e6-5c3e512386d9
> fix(console): make runtime in rerun works

- client/.flake8
- client/starwhale/api/_impl/data_store.py
- client/starwhale/api/_impl/dataset/model.py
- client/starwhale/base/blob/file.py
- client/starwhale/base/blob/store.py
- client/starwhale/base/bundle_copy.py
- client/starwhale/base/type.py
- client/starwhale/base/uri/resource.py
- client/starwhale/core/dataset/cli.py
- client/starwhale/core/dataset/model.py
- client/starwhale/core/dataset/view.py
- client/starwhale/mngt/__init__.py
- client/starwhale/utils/fs.py
- client/tests/core/test_dataset.py
- client/tests/sdk/test_dataset_sdk.py
[![asciicast](https://asciinema.org/a/601174.svg)](https://asciinema.org/a/601174)
> feat(client): support build dataset from csv

- client/starwhale/api/_impl/dataset/model.py
- client/starwhale/core/dataset/cli.py
- client/starwhale/core/dataset/model.py
- client/starwhale/core/dataset/view.py
- client/starwhale/utils/fs.py
- client/tests/core/test_dataset.py
- client/tests/sdk/test_dataset_sdk.py
- example/datasets/LLM/ComplexWebQuestions/dataset.py
- example/datasets/LLM/GrailQA_v1.0/dataset.py
- example/datasets/LLM/GraphQuestions/dataset.py
- example/datasets/LLM/KQApro/dataset.py
- example/datasets/LLM/QALD-9/dataset.py
- example/datasets/LLM/webQSP/dataset.py
- changes:
- support jsonl from the local files and remote http files
- support multi files or dir for json
- depends on: https://github.com/star-whale/starwhale/pull/2602
> feat(client): support dataset build from jsonl files

- console/src/api/WithAuth.tsx
- console/src/api/const.ts
- console/src/components/Alias.tsx
- console/src/pages/Dataset/DatasetVersionListCard.tsx
- console/src/pages/Model/ModelVersionListCard.tsx
- console/src/pages/Runtime/RuntimeVersionListCard.tsx
> fix(console): tag edit role access control

- server/controller/src/main/java/ai/starwhale/mlops/api/protocol/dataset/DatasetInfoVo.java
- server/controller/src/main/java/ai/starwhale/mlops/api/protocol/model/ModelInfoVo.java
- server/controller/src/main/java/ai/starwhale/mlops/api/protocol/runtime/RuntimeInfoVo.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/dataset/DatasetService.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/model/ModelService.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/runtime/RuntimeService.java
> chore(controller): add flatten properties for artifact vo

- server/controller/src/main/java/ai/starwhale/mlops/api/DataStoreApi.java
- server/controller/src/main/java/ai/starwhale/mlops/api/DataStoreController.java
- server/controller/src/test/java/ai/starwhale/mlops/api/DataStoreControllerTest.java
add table scan export
cc  @waynelwz
> feat(controller): add table scan export

- client/scripts/sw-docker-entrypoint
- client/starwhale/__init__.py
- client/starwhale/api/_impl/evaluation.py
- client/starwhale/api/_impl/experiment.py
- client/starwhale/api/_impl/job.py
- client/starwhale/api/job.py
- client/starwhale/base/scheduler/__init__.py
- client/starwhale/base/scheduler/step.py
- client/starwhale/base/scheduler/task.py
- client/starwhale/core/model/cli.py
- client/starwhale/core/model/model.py
- client/starwhale/core/model/view.py
- client/tests/core/test_model.py
- client/tests/sdk/test_job.py
- client/tests/sdk/test_model.py
- scripts/client_test/cli_test.py
- scripts/client_test/cmds/artifacts_cmd.py
- scripts/example/src/evaluator.py
- server/controller/pom.xml
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/JobService.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/spec/StepSpec.java
- server/controller/src/main/java/ai/starwhale/mlops/schedule/TaskRunningEnvBuilder.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/job/JobServiceTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/job/spec/JobSpecTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/job/spec/StepSpecTest.java
- server/controller/src/test/java/ai/starwhale/mlops/schedule/TaskRunningEnvBuilderTest.java
- server/pom.xml
Support command line options pass in to handlers
1. List is supported
2. Dataset & Context is supported
3. User could define his/her own `HandlerInput` to define how to explain the options
```python
from starwhale import (
Context,
Dataset,
handler,
IntInput,
ListInput,
HanderInput,
ContextInput,
DatasetInput,
)
class MyInput(HanderInput):
def parse(self, user_input):
return f"MyInput {user_input}"
class X:
def __init__(self) -> None:
self.a = 1
@handler()
def f(
self,
x=ListInput(IntInput),
y=2,
mi=MyInput(),
ds=DatasetInput(required=True),
ctx=ContextInput(),
):
assert self.a + x[0] is 3
assert self.a + x[1] is 2
assert y is 2
assert mi == "MyInput blab-la"
assert isinstance(ds, Dataset)
assert isinstance(ctx, Context)
@handler()
def f(
x=ListInput(IntInput()),
y=2,
mi=MyInput(), …
```
> feat: support model run handler with args

- docker/charts/templates/_helpers.tpl
- scripts/e2e_test/start_test.sh
> fix(chart): add default pypi configs in chart

- docker/charts/templates/controller-deployment.yaml
> chore(helm): update controller k8s probe config

- server/controller/src/main/java/ai/starwhale/mlops/api/protocol/job/JobVo.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/converter/JobConverter.java
> chore(controller): add stepSpec property for jobVo

- client/tests/core/test_runtime.py
related: https://github.com/star-whale/starwhale/actions/runs/5921313118/job/16053916883
> bug(client): fix runtime quickstart unit test

- client/starwhale/utils/fs.py
- example/llm-leaderboard/.gitignore
- example/llm-leaderboard/README.md
- example/llm-leaderboard/requirements.txt
- example/llm-leaderboard/runtime.yaml
- example/llm-leaderboard/src/benchmark/__init__.py
- example/llm-leaderboard/src/benchmark/base.py
- example/llm-leaderboard/src/benchmark/cmmlu.py
- example/llm-leaderboard/src/benchmark/consts.py
- example/llm-leaderboard/src/chat.py
- example/llm-leaderboard/src/cli/__init__.py
- example/llm-leaderboard/src/cli/build.py
- example/llm-leaderboard/src/cli/leaderboard.py
- example/llm-leaderboard/src/cli/submit.py
- example/llm-leaderboard/src/evaluation.py
- example/llm-leaderboard/src/llm/__init__.py
- example/llm-leaderboard/src/llm/aquila.py
- example/llm-leaderboard/src/llm/baichuan.py
- example/llm-leaderboard/src/llm/base.py
- example/llm-leaderboard/src/llm/chatglm.py
- example/llm-leaderboard/src/llm/llama.py
- example/llm-leaderboard/src/llm/qwen.py
- example/llm-leaderboard/src/main.py
- benchmark: cmmlu
- models:
- llama, llama2
- baichuan
- qwen
- chatglm, chatglm2
- aquila
- https://cloud.starwhale.cn/projects/257/evaluations
> example(LLM): add llm leaderboard examples

- console/src/domain/job/components/FormFieldModel.tsx
- console/src/domain/job/components/JobForm.tsx
- console/src/domain/job/schemas/job.tsx
- console/src/domain/setting/components/ResourcePoolSelector.tsx
> fix(console): make resource pool and step spec works in rerun

- server/controller/src/main/java/ai/starwhale/mlops/api/ProjectController.java
- server/controller/src/main/java/ai/starwhale/mlops/api/protocol/project/CreateProjectRequest.java
- server/controller/src/main/java/ai/starwhale/mlops/api/protocol/project/UpdateProjectRequest.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/project/ProjectService.java
- server/controller/src/test/java/ai/starwhale/mlops/api/ProjectControllerTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/project/ProjectServiceTest.java
> fix(controller): use current user when create project

- console/src/domain/job/components/FormFieldModel.tsx
- console/src/domain/job/components/JobForm.tsx
- console/src/pages/Project/JobNewCard.tsx
> fix(console): support job form auto fill disable

- client/starwhale/base/view.py
- client/starwhale/core/dataset/view.py
- client/starwhale/core/job/cli.py
- client/starwhale/core/job/model.py
- client/starwhale/core/job/view.py
- client/starwhale/core/model/model.py
- client/starwhale/core/model/view.py
- client/starwhale/core/project/view.py
- client/starwhale/core/runtime/view.py
- client/tests/core/test_job.py
> bug(client): fix job list show error for server instance

- example/llm-leaderboard/README.md
- example/llm-leaderboard/src/cli/__init__.py
- example/llm-leaderboard/src/cli/leaderboard.py
- example/llm-leaderboard/src/llm/base.py
- example/llm-leaderboard/src/llm/llama.py
- example/llm-leaderboard/src/llm/qwen.py
- supports llama2-chinese/alpaca  for 7b/13b models
- jobs:
- https://cloud.starwhale.cn/projects/257/jobs/722/tasks
- https://cloud.starwhale.cn/projects/257/jobs/721/tasks
- https://cloud.starwhale.cn/projects/257/jobs/720/tasks
- https://cloud.starwhale.cn/projects/257/jobs/719/tasks
> example(LLM): support llama2 chinese models

- console/packages/starwhale-core/src/context/PanelContextProvider.tsx
- console/packages/starwhale-core/src/datastore/hooks/useDatastorePage.tsx
- console/packages/starwhale-core/src/datastore/hooks/useDatastoreQueryParams.tsx
- console/packages/starwhale-core/src/events/app.ts
- console/packages/starwhale-core/src/form/WidgetFormModal.tsx
- console/packages/starwhale-ui/src/GridTable/components/ConfigColumns/ConfigColumns.tsx
- console/packages/starwhale-ui/src/GridTable/hooks/useGrid.ts
- console/packages/starwhale-ui/src/GridTable/hooks/useGridCurrentView.tsx
- console/packages/starwhale-ui/src/GridTable/store/StoreUpdater/index.tsx
- console/packages/starwhale-ui/src/GridTable/store/store.ts
- console/packages/starwhale-ui/src/RJSFForm/widgets/SelectWidget/index.tsx
- console/packages/starwhale-ui/src/Transfer/Transfer.tsx
- console/packages/starwhale-ui/src/Transfer/TransferList.tsx
- console/packages/starwhale-widgets/src/SectionWidget/index.tsx
- console/src/components/Editor/EvalSelectForm.tsx
- console/src/components/Editor/EvalSelectList.tsx
- console/src/pages/BaseSubLayout.tsx
- console/src/pages/Report/ReportEdit.tsx
- console/src/pages/Report/ReportOverviewLayout.tsx
> fix(console): new eval select logic/report header fixed etc

- console/package.json
- console/packages/starwhale-ui/src/MonacoEditor/index.tsx
- console/src/domain/job/components/ExecutorForm.tsx
- console/src/domain/job/components/FormFieldModel.tsx
- console/src/pages/Admin/SystemSettings.tsx
- console/src/pages/Model/ModelVersionOverviewFiles.tsx
- console/yarn.lock
> update(console): monaco editor disable remote load from cdn

- server/controller/src/main/java/ai/starwhale/mlops/api/ModelApi.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/project/ProjectDao.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/project/ProjectDaoTest.java
- Allow model ID in model-related getting url
- Reject the request if multiple projects by name are found
> fix(controller): model related api support model id

- server/controller/src/main/java/ai/starwhale/mlops/api/ModelController.java
> fix(controller): model path uri do not work

- console/src/domain/model/hooks/useModelFiles.ts
- console/src/pages/Model/ModelVersionOverviewFiles.tsx
> fix(console): error occurs when list model by project name

- client/starwhale/base/view.py
- client/starwhale/core/dataset/cli.py
- client/starwhale/core/model/cli.py
- client/starwhale/core/runtime/cli.py
- client/tests/core/test_runtime.py
> fix(client): prevent modification of built-in tags

- server/controller/src/main/java/ai/starwhale/mlops/schedule/impl/k8s/ResourceOverwriteSpec.java
- server/controller/src/test/java/ai/starwhale/mlops/schedule/impl/k8s/ResourceOverwriteSpecTest.java
> fix(controller): prevent overflow when setting the default memory request

- example/llm-leaderboard/.gitignore
- example/llm-leaderboard/leaderboard.md
- example/llm-leaderboard/src/benchmark/base.py
- example/llm-leaderboard/src/benchmark/cmmlu.py
- example/llm-leaderboard/src/cli/__init__.py
- example/llm-leaderboard/src/cli/build.py
- example/llm-leaderboard/src/evaluation.py
- example/llm-leaderboard/src/llm/aquila.py
- example/llm-leaderboard/src/llm/baichuan.py
- example/llm-leaderboard/src/llm/base.py
- example/llm-leaderboard/src/llm/chatglm.py
- example/llm-leaderboard/src/llm/llama.py
- example/llm-leaderboard/src/llm/qwen.py
- add `explanaion` field
- render `README.md` for the specified model automatically
- support `--push` for model build
- support `build --model all` to build all models
> example(LLM): tune llm leaderboard for explanaion and readme

- console/playwright/tests/admin-project.spec.ts
- console/playwright/tests/admin-setting.spec.ts
> fix(console): e2e text button to icon button

- console/packages/starwhale-core/src/form/WidgetFormModal.tsx
- console/packages/starwhale-ui/src/RJSFForm/widgets/SelectWidget/index.tsx
- console/packages/starwhale-ui/src/Select/Select.tsx
- console/src/domain/job/components/JobStatusSelector.tsx
- console/src/domain/model/components/ModelMultiSelector.tsx
- console/src/pages/Evaluation/EvaluationListCard.tsx
> feat(console): support eval table model multi select

- server/controller/src/main/java/ai/starwhale/mlops/domain/project/mapper/ProjectMapper.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/project/mapper/ProjectMapperTest.java
> fix(controller): fix project count error

- example/llm-leaderboard/src/llm/__init__.py
- example/llm-leaderboard/src/llm/tiger.py
> example(LLM): support tigerbot models

- example/llm-leaderboard/src/llm/__init__.py
- example/llm-leaderboard/src/llm/xverse.py
- https://cloud.starwhale.cn/projects/349/jobs/839/tasks
- https://cloud.starwhale.cn/projects/349/jobs/837/tasks
> example(LLM): support xverse llm models

- server/controller/src/main/java/ai/starwhale/mlops/domain/job/storage/JobRepo.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/job/storage/JobRepoTest.java
built-in jobs show in evaluation list without an id but only start time and finish time
> fix(controller): fix built-in job shows on evaluation list

- server/controller/src/main/java/ai/starwhale/mlops/api/protocol/report/CreateReportRequest.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/report/mapper/ReportMapper.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/report/ReportMapperTest.java
> fix(controller): report desc can't update to empty

- console/packages/starwhale-ui/src/GridTable/GridCombineTable.tsx
- console/packages/starwhale-ui/src/GridTable/GridTable.tsx
- console/packages/starwhale-ui/src/GridTable/hooks/useGridSelection.ts
- console/packages/starwhale-ui/src/GridTable/store/StoreUpdater/index.tsx
- console/packages/starwhale-ui/src/GridTable/store/store.ts
- console/packages/starwhale-ui/src/GridTable/types.ts
> fix(console):  cache selected record in case of data missing when pagination

- server/controller/src/main/java/ai/starwhale/mlops/StarwhaleControllerApplication.java
> chore(controller): show the exception of cmdline runner

- client/starwhale/api/_impl/dataset/builder/mapping_builder.py
> fix(client): flush of dataset may stuck after putting failed

- console/packages/starwhale-core/src/form/WidgetFormModal.tsx
- console/packages/starwhale-core/src/widget/withWidgetDynamicProps.tsx
- console/packages/starwhale-ui/src/Plotly/PlotlyViewer.tsx
- console/src/hooks/usePage.ts
- console/src/pages/Evaluation/EvaluationListResult.tsx
- console/src/pages/Model/ModelListCard.tsx
> update(console): decrease page size, min width for ploty chart

- console/packages/starwhale-core/src/types/index.ts
- console/packages/starwhale-core/src/widget/withWidgetDynamicProps.tsx
- console/packages/starwhale-ui/src/GridTable/store/StoreUpdater/index.tsx
- console/packages/starwhale-ui/src/GridTable/types.ts
- console/packages/starwhale-ui/src/base/data-table/headers/header-bar.tsx
- console/packages/starwhale-ui/src/base/data-table/headers/header-cell.tsx
- console/packages/starwhale-widgets/src/PanelTableWidget/index.tsx
- console/packages/starwhale-widgets/src/SectionWidget/component/SectionAccordionPanel.tsx
- console/packages/starwhale-widgets/src/SectionWidget/index.tsx
- console/src/components/Editor/EvalSelectList.tsx
- console/src/pages/Evaluation/EvaluationWidgetResults.tsx
- console/src/pages/Job/JobWidgetResults.tsx
fix: default results panel init without dynamic args so same config based on model name will be used, now use mode version for unique config
> update(console): report readonly mode remove edit actions

- client/starwhale/api/_impl/job/model.py
- client/starwhale/base/models/job.py
- client/starwhale/base/scheduler/step.py
- client/starwhale/base/store.py
- client/starwhale/base/view.py
- client/starwhale/core/job/model.py
- client/starwhale/core/job/view.py
- client/starwhale/core/model/model.py
- client/starwhale/utils/__init__.py
- client/tests/core/test_eval.py
- client/tests/core/test_job.py
- client/tests/data/job/job_manifest.yaml
> refactor(client): add job manifest model

- example/llm-leaderboard/runtime-analysis.yaml
- example/llm-leaderboard/src/analysis.py
- https://cloud.starwhale.cn/projects/349/evaluations/859/results
> example(LLM): add llm leaderboard analysis

- server/controller/src/main/java/ai/starwhale/mlops/api/DataStoreController.java
- server/controller/src/main/java/ai/starwhale/mlops/datastore/DataStore.java
- server/controller/src/main/java/ai/starwhale/mlops/datastore/exporter/RecordsStreamingExporter.java
- server/controller/src/main/java/ai/starwhale/mlops/datastore/exporter/RecordsStreamingExporterCsv.java
- server/controller/src/test/java/ai/starwhale/mlops/api/DataStoreControllerTest.java
- server/controller/src/test/java/ai/starwhale/mlops/datastore/exporter/RecordsExporterStreamingCsvTest.java
when limit is smaller than 0 , all results in the table will be exported
cc @waynelwz @lijing-susan
> feat(controller): export full table result

- client/starwhale/api/_impl/evaluation.py
- client/starwhale/api/_impl/job/handler.py
- client/tests/sdk/test_job_handler.py
- example/mnist/mnist/evaluator.py
```python
from starwhale import PipelineHandler, multi_classification
class MockHandler(PipelineHandler):
@PipelineHandler.run(replicas=4, resources={"memory": 200 * 1024})
def predict(self, *args): ...
@multi_classification()
@PipelineHandler.run(resources={"memory": 200 * 1024, "nvidia.com/gpu": 1})
def evaluate(self, *args, **kwargs): ...
```
> feat(SDK): PipelineHandler supports replicas and resources spec

- console/src/components/Link/Link.tsx
> fix(console): vscode error link

- client/starwhale/api/_impl/evaluation.py
- example/mnist/mnist/evaluator.py
- example/mnist/mnist/plain_evaluator.py
> example: fix mnist memory limit typo

- example/mnist/mnist/evaluator.py
- example/mnist/mnist/plain_evaluator.py
> example: update mnist memory limit value

- docker/Makefile
- error: https://github.com/star-whale/starwhale/actions/runs/6082448064/job/16500262722
- related pr: https://github.com/star-whale/starwhale/pull/2651/files#diff-2d5cf8144e7448f74d50e9f30614362fbba55750d498273b487f52e836a9721a
> bug(ci): fix dockerfile name typo

- example/llm-leaderboard/src/llm/baichuan.py
- support baichuan2 7b/7b-base/13b/13b-base models
> example(LLM): support baichuan2 llm models

- console/packages/starwhale-ui/src/Markdown/markdown.css
- console/packages/starwhale-ui/src/Text/Text.tsx
- console/src/domain/job/components/JobForm.tsx
- console/src/pages/Evaluation/EvaluationWidgetResults.tsx
- console/src/pages/Job/JobOverview.tsx
> update(console): job overview with actions / disable markdown dark theme

- console/src/i18n/locales.ts
- console/src/pages/Report/ReportPreview.tsx
> update(console): mobile experience notice

- server/controller/src/main/java/ai/starwhale/mlops/api/DatasetApi.java
- server/controller/src/main/java/ai/starwhale/mlops/api/DatasetController.java
- server/controller/src/main/java/ai/starwhale/mlops/api/ModelApi.java
- server/controller/src/main/java/ai/starwhale/mlops/api/ModelController.java
- server/controller/src/main/java/ai/starwhale/mlops/api/RuntimeApi.java
- server/controller/src/main/java/ai/starwhale/mlops/api/RuntimeController.java
- server/controller/src/main/java/ai/starwhale/mlops/api/protocol/bundle/DataRange.java
- server/controller/src/main/java/ai/starwhale/mlops/api/protocol/bundle/DataScope.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/dataset/DatasetService.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/model/ModelService.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/runtime/RuntimeService.java
- server/controller/src/test/java/ai/starwhale/mlops/api/DatasetControllerTest.java
- server/controller/src/test/java/ai/starwhale/mlops/api/ModelControllerTest.java
- server/controller/src/test/java/ai/starwhale/mlops/api/RuntimeControllerTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/dataset/DatasetServiceTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/model/ModelServiceTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/runtime/RuntimeServiceTest.java
> feat(controller): support set data range in artifact list-view-tree api 

- scripts/client_test/cli_test.sh
> fix(ci): remove the useless comment

- client/starwhale/api/_impl/job/model.py
- client/starwhale/base/bundle_copy.py
- client/starwhale/base/client/client.py
- client/starwhale/base/cloud.py
- client/starwhale/core/job/model.py
- client/starwhale/core/model/model.py
- client/starwhale/core/project/model.py
> refactor(client): parse respone when init

- server/controller/src/main/java/ai/starwhale/mlops/api/protocol/job/JobRequest.java
- server/controller/src/test/java/ai/starwhale/mlops/api/protocol/job/JobRequestTest.java
> fix(controller): remove not null constraint for job creation

- client/starwhale/api/_impl/job/model.py
> chore(SDK): fix job doc typo

- client/starwhale/api/_impl/evaluation.py
for the following cases:
- multi datasets
- `ignore_error=True`, but meets predict exception.
- batch > 1,  the number of input data is not equal to the number of predict results
> enhance(client): optimzie the predict count logging for greater accuracy

- server/controller/src/main/java/ai/starwhale/mlops/datastore/DataStore.java
- server/controller/src/test/java/ai/starwhale/mlops/api/DataStoreControllerTest.java
- server/controller/src/test/java/ai/starwhale/mlops/datastore/DataStoreTest.java
> chore(datastore): remove schema checking when query or scan

- README_ZH.md
- https://github.com/tianweidut/starwhale/tree/doc/update-readme
- https://github.com/tianweidut/starwhale/blob/doc/update-readme/README_ZH.md
> doc: update github readme

- console/index.html
- console/packages/starwhale-ui/src/DynamicSelector/DynamicSelector.tsx
- console/packages/starwhale-ui/src/DynamicSelector/SelectorItemRender.tsx
- console/packages/starwhale-ui/src/DynamicSelector/SelectorPopover.tsx
- console/packages/starwhale-ui/src/DynamicSelector/StyledComponent.tsx
- console/packages/starwhale-ui/src/DynamicSelector/index.tsx
- console/packages/starwhale-ui/src/DynamicSelector/types.tsx
- console/packages/starwhale-ui/src/Tree/StyledComponent.tsx
- console/packages/starwhale-ui/src/Tree/Tree.tsx
- console/packages/starwhale-ui/src/Tree/hooks/useTreeDataLoader.tsx
- console/packages/starwhale-ui/src/base/tree-view/styled-components.ts
- console/src/components/QuickGroup.tsx
- console/src/domain/dataset/components/DatasetTreeSelector.tsx
- console/src/domain/job/components/FormFieldModel.tsx
- console/src/domain/model/components/ModelLabel.tsx
- console/src/domain/model/components/ModelTreeSelector.tsx
- console/src/domain/runtime/components/RuntimeTreeSelector.tsx
- console/src/i18n/locales.ts
- console/src/pages/Project/ProjectListCard.tsx
- console/src/styles/_global.scss
- console/tailwind.config.js
> feat(console): tree selector support quick retrieval by shared/current/lastest

- client/starwhale/core/runtime/process.py
> chore(client): config resource type for runtime uri

- client/starwhale/api/_impl/dataset/model.py
- client/starwhale/base/bundle.py
- client/starwhale/base/client/api/model.py
- client/starwhale/base/client/api/runtime.py
- client/starwhale/base/client/models/models.py
- client/starwhale/base/cloud.py
- client/starwhale/base/models/base.py
- client/starwhale/base/models/dataset.py
- client/starwhale/base/models/job.py
- client/starwhale/base/models/model.py
- client/starwhale/base/models/runtime.py
- client/starwhale/base/uri/instance.py
- client/starwhale/base/uri/project.py
- client/starwhale/base/uri/resource.py
- client/starwhale/base/view.py
- client/starwhale/core/dataset/model.py
- client/starwhale/core/dataset/view.py
- client/starwhale/core/job/model.py
- client/starwhale/core/job/view.py
- client/starwhale/core/model/model.py
- client/starwhale/core/model/view.py
- client/starwhale/core/runtime/model.py
- client/starwhale/core/runtime/view.py
- client/tests/base/test_bundle.py
- client/tests/core/test_dataset.py
- client/tests/core/test_model.py
- client/tests/core/test_runtime.py
- client/tests/sdk/test_dataset_sdk.py
- client/tests/sdk/test_evaluation.py
> refactor(client): use pydantic model in runtime context

- console/src/components/QuickGroup.tsx
- console/src/domain/dataset/components/DatasetTreeSelector.tsx
- console/src/domain/dataset/hooks/useFetchDatasetTree.ts
- console/src/domain/dataset/services/dataset.ts
- console/src/domain/model/components/ModelTreeSelector.tsx
- console/src/domain/model/hooks/useFetchModelTree.ts
- console/src/domain/model/services/model.ts
- console/src/domain/runtime/components/RuntimeTreeSelector.tsx
- console/src/domain/runtime/hooks/useFetchRuntimeTree.ts
- console/src/domain/runtime/services/runtime.ts
> update(console): tree selector with recent api

- server/controller/src/main/java/ai/starwhale/mlops/domain/dataset/dataloader/DataStoreIndexProvider.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/dataset/dataloader/ReadRangeTest.java
> fix(controller): dataset load with wrong key type

- example/datasets/coco/README.md
- example/datasets/coco/coco_builder.py
- example/datasets/coco/example.py
> example(dataset): add coco ds sdk builder

- console/packages/starwhale-ui/src/Button/Button.tsx
- console/src/components/Editor/EvalSelectList.tsx
- console/src/domain/dataset/hooks/useFetchDatasets.ts
- console/src/domain/dataset/services/dataset.ts
- console/src/domain/model/hooks/useFetchModels.ts
- console/src/domain/model/services/model.ts
- console/src/domain/runtime/hooks/useFetchRuntimes.ts
- console/src/domain/runtime/services/runtime.ts
- console/src/i18n/locales.ts
- console/src/pages/Admin/UserManagement.tsx
- console/src/pages/Dataset/DatasetListCard.tsx
- console/src/pages/Model/ModelListCard.tsx
- console/src/pages/Project/ProjectListCard.tsx
- console/src/pages/Report/ReportPreview.tsx
- console/src/pages/Runtime/RuntimeListCard.tsx
- console/src/pages/Runtime/RuntimeVersionListCard.tsx
> update(console): support list search by name / fix react attr camelcase warning

- client/starwhale/base/client/api/job.py
- client/starwhale/base/client/api/model.py
- client/starwhale/base/client/api/runtime.py
- client/starwhale/base/client/client.py
- client/starwhale/core/model/model.py
- client/starwhale/core/model/view.py
- client/starwhale/core/runtime/model.py
> chore(client): support filter with the server api

- example/huge-tasks/README.md
- example/huge-tasks/dataset.py
- example/huge-tasks/evaluation.py
- example/huge-tasks/runtime.yaml
- example/huge-tasks/utils.py
> example: add huge tasks example

- .github/file-filter.yml
- .github/workflows/e2e-test.yml
- client/starwhale/base/client/models/models.py
- scripts/e2e_test/start_test.sh
Add OpenAPI model test in e2e test, this test will be triggered when:
- `e2e` labels in PR
- `server/controller/src/main/java/ai/starwhale/mlops/api/` folder changes
If the test fails, it will show diff of the models.py like https://github.com/star-whale/starwhale/actions/runs/6169069387/job/16742660920#step:19:265
```
openapi model is not up to date
+ git diff
diff --git a/client/starwhale/base/client/models/models.py b/client/starwhale/base/client/models/models.py
index ac93453..a4a563e 100644
--- a/client/starwhale/base/client/models/models.py
+++ b/client/starwhale/base/client/models/models.py
@@ -297,10 +297,10 @@ class JobRequest(BaseModel):
time_to_live_in_sec: Optional[int] = Field(None, alias='timeToLiveInSec')
model_version_url: str = Field(..., alias='modelVersionUrl') …
```
> chore(ci): add open api model test in e2e test

- client/starwhale/api/_impl/dataset/model.py
- client/starwhale/base/client/api/dataset.py
- client/starwhale/base/client/api/runtime.py
- client/starwhale/base/models/dataset.py
- client/starwhale/base/view.py
- client/starwhale/core/dataset/model.py
- client/starwhale/core/dataset/view.py
- client/tests/core/test_dataset.py
- client/tests/sdk/test_dataset_sdk.py
> refactor(client): dataset related model

- client/starwhale/base/client/models/models.py
- server/controller/src/main/java/ai/starwhale/mlops/api/JobController.java
- server/controller/src/main/java/ai/starwhale/mlops/api/protocol/event/Event.java
- server/controller/src/main/java/ai/starwhale/mlops/api/protocol/event/EventRequest.java
- server/controller/src/main/java/ai/starwhale/mlops/api/protocol/event/EventVo.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/event/EventConverter.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/event/EventService.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/event/mapper/EventMapper.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/event/po/EventEntity.java
- server/controller/src/main/resources/db/migration/v0_4_0/V0_4_0_019__add_event_table.sql
- server/controller/src/test/java/ai/starwhale/mlops/api/JobControllerTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/event/EventServiceTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/event/mapper/EventMapperTest.java
Add the following APIs:
(Note that the data field is optional, and must be a valid json string if set)
- Get event list of the job or task
GET  `/api/v1/project/{projectUrl}/job/{jobUrl}/event`
```json
{
"code": "string",
"message": "string",
"data": [
{
"eventType": "INFO",
"source": "CLIENT",
"message": "string",
"data": "string",
"timestamp": 0,
"id": 0
}
]
}
```
- Add an event for the job or task
POST `/api/v1/project/{projectUrl}/job/{jobUrl}/event`
```json
{
"eventType": "INFO",
"source": "CLIENT",
"message": "string",
"data": "string",
"timestamp": 0,
"relatedResource": {
"resource": "JOB",
"id": 0
}
}
```
> feat(controller): support event api for job

- client/starwhale/core/dataset/type.py
- client/tests/sdk/test_dataset.py
> chore(dataset): fix dataset types default init value issue

- example/huge-tasks/README.md
- example/huge-tasks/dataset.py
- example/huge-tasks/dataset.yaml
- scripts/client_test/cli_test.py
> ci(e2e): add huge-tasks example into e2e

- client/starwhale/api/_impl/data_store.py
- client/starwhale/base/cloud.py
- client/starwhale/core/dataset/copy.py
- update dataset copy client ui
- merge all blobs progress into the one progress
- add progress for dataset rows update
- before:
- after:
> chore(client): tune dataset copy progress ui

- client/starwhale/api/_impl/data_store.py
- client/starwhale/core/dataset/copy.py
- client/starwhale/core/dataset/tabular.py
- client/starwhale/core/dataset/type.py
- client/tests/core/test_dataset.py
- client/tests/sdk/test_dataset.py
- client/tests/sdk/test_dataset_sdk.py
> feat(dataset): support mixed types in the list or tuple for dataset features

- console/packages/starwhale-ui/src/GridDatastoreTable/components/Preview.tsx
- console/packages/starwhale-ui/src/GridTable/GridTable.tsx
- console/packages/starwhale-ui/src/GridTable/hooks/useGrid.ts
- console/packages/starwhale-ui/src/GridTable/hooks/useGridCellPreview.tsx
- console/packages/starwhale-ui/src/base/data-table/cells/cell-placement.tsx
- console/src/styles/_global.scss
> update(console): support record prev/next preview

- example/mnist/mnist/dataset_read.py
fix https://github.com/star-whale/starwhale/actions/runs/6194570712/job/16817783072
> fix(ci): ignore call to untyped function "show" in typed context

- client/starwhale/base/client/models/models.py
- client/tests/core/test_dataset.py
- console/src/components/Shared.tsx
- console/src/domain/dataset/components/DatasetForm.tsx
- console/src/domain/dataset/schemas/dataset.tsx
- console/src/domain/dataset/schemas/datasetVersion.tsx
- console/src/domain/model/schemas/model.tsx
- console/src/domain/model/schemas/modelVersion.tsx
- console/src/domain/runtime/schemas/runtime.tsx
- console/src/domain/runtime/schemas/runtimeVersion.tsx
- console/src/pages/Dataset/DatasetVersionOverview.tsx
- console/src/pages/Model/ModelVersionOverview.tsx
- console/src/pages/Runtime/RuntimeVersionOverview.tsx
- server/controller/src/main/java/ai/starwhale/mlops/api/protocol/dataset/DatasetVersionVo.java
- server/controller/src/main/java/ai/starwhale/mlops/api/protocol/dataset/DatasetViewVo.java
- server/controller/src/main/java/ai/starwhale/mlops/api/protocol/model/ModelVersionVo.java
- server/controller/src/main/java/ai/starwhale/mlops/api/protocol/model/ModelViewVo.java
- server/controller/src/main/java/ai/starwhale/mlops/api/protocol/runtime/RuntimeVersionVo.java
- server/controller/src/main/java/ai/starwhale/mlops/api/protocol/runtime/RuntimeViewVo.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/dataset/DatasetService.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/dataset/converter/DatasetVersionVoConverter.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/model/ModelService.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/model/converter/ModelVersionVoConverter.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/runtime/RuntimeService.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/runtime/converter/RuntimeVersionConverter.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/dataset/converter/DatasetVersionVoConverterTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/model/ModelVersionConverterTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/runtime/RuntimeVersionConverterTest.java
> refactor(controller): make shared boolean

- server/controller/src/main/java/ai/starwhale/mlops/schedule/impl/k8s/K8sJobTemplate.java
- server/controller/src/main/java/ai/starwhale/mlops/schedule/impl/k8s/K8sSwTaskScheduler.java
- server/controller/src/main/java/ai/starwhale/mlops/schedule/impl/k8s/SwSchedulerFactoryK8S.java
- server/controller/src/main/resources/application.yaml
- server/controller/src/test/java/ai/starwhale/mlops/schedule/impl/k8s/K8sJobTemplateTest.java
- server/controller/src/test/java/ai/starwhale/mlops/schedule/impl/k8s/K8sSwTaskSchedulerTest.java
current data consumption don't support the k8s' pod to restart by it self.
> fix(controller): remove backoff limit

- docker/charts/values.minikube.cn.yaml
Douban PyPI experiences occasional slowness and outdated packages.
> chore(helm): update pypi index url for minikube cn

- console/packages/starwhale-widgets/src/PanelTableWidget/index.tsx
> update(console): local debug params  for raw table name show

- example/huge-tasks/model.yaml
e2e needs model.yaml to build model package.
> chore(ci): add huge-tasks model.yaml for e2e case

- console/packages/starwhale-ui/src/Select/Toggle.tsx
- console/packages/starwhale-ui/src/TiptapEditor/components/EditorBubbleMenu.tsx
- console/src/components/LogViewer/LogViewer.tsx
- console/src/pages/Admin/UserManagement.tsx
- console/src/pages/Evaluation/EvaluationWidgetResults.tsx
- console/src/pages/Job/JobTasks.tsx
* update: temporary fix duplicate panel configuration
* fix: show popover when fullscreen / show log viewer when too many tasks
* optimize: user manage toggle ui
> update(console): temporary fix duplicate panel configuration / log viewer optimize when fullscreen

- client/starwhale/api/_impl/wrapper.py
- client/tests/sdk/test_wrapper.py
> enhance(client): add datastore log(evaluation, dataset) id type validation

- example/mnist/mnist/evaluator.py
- example/mnist/mnist/plain_evaluator.py
- scripts/client_test/cli_test.py
> chore(ci): tune examples for e2e

- client/starwhale/core/dataset/copy.py
> enhance(dataset): optimze dataset copy performance to minimize redundant full table scans

- scripts/client_test/cli_test.py
Some test examples should use non-pytorch runtime.
> chore(e2e): tune random runtime for examples

- client/setup.py
- client/starwhale/api/_impl/data_store.py
- client/tests/sdk/test_data_store.py
- client/tests/sdk/test_track.py
> optimize(datastore): speed up opening datastore

- console/packages/starwhale-ui/src/GridTable/store/store.ts
- console/packages/starwhale-ui/src/Transfer/Transfer.tsx
- console/packages/starwhale-ui/src/Transfer/TransferList.tsx
- console/packages/starwhale-ui/src/Viewer/TextViewer.tsx
- console/packages/starwhale-ui/src/base/data-table/column.tsx
- console/packages/starwhale-ui/src/base/data-table/data-custom-table.tsx
- console/packages/starwhale-ui/src/base/data-table/measure-column-widths.tsx
- console/packages/starwhale-ui/src/base/data-table/types.tsx
- console/packages/starwhale-ui/src/utils/useUnsortedSelection.ts
fix(console): column filter status error when drag
> feat(console): save column width/resize status to config

- client/starwhale/api/_impl/data_store.py
- client/starwhale/api/_impl/dataset/builder/mapping_builder.py
> enhance(datastore): auto dump memory table and reduce memory usage when building dataset

- client/starwhale/api/_impl/dataset/builder/mapping_builder.py
- client/starwhale/core/dataset/model.py
- client/tests/core/test_dataset.py
- client/tests/sdk/test_dataset.py
- client/tests/sdk/test_dataset_sdk.py
> enhance(dataset): fix dataset flush block when meets the unsupport types in the features

- example/huge-tasks/evaluation.py
- scripts/client_test/cli_test.py
> chore(ci): speedup e2e with disable huge-task in standalone

- docker/charts/templates/controller-deployment.yaml
- docker/charts/values.yaml
> chore(chart): add wal log cache support

- client/starwhale/api/_impl/data_store.py
- client/starwhale/base/models/base.py
> chore(datastore): add tombstone and checkpoint to manifest

- client/starwhale/api/_impl/evaluation/__init__.py
- client/starwhale/api/_impl/job/handler.py
- client/starwhale/core/model/copy.py
- client/starwhale/utils/__init__.py
- client/tests/sdk/test_job_handler.py
- example/mnist/mnist/evaluator.py
- example/mnist/mnist/plain_evaluator.py
> chore(SDK): support memory resource for human

- client/starwhale/api/_impl/dataset/model.py
- client/tests/sdk/test_dataset_sdk.py
- chages:
- __len__ slow but accuracy
- approximate_size fast but maybe inaccuracy
> enhance(dataset): tune the length of dataset

- client/starwhale/api/_impl/data_store.py
- client/tests/sdk/test_data_store.py
> enhance(datastore): support tombstone in local

- client/starwhale/core/runtime/model.py
- client/tests/core/test_runtime.py
> enhance(client): make building environment python version as the runtime default python version

- server/controller/src/main/java/ai/starwhale/mlops/domain/dataset/upload/DatasetUploader.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/model/ModelService.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/runtime/RuntimeService.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/dataset/DatasetUploaderTest.java
> chore(controller): unify artifact's creation conflict code

- client/starwhale/api/_impl/service.py
- client/tests/data/sdk/service/default_class.py
- client/tests/sdk/test_service.py
> fix(client): model build with example failed with the latest gradio version

- client/starwhale/api/_impl/data_store.py
- client/tests/sdk/test_data_store.py
> feat(datastore): datastore in standalone support checkpoint

- .github/workflows/codeql-analysis.yml
- .github/workflows/e2e-test.yml
dig for GitLFS unexpected usage, every day will use '~1.29GB' brandwith.
- remove cron
- disable codeQL
> chore(ci): disable e2e and codeql cron

- server/controller/src/main/java/ai/starwhale/mlops/datastore/parquet/SwReadSupport.java
- server/controller/src/main/java/ai/starwhale/mlops/datastore/parquet/SwWriteSupport.java
- server/controller/src/test/java/ai/starwhale/mlops/datastore/DataStoreTest.java
- server/controller/src/test/java/ai/starwhale/mlops/datastore/parquet/ParquetReadWriteTest.java
> bugfix(datastore): parquet read/write issue with list/map of objects

- client/starwhale/api/_impl/data_store.py
- client/starwhale/api/_impl/wrapper.py
> chore(client): update TableWriter default limits of run exceptions for fast fail

- console/src/domain/job/components/FormFieldTemplate.tsx
> update(console): job template not required

- server/controller/src/main/java/ai/starwhale/mlops/schedule/impl/k8s/RunExecutorK8s.java
- server/controller/src/main/java/ai/starwhale/mlops/schedule/impl/k8s/log/RunLogK8sCollectorFactory.java
- server/controller/src/main/java/ai/starwhale/mlops/schedule/impl/k8s/log/RunLogK8sStreamingCollector.java
- server/controller/src/main/java/ai/starwhale/mlops/schedule/impl/k8s/log/RunLogOfflineCollectorK8S.java
- server/controller/src/main/java/ai/starwhale/mlops/schedule/impl/k8s/reporting/JobEventHandler.java
- server/controller/src/main/java/ai/starwhale/mlops/schedule/impl/k8s/reporting/PodEventHandler.java
- server/controller/src/test/java/ai/starwhale/mlops/schedule/impl/k8s/JobEventHandlerTest.java
- server/controller/src/test/java/ai/starwhale/mlops/schedule/impl/k8s/PodEventHandlerTest.java
- server/controller/src/test/java/ai/starwhale/mlops/schedule/impl/k8s/RunExecutorK8sTest.java
modify k8s job name to a legal one so that people could edit job yaml
> chore(controller): modify k8s job name to a legal one

- client/starwhale/cli/__init__.py
- client/starwhale/cli/deubg/__init__.py
- client/starwhale/cli/deubg/datastore.py
https://github.com/star-whale/starwhale/assets/3217223/9b1810d3-e0bc-4dc0-85c5-0bde0b5da57c
> enhance(client): add debug cli for data store

- client/tests/sdk/test_track.py
> fix(ut): make testing table of data store stable

- client/starwhale/core/dataset/tabular.py
- client/starwhale/utils/__init__.py
- client/tests/sdk/test_dataset_sdk.py
test for `example/datasets/LLM/KQApro`
> bug(sdk): fix list/tuple types check for converting sequence

- example/nmt/nmt/evaluator.py
> bug(example): fix nmt example typo

- client/starwhale/base/uri/instance.py
- client/starwhale/core/instance/view.py
- client/starwhale/core/model/store.py
- client/starwhale/mngt/__init__.py
- client/starwhale/utils/config.py
- client/tests/utils/test_config.py
> chore(client): fix mypy lint issue

- server/controller/src/main/java/ai/starwhale/mlops/domain/task/converter/TaskBoConverter.java
- server/controller/src/test/java/ai/starwhale/mlops/ObjectMockHolder.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/task/TaskBoConverterTest.java
fix current run is null for a running task after controller restart
> fix(controller): fix current run is null for a running task after controller restart

- console/packages/starwhale-ui/src/GridTable/components/ToolBar/index.tsx
- console/packages/starwhale-ui/src/IconFont/index.tsx
- console/src/domain/job/components/JobActionGroup.tsx
- console/src/i18n/locales.ts
- console/src/pages/Dataset/DatasetVersionListCard.tsx
- console/src/pages/Job/JobListCard.tsx
> fix(console): locale for save as / datset columns / iconfont

- scripts/client_test/cli_test.py
> chore(test): auto copy test use local dataset

- server/controller/src/main/java/ai/starwhale/mlops/domain/dataset/dataloader/DataLoader.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/dataset/dataloader/DataReadManager.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/dataset/dataloader/dao/DataReadLogDao.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/dataset/dataloader/mapper/DataReadLogMapper.java
- server/controller/src/main/resources/application.yaml
- server/controller/src/test/java/ai/starwhale/mlops/domain/dataset/dataloader/MultiConsumerTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/dataset/dataloader/ReadRangeTest.java
Cache the unassigned data to memory(Replace the row lock by 'select ... for update').
> fix(controller): cache unassigned range data to memory for optimise dataset consumption

- console/playwright/tests/admin-project.spec.ts
> update(console): e2e summary moved to overview

- client/starwhale/base/client/client.py
- client/tests/base/client/test_client.py
> chore(client): add retry condition and count limit for api requests

- console/src/domain/job/components/JobForm.tsx
- console/src/domain/job/components/JobStatusSelector.tsx
- console/src/i18n/locales.ts
- console/src/pages/Project/JobNewCard.tsx
> update(console):redirect when job created  / use full job status for advanced search

- client/starwhale/api/_impl/evaluation/pipeline.py
- client/starwhale/api/_impl/job/model.py
- client/starwhale/base/bundle_copy.py
- client/starwhale/consts/__init__.py
- client/starwhale/core/model/cli.py
- client/starwhale/core/model/model.py
- client/tests/core/test_model.py
- client/tests/sdk/test_job_sdk.py
- scripts/client_test/cmds/project_cmd.py
> feat(SDK): add job create sdk

- client/tests/sdk/test_loader.py
fix: https://github.com/star-whale/starwhale/actions/runs/6494737088/job/17638402067
> chore(ci): enhance session consume test stability

- server/controller/src/main/java/ai/starwhale/mlops/configuration/CommonExceptionHandler.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/dataset/dataloader/DataLoader.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/dataset/dataloader/DataReadManager.java
- server/controller/src/main/java/ai/starwhale/mlops/exception/SwRequestFrequentException.java
- server/controller/src/main/resources/application.yaml
- server/controller/src/test/java/ai/starwhale/mlops/domain/dataset/dataloader/MultiConsumerTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/dataset/dataloader/ReadRangeTest.java
close https://github.com/star-whale/starwhale/issues/2836
Add timeout for keylock.
BUG desc:The keyLock don't resolve the case of timeout, so it will be queued a long time even the client has been killed by the timeout error.
> fix(controller): add max wait time for load request

- example/huge-tasks/evaluation.py
> chore(example): update huge-tasks example evaluate validation

- client/starwhale/base/client/models/models.py
- server/controller/src/main/java/ai/starwhale/mlops/api/protocol/task/TaskVo.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/task/converter/TaskConverter.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/task/TaskConverterTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/task/TaskServiceTest.java
> feat(controller): add run info into taskVo

- server/controller/src/main/java/ai/starwhale/mlops/datastore/impl/MemoryTableImpl.java
- server/controller/src/test/java/ai/starwhale/mlops/datastore/impl/MemoryTableImplTest.java
> fix(datastore): normalize the revision in snapshot for backward compatibility

- server/controller/src/main/java/ai/starwhale/mlops/schedule/impl/k8s/reporting/PodEventHandler.java
- server/controller/src/test/java/ai/starwhale/mlops/schedule/impl/k8s/PodEventHandlerTest.java
> fix(controller): add start and stop time for run when canceled

- client/starwhale/api/_impl/data_store.py
- client/starwhale/cli/deubg/datastore.py
- client/tests/sdk/test_data_store.py
> chore(client): support project opt when listing table in debug cli

- scripts/client_test/cli_test.py
- scripts/client_test/cmds/base/invoke.py
> ci(e2e): add comparision between local and remote dataset

- client/starwhale/api/_impl/evaluation/log.py
- client/starwhale/api/_impl/job/model.py
- example/cifar10/READMD.md
- example/cifar10/README-zh.md
- example/imageNet-ft/README-zh.md
- example/mnist/README-zh.md
- example/mnist/README.md
- update Python SDK docs
- remove broken links README for examples
> chore: update docs for sdk and example

- client/tests/sdk/test_track.py
resolve issue: https://github.com/star-whale/starwhale/actions/runs/6481536916/job/17599259840?pr=2838#step:8:1104
> chore(ci): improve tracker run test stability in the slow machine

- client/starwhale/api/_impl/dataset/model.py
- client/starwhale/core/dataset/cli.py
- client/starwhale/core/dataset/model.py
- client/starwhale/core/dataset/view.py
- client/tests/core/test_dataset.py
- client/tests/sdk/test_dataset_sdk.py
> refine(client): dataset head always fetch raw

- client/starwhale/base/client/models/models.py
- server/controller/src/main/java/ai/starwhale/mlops/api/JobController.java
- server/controller/src/main/java/ai/starwhale/mlops/api/protocol/event/Event.java
- server/controller/src/main/java/ai/starwhale/mlops/api/protocol/event/EventRequest.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/event/EventConverter.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/event/EventService.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/event/mapper/EventMapper.java
- server/controller/src/main/resources/application.yaml
- server/controller/src/main/resources/db/migration/v0_4_0/V0_4_0_025__alter_event_resource.sql
- server/controller/src/test/java/ai/starwhale/mlops/domain/event/EventServiceTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/event/mapper/EventMapperTest.java
> enhance(controller): event api support run id

- client/tests/sdk/test_evaluation_pipeline.py
> chore(ci): fix evaluation test typo

- client/starwhale/api/_impl/data_store.py
- client/starwhale/base/client/models/models.py
- client/tests/sdk/test_data_store.py
- client/tests/sdk/test_dataset.py
- server/controller/src/main/java/ai/starwhale/mlops/datastore/ColumnSchema.java
- server/controller/src/main/java/ai/starwhale/mlops/datastore/ColumnSchemaDesc.java
- server/controller/src/main/java/ai/starwhale/mlops/datastore/impl/RecordDecoder.java
- server/controller/src/main/java/ai/starwhale/mlops/datastore/impl/WalRecordDecoder.java
- server/controller/src/main/protobuf/wal.proto
- server/controller/src/test/java/ai/starwhale/mlops/datastore/DataStoreTest.java
> enhance(datastore): support multiple type of list

- console/packages/starwhale-ui/src/Markdown/Markdown.tsx
- console/packages/starwhale-ui/src/Markdown/markdown.css
- console/src/assets/docs/QuickStartNewModelEN.md
- console/src/assets/docs/QuickStartNewModelZH.md
- console/src/components/Link/ButtonLink.tsx
- console/src/consts/index.ts
- console/src/domain/project/components/QuickStart.tsx
- console/src/domain/project/components/QuickStartNewModel.tsx
- console/src/hooks/useLocaleConst.ts
- console/src/i18n/locales.ts
- console/src/pages/Model/ModelListCard.tsx
- console/src/pages/Model/ModelReadmeOverview.tsx
- console/src/pages/Project/ProjectLayout.tsx
- console/src/pages/Project/ProjectListCard.tsx
- console/src/styles/_global.scss
- console/uno.config.ts
> feat(console): support model/project quick notice with locale

- client/starwhale/base/data_type.py
> enhance(client): clear cache for link _signed_uri

- console/src/pages/Model/ModelVersionOverview.tsx
> update(console): add handler to model overview

- client/starwhale/base/data_type.py
> enhance(SDK): retrieve the content of Text using the fetch_data function

- server/controller/src/main/java/ai/starwhale/mlops/domain/dataset/DatasetService.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/evaluation/EvaluationService.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/JobServiceForWeb.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/model/ModelService.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/report/ReportService.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/runtime/RuntimeService.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/task/TaskService.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/trash/TrashService.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/user/UserService.java
> chore(controller): use try-resource to recode pagehelper

- client/starwhale/api/_impl/dataset/loader.py
- client/starwhale/api/_impl/evaluation/log.py
- client/starwhale/base/data_type.py
- client/starwhale/core/dataset/store.py
- client/tests/base/test_data_type.py
- client/tests/core/test_dataset_store.py
- client/tests/sdk/test_loader.py
- scripts/example/src/evaluator.py
depends on: https://github.com/star-whale/starwhale/pull/2887
> enhance(client): remove artifacts owner setter

- client/Makefile
- scripts/client_test/cli_test.py
> chore(e2e): compare datastore table instead of dataset

- server/controller/src/main/java/ai/starwhale/mlops/api/protocol/event/EventRequest.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/event/EventService.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/JobServiceForWeb.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/event/EventServiceTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/job/JobServiceForWebTest.java
> enhance(controller): add job event in server side

- console/packages/starwhale-ui/src/GridTable/hooks/useGridQuery.tsx
- console/src/components/QuickGroup.tsx
> update(console): use current project as default tree data list

- scripts/publish/image_sync.sh
get tag diff first before coping image
> chore: speed up image sync

- .github/file-filter.yml
- .github/workflows/client.yaml
- .github/workflows/console.yml
- .github/workflows/e2e-test.yml
- .github/workflows/server-ut-report.yml
https://docs.github.com/en/actions/using-jobs/using-concurrency
> enhance(ci): auto cancel the previous run

- console/packages/starwhale-ui/src/GridDatastoreTable/hooks/useDatastoreSummaryColumns.tsx
- console/packages/starwhale-ui/src/RJSFForm/widgets/SelectWidget/index.tsx
- console/packages/starwhale-ui/src/Select/Select.tsx
- console/packages/starwhale-ui/src/TiptapEditor/index.tsx
- console/src/domain/model/components/ModelLabel.tsx
- console/src/pages/Evaluation/EvaluationListCard.tsx
- console/src/pages/Evaluation/EvaluationOverviewLayout.tsx
- console/src/pages/Job/JobOverviewLayout.tsx
- console/src/pages/Model/ModelOverviewLayout.tsx
> update(console): action configable,  report autofocus, job result overflow scroll and   optimize ui

- client/starwhale/base/client/models/models.py
- server/controller/src/main/java/ai/starwhale/mlops/api/JobController.java
- server/controller/src/main/java/ai/starwhale/mlops/api/protocol/event/Event.java
- server/controller/src/main/java/ai/starwhale/mlops/schedule/impl/k8s/EventWatcher.java
- server/controller/src/main/java/ai/starwhale/mlops/schedule/impl/k8s/K8sClient.java
- server/controller/src/main/java/ai/starwhale/mlops/schedule/impl/k8s/Util.java
- server/controller/src/main/java/ai/starwhale/mlops/schedule/impl/k8s/reporting/JobEventHandler.java
- server/controller/src/main/java/ai/starwhale/mlops/schedule/impl/k8s/reporting/K8sEventListener.java
- server/controller/src/main/java/ai/starwhale/mlops/schedule/impl/k8s/reporting/PodEventHandler.java
- server/controller/src/main/java/ai/starwhale/mlops/schedule/impl/k8s/reporting/ResourceEventHolder.java
- server/controller/src/main/java/ai/starwhale/mlops/schedule/impl/k8s/reporting/RunEventListener.java
- server/controller/src/main/resources/application.yaml
- server/controller/src/test/java/ai/starwhale/mlops/api/JobControllerTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/PageTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/model/ModelServiceTest.java
- server/controller/src/test/java/ai/starwhale/mlops/schedule/impl/k8s/reporting/ResourceEventHolderTest.java
- server/controller/src/test/java/ai/starwhale/mlops/schedule/impl/k8s/reporting/RunEventListenerTest.java
> enhance(controller): support logging scheduler event to run of job

- server/controller/src/main/java/ai/starwhale/mlops/domain/event/EventService.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/event/mapper/EventMapper.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/event/EventServiceTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/event/mapper/EventMapperTest.java
> chore(controller): list event support task-scoped aggregation

- example/code-generation/code-llama/.gitignore
- example/code-generation/code-llama/README.md
- example/code-generation/code-llama/download.py
- example/code-generation/code-llama/inference.py
- example/code-generation/code-llama/requirements.txt
- example/code-generation/code-llama/runtime.yaml
- https://cloud.starwhale.cn/projects/404/models/203/versions/266/readme
> example: add code-llama example

- server/controller/src/main/java/ai/starwhale/mlops/schedule/reporting/listener/impl/RunUpdateListenerForStatus.java
- server/controller/src/test/java/ai/starwhale/mlops/schedule/reporting/listener/impl/RunUpdateListenerForStatusTest.java
> fix(controller): make proxy works after serving handler run

- client/pyproject.toml
- client/starwhale/api/_impl/data_store.py
- client/starwhale/base/client/models/models.py
- client/starwhale/base/view.py
- client/starwhale/core/dataset/tabular.py
- client/starwhale/utils/json.py
- client/starwhale/web/data_store.py
- client/tests/sdk/test_data_store.py
- server/controller/src/main/java/ai/starwhale/mlops/api/protocol/datastore/RecordValueDesc.java
- server/controller/src/main/java/ai/starwhale/mlops/datastore/ColumnSchema.java
- server/controller/src/main/java/ai/starwhale/mlops/datastore/ColumnSchemaDesc.java
- server/controller/src/main/java/ai/starwhale/mlops/datastore/impl/RecordDecoder.java
- server/controller/src/main/java/ai/starwhale/mlops/datastore/impl/WalRecordDecoder.java
- server/controller/src/main/protobuf/wal.proto
- server/controller/src/test/java/ai/starwhale/mlops/datastore/DataStoreTest.java
> enhance(datastore): map support multiple key value schemas

- console/src/pages/Model/ModelVersionListCard.tsx
- server/controller/src/main/java/ai/starwhale/mlops/domain/dataset/DatasetService.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/model/ModelService.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/dataset/DatasetServiceTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/model/ModelServiceTest.java
> fix(controller): add missing owner for dataset and model

- client/starwhale/api/_impl/data_store.py
- client/starwhale/api/_impl/evaluation/pipeline.py
- client/starwhale/core/dataset/tabular.py
- client/tests/core/test_dataset.py
- client/tests/sdk/test_data_store.py
- client/tests/sdk/test_dataset.py
- client/tests/sdk/test_dataset_sdk.py
Dataset support dict with int key now.
> enhance(client): prefer using the built-in map when building dataset

- client/starwhale/cli/deubg/datastore.py
> chore(client): list tables without switch instance in datastore debug cli

- console/src/components/BaseSidebar.tsx
- console/src/domain/project/components/ProjectForm.tsx
- console/src/domain/project/schemas/project.tsx
- console/src/domain/project/services/project.ts
- console/src/i18n/locales.ts
- console/src/pages/Project/Overview.tsx
- console/src/pages/Project/ProjectListCard.tsx
> feat(console): support project readme

- server/controller/src/main/java/ai/starwhale/mlops/schedule/impl/k8s/reporting/RunEventListener.java
- server/controller/src/main/resources/application.yaml
> chore(controller): enable scheduler event log by default

- .gitignore
- example/image-segmentation/README.md
- example/image-segmentation/models/segment-anything/.gitignore
- example/image-segmentation/models/segment-anything/.swignore
- example/image-segmentation/models/segment-anything/Makefile
- example/image-segmentation/models/segment-anything/README.md
- example/image-segmentation/models/segment-anything/sam.py
- example/image-segmentation/runtime/requirements.txt
- example/image-segmentation/runtime/runtime.yaml
- Offline Evaluation with coco stuff datasets:
- https://cloud.starwhale.cn/projects/398/evaluations/951/results 
- ![image](https://github.com/star-whale/starwhale/assets/590748/7b4add73-6ce6-4cee-91df-923514073ca5)
- Online Evaluation:
- ![image](https://github.com/star-whale/starwhale/assets/590748/415b6195-7d2a-4d66-b2f7-a66eaf899166)
> example: support segment anything model

- example/image-segmentation/README.md
- example/image-segmentation/models/segment-anything/sam.py
- https://cloud.starwhale.cn/projects/398/evaluations
- https://cloud.starwhale.cn/projects/398/evaluations/954/results
> example: add evaluate phase for segment anything model

- client/starwhale/api/_impl/data_store.py
> chore(datastore): shorten first item response time

- console/src/domain/job/hooks/useFetchJobs.ts
- console/src/domain/job/services/job.ts
- console/src/pages/Model/ModelOverviewLayout.tsx
- console/src/pages/Model/ModelVersionServings.tsx
- console/src/routes.tsx
online demo:
- http://jialei.pre.intra.starwhale.ai/projects/1/models/3/versions/3/servings
- http://jialei.pre.intra.starwhale.ai/projects/1/models/1/versions/1/overview
> enhance(console): show running serving pages of current model version

- client/starwhale/integrations/huggingface/dataset.py
- client/tests/sdk/test_dataset_sdk.py
- issue:
- hf raw data:   https://huggingface.co/datasets/lambdalabs/pokemon-blip-captions
- hf lib:
- starwhale dataset: 
- fixed:
> enhance(SDK): enhance hf datasets to handle abnormal dataset without config class

- server/controller/src/main/java/ai/starwhale/mlops/configuration/security/ProjectNameExtractorDataStoreMixed.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/dataset/DatasetDao.java
- server/controller/src/test/java/ai/starwhale/mlops/api/config/ProjectNameExtractorDataStoreMixedTest.java
> chore(controller): validate the resource version owner

- console/packages/starwhale-ui/src/GridTable/GridTable.tsx
- console/packages/starwhale-ui/src/Markdown/Markdown.tsx
- console/src/components/Link/TextLink.tsx
- console/src/components/QuickGroup.tsx
- console/src/main.tsx
- console/src/pages/Evaluation/EvaluationOverview.tsx
- console/src/pages/Job/JobOverview.tsx
- console/src/pages/Project/ProjectListCard.tsx
> fix(console): overview link/project desc overflow/tree default selector

- server/controller/src/main/java/ai/starwhale/mlops/domain/job/JobDao.java
> fix(controller): npe in ds build job

- console/packages/starwhale-ui/src/base/data-table/inner-table-element.tsx
> fix(console): eval action position when scrolling

- client/scripts/sw-docker-entrypoint
- client/starwhale/base/client/models/models.py
- server/controller/src/main/java/ai/starwhale/mlops/api/DatasetController.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/dataset/DatasetService.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/dataset/build/BuildType.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/dataset/build/bo/CreateBuildRecordRequest.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/dataset/build/mapper/BuildRecordMapper.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/dataset/DatasetServiceTest.java
> feat(controller): support more file type for dataset build

- client/starwhale/base/client/models/models.py
- server/controller/src/main/java/ai/starwhale/mlops/api/protocol/model/CreateModelVersionRequest.java
> feat(controller): add model source when copy (#2953)

- .github/workflows/server-ut-report.yml
- server/Makefile
- server/controller/src/test/java/ai/starwhale/mlops/schedule/impl/k8s/reporting/ResourceEventHolderTest.java
- server/pom.xml
- Print ut summary only
- Upload the details to github artifact if fails
demo:
summary: https://github.com/star-whale/starwhale/actions/runs/6833263621/job/18584844620?pr=2963
log details: https://github.com/star-whale/starwhale/actions/runs/6833263621?pr=2963
> chore(ci): reduce ut log output of controller

- client/starwhale/base/client/models/models.py
- server/controller/src/main/java/ai/starwhale/mlops/api/protocol/model/CreateModelVersionRequest.java
> fix(controller): fix compile error

- client/starwhale/core/model/copy.py
- client/tests/base/test_copy.py
- related: https://github.com/star-whale/starwhale/pull/2964
> feat(client): support finetune model source field for model copy

- server/controller/src/main/java/ai/starwhale/mlops/api/FineTuneController.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/ft/FineTuneAppService.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/ft/FineTuneDomainService.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/model/ModelService.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/model/mapper/ModelVersionMapper.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/model/po/ModelVersionEntity.java
- server/controller/src/main/resources/db/migration/v0_4_0/V0_4_0_031__add_draft_model.sql
- server/controller/src/test/java/ai/starwhale/mlops/domain/ft/FineTuneAppServiceTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/model/ModelServiceTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/model/mapper/ModelVersionMapperTest.java
> feat(controller): Sft/model copy with ft id

- client/starwhale/base/client/models/models.py
- scripts/apitest/pytest/test_evaluation.py
- server/controller/src/main/java/ai/starwhale/mlops/api/EvaluationController.java
- server/controller/src/main/java/ai/starwhale/mlops/api/JobController.java
- server/controller/src/main/java/ai/starwhale/mlops/api/protocol/job/JobRequest.java
- server/controller/src/main/java/ai/starwhale/mlops/api/protocol/job/JobTemplateVo.java
- server/controller/src/main/java/ai/starwhale/mlops/common/IdConverter.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/evaluation/EvaluationService.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/ft/FineTuneAppService.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/converter/JobConverter.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/converter/UserJobConverter.java
- server/controller/src/test/java/ai/starwhale/mlops/api/EvaluationControllerTest.java
- server/controller/src/test/java/ai/starwhale/mlops/api/JobControllerTest.java
- server/controller/src/test/java/ai/starwhale/mlops/api/TaskLogWsServerTest.java
- server/controller/src/test/java/ai/starwhale/mlops/common/IdConverterTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/evaluation/EvaluationServiceTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/ft/FineTuneAppServiceTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/job/converter/JobConverterTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/job/converter/UserJobConverterTest.java
- Remove useless evaluation APIs
- Convert resource id from Long to String in job request
> refactor(controller): remove unreachable code

- server/controller/src/main/resources/db/migration/v0_4_0/V0_4_0_030__ft_related.sql
> fix(controlle): remove unique constrain for job on finetune

- server/controller/src/main/java/ai/starwhale/mlops/datastore/ColumnSchema.java
- server/controller/src/test/java/ai/starwhale/mlops/datastore/ColumnSchemaTest.java
> fix(datastore): fix NPE when list diff without sparse element type inited

- server/controller/src/main/java/ai/starwhale/mlops/configuration/FeaturesProperties.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/ft/FineTuneAppService.java
- server/controller/src/main/java/ai/starwhale/mlops/exception/SwValidationException.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/ft/FineTuneAppServiceTest.java
> chore(controller): support disabling the fine tuning feature

- scripts/publish/image_sync.sh
> chore: image sync loss star-whale

- example/runtime/pytorch-cn-mirror/requirements.txt
- example/runtime/pytorch/requirements.txt
- remove specified to solve some wheel not found issue for greater than python 3.8
> example(runtime): update pytorch example runtime

- server/controller/src/main/java/ai/starwhale/mlops/domain/blob/CachedBlobService.java
- server/storage-access-layer/src/main/java/ai/starwhale/mlops/storage/configuration/StorageAccessConfig.java
> bugfix(storage): add ksyun configuration

- console/packages/starwhale-ui/src/Button/Button.tsx
- console/packages/starwhale-ui/src/GridTable/components/TableActions.tsx
- console/src/components/Table/index.tsx
> fix(console): action bar not rerender

- server/controller/src/main/java/ai/starwhale/mlops/domain/ft/FineTuneAppService.java
> fix(controller): train and eval dataset wrong

- server/controller/src/main/java/ai/starwhale/mlops/domain/model/mapper/ModelVersionMapper.java
> fix(controller): fix sql error in sft release function

- client/starwhale/base/client/models/models.py
- server/controller/src/main/java/ai/starwhale/mlops/api/protocol/job/JobRequest.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/ft/FineTuneAppService.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/ft/mapper/FineTuneMapper.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/ft/po/FineTuneEntity.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/ft/vo/FineTuneVo.java
- server/controller/src/main/resources/db/migration/v0_4_0/V0_4_0_033__update_column_name_for_ft.sql
- server/controller/src/test/java/ai/starwhale/mlops/domain/ft/FineTuneAppServiceTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/ft/mapper/FineTuneMapperTest.java
> chore(controller): rename eval dataset to validation

- server/controller/src/main/java/ai/starwhale/mlops/domain/job/spec/StepSpec.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/job/JobParserTest.java
> fix(controller): add step spec extra param

- client/setup.py
- client/starwhale/api/_impl/service/service.py
- client/starwhale/api/_impl/service/types.py
- client/starwhale/web/server.py
- client/tests/data/sdk/service/default_class.py
- client/tests/sdk/test_types.py
- example/PennFudanPed/pfp/evaluator.py
- example/image-classification/models/cnn/evaluator.py
- example/image-classification/models/vit/inference.py
- example/image-segmentation/models/segment-anything/sam.py
- example/mnist/mnist/custom_evaluator.py
- example/mnist/mnist/evaluator.py
- example/mnist/mnist/plain_evaluator.py
- example/nmt/nmt/evaluator.py
- example/stable-diffusion/txt2img/run.py
- example/text_cls_AG_NEWS/tcan/evaluator.py
- example/ucf101/ucf101/evaluator.py
> enhance(client): support gradio components in api decorator

- scripts/e2e_test/start_test.sh
bad case: https://github.com/star-whale/starwhale/actions/runs/6940569061/job/18879739959?pr=3004
> chore(ci): make e2e stable

- server/controller/src/test/java/ai/starwhale/mlops/domain/job/JobUpdateHelperTest.java
https://github.com/star-whale/starwhale/actions/runs/6938173191/attempts/1
> chore(controller): make JobUpdateHelperTest stable

- example/llm-finetune/models/baichuan2/finetune.py
> example(LLM): update baichuan2 example for including lora finetune module

- client/starwhale/api/_impl/experiment.py
> enhance(SDK): add finetune tag automatically when the model building is triggered by the finetune decorator

- server/storage-access-layer/src/main/java/ai/starwhale/mlops/storage/StorageAccessService.java
> chore(controller): add 'cos' schema name for QCloud

- client/starwhale/integrations/huggingface/dataset.py
- convert issue:
- docs: https://huggingface.co/docs/datasets/package_reference/main_classes#datasets.Features
- example features definition: https://huggingface.co/datasets/BAAI/COIG/blob/main/COIG.py#L58
- fixed
> bug(SDK): fix the ingestion process for list in huggingface datasets

- client/starwhale/core/model/view.py
- changes:
- remove useless columns: Path
- add pager for cloud project
- fix no size crash issue
- format createAt for human
- before:
- [![asciicast](https://asciinema.org/a/622156.svg)](https://asciinema.org/a/622156)
- after:
- [![asciicast](https://asciinema.org/a/622157.svg)](https://asciinema.org/a/622157)
> enhance(client): update model list output

- server/controller/src/main/java/ai/starwhale/mlops/domain/ft/FineTuneAppService.java
> fix(controller): Collector.toMap require non-null value 

- client/Makefile
- client/setup.py
- client/starwhale/api/_impl/data_store.py
- client/starwhale/api/_impl/job/handler.py
- client/starwhale/api/_impl/service/service.py
- client/starwhale/base/client/client.py
- client/starwhale/base/client/models/base.py
- client/starwhale/base/client/models/models.py
- client/starwhale/base/models/base.py
- client/starwhale/base/models/dataset.py
- client/starwhale/base/models/job.py
- client/starwhale/base/models/model.py
- client/starwhale/cli/assistance/broker.py
- client/starwhale/core/model/model.py
- client/starwhale/core/model/store.py
- client/starwhale/web/data_store.py
- client/tests/base/models/test_base.py
- client/tests/core/test_model.py
- client/tests/data/job/job_manifest.yaml
- client/tests/sdk/test_job_handler.py
- client/tests/sdk/test_model.py
ref: https://docs.pydantic.dev/latest/migration/
> chore(client): use pydantic v2

- example/runtime/pytorch-e2e/requirements.txt
- related pr: https://github.com/star-whale/starwhale/pull/2978
> chore(ci): add gradio dependency for e2e runtime

- client/starwhale/base/client/models/models.py
- server/controller/src/main/java/ai/starwhale/mlops/api/FineTuneController.java
- server/controller/src/main/java/ai/starwhale/mlops/api/JobController.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/ft/FineTuneAppService.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/JobType.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/converter/JobConverter.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/ft/FineTuneAppServiceTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/job/mapper/JobMapperTest.java
> feat(controller): support online eval in fine-tune space

- server/controller/src/main/java/ai/starwhale/mlops/domain/job/spec/svc/ApiSpec.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/spec/svc/ComponentSpec.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/spec/svc/ServiceSpec.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/job/spec/JobSpecTest.java
> fix(controller): add constructor for the class which used for deserialization

- scripts/publish/image_sync.sh
> fix(ci): sync latest image in whatever case

- client/starwhale/base/scheduler/step.py
bad case: http://e2e-20231128.pre.intra.starwhale.ai/projects/1/jobs/8/tasks?active=log&taskId=116
demo: http://jialei.pre.intra.starwhale.ai/projects/1/jobs/2/servings
> fix(client): online serving failed when run in pod

- client/starwhale/api/_impl/service/types/llm.py
- client/starwhale/api/_impl/service/types/types.py
- client/starwhale/base/client/models/models.py
- client/tests/data/sdk/service/default_class.py
- client/tests/sdk/test_service.py
- example/web-handler/main.py
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/spec/svc/ComponentSpec.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/spec/svc/ComponentValueSpec.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/spec/svc/ComponentValueSpecBool.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/spec/svc/ComponentValueSpecFloat.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/spec/svc/ComponentValueSpecInt.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/spec/svc/ComponentValueSpecString.java
> enhance(client): online service spec support component value spec

- server/storage-access-layer/src/main/java/ai/starwhale/mlops/storage/fs/FsStorageSignature.java
> fix(controller): fix FsStorageSignature object not installed by spring

- .github/workflows/e2e-test.yml
- client/starwhale/cli/server/compose.tmpl
- scripts/e2e_test/start_test.sh
depends on: https://github.com/star-whale/starwhale/pull/3035
> chore(ci): enable github e2e test using the `swcli server start` command

- example/stable-diffusion/txt2img-ft/README.md
- example/stable-diffusion/txt2img-ft/build_model.py
- example/stable-diffusion/txt2img-ft/evaluation.py
- example/stable-diffusion/txt2img-ft/finetune.py
- example/stable-diffusion/txt2img-ft/model.yaml
- example/stable-diffusion/txt2img-ft/requirements.txt
[readme](https://github.com/star-whale/starwhale/blob/61f7418f23e19b54ee4dea1ade97873213d7be83/example/stable-diffusion/txt2img-ft/README.md)
> chore(example): update example for sd-ft

- example/llm-finetune/runtime/requirements.txt
- example/llm-finetune/runtime/runtime.yaml
> example: update llm finetune runtime deps

- console/client/App.tsx
- console/client/ServingPage.tsx
- console/client/components/ChatGroup.tsx
- console/client/pages/llm/LLMChat.tsx
- console/packages/starwhale-ui/src/Link/ButtonLink.tsx
- console/packages/starwhale-ui/src/Popover/PopoverContainer.tsx
- console/packages/starwhale-ui/src/Search/FilterRenderer.tsx
- console/packages/starwhale-ui/src/Search/Search.tsx
- console/packages/starwhale-ui/src/Search/components/FieldDefault.tsx
- console/packages/starwhale-ui/src/Search/types.ts
- console/packages/starwhale-ui/src/Serving/store/chat.ts
> update(console): support client serving and optimize ui

- scripts/e2e_test/start_test.sh
> chore(ci): prevent changing yarn.lock in e2e

- README.md
> chore(doc): fix cloud broken link

- client/starwhale/api/_impl/model.py
- client/starwhale/core/model/view.py
> enhance(SDK): support package runtime for model build sdk

- README.md
- README_ZH.md
> chore(doc): fix github action broken links

- docker/Dockerfile.base
> enhance(docker): add conda bin into /usr/local/bin, make debug mode happy

- docker/external/base-entrypoint.sh
> enhance(docker): add pydistutils cfg file for setuptools easy install

- example/llm-finetune/models/baichuan2/evaluation.py
- example/llm-finetune/models/baichuan2/finetune.py
- example/llm-finetune/models/chatglm3/evaluation.py
- example/llm-finetune/models/chatglm3/finetune.py
- example/llm-finetune/runtime/runtime.yaml
> example(LLM): use `@starwhale.argument` feature to refactor llm finetune examples

- client/starwhale/utils/debug.py
[![asciicast](https://asciinema.org/a/631563.svg)](https://asciinema.org/a/631563)
> chore(client): ignore warnings when logger level is 0(error)

- client/starwhale/base/client/models/models.py
- console/src/api/server/data-contracts.ts
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/spec/StepSpec.java
- server/controller/src/main/java/ai/starwhale/mlops/schedule/impl/container/impl/SwCliModelHandlerContainerSpecification.java
- server/controller/src/test/java/ai/starwhale/mlops/schedule/impl/contianer/SwCliModelHandlerContainerSpecificationTest.java
when the argument is multiple, like this:
the expect action is:
> fix(controller): support multiple value

- client/setup.py
- client/starwhale/mngt/__init__.py
> chore(client): fix environment check for macOS environment
