controller/src/main/java/ai/starwhale/mlops/api/LoginController.java
controller/src/main/java/ai/starwhale/mlops/api/protocol/Code.java
controller/src/main/java/ai/starwhale/mlops/api/protocol/ResponseMessage.java
controller/src/main/java/ai/starwhale/mlops/api/protocol/user/LoginRequest.java
controller/src/main/java/ai/starwhale/mlops/configuration/CommonExceptionHandler.java

I've moved api related classes to the api package

move api related class to api package

---

.github/ISSUE_TEMPLATE/config.yaml
.github/PULL_REQUEST_TEMPLATE.md
.gitignore
client/README.md
client/setup.py
code-of-conduct.md
docs/README.md

- add some github config
- add project skeleton files
- add python code skeleton
-  update ignore for some py/env ignores

init client and config code skeleton

---

server/controller/src/main/java/ai/starwhale/mlops/configuration/security/JwtTokenFilter.java
server/controller/src/main/java/ai/starwhale/mlops/domain/user/UserService.java
server/pom.xml

fix:change default jdk to 8

---

server/controller/src/main/java/ai/starwhale/mlops/configuration/security/JwtTokenFilter.java
server/controller/src/main/java/ai/starwhale/mlops/domain/user/UserService.java
server/pom.xml

Revert "fix:change default jdk to 8"

---

server/pom.xml

fix:change default jdk to 11

---

client/requirements.txt
client/starwhale/cli/model.py
client/starwhale/consts/__init__.py
client/starwhale/swmp/model.py
client/starwhale/swmp/store.py
client/starwhale/utils/__init__.py

- Add `swmp model list` command
- Add `swmp model info` command

Add swmp model list/info cmd

---

client/starwhale/cli/__init__.py
client/starwhale/cli/mngt.py
client/starwhale/mngt/user.py
client/starwhale/utils/__init__.py
client/starwhale/utils/config.py

add login/logout cmd

---

client/starwhale/cli/__init__.py
client/starwhale/cli/mngt.py
client/starwhale/cli/model.py
client/starwhale/consts/__init__.py
client/starwhale/mngt/user.py
client/starwhale/swmp/store.py
client/starwhale/utils/__init__.py
client/starwhale/utils/debug.py

- dep: https://github.com/star-whale/starwhale/pull/19
- add cmd: `swcli model push/pull`
- push/pull api is mock cc  @dreamlandliu  
- add cmd: `swcli model delete`

add swmp pull/push/del cli

---

.gitignore
client/requirements.txt
example/mnist/process.py

design `swds` format, include: 
- `data_ubyte_{index}.swds_bin`  --> data bin
- `label_ubyte_{index}.swds_bin`          --> label bin, correlate with data bin file
- `index.jsonl`                              --> data/label index json line
- bin format:
```
header_magic  uint32  I
crc           uint32  I
idx           uint64  Q
size          uint32  I
data_magic    uint32  I --> above 24 bytes
data bytes...
padding bytes...
```
- jsonl:
```
{
"id": 0,
"data": {
"file": "data_ubyte_0.swds_bin",
"offset": 0,
"size": 39200
},
"label": {
"file": "label_ubyte_0.swds_bin",
"offset": 0,
"size": 50
}
}
```
- run script:
- files list:
in production, we will use `64MB` as file volume default size.  
- index.jsonl file:
- abstract SW Python SDK, user only provide `iter_data_slice` and …

add mnist to swds script

---

server/agent/pom.xml
server/agent/src/main/java/ai/starwhale/mlops/agent/configuration/DockerConfiguration.java
server/agent/src/main/java/ai/starwhale/mlops/agent/container/impl/DockerClient.java
server/agent/src/main/java/ai/starwhale/mlops/agent/taskexecutor/TaskExecutor.java
server/agent/src/main/java/ai/starwhale/mlops/agent/taskexecutor/TaskSource.java
server/agent/src/main/resources/docker-java.properties
server/controller-sdk/src/main/java/ai/starwhale/mlops/api/protocol/report/ReportRequest.java
server/controller-sdk/src/main/java/ai/starwhale/mlops/domain/node/Node.java
server/controller-sdk/src/main/java/ai/starwhale/mlops/domain/task/Task.java

WIP:Feat-agent task report

---

server/agent/pom.xml
server/agent/src/main/java/ai/starwhale/mlops/agent/StarWhaleAgentApplication.java
server/agent/src/main/java/ai/starwhale/mlops/agent/configuration/AgentProperties.java
server/agent/src/main/java/ai/starwhale/mlops/agent/configuration/DockerConfiguration.java
server/agent/src/main/java/ai/starwhale/mlops/agent/configuration/TaskConfiguration.java
server/agent/src/main/java/ai/starwhale/mlops/agent/container/impl/DockerContainerClient.java
server/agent/src/main/java/ai/starwhale/mlops/agent/task/EvaluationTask.java
server/agent/src/main/java/ai/starwhale/mlops/agent/taskexecutor/Scheduler.java
server/agent/src/main/java/ai/starwhale/mlops/agent/taskexecutor/SourcePool.java
server/agent/src/main/java/ai/starwhale/mlops/agent/taskexecutor/TaskExecutor.java
server/agent/src/main/java/ai/starwhale/mlops/agent/taskexecutor/TaskSource.java
server/agent/src/main/java/ai/starwhale/mlops/agent/taskexecutor/initializer/TaskPoolInitializer.java
server/agent/src/test/java/ai/starwhale/mlops/agent/test/StarWhaleAgentTestApplication.java
server/agent/src/test/java/ai/starwhale/mlops/agent/test/TaskExecutorTest.java
server/agent/src/test/resources/application-integrationtest.yaml
server/agent/src/test/resources/tasks/1234567890.taskinfo
server/agent/src/test/resources/tasks/1234567891.taskinfo
server/controller-sdk/src/main/java/ai/starwhale/mlops/api/protocol/report/ReportRequest.java
server/controller-sdk/src/main/java/ai/starwhale/mlops/api/protocol/report/ReportResponse.java
server/controller-sdk/src/main/java/ai/starwhale/mlops/domain/node/Device.java
server/controller-sdk/src/main/java/ai/starwhale/mlops/domain/task/TaskTrigger.java
server/controller/src/main/java/ai/starwhale/mlops/domain/job/JobSpliter.java
server/controller/src/main/java/ai/starwhale/mlops/domain/job/SimpleJobSpliter.java
server/controller/src/main/java/ai/starwhale/mlops/reporting/ReportProcessorImp.java
server/controller/src/main/java/ai/starwhale/mlops/schedule/SimpleTaskScheduler.java
server/controller/src/main/java/ai/starwhale/mlops/schedule/TaskScheduler.java
server/controller/src/test/java/ai/starwhale/test/job/TestSimpleJobSpliter.java

Agent optimize

---

server/agent/src/main/java/ai/starwhale/mlops/agent/task/EvaluationTask.java
server/controller-sdk/src/main/java/ai/starwhale/mlops/domain/node/Node.java
server/controller-sdk/src/main/java/ai/starwhale/mlops/domain/swds/index/SWDSBlock.java
server/controller-sdk/src/main/java/ai/starwhale/mlops/domain/swds/index/SWDSDataLocation.java
server/controller-sdk/src/main/java/ai/starwhale/mlops/domain/swds/index/SWDSIndex.java
server/controller-sdk/src/main/java/ai/starwhale/mlops/domain/task/TaskTrigger.java
server/controller/src/main/java/ai/starwhale/mlops/reporting/ReportProcessorImp.java
server/controller/src/main/java/ai/starwhale/mlops/schedule/CommandingTasksChecker.java
server/controller/src/main/java/ai/starwhale/mlops/schedule/SimpleTaskScheduler.java

modify report protocol

---

client/starwhale/swds/store.py
client/starwhale/swmp/store.py

- add `swcli dataset push` cli, but which is not worked right with Controller yet.
- upload phase:  
1.  _manifest.yaml  <-- start,  resp upload_id
2. upload blobs(data + swds_meta)  <-- with `X-SW-UPLOAD-ID`
3. cancel or end the upload   <-- with `X-SW-UPLOAD-ID`

add swds push cmd

---

server/agent/src/main/java/ai/starwhale/mlops/agent/configuration/AgentProperties.java
server/agent/src/main/java/ai/starwhale/mlops/agent/configuration/DockerConfiguration.java
server/agent/src/main/java/ai/starwhale/mlops/agent/configuration/NodeConfiguration.java
server/agent/src/main/java/ai/starwhale/mlops/agent/container/ImageConfig.java
server/agent/src/main/java/ai/starwhale/mlops/agent/container/impl/DockerContainerClient.java
server/agent/src/main/java/ai/starwhale/mlops/agent/node/SourcePool.java
server/agent/src/main/java/ai/starwhale/mlops/agent/node/gpu/GPUInfo.java
server/agent/src/main/java/ai/starwhale/mlops/agent/node/gpu/NvidiaDetect.java
server/agent/src/main/java/ai/starwhale/mlops/agent/task/EvaluationTask.java
server/agent/src/main/java/ai/starwhale/mlops/agent/task/Scheduler.java
server/agent/src/main/java/ai/starwhale/mlops/agent/task/TaskPool.java
server/agent/src/main/java/ai/starwhale/mlops/agent/task/action/Context.java
server/agent/src/main/java/ai/starwhale/mlops/agent/task/action/init/RebuildTasksAction.java
server/agent/src/main/java/ai/starwhale/mlops/agent/task/action/normal/AbsBaseTaskTransition.java
server/agent/src/main/java/ai/starwhale/mlops/agent/task/action/normal/FinishedOrCanceled2ArchivedAction.java
server/agent/src/main/java/ai/starwhale/mlops/agent/task/action/normal/MonitorRunningTaskAction.java
server/agent/src/main/java/ai/starwhale/mlops/agent/task/action/normal/Preparing2RunningAction.java
server/agent/src/main/java/ai/starwhale/mlops/agent/task/action/normal/Uploading2FinishedAction.java
server/agent/src/main/java/ai/starwhale/mlops/agent/task/action/report/ReportAction.java
server/agent/src/main/java/ai/starwhale/mlops/agent/task/executor/TaskExecutor.java
server/agent/src/main/java/ai/starwhale/mlops/agent/task/initializer/TaskPoolInitializer.java
server/agent/src/main/java/ai/starwhale/mlops/agent/task/persistence/FileSystemTaskPersistence.java
server/agent/src/main/java/ai/starwhale/mlops/agent/task/persistence/TaskPersistence.java
server/agent/src/main/resources/application.yaml
server/agent/src/test/java/ai/starwhale/mlops/agent/test/TaskExecutorTest.java
server/controller-sdk/src/main/java/ai/starwhale/mlops/api/protocol/ResponseMessage.java
server/controller-sdk/src/main/java/ai/starwhale/mlops/api/protocol/report/ReportResponse.java

Agent docker gpu test

---

CONTRIBUTING.md

add placeholder doc for contributing

---

server/controller/src/main/java/ai/starwhale/mlops/api/protocol/agent/AgentVO.java
server/controller/src/main/java/ai/starwhale/mlops/api/protocol/project/ProjectVO.java
server/controller/src/main/java/ai/starwhale/mlops/api/protocol/runtime/BaseImageVO.java
server/controller/src/main/java/ai/starwhale/mlops/api/protocol/swmp/SWModelPackageInfoVO.java
server/controller/src/main/java/ai/starwhale/mlops/api/protocol/swmp/SWModelPackageVO.java
server/controller/src/main/java/ai/starwhale/mlops/api/protocol/swmp/SWModelPackageVersionVO.java
server/controller/src/main/java/ai/starwhale/mlops/api/protocol/task/TaskVO.java
server/controller/src/main/java/ai/starwhale/mlops/api/protocol/user/RoleVO.java
server/controller/src/main/java/ai/starwhale/mlops/api/protocol/user/UserVO.java
server/controller/src/main/java/ai/starwhale/mlops/domain/job/BaseImageConvertor.java
server/controller/src/main/java/ai/starwhale/mlops/domain/job/JobConvertor.java
server/controller/src/main/java/ai/starwhale/mlops/domain/project/ProjectConvertor.java
server/controller/src/main/java/ai/starwhale/mlops/domain/swds/SWDSConvertor.java
server/controller/src/main/java/ai/starwhale/mlops/domain/swds/SWDSVersionConvertor.java
server/controller/src/main/java/ai/starwhale/mlops/domain/swmp/SWMPConvertor.java
server/controller/src/main/java/ai/starwhale/mlops/domain/swmp/SWMPVersionConvertor.java
server/controller/src/main/java/ai/starwhale/mlops/domain/system/AgentConvertor.java
server/controller/src/main/java/ai/starwhale/mlops/domain/task/TaskConvertor.java
server/controller/src/main/java/ai/starwhale/mlops/domain/user/RoleConvertor.java
server/controller/src/main/java/ai/starwhale/mlops/domain/user/UserConvertor.java

vos and convertors npe

---

server/agent/pom.xml
server/agent/src/main/java/ai/starwhale/mlops/agent/configuration/AgentProperties.java
server/agent/src/main/java/ai/starwhale/mlops/agent/configuration/NodeConfiguration.java
server/agent/src/main/java/ai/starwhale/mlops/agent/container/ContainerClient.java
server/agent/src/main/java/ai/starwhale/mlops/agent/container/ImageConfig.java
server/agent/src/main/java/ai/starwhale/mlops/agent/container/impl/DockerContainerClient.java
server/agent/src/main/java/ai/starwhale/mlops/agent/node/SourcePool.java
server/agent/src/main/java/ai/starwhale/mlops/agent/node/cpu/CPUDetect.java
server/agent/src/main/java/ai/starwhale/mlops/agent/node/cpu/CPUInfo.java
server/agent/src/main/java/ai/starwhale/mlops/agent/node/cpu/SimpleCPUDetect.java
server/agent/src/main/java/ai/starwhale/mlops/agent/node/gpu/GPUDetect.java
server/agent/src/main/java/ai/starwhale/mlops/agent/node/gpu/NvidiaCmdDetect.java
server/agent/src/main/java/ai/starwhale/mlops/agent/node/host/HostDetect.java
server/agent/src/main/java/ai/starwhale/mlops/agent/node/host/HostInfo.java
server/agent/src/main/java/ai/starwhale/mlops/agent/node/host/SimpleHostDetect.java
server/agent/src/main/java/ai/starwhale/mlops/agent/task/action/DoTransition.java
server/agent/src/main/java/ai/starwhale/mlops/agent/task/action/normal/AbsBaseTaskTransition.java
server/agent/src/main/java/ai/starwhale/mlops/agent/task/action/normal/MonitorRunningTaskAction.java
server/agent/src/main/java/ai/starwhale/mlops/agent/task/action/normal/Preparing2RunningAction.java
server/agent/src/main/java/ai/starwhale/mlops/agent/task/persistence/FileSystemTaskPersistence.java
server/agent/src/main/java/ai/starwhale/mlops/agent/task/persistence/TaskPersistence.java
server/agent/src/main/resources/application.yaml
server/agent/src/test/java/ai/starwhale/mlops/agent/test/TaskExecutorTest.java
server/controller-sdk/src/main/java/ai/starwhale/mlops/domain/swds/index/SWDSIndex.java

Agent docker gpu support

---

server/controller/src/main/java/ai/starwhale/mlops/api/DatasetApi.java
server/controller/src/main/java/ai/starwhale/mlops/api/DatasetController.java
server/controller/src/main/java/ai/starwhale/mlops/api/JobApi.java
server/controller/src/main/java/ai/starwhale/mlops/domain/job/JobSWDSVersionMapper.java
server/controller/src/main/java/ai/starwhale/mlops/domain/job/JobService.java
server/controller/src/main/java/ai/starwhale/mlops/domain/swds/SWDatasetMapper.java
server/controller/src/main/java/ai/starwhale/mlops/domain/swds/SWDatasetService.java
server/controller/src/main/java/ai/starwhale/mlops/domain/swds/SWDatasetVersionMapper.java
server/controller/src/main/java/ai/starwhale/mlops/domain/task/TaskService.java
server/controller/src/main/resources/mapper/JobSWDSVersionMapper.xml
server/controller/src/main/resources/mapper/SWDatasetVersionMapper.xml

job & swds relation mappers

---

.gitignore
client/requirements.txt
client/setup.py
client/starwhale/api/_impl/dataset.py
client/starwhale/api/_impl/loader.py
client/starwhale/api/_impl/model.py
client/starwhale/api/model.py
client/starwhale/cli/dataset.py
client/starwhale/utils/log.py
example/mnist/Makefile
example/mnist/dataset.yaml
example/mnist/mnist/ppl.py
example/mnist/test/swds_fuse.json
example/mnist/test/swds_fuse_simple.json
example/mnist/test/swds_s3.json
example/mnist/test/swds_s3_simple.json

- very simple pipeline and dataloader SDK API
- support fuse and s3 backend
- support dynamic buffer in-memory dataloader for s3 backend, it does not write data into local hard disk. 
- add more info into `swds_bin` binary 
- env setting: `SW_TASK_LOG_DIR`  , `SW_TASK_RESULT_DIR`,  `SW_TASK_STATUS_DIR` , `SW_TASK_ID`, `SW_JOB_ID`
- result/status timeline/log all use jsonline format
- auto collect result/status/log 
``` python
from starwhale.api.model import PipelineHandler
class MNISTInference(PipelineHandler):
def __init__(self, device="cpu") -> None:
super().__init__(merge_label=True, ignore_error=True)   # some args for PipelineHandler, use default is ok
def handle(self, data, batch_size, **kw):   # you must override handle method, and you will get raw bytes test dataset foreach batch …
```

pipeline and data loader sdk

---

client/starwhale/swds/dataset.py
client/starwhale/swmp/model.py

add name into _manifest.yaml  @anda-ren

add name into _manifest.yaml

---

server/agent/src/main/java/ai/starwhale/mlops/agent/configuration/AgentProperties.java
server/agent/src/main/java/ai/starwhale/mlops/agent/exception/UploadException.java
server/agent/src/main/java/ai/starwhale/mlops/agent/task/action/init/RebuildTasksAction.java
server/agent/src/main/java/ai/starwhale/mlops/agent/task/action/normal/Init2PreparingAction.java
server/agent/src/main/java/ai/starwhale/mlops/agent/task/action/normal/MonitorRunningTaskAction.java
server/agent/src/main/java/ai/starwhale/mlops/agent/task/action/normal/Preparing2RunningAction.java
server/agent/src/main/java/ai/starwhale/mlops/agent/task/action/normal/Uploading2FinishedAction.java
server/agent/src/main/java/ai/starwhale/mlops/agent/task/persistence/FileSystemTaskPersistence.java
server/agent/src/main/java/ai/starwhale/mlops/agent/task/persistence/TaskPersistence.java
server/agent/src/main/resources/application.yaml
server/agent/src/test/java/ai/starwhale/mlops/agent/test/TaskExecutorTest.java

Agent：optimize code which communicate with container 

---

client/starwhale/swmp/store.py

fix swmp delete cannot work and run twice

---

.gitignore
client/Makefile
client/requirements.txt
client/setup.py

build and upload pypi.org : https://pypi.org/project/starwhale/
create your venv , and then run `pip install starwhale==0.1.0.dev0`

fix client setup script for pypi

---

server/controller/pom.xml
server/controller/src/main/java/ai/starwhale/mlops/StarWhaleControllerApplication.java
server/controller/src/main/java/ai/starwhale/mlops/configuration/bean/StorageConfig.java
server/controller/src/main/java/ai/starwhale/mlops/configuration/bean/StorageProperties.java
server/controller/src/main/java/ai/starwhale/mlops/configuration/json/ObjectMapperConfig.java
server/controller/src/main/java/ai/starwhale/mlops/domain/job/JobService.java
server/controller/src/main/java/ai/starwhale/mlops/domain/job/bo/JobBoConverter.java
server/controller/src/main/java/ai/starwhale/mlops/domain/job/split/JobSpliteratorByIndex.java
server/controller/src/main/java/ai/starwhale/mlops/domain/swds/index/SWDSBlockSerializer.java
server/controller/src/main/java/ai/starwhale/mlops/domain/swds/index/SWDSIndexLoaderImpl.java
server/controller/src/main/java/ai/starwhale/mlops/domain/swds/upload/HotSwdsHolder.java
server/controller/src/main/java/ai/starwhale/mlops/domain/swds/upload/SwdsUploader.java
server/controller/src/main/java/ai/starwhale/mlops/domain/swmp/SWModelPackageService.java
server/controller/src/main/java/ai/starwhale/mlops/domain/task/LivingTaskLoader.java
server/controller/src/main/java/ai/starwhale/mlops/domain/task/LivingTaskStatusMachineImpl.java
server/controller/src/main/java/ai/starwhale/mlops/domain/task/bo/TaskBoConverter.java
server/controller/src/main/java/ai/starwhale/mlops/reporting/ReportProcessorImp.java
server/controller/src/main/java/ai/starwhale/mlops/resulting/ResultCollectManager.java
server/controller/src/main/java/ai/starwhale/mlops/resulting/impl/NaiveCollectorFinder.java
server/controller/src/main/java/ai/starwhale/mlops/resulting/impl/clsmulti/MCResultCollector.java
server/controller/src/main/java/ai/starwhale/mlops/resulting/impl/clsmulti/MCResultCollectorFactory.java
server/controller/src/main/java/ai/starwhale/mlops/schedule/CommandingTasksChecker.java
server/controller/src/main/java/ai/starwhale/mlops/schedule/SimpleTaskScheduler.java
server/controller/src/main/resources/application.yaml
server/pom.xml

- add spring bean configuration

add spring bean configuration

---

server/agent/src/main/java/ai/starwhale/mlops/agent/task/TaskPool.java
server/agent/src/main/java/ai/starwhale/mlops/agent/task/action/normal/Init2PreparingAction.java
server/controller-sdk/src/main/java/ai/starwhale/mlops/domain/job/Job.java
server/controller-sdk/src/main/java/ai/starwhale/mlops/domain/task/TaskStatus.java
server/controller/src/main/java/ai/starwhale/mlops/domain/job/JobMapper.java
server/controller/src/main/java/ai/starwhale/mlops/domain/job/JobService.java
server/controller/src/main/java/ai/starwhale/mlops/domain/job/bo/JobBoConverter.java
server/controller/src/main/java/ai/starwhale/mlops/domain/job/split/JobSpliteratorByIndex.java
server/controller/src/main/java/ai/starwhale/mlops/domain/swds/upload/SwdsUploader.java
server/controller/src/main/java/ai/starwhale/mlops/domain/swmp/SWModelPackageService.java
server/controller/src/main/java/ai/starwhale/mlops/domain/task/LivingTaskLoader.java
server/controller/src/main/java/ai/starwhale/mlops/domain/task/LivingTaskStatusMachine.java
server/controller/src/main/java/ai/starwhale/mlops/domain/task/LivingTaskStatusMachineImpl.java
server/controller/src/main/java/ai/starwhale/mlops/domain/task/TaskMapper.java
server/controller/src/main/java/ai/starwhale/mlops/domain/task/bo/StagingTaskStatus.java
server/controller/src/main/java/ai/starwhale/mlops/domain/task/bo/TaskCommand.java
server/controller/src/main/java/ai/starwhale/mlops/domain/user/User.java
server/controller/src/main/java/ai/starwhale/mlops/exception/SWAuthException.java
server/controller/src/main/java/ai/starwhale/mlops/reporting/ReportProcessorImp.java
server/controller/src/main/java/ai/starwhale/mlops/resulting/ResultCollectManager.java
server/controller/src/main/java/ai/starwhale/mlops/schedule/CommandingTasksChecker.java
server/controller/src/main/java/ai/starwhale/mlops/schedule/SimpleTaskScheduler.java
server/controller/src/main/resources/mapper/JobMapper.xml
server/controller/src/main/resources/mapper/TaskMapper.xml
server/storage-access-layer/src/main/java/ai/starwhale/mlops/storage/StorageAccessService.java
server/storage-access-layer/src/main/java/ai/starwhale/mlops/storage/s3/StorageAccessServiceS3.java

clear todos

---

server/controller/src/main/java/ai/starwhale/mlops/api/JobApi.java
server/controller/src/main/java/ai/starwhale/mlops/api/JobController.java
server/controller/src/main/java/ai/starwhale/mlops/api/protocol/job/JobVO.java
server/controller/src/main/java/ai/starwhale/mlops/domain/job/JobService.java

RestAPI for Evaluation Result

---

server/controller/src/main/java/ai/starwhale/mlops/api/ProjectController.java
server/controller/src/main/java/ai/starwhale/mlops/api/UserController.java
server/controller/src/main/java/ai/starwhale/mlops/api/protocol/project/ProjectVO.java
server/controller/src/main/java/ai/starwhale/mlops/domain/project/Project.java
server/controller/src/main/java/ai/starwhale/mlops/domain/project/ProjectConvertor.java
server/controller/src/main/java/ai/starwhale/mlops/domain/project/ProjectEntity.java
server/controller/src/main/java/ai/starwhale/mlops/domain/project/ProjectMapper.java
server/controller/src/main/java/ai/starwhale/mlops/domain/project/ProjectService.java
server/controller/src/main/resources/mapper/ProjectMapper.xml
server/controller/src/main/resources/sql/schema.sql

Default project for user

---

server/controller/src/main/java/ai/starwhale/mlops/configuration/bean/StorageConfig.java
server/controller/src/main/java/ai/starwhale/mlops/configuration/bean/StorageProperties.java
server/controller/src/main/java/ai/starwhale/mlops/domain/swds/index/SWDSIndexLoaderImpl.java
server/controller/src/main/resources/sql/schema.sql
server/storage-access-layer/src/main/java/ai/starwhale/mlops/storage/s3/S3Config.java

fix application start issue

---

server/agent/src/main/resources/application.yaml
server/controller/src/main/java/ai/starwhale/mlops/StarWhaleControllerApplication.java
server/controller/src/main/java/ai/starwhale/mlops/configuration/bean/StorageConfig.java
server/controller/src/main/resources/application.yaml
server/storage-access-layer/pom.xml
server/storage-access-layer/src/main/java/ai/starwhale/mlops/storage/configuration/StorageAccessConfig.java
server/storage-access-layer/src/main/java/ai/starwhale/mlops/storage/configuration/StorageProperties.java
server/storage-access-layer/src/main/resources/META-INF/spring.factories

feat:make storage access sdk as a starter

---

server/controller/src/main/java/ai/starwhale/mlops/domain/project/ProjectManager.java
server/controller/src/main/java/ai/starwhale/mlops/domain/project/ProjectMapper.java
server/controller/src/main/java/ai/starwhale/mlops/domain/swds/SWDatasetService.java
server/controller/src/main/java/ai/starwhale/mlops/domain/swmp/SWModelPackageService.java
server/controller/src/main/resources/mapper/ProjectMapper.xml

Project Manager

---

server/controller-sdk/src/main/java/ai/starwhale/mlops/api/protocol/report/resp/TaskTrigger.java
server/controller-sdk/src/main/java/ai/starwhale/mlops/domain/job/Job.java
server/controller-sdk/src/main/java/ai/starwhale/mlops/domain/swmp/SWModelPackage.java
server/controller-sdk/src/main/java/ai/starwhale/mlops/domain/task/TaskStatus.java
server/controller/src/main/java/ai/starwhale/mlops/domain/job/JobService.java
server/controller/src/main/java/ai/starwhale/mlops/domain/job/bo/JobBoConverter.java
server/controller/src/main/java/ai/starwhale/mlops/domain/job/split/JobSpliteratorByIndex.java
server/controller/src/main/java/ai/starwhale/mlops/domain/task/LivingTaskStatusMachine.java
server/controller/src/main/java/ai/starwhale/mlops/domain/task/LivingTaskStatusMachineImpl.java
server/controller/src/main/java/ai/starwhale/mlops/domain/task/TaskJobStatusHelper.java
server/controller/src/main/java/ai/starwhale/mlops/domain/task/bo/TaskBoConverter.java
server/controller/src/main/java/ai/starwhale/mlops/resulting/ResultCollectManager.java

- add name&version in swmp vo
- change job split strategy
- add pause&resume job/
- refactor cancel job
- add deviceAmount&deviceClass in task vo
- fix some bug

add pause job & adjust agent protocol

---

server/agent/src/main/java/ai/starwhale/mlops/agent/task/action/init/RebuildTasksAction.java
server/agent/src/main/java/ai/starwhale/mlops/agent/task/persistence/FileSystemTaskPersistence.java
server/agent/src/main/java/ai/starwhale/mlops/agent/task/persistence/TaskPersistence.java

fix:REMOVE TODO

---

server/agent/src/main/java/ai/starwhale/mlops/agent/configuration/AgentProperties.java
server/agent/src/main/java/ai/starwhale/mlops/agent/task/EvaluationTask.java
server/agent/src/main/java/ai/starwhale/mlops/agent/task/action/normal/Preparing2RunningAction.java
server/agent/src/main/java/ai/starwhale/mlops/agent/task/persistence/FileSystemTaskPersistence.java
server/agent/src/main/java/ai/starwhale/mlops/agent/task/persistence/TaskPersistence.java
server/agent/src/main/resources/application.yaml
server/agent/src/test/java/ai/starwhale/mlops/agent/test/TaskExecutorTest.java
server/storage-access-layer/src/main/java/ai/starwhale/mlops/storage/configuration/StorageProperties.java

feat:add cpu allocate;optimise container params

---

client/starwhale/base/store.py
client/starwhale/cli/dataset.py
client/starwhale/cli/mngt.py
client/starwhale/cli/model.py
client/starwhale/consts/__init__.py
client/starwhale/mngt/user.py
client/starwhale/swds/store.py
client/starwhale/swmp/store.py
client/starwhale/utils/http.py
example/mnist/dataset.yaml

- login:
- swmp push:
- swmp pull:
- swds push:

fix swds/swmp/login client for stable controller api

---

server/controller/src/main/java/ai/starwhale/mlops/api/DatasetController.java
server/controller/src/main/java/ai/starwhale/mlops/api/JobController.java
server/controller/src/main/java/ai/starwhale/mlops/api/ProjectController.java
server/controller/src/main/java/ai/starwhale/mlops/api/SWModelPackageController.java
server/controller/src/main/java/ai/starwhale/mlops/domain/project/ProjectService.java
server/controller/src/main/java/ai/starwhale/mlops/domain/user/UserService.java
server/controller/src/main/java/ai/starwhale/mlops/exception/SWAuthException.java
server/controller/src/main/java/ai/starwhale/mlops/exception/SWProcessException.java
server/controller/src/main/java/ai/starwhale/mlops/exception/SWValidationException.java

Rest Controller Exceptions

---

server/controller/src/main/java/ai/starwhale/mlops/configuration/security/JwtLoginFilter.java

fix bug: clear login params cache

---

server/controller/pom.xml
server/controller/src/main/java/ai/starwhale/mlops/api/DatasetController.java
server/controller/src/main/java/ai/starwhale/mlops/api/protocol/swmp/ClientSWMPRequest.java
server/controller/src/main/java/ai/starwhale/mlops/common/util/Blake2bUtil.java
server/controller/src/main/java/ai/starwhale/mlops/configuration/CommonExceptionHandler.java
server/controller/src/main/java/ai/starwhale/mlops/domain/job/JobService.java
server/controller/src/main/java/ai/starwhale/mlops/domain/swds/SWDatasetService.java
server/controller/src/main/java/ai/starwhale/mlops/domain/swds/SWDatasetVersionEntity.java
server/controller/src/main/java/ai/starwhale/mlops/domain/swds/SWDatasetVersionMapper.java
server/controller/src/main/java/ai/starwhale/mlops/domain/swds/upload/HotSwdsHolder.java
server/controller/src/main/java/ai/starwhale/mlops/domain/swds/upload/Manifest.java
server/controller/src/main/java/ai/starwhale/mlops/domain/swds/upload/SWDSVersionWithMeta.java
server/controller/src/main/java/ai/starwhale/mlops/domain/swds/upload/SWDSVersionWithMetaConverter.java
server/controller/src/main/java/ai/starwhale/mlops/domain/swds/upload/SwdsUploader.java
server/controller/src/main/java/ai/starwhale/mlops/domain/swds/upload/VersionMeta.java
server/controller/src/main/java/ai/starwhale/mlops/exception/SWAuthException.java
server/controller/src/main/java/ai/starwhale/mlops/exception/SWProcessException.java
server/controller/src/main/java/ai/starwhale/mlops/exception/SWValidationException.java
server/controller/src/main/java/ai/starwhale/mlops/resulting/ResultCollectManager.java
server/controller/src/main/resources/application.yaml
server/controller/src/main/resources/mapper/SWDatasetVersionMapper.xml
server/controller/src/main/resources/sql/schema.sql
server/pom.xml

- allow swds upload duplicate version during uploading phase

allow swds upload duplicate version during uploading phase

---

server/agent/src/main/java/ai/starwhale/mlops/agent/task/action/DoTransition.java
server/agent/src/main/java/ai/starwhale/mlops/agent/task/action/init/RebuildTasksAction.java
server/agent/src/main/java/ai/starwhale/mlops/agent/task/action/normal/AbsBaseTaskTransition.java
server/agent/src/main/java/ai/starwhale/mlops/agent/task/action/normal/FinishedOrCanceled2ArchivedAction.java
server/agent/src/main/java/ai/starwhale/mlops/agent/task/action/normal/Init2PreparingAction.java
server/agent/src/main/java/ai/starwhale/mlops/agent/task/action/normal/MonitorRunningTaskAction.java
server/agent/src/main/java/ai/starwhale/mlops/agent/task/action/normal/Preparing2RunningAction.java
server/agent/src/main/java/ai/starwhale/mlops/agent/task/action/normal/Uploading2FinishedAction.java
server/agent/src/main/java/ai/starwhale/mlops/agent/task/action/report/ReportAction.java
server/agent/src/main/java/ai/starwhale/mlops/agent/task/persistence/FileSystemTaskPersistence.java
server/agent/src/main/java/ai/starwhale/mlops/agent/task/persistence/TaskPersistence.java
server/agent/src/main/resources/application.yaml
server/agent/src/test/java/ai/starwhale/mlops/agent/test/TaskActionTest.java
server/agent/src/test/java/ai/starwhale/mlops/agent/test/TaskExecutorTest.java
server/agent/src/test/resources/application-integrationtest.yaml

Agent debug test

---

server/controller-sdk/src/main/java/ai/starwhale/mlops/api/protocol/ResponseMessage.java
server/controller-sdk/src/main/java/ai/starwhale/mlops/api/protocol/report/req/ReportRequest.java
server/controller-sdk/src/main/java/ai/starwhale/mlops/domain/job/JobRuntime.java
server/controller-sdk/src/main/java/ai/starwhale/mlops/domain/node/Device.java
server/controller-sdk/src/main/java/ai/starwhale/mlops/domain/node/Node.java
server/controller-sdk/src/main/java/ai/starwhale/mlops/domain/swds/SWDataSet.java
server/controller-sdk/src/main/java/ai/starwhale/mlops/domain/swds/index/SWDSBlock.java
server/controller-sdk/src/main/java/ai/starwhale/mlops/domain/swds/index/SWDSDataLocation.java
server/controller-sdk/src/main/java/ai/starwhale/mlops/domain/swmp/SWModelPackage.java
server/controller/src/main/java/ai/starwhale/mlops/api/ReportController.java
server/controller/src/main/java/ai/starwhale/mlops/configuration/security/SecurityConfiguration.java
server/controller/src/main/java/ai/starwhale/mlops/domain/job/JobService.java
server/controller/src/main/java/ai/starwhale/mlops/domain/job/bo/JobBoConverter.java
server/controller/src/main/java/ai/starwhale/mlops/domain/job/split/JobSpliteratorByIndex.java
server/controller/src/main/java/ai/starwhale/mlops/domain/swds/index/SWDSBlockSerializer.java
server/controller/src/main/java/ai/starwhale/mlops/domain/system/Agent.java
server/controller/src/main/java/ai/starwhale/mlops/domain/task/LivingTaskStatusMachineImpl.java
server/controller/src/main/java/ai/starwhale/mlops/domain/task/bo/Task.java
server/controller/src/main/java/ai/starwhale/mlops/domain/task/bo/TaskBoConverter.java
server/controller/src/main/java/ai/starwhale/mlops/domain/task/bo/TaskCommand.java
server/controller/src/main/java/ai/starwhale/mlops/reporting/ReportProcessorImp.java
server/controller/src/main/java/ai/starwhale/mlops/schedule/CommandingTasksChecker.java
server/controller/src/main/resources/sql/schema.sql

fix test issues

---

server/controller/src/main/java/ai/starwhale/mlops/domain/job/JobService.java
server/controller/src/main/java/ai/starwhale/mlops/domain/project/ProjectService.java
server/controller/src/main/java/ai/starwhale/mlops/domain/swds/SWDatasetService.java
server/controller/src/main/java/ai/starwhale/mlops/domain/swds/mapper/SWDatasetVersionMapper.java
server/controller/src/main/java/ai/starwhale/mlops/domain/swmp/SWModelPackageService.java
server/controller/src/main/java/ai/starwhale/mlops/domain/user/UserService.java
server/controller/src/test/java/ai/starwhale/test/login/TestLoginRequest.java

throw exceptions in services

---

server/agent/src/main/java/ai/starwhale/mlops/agent/configuration/NodeConfiguration.java
server/agent/src/main/java/ai/starwhale/mlops/agent/container/impl/DockerContainerClient.java
server/agent/src/main/java/ai/starwhale/mlops/agent/node/initializer/SourcePoolInitializer.java
server/agent/src/main/java/ai/starwhale/mlops/agent/task/Scheduler.java
server/agent/src/main/java/ai/starwhale/mlops/agent/task/action/init/RebuildTasksAction.java
server/agent/src/main/java/ai/starwhale/mlops/agent/task/action/normal/MonitorRunningTaskAction.java
server/agent/src/main/java/ai/starwhale/mlops/agent/task/action/normal/Preparing2RunningAction.java
server/agent/src/main/java/ai/starwhale/mlops/agent/task/action/report/ReportAction.java
server/agent/src/main/java/ai/starwhale/mlops/agent/task/initializer/TaskPoolInitializer.java
server/agent/src/main/java/ai/starwhale/mlops/agent/task/persistence/FileSystemTaskPersistence.java
server/agent/src/main/java/ai/starwhale/mlops/agent/task/persistence/TaskPersistence.java
server/agent/src/main/java/ai/starwhale/mlops/agent/utils/TarUtil.java
server/agent/src/main/resources/application.yaml
server/agent/src/main/resources/docker-java.properties

feat:agent bug fix

---

server/controller/src/main/java/ai/starwhale/mlops/configuration/DataSourceInitializerConfiguration.java

DataSourceInitializerConfiguration

---

server/controller/src/main/java/ai/starwhale/mlops/domain/job/JobService.java
server/controller/src/main/java/ai/starwhale/mlops/domain/project/ProjectService.java
server/controller/src/main/java/ai/starwhale/mlops/domain/swds/SWDatasetService.java
server/controller/src/main/java/ai/starwhale/mlops/domain/swmp/SWModelPackageService.java
server/controller/src/main/java/ai/starwhale/mlops/domain/user/UserService.java

service logs

---

server/agent/src/main/java/ai/starwhale/mlops/agent/configuration/NodeConfiguration.java
server/agent/src/main/java/ai/starwhale/mlops/agent/configuration/TaskConfiguration.java
server/agent/src/main/java/ai/starwhale/mlops/agent/container/ImageConfig.java
server/agent/src/main/java/ai/starwhale/mlops/agent/container/impl/DockerContainerClient.java
server/agent/src/main/java/ai/starwhale/mlops/agent/exception/ErrorCode.java
server/agent/src/main/java/ai/starwhale/mlops/agent/node/SourcePool.java
server/agent/src/main/java/ai/starwhale/mlops/agent/node/base/SimpleSystemDetect.java
server/agent/src/main/java/ai/starwhale/mlops/agent/node/base/SystemInfo.java
server/agent/src/main/java/ai/starwhale/mlops/agent/node/cpu/SimpleCPUDetect.java
server/agent/src/main/java/ai/starwhale/mlops/agent/node/gpu/NvidiaCmdDetect.java
server/agent/src/main/java/ai/starwhale/mlops/agent/node/initializer/SourcePoolInitializer.java
server/agent/src/main/java/ai/starwhale/mlops/agent/task/EvaluationTask.java
server/agent/src/main/java/ai/starwhale/mlops/agent/task/Scheduler.java
server/agent/src/main/java/ai/starwhale/mlops/agent/task/TaskPool.java
server/agent/src/main/java/ai/starwhale/mlops/agent/task/action/init/RebuildTasksAction.java
server/agent/src/main/java/ai/starwhale/mlops/agent/task/action/normal/MonitorRunningTaskAction.java
server/agent/src/main/java/ai/starwhale/mlops/agent/task/action/normal/Preparing2RunningAction.java
server/agent/src/main/java/ai/starwhale/mlops/agent/task/action/normal/Uploading2FinishedAction.java
server/agent/src/main/java/ai/starwhale/mlops/agent/task/action/normal/cancel/AbsBaseCancelTaskTransition.java
server/agent/src/main/java/ai/starwhale/mlops/agent/task/action/normal/cancel/Running2CanceledAction.java
server/agent/src/main/java/ai/starwhale/mlops/agent/task/action/report/ReportAction.java
server/agent/src/main/java/ai/starwhale/mlops/agent/task/executor/TaskExecutor.java
server/agent/src/main/java/ai/starwhale/mlops/agent/task/initializer/TaskPoolInitializer.java
server/agent/src/main/java/ai/starwhale/mlops/agent/task/persistence/FileSystemTaskPersistence.java
server/agent/src/main/java/ai/starwhale/mlops/agent/task/persistence/TaskPersistence.java
server/agent/src/test/java/ai/starwhale/mlops/agent/test/TaskActionTest.java
server/agent/src/test/java/ai/starwhale/mlops/agent/test/TaskExecutorTest.java
server/controller-sdk/src/main/java/ai/starwhale/mlops/domain/node/Node.java

Agent debug test fix

---

server/controller/src/main/java/ai/starwhale/mlops/configuration/schedule/ScheduleConfig.java
server/controller/src/main/java/ai/starwhale/mlops/domain/task/LivingTaskStatusMachineImpl.java
server/controller/src/main/java/ai/starwhale/mlops/domain/task/bo/Task.java
server/controller/src/main/java/ai/starwhale/mlops/reporting/ReportProcessorImp.java
server/controller/src/main/java/ai/starwhale/mlops/resulting/ResultCollectManager.java
server/controller/src/main/java/ai/starwhale/mlops/resulting/impl/NaiveResultingPPLFinder.java
server/controller/src/main/java/ai/starwhale/mlops/resulting/impl/clsmulti/metrics/CohenKappa.java
server/controller/src/main/java/ai/starwhale/mlops/resulting/impl/clsmulti/metrics/MBCConfusionMetrics.java
server/controller/src/main/java/ai/starwhale/mlops/resulting/impl/clsmulti/metrics/MCConfusionMetrics.java
server/controller/src/main/java/ai/starwhale/mlops/resulting/impl/clsmulti/ppl/MCResultingPPL.java
server/controller/src/main/java/ai/starwhale/mlops/resulting/pipline/ResultingPPL.java
server/controller/src/test/java/ai/starwhale/test/domain/task/TestLivingTaskStatusMachine.java
server/storage-access-layer/src/main/java/ai/starwhale/mlops/storage/StorageAccessService.java
server/storage-access-layer/src/main/java/ai/starwhale/mlops/storage/StorageObjectInfo.java
server/storage-access-layer/src/main/java/ai/starwhale/mlops/storage/s3/StorageAccessServiceS3.java

fix test issue

---

server/controller/src/main/java/ai/starwhale/mlops/domain/swmp/SWModelPackageService.java

get swmp version file list

---

server/controller/src/main/java/ai/starwhale/mlops/common/util/BatchOperateHelper.java
server/controller/src/main/java/ai/starwhale/mlops/domain/job/JobService.java
server/controller/src/main/java/ai/starwhale/mlops/domain/job/split/JobSpliteratorByIndex.java
server/controller/src/main/java/ai/starwhale/mlops/domain/swds/upload/SwdsUploader.java
server/controller/src/main/java/ai/starwhale/mlops/domain/task/LivingTaskStatusMachineImpl.java
server/controller/src/main/java/ai/starwhale/mlops/reporting/ReportProcessorImp.java
server/controller/src/test/java/ai/starwhale/test/common/BatchOperateHelperTest.java

- split giant batch jobs
- fix upload id issue

split giant batch jobs

---

server/agent/src/main/java/ai/starwhale/mlops/agent/configuration/NodeConfiguration.java
server/agent/src/main/java/ai/starwhale/mlops/agent/configuration/TaskConfiguration.java
server/agent/src/main/java/ai/starwhale/mlops/agent/task/action/normal/AbsBaseTaskTransition.java
server/agent/src/main/java/ai/starwhale/mlops/agent/task/action/normal/Preparing2RunningAction.java
server/agent/src/main/java/ai/starwhale/mlops/agent/task/persistence/FileSystemPath.java
server/agent/src/main/java/ai/starwhale/mlops/agent/task/persistence/FileSystemTaskPersistence.java
server/agent/src/main/java/ai/starwhale/mlops/agent/task/persistence/TaskPersistence.java
server/agent/src/test/java/ai/starwhale/mlops/agent/test/TaskActionTest.java
server/agent/src/test/java/ai/starwhale/mlops/agent/test/TaskDirTest.java
server/agent/src/test/java/ai/starwhale/mlops/agent/test/TaskExecutorTest.java

Agent separate FSPath from task impl

---

docker/charts/agent.yaml
docker/charts/namespace.yaml

we can run `Agent DaemonSet`, which include `taskset` docker in docker container, `agent` container.

add taskset kubernetes yaml

---

server/controller/src/main/java/ai/starwhale/mlops/api/DatasetController.java
server/controller/src/main/java/ai/starwhale/mlops/domain/swds/SWDatasetService.java

get swds info

---

docker/charts/agent.yaml

add cpu daemonset

---

server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/action/normal/Preparing2RunningAction.java
server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/persistence/FileSystemPath.java
server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/persistence/FileSystemTaskPersistence.java
server/agent/src/main/resources/application.yaml
server/agent/src/main/resources/docker-java.properties
server/agent/src/test/java/ai/starwhale/mlops/agent/test/TaskDirTest.java

Agent cmp support

---

server/controller/src/main/java/ai/starwhale/mlops/configuration/security/JwtLoginFilter.java

login fiter: use form-data

---

server/agent/Dockerfile
server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/action/normal/Preparing2RunningAction.java
server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/persistence/FileSystemTaskPersistence.java

feat:add cmp support

---

server/controller/src/main/resources/mapper/JobMapper.xml

fix select jobs bug

---

server/controller/src/main/java/ai/starwhale/mlops/api/JobApi.java
server/controller/src/main/java/ai/starwhale/mlops/api/JobController.java
server/controller/src/main/java/ai/starwhale/mlops/common/IDConvertor.java
server/controller/src/main/java/ai/starwhale/mlops/domain/job/JobService.java
server/controller/src/main/java/ai/starwhale/mlops/domain/job/mapper/JobMapper.java
server/controller/src/main/resources/mapper/JobMapper.xml

list job by swmpId or order by swmpId

---

server/controller-sdk/src/main/java/ai/starwhale/mlops/api/protocol/TaskStatusInterface.java
server/controller-sdk/src/main/java/ai/starwhale/mlops/api/protocol/report/req/TaskReport.java
server/controller-sdk/src/main/java/ai/starwhale/mlops/domain/task/TaskStatus.java
server/controller/src/main/java/ai/starwhale/mlops/api/protocol/swds/upload/UploadRequest.java
server/controller/src/main/java/ai/starwhale/mlops/common/Reduceable.java
server/controller/src/main/java/ai/starwhale/mlops/domain/job/status/JobStatusMachine.java
server/controller/src/main/java/ai/starwhale/mlops/domain/swds/upload/SwdsUploader.java
server/controller/src/main/java/ai/starwhale/mlops/domain/system/StatusMachine.java
server/controller/src/main/java/ai/starwhale/mlops/domain/task/LivingTaskStatusMachineImpl.java
server/controller/src/main/java/ai/starwhale/mlops/domain/task/status/TaskStatusMachine.java
server/controller/src/main/resources/sql/schema.sql

- fix test issue refactor status

fix test issue refactor status

---

server/controller/src/main/java/ai/starwhale/mlops/api/DatasetController.java
server/controller/src/main/java/ai/starwhale/mlops/api/JobController.java
server/controller/src/main/java/ai/starwhale/mlops/api/ProjectController.java
server/controller/src/main/java/ai/starwhale/mlops/api/SWModelPackageController.java
server/controller/src/main/java/ai/starwhale/mlops/api/SystemController.java
server/controller/src/main/java/ai/starwhale/mlops/api/UserController.java
server/controller/src/main/java/ai/starwhale/mlops/common/util/PageUtil.java
server/controller/src/main/java/ai/starwhale/mlops/domain/job/JobService.java
server/controller/src/main/java/ai/starwhale/mlops/domain/project/ProjectService.java
server/controller/src/main/java/ai/starwhale/mlops/domain/swds/SWDatasetService.java
server/controller/src/main/java/ai/starwhale/mlops/domain/swmp/SWModelPackageService.java
server/controller/src/main/java/ai/starwhale/mlops/domain/system/SystemService.java
server/controller/src/main/java/ai/starwhale/mlops/domain/task/TaskService.java
server/controller/src/main/java/ai/starwhale/mlops/domain/user/UserService.java

fix bug: PageInfo parameters error

---

.gitignore
docker/Dockerfile.agent
docker/Dockerfile.controller
docker/Makefile
server/agent/pom.xml
server/controller/pom.xml
server/pom.xml

feat:image for controller and agent

---

server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/InferenceStage.java
server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/InferenceTask.java
server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/InferenceTaskStatus.java
server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/TaskPool.java
server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/action/end/ArchivedAction.java
server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/action/init/RebuildTasksAction.java
server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/action/normal/Init2PreparingAction.java
server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/action/normal/MonitoringAction.java
server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/action/normal/Preparing2RunningAction.java
server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/action/normal/Uploading2FinishedAction.java
server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/action/normal/cancel/AbsBaseCancelPPLTaskAction.java
server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/action/normal/cancel/ExecuteStage.java
server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/action/normal/cancel/Preparing2CanceledAction.java
server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/action/normal/cancel/Running2CanceledAction.java
server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/action/normal/cancel/Uploading2CanceledAction.java
server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/action/report/ReportAction.java
server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/executor/TaskExecutor.java
server/agent/src/test/java/ai/starwhale/mlops/agent/test/TaskExecutorTest.java
server/pom.xml

feat:agent task status optimise

---

server/controller/src/main/resources/sql/schema.sql

modify job/task status fields in schema.sql

---

server/controller/src/main/java/ai/starwhale/mlops/domain/job/JobService.java
server/controller/src/main/java/ai/starwhale/mlops/domain/task/LivingTaskCache.java
server/controller/src/main/java/ai/starwhale/mlops/domain/task/LivingTaskCacheImpl.java
server/controller/src/main/java/ai/starwhale/mlops/domain/task/LivingTaskLoader.java
server/controller/src/main/java/ai/starwhale/mlops/domain/task/TaskJobStatusHelper.java
server/controller/src/main/java/ai/starwhale/mlops/domain/task/status/TaskStatusMachine.java
server/controller/src/main/java/ai/starwhale/mlops/reporting/ReportProcessorImp.java
server/controller/src/main/java/ai/starwhale/mlops/resulting/CMPTaskFire.java
server/controller/src/main/java/ai/starwhale/mlops/schedule/CommandingTasksChecker.java
server/controller/src/main/java/ai/starwhale/mlops/schedule/SWTaskScheduler.java
server/controller/src/main/java/ai/starwhale/mlops/schedule/SimpleSWTaskScheduler.java
server/controller/src/main/resources/application.yaml
server/controller/src/main/resources/mapper/TaskMapper.xml
server/controller/src/test/java/ai/starwhale/test/agent/AgentMocker.java
server/controller/src/test/java/ai/starwhale/test/domain/task/TestLivingTaskCache.java
server/controller/src/test/java/ai/starwhale/test/domain/task/TestTaskJobStatusHelper.java
server/controller/src/test/java/ai/starwhale/test/domain/task/TestTaskStatusRequirement.java

- refactor task status : add unit test & fix unit test issue

refactor task status : add unit test & fix unit test issue

---

.gitignore
docker/charts/controller.yaml
server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/persistence/FileSystemTaskPersistence.java
server/agent/src/test/java/ai/starwhale/mlops/agent/test/TaskActionTest.java
server/agent/src/test/java/ai/starwhale/mlops/agent/test/TaskExecutorTest.java
server/controller/pom.xml
server/controller/src/main/java/ai/starwhale/mlops/StarWhaleControllerApplication.java
server/controller/src/main/java/ai/starwhale/mlops/api/DatasetController.java
server/controller/src/main/java/ai/starwhale/mlops/api/EnvController.java
server/controller/src/main/java/ai/starwhale/mlops/api/ErrorController.java
server/controller/src/main/java/ai/starwhale/mlops/api/JobController.java
server/controller/src/main/java/ai/starwhale/mlops/api/ProjectController.java
server/controller/src/main/java/ai/starwhale/mlops/api/ReportController.java
server/controller/src/main/java/ai/starwhale/mlops/api/SWModelPackageController.java
server/controller/src/main/java/ai/starwhale/mlops/api/SystemController.java
server/controller/src/main/java/ai/starwhale/mlops/api/UserController.java
server/controller/src/main/java/ai/starwhale/mlops/configuration/ControllerProperties.java
server/controller/src/main/java/ai/starwhale/mlops/configuration/security/JwtLoginFilter.java
server/controller/src/main/java/ai/starwhale/mlops/configuration/security/SecurityConfiguration.java
server/controller/src/main/resources/application.yaml
server/pom.xml

feat:controller auto package with ui

---

server/controller/src/main/java/ai/starwhale/mlops/configuration/ControllerProperties.java
server/controller/src/main/java/ai/starwhale/mlops/configuration/security/SecurityConfiguration.java
server/controller/src/main/resources/application.yaml

feat:add report to white list

---

server/controller/src/main/java/ai/starwhale/mlops/domain/job/JobService.java
server/controller/src/main/java/ai/starwhale/mlops/domain/task/LivingTaskCache.java
server/controller/src/main/java/ai/starwhale/mlops/domain/task/LivingTaskCacheImpl.java
server/controller/src/main/java/ai/starwhale/mlops/domain/task/bo/Task.java
server/controller/src/main/java/ai/starwhale/mlops/reporting/ReportProcessorImp.java
server/controller/src/main/java/ai/starwhale/mlops/reporting/ReportedTask.java
server/controller/src/main/java/ai/starwhale/mlops/resulting/CMPTaskFire.java
server/controller/src/main/java/ai/starwhale/mlops/schedule/CommandingTasksChecker.java
server/controller/src/main/java/ai/starwhale/mlops/schedule/SimpleSWTaskScheduler.java
server/controller/src/test/java/ai/starwhale/test/agent/AgentMocker.java
server/controller/src/test/java/ai/starwhale/test/domain/task/TestLivingTaskCache.java
server/controller/src/test/java/ai/starwhale/test/domain/task/TestTaskJobStatusHelper.java

- add queue ability to AgentMocker
- refactor task reference related code
- fix agent mocker queue issue
- fix paused job can't reschedule issue
- fix task status not update properly of these who are reported from task lost agent

add queue ability to AgentMocker & bug fix

---

server/controller/src/main/java/ai/starwhale/mlops/domain/swds/upload/HotSwdsHolder.java
server/controller/src/main/java/ai/starwhale/mlops/domain/swds/upload/HotSwdsLoader.java
server/controller/src/main/java/ai/starwhale/mlops/domain/task/LivingTaskLoader.java

- alter from PostConstruct to CommandLineRunner

alter from PostConstruct to CommandLineRunner

---

server/controller/src/main/resources/sql/init-data.sql

init-data.sql for user&role

---

server/controller/src/main/java/ai/starwhale/mlops/api/DatasetController.java
server/controller/src/main/java/ai/starwhale/mlops/api/SWModelPackageApi.java
server/controller/src/main/java/ai/starwhale/mlops/api/SWModelPackageController.java
server/controller/src/main/java/ai/starwhale/mlops/api/protocol/swds/upload/UploadRequest.java
server/controller/src/main/java/ai/starwhale/mlops/api/protocol/swmp/ClientSWMPRequest.java
server/controller/src/main/java/ai/starwhale/mlops/domain/project/ProjectManager.java
server/controller/src/main/java/ai/starwhale/mlops/domain/swds/SWDatasetService.java
server/controller/src/main/java/ai/starwhale/mlops/domain/swds/upload/SwdsUploader.java
server/controller/src/main/java/ai/starwhale/mlops/domain/swmp/SWModelPackageService.java
server/controller/src/main/resources/db/migration/V00001__Create_schema.sql

- support swds & swmp force push, support project selecting

support swds & swmp force push, support project selecting

---

server/controller/src/main/java/ai/starwhale/mlops/domain/storage/StoragePathCoordinator.java

- tune storage path coordinator

tune storage path coordinator

---

docker/chart/templates/_helpers.tpl
docker/chart/templates/controller-deployment.yaml
docker/chart/values.yaml

helm charts upgrade for versions

---

server/controller/src/main/java/ai/starwhale/mlops/api/JobController.java

job action words

---

server/controller/src/main/java/ai/starwhale/mlops/api/protocol/job/JobVO.java
server/controller/src/main/java/ai/starwhale/mlops/domain/job/JobConvertor.java
server/controller/src/main/java/ai/starwhale/mlops/domain/job/mapper/JobMapper.java
server/controller/src/main/java/ai/starwhale/mlops/domain/system/agent/Agent.java
server/controller/src/main/java/ai/starwhale/mlops/domain/system/agent/AgentCache.java
server/controller/src/main/java/ai/starwhale/mlops/domain/system/agent/AgentConverter.java
server/controller/src/main/java/ai/starwhale/mlops/domain/system/mapper/AgentMapper.java
server/controller/src/main/java/ai/starwhale/mlops/domain/task/LivingTaskCacheImpl.java
server/controller/src/main/resources/mapper/JobMapper.xml

- fill job finished time 
- fix agent time zone bug

fill job finished time & fix agent time zone bug

---

server/controller-sdk/src/main/java/ai/starwhale/mlops/api/protocol/report/req/TaskLog.java
server/controller-sdk/src/main/java/ai/starwhale/mlops/api/protocol/report/req/TaskReport.java
server/controller-sdk/src/main/java/ai/starwhale/mlops/api/protocol/report/resp/LogReader.java
server/controller-sdk/src/main/java/ai/starwhale/mlops/api/protocol/report/resp/ReportResponse.java

task log protocol objects

---

server/controller-sdk/src/main/java/ai/starwhale/mlops/api/protocol/report/resp/ResultPath.java
server/controller-sdk/src/main/java/ai/starwhale/mlops/api/protocol/report/resp/TaskTrigger.java
server/controller/src/main/java/ai/starwhale/mlops/api/LogApi.java
server/controller/src/main/java/ai/starwhale/mlops/api/LogController.java
server/controller/src/main/java/ai/starwhale/mlops/domain/job/split/JobSpliteratorByIndex.java
server/controller/src/main/java/ai/starwhale/mlops/domain/system/agent/Agent.java
server/controller/src/main/java/ai/starwhale/mlops/domain/task/TaskService.java
server/controller/src/main/java/ai/starwhale/mlops/domain/task/bo/ResultPathConverter.java
server/controller/src/main/java/ai/starwhale/mlops/domain/task/bo/Task.java
server/controller/src/main/java/ai/starwhale/mlops/domain/task/bo/TaskBoConverter.java
server/controller/src/main/java/ai/starwhale/mlops/resulting/CMPTaskFire.java
server/controller/src/main/java/ai/starwhale/mlops/schedule/CommandingTasksChecker.java
server/controller/src/test/java/ai/starwhale/test/agent/AgentMocker.java
server/controller/src/test/java/ai/starwhale/test/schedule/TestCommandingTasksChecker.java

- offline log api
- task status loss bug fix

offline log api & task status loss bug fix

---

console/package.json
console/src/components/BusyLoaderWrapper/BusyPlaceholder.tsx
console/src/pages/BaseSubLayout.tsx
console/src/utils/datetime.ts
console/yarn.lock

1. job UI optimize
2. datetime by browser timezone

enhance: datetime by browser timezone

---

server/controller-sdk/src/main/java/ai/starwhale/mlops/api/protocol/report/req/TaskLog.java
server/controller/pom.xml
server/controller/src/main/java/ai/starwhale/mlops/api/ReportController.java
server/controller/src/main/java/ai/starwhale/mlops/api/TaskLogWSServer.java
server/controller/src/main/java/ai/starwhale/mlops/configuration/WebSocketConfig.java
server/controller/src/main/java/ai/starwhale/mlops/reporting/ReportProcessorImp.java

online task log with websocket

---

docker/chart/templates/NOTES.txt
docker/chart/templates/controller-deployment.yaml
docker/chart/templates/controller-ingress.yaml
docker/chart/values.yaml

tune helm chart for minikube

---

docker/chart/templates/_helpers.tpl

fix charts buckets typo

---

server/controller/src/main/java/ai/starwhale/mlops/domain/system/agent/AgentCache.java
server/controller/src/test/java/ai/starwhale/test/agent/AgentMocker.java
server/controller/src/test/java/ai/starwhale/test/agent/AgentMockerRunner.java

- support multiple agent mocker

support multiple agent mocker

---

docker/Makefile
docker/chart/values.yaml
server/agent/src/main/java/ai/starwhale/mlops/agent/container/impl/DockerContainerClient.java
server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/LogRecorder.java
server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/persistence/FileSystemTaskPersistence.java
server/agent/src/main/java/ai/starwhale/mlops/agent/utils/FileUtil.java
server/controller/pom.xml

Fix file executable bug

---

server/controller-sdk/src/main/java/ai/starwhale/mlops/api/protocol/report/resp/ResultPath.java
server/controller/pom.xml
server/controller/src/main/java/ai/starwhale/mlops/domain/task/TaskService.java
server/controller/src/main/java/ai/starwhale/mlops/resulting/CMPTaskFire.java

fix result dir bug

---

docker/Makefile
docker/chart/values.yaml
server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/persistence/FileSystemTaskPersistence.java

fix: result path bug fix

---

server/controller/src/main/java/ai/starwhale/mlops/domain/system/mapper/AgentMapper.java

add param declaration

---

server/controller/src/main/resources/mapper/AgentMapper.xml
server/controller/src/main/resources/mapper/BaseImageMapper.xml
server/controller/src/main/resources/mapper/JobMapper.xml
server/controller/src/main/resources/mapper/Role.xml
server/controller/src/main/resources/mapper/SWDatasetMapper.xml
server/controller/src/main/resources/mapper/SWModelPackageMapper.xml
server/controller/src/main/resources/mapper/TaskMapper.xml
server/controller/src/main/resources/mapper/UserMapper.xml

add order for queries of list

---

server/controller/src/main/java/ai/starwhale/mlops/configuration/security/JwtTokenFilter.java

get jwt token by request parameter

---

docker/Makefile
docker/chart/values.yaml
server/agent/src/main/java/ai/starwhale/mlops/agent/container/ContainerClient.java
server/agent/src/main/java/ai/starwhale/mlops/agent/container/impl/DockerContainerClient.java
server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/LogRecorder.java
server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/action/end/ArchivedAction.java
server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/action/normal/Preparing2RunningAction.java
server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/action/normal/Uploading2FinishedAction.java
server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/action/normal/cancel/Running2CanceledAction.java
server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/persistence/FileSystemPath.java
server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/persistence/FileSystemTaskPersistence.java
server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/persistence/TaskPersistence.java

Log bug fix

---

server/controller/src/main/java/ai/starwhale/mlops/domain/job/mapper/JobMapper.java
server/controller/src/main/java/ai/starwhale/mlops/resulting/CMPTaskFire.java
server/controller/src/main/resources/mapper/JobMapper.xml

- fix: #issue:178 update job result path with task path

fix: #issue:178 update job result path with task path

---

server/controller/src/main/java/ai/starwhale/mlops/api/JobController.java
server/controller/src/main/java/ai/starwhale/mlops/common/Invoker.java
server/controller/src/main/java/ai/starwhale/mlops/common/InvokerManager.java

use invoker instead of if-else

---

server/controller/src/main/java/ai/starwhale/mlops/configuration/security/JwtLoginSuccessHandler.java

add user information in login response

---

server/controller/src/main/resources/mapper/AgentMapper.xml

sql error fix

---

server/controller/src/main/java/ai/starwhale/mlops/api/SWModelPackageApi.java
server/controller/src/main/java/ai/starwhale/mlops/api/protocol/job/JobVO.java
server/controller/src/main/java/ai/starwhale/mlops/api/protocol/project/ProjectVO.java
server/controller/src/main/java/ai/starwhale/mlops/api/protocol/swds/DatasetVO.java
server/controller/src/main/java/ai/starwhale/mlops/api/protocol/swds/DatasetVersionVO.java
server/controller/src/main/java/ai/starwhale/mlops/api/protocol/swmp/SWModelPackageVO.java
server/controller/src/main/java/ai/starwhale/mlops/api/protocol/swmp/SWModelPackageVersionVO.java
server/controller/src/main/java/ai/starwhale/mlops/api/protocol/task/TaskVO.java
server/controller/src/main/java/ai/starwhale/mlops/domain/job/JobConvertor.java
server/controller/src/main/java/ai/starwhale/mlops/domain/project/ProjectConvertor.java
server/controller/src/main/java/ai/starwhale/mlops/domain/swds/SWDSConvertor.java
server/controller/src/main/java/ai/starwhale/mlops/domain/swds/SWDSVersionConvertor.java
server/controller/src/main/java/ai/starwhale/mlops/domain/swmp/SWMPConvertor.java
server/controller/src/main/java/ai/starwhale/mlops/domain/swmp/SWMPVersionConvertor.java
server/controller/src/main/java/ai/starwhale/mlops/domain/task/TaskConvertor.java

Enhancement & Bug in issue #186

---

server/controller/src/main/java/ai/starwhale/mlops/api/EnvController.java
server/controller/src/main/java/ai/starwhale/mlops/api/ProjectController.java
server/controller/src/main/java/ai/starwhale/mlops/api/SWModelPackageApi.java
server/controller/src/main/java/ai/starwhale/mlops/api/SWModelPackageController.java
server/controller/src/main/java/ai/starwhale/mlops/api/SystemController.java
server/controller/src/main/java/ai/starwhale/mlops/api/UserController.java
server/controller/src/main/java/ai/starwhale/mlops/domain/swmp/SWMPObject.java
server/controller/src/main/java/ai/starwhale/mlops/domain/swmp/SWModelPackageService.java
server/controller/src/main/java/ai/starwhale/mlops/domain/swmp/mapper/SWModelPackageVersionMapper.java
server/controller/src/main/resources/mapper/ProjectMapper.xml
server/controller/src/main/resources/mapper/SWModelPackageVersionMapper.xml
server/controller/src/test/java/ai/starwhale/test/login/TestPasswordEncoder.java

Enhancement: get the file list by model version id

---

docker/Makefile
server/agent/src/test/java/ai/starwhale/mlops/agent/test/TaskActionTest.java
server/agent/src/test/java/ai/starwhale/mlops/agent/test/TaskExecutorTest.java

fix: maven build path bug

---

.github/workflows/maven-build.yml
.github/workflows/release.yml

feat: add ci for maven build and release

---

.github/workflows/maven-build.yml

Update trigger time for maven-build.yml

---

client/starwhale/base/store.py
client/starwhale/swds/store.py
client/starwhale/swmp/store.py

fix unfriendly trackback error.
- https://github.com/star-whale/starwhale/issues/295
- #220

bug: fix empty exception for swmp/swds list

---

client/starwhale/swmp/store.py

related: #194 
swmp list use extracted swmp _manifest.yaml first.

enhance: use extracted manifest for swmp list

---

README.md

chores: update readme for ci badge

---

server/controller/src/main/java/ai/starwhale/mlops/api/EnvApi.java
server/controller/src/main/java/ai/starwhale/mlops/api/EnvController.java
server/controller/src/main/java/ai/starwhale/mlops/api/protocol/runtime/BaseImageRequest.java
server/controller/src/main/java/ai/starwhale/mlops/domain/job/BaseImage.java
server/controller/src/main/java/ai/starwhale/mlops/domain/job/EnvService.java
server/controller/src/main/java/ai/starwhale/mlops/domain/job/mapper/BaseImageMapper.java
server/controller/src/main/resources/mapper/BaseImageMapper.xml

feature: add base image management API

---

client/.flake8
client/Makefile
client/pyproject.toml
client/requirements.txt
client/starwhale/api/_impl/loader.py
client/starwhale/api/_impl/model.py
client/starwhale/cli/__init__.py
client/starwhale/cluster/model.py
client/starwhale/cluster/view.py
client/starwhale/eval/store.py
client/starwhale/mngt/user.py
client/starwhale/swds/dataset.py
client/starwhale/swmp/docker.py
client/starwhale/swmp/model.py
client/starwhale/swmp/store.py
client/starwhale/utils/__init__.py
client/starwhale/utils/debug.py
client/starwhale/utils/error.py
client/starwhale/utils/load.py
client/starwhale/utils/obj.py
client/starwhale/utils/progress.py
client/starwhale/utils/venv.py

- add flake8
- fix client codes for flake8
- #223

ci: add python flake8 lint

---

.github/workflows/client.yaml
client/Makefile
client/pyproject.toml
client/requirements-dev.txt
client/setup.py
client/starwhale/api/_impl/dataset.py
client/starwhale/api/_impl/loader.py
client/starwhale/api/_impl/metric.py
client/starwhale/api/_impl/model.py
client/starwhale/base/store.py
client/starwhale/cli/eval.py
client/starwhale/cli/model.py
client/starwhale/cluster/model.py
client/starwhale/cluster/view.py
client/starwhale/consts/__init__.py
client/starwhale/consts/env.py
client/starwhale/eval/executor.py
client/starwhale/eval/store.py
client/starwhale/swds/dataset.py
client/starwhale/swds/store.py
client/starwhale/swmp/docker.py
client/starwhale/swmp/model.py
client/starwhale/swmp/store.py
client/starwhale/utils/__init__.py
client/starwhale/utils/config.py
client/starwhale/utils/log.py
client/starwhale/utils/process.py

- add mypy ci
- fix code for mypy type check
- #223

ci: add mypy type hint check

---

Makefile
client/Makefile
client/requirements-dev.txt
client/tests/utils/test_config.py

ci: add pytest framework for client

---

server/controller/src/main/java/ai/starwhale/mlops/api/DatasetController.java
server/controller/src/main/java/ai/starwhale/mlops/api/JobController.java
server/controller/src/main/java/ai/starwhale/mlops/api/ProjectApi.java
server/controller/src/main/java/ai/starwhale/mlops/api/ProjectController.java
server/controller/src/main/java/ai/starwhale/mlops/api/SWModelPackageController.java
server/controller/src/main/java/ai/starwhale/mlops/api/UserController.java
server/controller/src/main/java/ai/starwhale/mlops/common/BaseParams.java
server/controller/src/main/java/ai/starwhale/mlops/common/OrderParams.java
server/controller/src/main/java/ai/starwhale/mlops/configuration/security/JwtTokenFilter.java
server/controller/src/main/java/ai/starwhale/mlops/domain/job/JobService.java
server/controller/src/main/java/ai/starwhale/mlops/domain/project/Project.java
server/controller/src/main/java/ai/starwhale/mlops/domain/project/ProjectManager.java
server/controller/src/main/java/ai/starwhale/mlops/domain/project/ProjectService.java
server/controller/src/main/java/ai/starwhale/mlops/domain/project/mapper/ProjectMapper.java
server/controller/src/main/java/ai/starwhale/mlops/domain/swds/SWDSObject.java
server/controller/src/main/java/ai/starwhale/mlops/domain/swds/SWDatasetService.java
server/controller/src/main/java/ai/starwhale/mlops/domain/swmp/SWModelPackageService.java
server/controller/src/main/java/ai/starwhale/mlops/domain/task/TaskService.java
server/controller/src/main/java/ai/starwhale/mlops/domain/user/Role.java
server/controller/src/main/java/ai/starwhale/mlops/domain/user/User.java
server/controller/src/main/java/ai/starwhale/mlops/domain/user/UserService.java
server/controller/src/main/resources/mapper/ProjectMapper.xml

refactor: Use Long type id in services. Move idConvertor to controllers.

---

server/controller/src/main/java/ai/starwhale/mlops/common/IDConvertor.java

fix : number format error in id convertor

---

.github/workflows/release.yml
docker/Makefile

fix: adjust the sequence for build images

---

server/controller/src/main/java/ai/starwhale/mlops/api/JobApi.java
server/controller/src/main/java/ai/starwhale/mlops/api/JobController.java
server/controller/src/main/java/ai/starwhale/mlops/api/protocol/job/JobVO.java
server/controller/src/main/java/ai/starwhale/mlops/domain/job/JobConvertor.java
server/controller/src/main/java/ai/starwhale/mlops/domain/job/JobEntity.java
server/controller/src/main/java/ai/starwhale/mlops/domain/job/JobService.java
server/controller/src/main/java/ai/starwhale/mlops/domain/job/mapper/JobMapper.java
server/controller/src/main/resources/db/migration/V00005__add_job_comment.sql
server/controller/src/main/resources/mapper/JobMapper.xml

feature: add job comment

---

docker/Dockerfile.base_server
docker/Dockerfile.server
docker/Makefile

seperate some fixed layers into server base image, which can speedup the buiding of server image.

enhanced: refactor server image

---

client/starwhale/api/_impl/model.py
client/starwhale/swmp/model.py

fix typing namedTuple index and idx name error.

bug: fix ppl/cmp refactor bugs

---

.github/workflows/release.yml

hotfix: fix release yaml install typo

---

client/starwhale/cli/cluster.py
client/starwhale/cli/eval.py
client/starwhale/cli/project.py
client/starwhale/cluster/model.py
client/starwhale/cluster/view.py
client/starwhale/mngt/user.py
client/starwhale/utils/debug.py
client/starwhale/utils/http.py

- add `swcli project create` cmd to create project
- ![image](https://user-images.githubusercontent.com/590748/168422983-0635564c-955e-4c0d-9c55-9cee0871dc20.png)
- ![image](https://user-images.githubusercontent.com/590748/168422996-cc82eaa2-0e31-4a43-b780-ebae6230db82.png)
- #190  #186 
- update role field for new api
- update `createdTime` field 
- add `swcli eval cluster run ` cmd to create job.
- ![image](https://user-images.githubusercontent.com/590748/168427633-05e718f3-a300-43bc-86ef-d02f158b2bd8.png)
- https://github.com/star-whale/starwhale/issues/284

feat: swcli create cmd for cluster project/job

---

.github/workflows/docs.yaml

hotfix: fix docs ci main branch typo

---

server/agent/src/main/resources/application.yaml

fix:agent properties bug

---

client/starwhale/utils/venv.py

use more common file name for python req file name
related issue: #278

chores: refactor dump pip file name

---

server/controller/src/main/java/ai/starwhale/mlops/domain/project/ProjectManager.java
server/controller/src/main/java/ai/starwhale/mlops/domain/project/ProjectService.java
server/controller/src/main/java/ai/starwhale/mlops/domain/project/mapper/ProjectMapper.java
server/controller/src/main/resources/mapper/ProjectMapper.xml

fix bug: Add project name verification before creating project

---

client/starwhale/swmp/model.py
client/starwhale/utils/__init__.py
client/starwhale/utils/error.py
client/starwhale/utils/venv.py
example/mnist/model.yaml

enhance: add model.yaml runtime check

---

client/starwhale/swmp/store.py
client/starwhale/utils/fs.py
client/starwhale/utils/ui.py

enhance: add sudo empty_dir cmd as the permission error fallback

---

client/.flake8
client/pyproject.toml
client/starwhale/api/_impl/metric.py
client/starwhale/api/_impl/model.py
example/mnist/mnist/ppl.py
example/mnist/test/ppl_output_fuse_smoke.json

related: #196 
- cmp output file: [current.zip](https://github.com/star-whale/starwhale/files/8699705/current.zip)
- field: 
```json
{
"roc_auc": {
"0": {
"fpr": [0,0,],
"tpr": [0,0,],
"auc": 0.9999712656681298,
"thresholds": [2,2],
}
}
}
```

feat: add roc/auc for multi classification report

---

client/starwhale/base/store.py
client/starwhale/cli/dataset.py
client/starwhale/cli/eval.py
client/starwhale/cli/model.py
client/starwhale/cluster/view.py
client/starwhale/eval/store.py
client/starwhale/swds/dataset.py
client/starwhale/swds/store.py
client/starwhale/swmp/model.py
client/starwhale/swmp/store.py

- issue: #216 
- feature show:
- ![image](https://user-images.githubusercontent.com/590748/168748305-2906d9af-b59d-4ae7-98c1-e0068220752a.png)
- ![image](https://user-images.githubusercontent.com/590748/168748352-5c10da38-e7c5-4c69-a846-477683c66830.png)
- ![image](https://user-images.githubusercontent.com/590748/168748395-9937fcec-5679-4ff3-a10e-c082983488ce.png)

feat: support short name for swmp/swds/eval/dataset

---

client/pyproject.toml
client/starwhale/__init__.py
client/starwhale/api/_impl/dataset.py
client/starwhale/api/_impl/model.py
client/starwhale/cli/__init__.py
client/starwhale/cli/mngt.py
client/starwhale/cluster/model.py
client/starwhale/mngt/user.py
client/starwhale/utils/http.py

- enable mypy `disallow_untyped_calls` flag.
- #223

refactor: update for mypy disallow_untyped_calls

---

server/controller/src/main/java/ai/starwhale/mlops/api/DatasetApi.java
server/controller/src/main/java/ai/starwhale/mlops/api/DatasetController.java
server/controller/src/main/java/ai/starwhale/mlops/domain/storage/StorageService.java
server/controller/src/main/java/ai/starwhale/mlops/domain/swds/SWDatasetService.java
server/controller/src/main/java/ai/starwhale/mlops/domain/swds/mapper/SWDatasetVersionMapper.java
server/controller/src/main/java/ai/starwhale/mlops/domain/swds/upload/SwdsUploader.java
server/controller/src/main/resources/mapper/SWDatasetVersionMapper.xml

- add swds pull & list for CLI

add swds pull & list for CLI

---

client/starwhale/api/_impl/loader.py

- expose: `SW_S3_CONNECT_TIMEOUT` , `SW_S3_READ_TIMEOUT`, `SW_S3_TOTAL_MAX_ATTEMPTS` env for s3 connection
- set more reasonable default timeout value
- issue: #219 
- ref: https://botocore.amazonaws.com/v1/documentation/api/latest/reference/config.html

enhance: set more reasonable s3 config for timeout and retry

---

server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/action/end/ArchivedAction.java

fix:agent error catch

---

server/controller/src/main/java/ai/starwhale/mlops/domain/task/TaskJobStatusHelper.java
server/controller/src/main/java/ai/starwhale/mlops/domain/task/cache/CacheWrapperForWatch.java
server/controller/src/main/java/ai/starwhale/mlops/domain/task/cache/CacheWrapperReadOnly.java
server/controller/src/main/java/ai/starwhale/mlops/domain/task/cache/LivingTaskCache.java
server/controller/src/main/java/ai/starwhale/mlops/domain/task/cache/LivingTaskCacheImpl.java
server/controller/src/main/java/ai/starwhale/mlops/domain/task/status/watchers/TaskWatcherForCache.java
server/controller/src/main/java/ai/starwhale/mlops/domain/task/status/watchers/TaskWatcherForJob.java
server/controller/src/main/java/ai/starwhale/mlops/reporting/ReportProcessorImp.java
server/controller/src/main/java/ai/starwhale/mlops/schedule/SimpleSWTaskScheduler.java
server/controller/src/main/resources/db/migration/V00006__add_dag.sql
server/controller/src/test/java/ai/starwhale/test/domain/task/TestTaskJobStatusHelper.java

- fix task of fail job can't update it's status

fix task of fail job can't update it's status

---

docker/charts/Chart.yaml

hotfix: fix Chart.yaml version typo

---

docker/charts/templates/_helpers.tpl

hotfix: fix latest default tag

---

.github/workflows/helm-charts.yaml
docker/charts/Makefile
docker/charts/README.md
docker/charts/templates/NOTES.txt

- add `helm template` lint
- fix notes typo
- update helm charts readme for  minikube example
- #240 
- #258

fix: update helm charts notes

---

docker/charts/Chart.yaml

chroes: update logo icon for helm charts

---

bootstrap/roles/agent/tasks/main.yaml
bootstrap/roles/controller/tasks/main.yaml
bootstrap/roles/minio/tasks/main.yaml
bootstrap/roles/mysql/tasks/main.yaml

fix: bootstrap mount docker path

---

server/controller/src/main/java/ai/starwhale/mlops/api/JobController.java
server/controller/src/main/java/ai/starwhale/mlops/api/protocol/job/JobRequest.java
server/controller/src/main/resources/mapper/SWDatasetVersionMapper.xml
server/controller/src/main/resources/mapper/SWModelPackageVersionMapper.xml

fix bug: revert swds/swmp version unique index error & matching property names

---

client/starwhale/cluster/model.py

for: https://github.com/star-whale/starwhale/pull/375

chores: update field for server api changed

---

console/src/domain/job/components/JobForm.tsx
console/src/domain/job/schemas/agent.tsx
console/src/domain/job/schemas/job.tsx
console/src/i18n/locales.ts
console/src/pages/Settings/SettingAgentListCard.tsx

1. change deviceCount to deviceAmount
2. agent can be deleted only when status offline

chores: change deviceCount to deviceAmount

---

example/mnist/mnist/ppl.py

bug: fix mnist ppl typo for numpy input

---

client/starwhale/base/store.py
client/starwhale/eval/store.py
client/starwhale/swds/dataset.py
client/starwhale/swds/store.py
client/starwhale/swmp/store.py
example/mnist/mnist/ppl.py

bug:  fix push fullname error

---

docker/charts/values.yaml

chores: update default request/limit for controller cpu

---

client/starwhale/base/store.py
client/starwhale/swmp/store.py
client/starwhale/utils/http.py

- fix `silent` for wrap http
- fix shortname error

bug: fix push error for silent and parse name

---

server/controller/src/main/java/ai/starwhale/mlops/api/SWModelPackageApi.java
server/controller/src/main/java/ai/starwhale/mlops/api/SWModelPackageController.java
server/controller/src/main/java/ai/starwhale/mlops/domain/swmp/SWModelPackageService.java

- tune swmp pull memory consumtion

tune swmp pull memory consumtion

---

client/starwhale/instance/__init__.py

enhance: highlight current instance in list

---

server/controller/src/main/java/ai/starwhale/mlops/api/EnvApi.java
server/controller/src/main/java/ai/starwhale/mlops/api/EnvController.java
server/controller/src/main/java/ai/starwhale/mlops/domain/job/EnvService.java
server/controller/src/main/resources/mapper/JobMapper.xml
server/controller/src/main/resources/mapper/TaskMapper.xml

fix bug of job list

---

server/controller/src/main/java/ai/starwhale/mlops/api/ProjectApi.java
server/controller/src/main/java/ai/starwhale/mlops/api/ProjectController.java
server/controller/src/main/java/ai/starwhale/mlops/api/TaskLogWSServer.java
server/controller/src/main/java/ai/starwhale/mlops/domain/project/ProjectService.java
server/controller/src/main/java/ai/starwhale/mlops/domain/project/mapper/ProjectMapper.java
server/controller/src/main/resources/mapper/JobMapper.xml
server/controller/src/main/resources/mapper/ProjectMapper.xml

Project recover & remove. Job log report & Job list order

---

server/controller/src/main/java/ai/starwhale/mlops/api/JobApi.java
server/controller/src/main/java/ai/starwhale/mlops/api/JobController.java
server/controller/src/main/java/ai/starwhale/mlops/api/ProjectApi.java
server/controller/src/main/java/ai/starwhale/mlops/api/ProjectController.java
server/controller/src/main/java/ai/starwhale/mlops/common/IDConvertor.java
server/controller/src/main/java/ai/starwhale/mlops/domain/job/JobEntity.java
server/controller/src/main/java/ai/starwhale/mlops/domain/job/JobManager.java
server/controller/src/main/java/ai/starwhale/mlops/domain/job/JobService.java
server/controller/src/main/java/ai/starwhale/mlops/domain/job/mapper/JobMapper.java
server/controller/src/main/java/ai/starwhale/mlops/domain/project/Project.java
server/controller/src/main/java/ai/starwhale/mlops/domain/project/ProjectManager.java
server/controller/src/main/java/ai/starwhale/mlops/domain/project/ProjectService.java
server/controller/src/main/java/ai/starwhale/mlops/domain/project/mapper/ProjectMapper.java
server/controller/src/main/resources/db/migration/V00007__add_job_deleted.sql
server/controller/src/main/resources/mapper/JobMapper.xml
server/controller/src/main/resources/mapper/ProjectMapper.xml

Project APIs support id/name as projectUrl. Remove and recover job by jobUrl(job_id or uuid)

---

server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/action/normal/Preparing2RunningAction.java

fix:agent allocate devices bug

---

server/controller/src/main/java/ai/starwhale/mlops/api/JobApi.java
server/controller/src/main/java/ai/starwhale/mlops/api/JobController.java
server/controller/src/main/java/ai/starwhale/mlops/api/ProjectController.java
server/controller/src/main/java/ai/starwhale/mlops/domain/dag/DAGQuerier.java
server/controller/src/main/java/ai/starwhale/mlops/domain/job/JobManager.java
server/controller/src/main/java/ai/starwhale/mlops/domain/job/JobService.java
server/controller/src/main/java/ai/starwhale/mlops/domain/project/Project.java
server/controller/src/main/java/ai/starwhale/mlops/domain/project/ProjectManager.java
server/controller/src/main/java/ai/starwhale/mlops/domain/task/TaskService.java

Job apis support job url(job id or uuid) instead of job id

---

server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/action/normal/Preparing2RunningAction.java

fix device set bug

---

client/starwhale/swds/dataset.py
example/PennFudanPed/code/coco_eval.py
example/PennFudanPed/code/coco_utils.py
example/PennFudanPed/code/data_slicer.py
example/PennFudanPed/code/ds.py
example/PennFudanPed/code/engine.py
example/PennFudanPed/code/model.py
example/PennFudanPed/code/ppl.py
example/PennFudanPed/code/test.py
example/PennFudanPed/code/train.py
example/PennFudanPed/code/transforms.py
example/PennFudanPed/code/utils.py
example/PennFudanPed/dataset.yaml
example/PennFudanPed/model.yaml
example/PennFudanPed/requirements.txt

- an example of mask rcnn with backbone of resnet50 trained on PennFudanPed dataset to do pedestrian detection and instance segmentation
- fix writer close issue
you could view it on http://console.pre.intra.starwhale.ai/projects/1/jobs/35/tasks
and extract the evaluation metrics use
`curl -X 'GET' \
'http://console.pre.intra.starwhale.ai/api/v1/project/1/job/35/result' \
-H 'accept: application/json' \
-H 'Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxLHN0YXJ3aGFsZSIsImlzcyI6InN0YXJXaGFsZSIsImlhdCI6MTY1MzYxNzgwNSwiZXhwIjoxNjUzNzA0MjA1fQ.7KJ0RW04BpIL2YC0ubSiFVS4na7wXqEk6NEj1VodHLDsm9eUxkhbyCnojrlKdQrC0ImjikpRPNseVu0Lp11sBg'`
`{
"data": [
{
"bbox": [
0.8758785903756364,
0.999381188118812,
0.9535442674702251,
-1,
0.9663366336633663, …

an example of mask rcnn on PennFudanPed

---

server/controller/src/main/java/ai/starwhale/mlops/api/ProjectController.java
server/controller/src/main/java/ai/starwhale/mlops/api/RuntimeApi.java
server/controller/src/main/java/ai/starwhale/mlops/api/RuntimeController.java
server/controller/src/main/java/ai/starwhale/mlops/api/protocol/runtime/ClientRuntimeRequest.java
server/controller/src/main/java/ai/starwhale/mlops/api/protocol/runtime/RuntimeInfoVO.java
server/controller/src/main/java/ai/starwhale/mlops/api/protocol/runtime/RuntimeRevertRequest.java
server/controller/src/main/java/ai/starwhale/mlops/api/protocol/runtime/RuntimeVO.java
server/controller/src/main/java/ai/starwhale/mlops/api/protocol/runtime/RuntimeVersionVO.java
server/controller/src/main/java/ai/starwhale/mlops/common/util/JwtTokenUtil.java
server/controller/src/main/java/ai/starwhale/mlops/domain/project/ProjectManager.java
server/controller/src/main/java/ai/starwhale/mlops/domain/runtime/RuntimeConvertor.java
server/controller/src/main/java/ai/starwhale/mlops/domain/runtime/RuntimeManager.java
server/controller/src/main/java/ai/starwhale/mlops/domain/runtime/RuntimeQuery.java
server/controller/src/main/java/ai/starwhale/mlops/domain/runtime/RuntimeService.java
server/controller/src/main/java/ai/starwhale/mlops/domain/runtime/RuntimeVersion.java
server/controller/src/main/java/ai/starwhale/mlops/domain/runtime/RuntimeVersionConvertor.java
server/controller/src/main/java/ai/starwhale/mlops/domain/runtime/RuntimeVersionQuery.java
server/controller/src/main/java/ai/starwhale/mlops/domain/runtime/mapper/RuntimeMapper.java
server/controller/src/main/java/ai/starwhale/mlops/domain/runtime/mapper/RuntimeVersionMapper.java
server/controller/src/main/java/ai/starwhale/mlops/domain/storage/StoragePathCoordinator.java
server/controller/src/main/java/ai/starwhale/mlops/domain/swds/SWDatasetService.java
server/controller/src/main/java/ai/starwhale/mlops/domain/swds/upload/SwdsUploader.java
server/controller/src/main/java/ai/starwhale/mlops/domain/swmp/SWModelPackageService.java
server/controller/src/main/java/ai/starwhale/mlops/exception/SWValidationException.java
server/controller/src/main/resources/mapper/RuntimeMapper.xml
server/controller/src/main/resources/mapper/RuntimeVersionMapper.xml

REST Api for SWRuntime

---

client/starwhale/api/_impl/model.py

- related issue:  #407 
- record raise directly

fix: raise exception for ppl/cmp handler

---

docker/charts/templates/_helpers.tpl
docker/charts/templates/controller-deployment.yaml

extend the probe initialDelaySeconds

extend the startup probe initialDelaySeconds

---

server/controller/src/main/java/ai/starwhale/mlops/api/ProjectController.java
server/controller/src/main/java/ai/starwhale/mlops/api/RuntimeController.java
server/controller/src/main/java/ai/starwhale/mlops/api/SWModelPackageApi.java
server/controller/src/main/java/ai/starwhale/mlops/api/SWModelPackageController.java
server/controller/src/main/java/ai/starwhale/mlops/api/protocol/swmp/RevertSWMPVersionRequest.java
server/controller/src/main/java/ai/starwhale/mlops/domain/runtime/RuntimeService.java
server/controller/src/main/java/ai/starwhale/mlops/domain/swmp/SWMPQuery.java
server/controller/src/main/java/ai/starwhale/mlops/domain/swmp/SWMPVersionQuery.java
server/controller/src/main/java/ai/starwhale/mlops/domain/swmp/SWModelPackageService.java
server/controller/src/main/java/ai/starwhale/mlops/domain/swmp/SwmpManager.java
server/controller/src/main/java/ai/starwhale/mlops/domain/swmp/mapper/SWModelPackageMapper.java
server/controller/src/main/java/ai/starwhale/mlops/domain/swmp/mapper/SWModelPackageVersionMapper.java
server/controller/src/main/resources/mapper/SWModelPackageMapper.xml

RESTApis for SWMP support id/name in url

---

client/starwhale/base/bundle.py
client/starwhale/base/bundle_copy.py
client/starwhale/base/cloud.py
client/starwhale/base/view.py
client/starwhale/core/dataset/cli.py
client/starwhale/core/dataset/model.py
client/starwhale/core/dataset/view.py
client/starwhale/core/model/cli.py
client/starwhale/core/model/model.py
client/starwhale/core/model/view.py
client/starwhale/core/runtime/model.py
client/starwhale/core/runtime/view.py
client/tests/core/test_dataset.py
client/tests/core/test_model.py
client/tests/core/test_runtime.py

-  https://github.com/star-whale/starwhale/issues/447
-  https://github.com/star-whale/starwhale/issues/430
- list runtime/model/dataset
- ![cloud-list](https://user-images.githubusercontent.com/590748/171608267-f834dbe2-9b48-4c2c-99e0-33dd691e6908.gif)
- info
- ![image](https://user-images.githubusercontent.com/590748/171613576-d275101a-2a6c-41c8-9cf3-f0f531dc7d1d.png)
- history
- ![cloud-info](https://user-images.githubusercontent.com/590748/171614395-8596d7ed-fed6-461b-8058-79c1a274af2e.gif)

feat: add cmds for cloud mode

---

client/starwhale/base/bundle_copy.py

bug: fix runtime copy existed typo

---

client/starwhale/cli/mngt.py
client/starwhale/mngt/__init__.py
client/starwhale/utils/fs.py
client/tests/core/test_mngt.py

- add web ui command:
-  ![ui](https://user-images.githubusercontent.com/590748/171994882-a53e6ad8-2e9f-43ad-b964-42a20c3d55f2.gif)
- add gc command: #265

feat: add gc/ui command

---

server/controller-sdk/src/main/java/ai/starwhale/mlops/api/protocol/report/resp/SWRunTime.java
server/controller-sdk/src/main/java/ai/starwhale/mlops/api/protocol/report/resp/TaskTrigger.java
server/controller/src/main/java/ai/starwhale/mlops/api/JobController.java
server/controller/src/main/java/ai/starwhale/mlops/api/protocol/job/JobRequest.java
server/controller/src/main/java/ai/starwhale/mlops/api/protocol/job/JobVO.java
server/controller/src/main/java/ai/starwhale/mlops/domain/job/Job.java
server/controller/src/main/java/ai/starwhale/mlops/domain/job/JobConvertor.java
server/controller/src/main/java/ai/starwhale/mlops/domain/job/JobEntity.java
server/controller/src/main/java/ai/starwhale/mlops/domain/job/JobService.java
server/controller/src/main/java/ai/starwhale/mlops/domain/job/bo/JobBoConverter.java
server/controller/src/main/java/ai/starwhale/mlops/domain/job/split/JobSpliteratorEvaluation.java
server/controller/src/main/java/ai/starwhale/mlops/domain/runtime/RuntimeService.java
server/controller/src/main/java/ai/starwhale/mlops/domain/task/TaskService.java
server/controller/src/main/java/ai/starwhale/mlops/domain/task/bo/TaskBoConverter.java
server/controller/src/main/resources/db/migration/V00010__modify_job.sql
server/controller/src/main/resources/mapper/JobMapper.xml
server/controller/src/main/resources/sql/schema.sql
server/controller/src/test/java/ai/starwhale/test/domain/task/TestJobStatusCalculator.java

- replace base image to runtime in job create api **request** @waynelwz @tianweidut 
- replace base image to runtime in task report api **response** @goldenxinxing  
- replace base image to runtime in job view api **response** @waynelwz @tianweidut 
**Request For List Job**
```
curl -X 'GET' \
'http://localhost:8082/api/v1/project/1/job?pageNum=1&pageSize=10' \
-H 'accept: application/json' \
-H 'Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxLHN0YXJ3aGFsZSIsImlzcyI6InN0YXJXaGFsZSIsImlhdCI6MTY1NDQ5NzkzMSwiZXhwIjoxNjU3MDg5OTMxfQ.UL1BVp3Z_l_xqGQKk-Q3mFZu1i8yHrf6eD-XC3gdOBOHlzbSgLViYzdvoFj1CWjNJzL5EN90OctOFRuhL8_now'
```
**Response For List Job**
```
{
"data": {
"total": 1,
"list": [
{
"id": "1",
"uuid": "1c17295711e34d5b8cc12c9b62d3efc7", …
```

runtime related change

---

server/controller/src/main/java/ai/starwhale/mlops/api/ProjectController.java
server/controller/src/main/java/ai/starwhale/mlops/api/protocol/runtime/RuntimeInfoVO.java
server/controller/src/main/java/ai/starwhale/mlops/api/protocol/swds/SWDatasetInfoVO.java
server/controller/src/main/java/ai/starwhale/mlops/api/protocol/swmp/SWModelPackageInfoVO.java
server/controller/src/main/java/ai/starwhale/mlops/api/protocol/user/RoleVO.java
server/controller/src/main/java/ai/starwhale/mlops/domain/runtime/RuntimeService.java
server/controller/src/main/java/ai/starwhale/mlops/domain/swds/SWDatasetService.java
server/controller/src/main/java/ai/starwhale/mlops/domain/swmp/SWModelPackageService.java
server/controller/src/main/java/ai/starwhale/mlops/domain/user/RoleConvertor.java

Uniform fields naming

---

client/starwhale/base/bundle_copy.py
client/starwhale/base/cloud.py

-  https://github.com/star-whale/starwhale/issues/449
- ![image](https://user-images.githubusercontent.com/590748/172007471-8ee02bbc-f84b-41a2-8dce-badb1a0a88d5.png)
- ![image](https://user-images.githubusercontent.com/590748/172037134-3d7f9ae3-5953-460e-ba7c-8cf82d0cbf50.png)
- ![image](https://user-images.githubusercontent.com/590748/172037175-c40f1577-c43b-4b6c-91d2-d9ec36655b0a.png)

feat: add progress bar for copy

---

server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/persistence/FileSystemTaskPersistence.java

fix runtime dir error

---

server/controller/src/main/java/ai/starwhale/mlops/api/DatasetApi.java
server/controller/src/main/java/ai/starwhale/mlops/api/DatasetController.java
server/controller/src/main/java/ai/starwhale/mlops/api/SWModelPackageApi.java
server/controller/src/main/java/ai/starwhale/mlops/api/SWModelPackageController.java
server/controller/src/main/java/ai/starwhale/mlops/domain/runtime/RuntimeService.java
server/controller/src/main/java/ai/starwhale/mlops/domain/swds/SWDatasetService.java
server/controller/src/main/java/ai/starwhale/mlops/domain/swds/mapper/SWDatasetMapper.java
server/controller/src/main/java/ai/starwhale/mlops/domain/swmp/SWModelPackageService.java
server/controller/src/main/java/ai/starwhale/mlops/domain/swmp/mapper/SWModelPackageMapper.java
server/controller/src/main/resources/mapper/SWDatasetMapper.xml
server/controller/src/main/resources/mapper/SWModelPackageMapper.xml

Recover model & dataset rest api

---

bootstrap/starwhale_bootstrap/cmd.py
bootstrap/starwhale_bootstrap/playbook/roles/agent/tasks/main.yaml
docker/charts/templates/_helpers.tpl
docker/charts/values.yaml
server/agent/src/main/java/ai/starwhale/mlops/agent/configuration/AgentProperties.java
server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/InferenceTask.java
server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/action/normal/Preparing2RunningAction.java
server/agent/src/main/resources/application.yaml

add default base image;record image for task container

---

client/starwhale/core/runtime/model.py
example/mnist/requirements.txt
example/mnist/runtime.yaml

- add `base_image` field into _manifest.yaml for runtime
- update runtime example

fix: update runtime base image field

---

server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/persistence/FileSystemTaskPersistence.java

yaml parse disable fail on unknown properties

---

server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/action/normal/Preparing2RunningAction.java
server/agent/src/test/java/ai/starwhale/mlops/agent/test/TaskActionTest.java

fix runtime volume bug

---

client/starwhale/base/bundle.py
client/starwhale/consts/__init__.py
client/starwhale/core/dataset/model.py
client/starwhale/core/model/model.py
example/mnist/.swignore
example/mnist/dataset.yaml
example/mnist/model.yaml

related: https://github.com/star-whale/starwhale/issues/191

feat: support .swignore for model/runtime ignore dirs

---

server/controller/src/main/java/ai/starwhale/mlops/resulting/ResultQuerier.java

fix result bug

---

client/starwhale/core/runtime/view.py

fix: runtime build type typo

---

client/starwhale/base/view.py
client/starwhale/core/job/model.py
client/starwhale/core/job/view.py

- related pr：  https://github.com/star-whale/starwhale/pull/484

chores: update job cli for new controller api

---

client/starwhale/base/cloud.py
client/starwhale/core/project/model.py

- force to specify the instance uri for http request function
- before
- ![image](https://user-images.githubusercontent.com/590748/172371065-6bd06ac9-ef70-4712-9440-93b0b7900a07.png)
- after
-  ![image](https://user-images.githubusercontent.com/590748/172370795-f533ceac-c741-4728-9422-9837df30af93.png)

fix: get cloud info typo

---

server/agent/src/main/java/ai/starwhale/mlops/agent/container/impl/DockerContainerClient.java

optimise pull image way

---

client/starwhale/core/job/view.py

chores: update info output

---

server/controller/src/main/java/ai/starwhale/mlops/domain/job/JobConvertor.java
server/controller/src/main/java/ai/starwhale/mlops/domain/job/JobService.java
server/controller/src/main/java/ai/starwhale/mlops/domain/task/status/TaskStatusChangeWatcher.java
server/controller/src/main/java/ai/starwhale/mlops/domain/task/status/WatchableTask.java
server/controller/src/main/java/ai/starwhale/mlops/domain/task/status/watchers/TaskWatcherForPersist.java

- fix task persistent bug
- fix job list bug

fix task persistent, job list bug

---

server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/action/normal/Preparing2RunningAction.java

volume pip cache dir for task container

---

client/starwhale/consts/__init__.py
client/starwhale/utils/config.py
client/tests/data/config.yaml

- add version for config.yaml
- auto upgrade version to new version format

enhance：add version for starwhale local config.yaml

---

server/controller/src/main/java/ai/starwhale/mlops/api/DatasetApi.java
server/controller/src/main/java/ai/starwhale/mlops/api/DatasetController.java
server/controller/src/main/java/ai/starwhale/mlops/api/protocol/runtime/ClientRuntimeRequest.java
server/controller/src/main/java/ai/starwhale/mlops/api/protocol/swds/upload/UploadRequest.java
server/controller/src/main/java/ai/starwhale/mlops/domain/runtime/RuntimeService.java
server/controller/src/main/java/ai/starwhale/mlops/domain/swds/SWDatasetService.java
server/controller/src/main/java/ai/starwhale/mlops/domain/swds/mapper/SWDatasetMapper.java
server/controller/src/main/resources/mapper/SWDatasetMapper.xml

Runtime push force & head dataset api

---

server/controller/src/main/java/ai/starwhale/mlops/api/protocol/dag/GraphVO.java
server/controller/src/main/java/ai/starwhale/mlops/common/TimeConcern.java
server/controller/src/main/java/ai/starwhale/mlops/domain/dag/DAGQuerier.java
server/controller/src/main/java/ai/starwhale/mlops/domain/dag/bo/GraphNode.java
server/controller/src/main/java/ai/starwhale/mlops/domain/job/Job.java
server/controller/src/main/java/ai/starwhale/mlops/domain/job/step/Step.java
server/controller/src/main/java/ai/starwhale/mlops/domain/job/step/StepConverter.java
server/controller/src/main/java/ai/starwhale/mlops/domain/job/step/mapper/StepMapper.java
server/controller/src/main/java/ai/starwhale/mlops/domain/job/step/status/StepStatusMachine.java
server/controller/src/main/java/ai/starwhale/mlops/domain/task/TaskEntity.java
server/controller/src/main/java/ai/starwhale/mlops/domain/task/bo/Task.java
server/controller/src/main/java/ai/starwhale/mlops/domain/task/bo/TaskBoConverter.java
server/controller/src/main/java/ai/starwhale/mlops/domain/task/mapper/TaskMapper.java
server/controller/src/main/java/ai/starwhale/mlops/domain/task/status/watchers/TaskWatcherForJobStatus.java
server/controller/src/main/java/ai/starwhale/mlops/domain/task/status/watchers/TaskWatcherForPersist.java
server/controller/src/main/resources/db/migration/V00011__add_time_to_task_step.sql
server/controller/src/main/resources/mapper/StepMapper.xml
server/controller/src/main/resources/mapper/TaskMapper.xml

- fill more information in DAG

fill more information in DAG

---

client/starwhale/utils/config.py
client/tests/utils/test_config.py

- issue: https://github.com/star-whale/starwhale/issues/519

fix: handle not found instance and project

---

client/starwhale/utils/venv.py
client/tests/core/test_runtime.py

fix: https://github.com/star-whale/starwhale/issues/523

enhance: use virtualvenv for venv_setup

---

client/starwhale/core/runtime/cli.py
client/starwhale/core/runtime/model.py
client/starwhale/core/runtime/view.py
client/starwhale/utils/venv.py

related: https://github.com/star-whale/starwhale/issues/511

feat: add runtime activate cmd

---

client/scripts/sw-docker-entrypoint
client/starwhale/utils/venv.py

hotfix:graceful to handle pip cache

---

server/controller/src/main/java/ai/starwhale/mlops/api/protocol/runtime/ClientRuntimeRequest.java
server/controller/src/main/java/ai/starwhale/mlops/api/protocol/runtime/RuntimeInfoVO.java
server/controller/src/main/java/ai/starwhale/mlops/api/protocol/runtime/RuntimeVersionVO.java
server/controller/src/main/java/ai/starwhale/mlops/api/protocol/swmp/ClientSWMPRequest.java
server/controller/src/main/java/ai/starwhale/mlops/api/protocol/swmp/SWModelPackageInfoVO.java
server/controller/src/main/java/ai/starwhale/mlops/api/protocol/swmp/SWModelPackageVersionVO.java
server/controller/src/main/java/ai/starwhale/mlops/domain/runtime/RuntimeService.java
server/controller/src/main/java/ai/starwhale/mlops/domain/runtime/RuntimeVersionConvertor.java
server/controller/src/main/java/ai/starwhale/mlops/domain/runtime/RuntimeVersionEntity.java
server/controller/src/main/java/ai/starwhale/mlops/domain/swds/SWDatasetService.java
server/controller/src/main/java/ai/starwhale/mlops/domain/swmp/SWMPVersionConvertor.java
server/controller/src/main/java/ai/starwhale/mlops/domain/swmp/SWModelPackageService.java
server/controller/src/main/java/ai/starwhale/mlops/domain/swmp/SWModelPackageVersionEntity.java
server/controller/src/main/resources/db/migration/V00012__add_manifest.sql
server/controller/src/main/resources/mapper/RuntimeVersionMapper.xml
server/controller/src/main/resources/mapper/SWModelPackageVersionMapper.xml

api: Runtime & Model manifest

---

docker/Dockerfile.base
docker/Makefile

WIP: chores: upgrade base image to 0.2.0 for pip upgrade

---

client/starwhale/core/job/executor.py

related: https://github.com/star-whale/starwhale/issues/531

fix: remove logger catch for executor run

---

server/controller/src/main/java/ai/starwhale/mlops/api/protocol/swmp/SWModelPackageVersionVO.java
server/controller/src/main/java/ai/starwhale/mlops/domain/storage/StorageService.java
server/controller/src/main/java/ai/starwhale/mlops/domain/swmp/SWModelPackageService.java

add model size field into model version api

---

server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/action/normal/Preparing2RunningAction.java

fix pip cache dir bug

---

client/starwhale/core/job/model.py

related:  https://github.com/star-whale/starwhale/pull/536

chores: update cli job create parameter name

---

server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/action/normal/AbsBaseTaskAction.java
server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/action/normal/MonitoringAction.java
server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/action/normal/Preparing2RunningAction.java
server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/persistence/FileSystemPath.java
server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/persistence/FileSystemTaskPersistence.java
server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/persistence/TaskPersistence.java

add log for agent at stage of preparing and running

---

client/setup.py
client/starwhale/core/runtime/model.py
client/starwhale/utils/venv.py

related: #522 
- ![image](https://user-images.githubusercontent.com/590748/172983109-b6a71ab5-6d4b-4258-9b59-b357ac74c825.png)

enhance: add runtime validator

---

server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/action/normal/Preparing2RunningAction.java

example support 2.0

---

server/controller/src/main/java/ai/starwhale/mlops/api/DatasetApi.java
server/controller/src/main/java/ai/starwhale/mlops/api/DatasetController.java
server/controller/src/main/java/ai/starwhale/mlops/api/RuntimeApi.java
server/controller/src/main/java/ai/starwhale/mlops/api/RuntimeController.java
server/controller/src/main/java/ai/starwhale/mlops/api/SWModelPackageApi.java
server/controller/src/main/java/ai/starwhale/mlops/api/SWModelPackageController.java
server/controller/src/main/java/ai/starwhale/mlops/common/TagAction.java
server/controller/src/main/java/ai/starwhale/mlops/common/util/TagUtil.java
server/controller/src/main/java/ai/starwhale/mlops/domain/runtime/RuntimeService.java
server/controller/src/main/java/ai/starwhale/mlops/domain/swds/SWDatasetService.java
server/controller/src/main/java/ai/starwhale/mlops/domain/swmp/SWModelPackageService.java
server/controller/src/main/java/ai/starwhale/mlops/domain/swmp/SWModelPackageVersionEntity.java
server/controller/src/main/resources/mapper/SWModelPackageVersionMapper.xml

add/remove/search tag for model/dataset/runtime

---

server/controller/src/main/java/ai/starwhale/mlops/domain/job/JobService.java
server/controller/src/main/java/ai/starwhale/mlops/domain/job/cache/HotJobsLoader.java
server/controller/src/main/java/ai/starwhale/mlops/domain/job/cache/JobLoader.java
server/controller/src/main/java/ai/starwhale/mlops/domain/job/status/JobStatusMachine.java
server/controller/src/main/java/ai/starwhale/mlops/reporting/ReportProcessorImp.java

allow failed job be resumed

---

server/controller/src/main/java/ai/starwhale/mlops/api/DatasetApi.java
server/controller/src/main/java/ai/starwhale/mlops/api/DatasetController.java
server/controller/src/main/java/ai/starwhale/mlops/api/JobApi.java
server/controller/src/main/java/ai/starwhale/mlops/api/JobController.java
server/controller/src/main/java/ai/starwhale/mlops/api/ProjectApi.java
server/controller/src/main/java/ai/starwhale/mlops/api/ProjectController.java
server/controller/src/main/java/ai/starwhale/mlops/api/RuntimeApi.java
server/controller/src/main/java/ai/starwhale/mlops/api/RuntimeController.java
server/controller/src/main/java/ai/starwhale/mlops/api/SWModelPackageApi.java
server/controller/src/main/java/ai/starwhale/mlops/api/SWModelPackageController.java
server/controller/src/main/java/ai/starwhale/mlops/api/UserApi.java
server/controller/src/main/java/ai/starwhale/mlops/api/UserController.java
server/controller/src/main/java/ai/starwhale/mlops/api/protocol/job/JobModifyRequest.java
server/controller/src/main/java/ai/starwhale/mlops/api/protocol/job/JobRequest.java
server/controller/src/main/java/ai/starwhale/mlops/api/protocol/runtime/RuntimeTagRequest.java
server/controller/src/main/java/ai/starwhale/mlops/api/protocol/swds/SWDSTagRequest.java
server/controller/src/main/java/ai/starwhale/mlops/api/protocol/swmp/SWMPTagRequest.java
server/controller/src/main/java/ai/starwhale/mlops/api/protocol/user/UserUpdatePasswordRequest.java
server/controller/src/main/java/ai/starwhale/mlops/api/protocol/user/UserUpdateStateRequest.java
server/controller/src/main/java/ai/starwhale/mlops/domain/job/JobService.java
server/controller/src/main/java/ai/starwhale/mlops/domain/project/ProjectManager.java

The parameters of PUT Method Request use body mode

---

client/starwhale/consts/__init__.py
client/starwhale/core/runtime/cli.py
client/starwhale/core/runtime/model.py
client/starwhale/core/runtime/view.py
client/starwhale/utils/__init__.py
client/starwhale/utils/venv.py
client/tests/core/test_runtime.py
docker/Makefile

- remove `base_image` in runtime.yaml
- import `starwhale_version`, which also inject `base_image` for runtime
- refactor dockerfile for starwhale image tag
- auto install starwhale in runtime creation
- ![image](https://user-images.githubusercontent.com/590748/173363419-a266cb46-e7ef-4721-afb0-79394ed84b3c.png)
- ![image](https://user-images.githubusercontent.com/590748/173363511-1549ed8c-c4c9-4b5a-92b0-628a49f98c33.png)
- check `starwhale` pkg resources in build runtime phase
- ![image](https://user-images.githubusercontent.com/590748/173376766-ccd6052c-0ca3-4497-85fc-749723ce13bb.png) 
- #560 
- #525

enhance: runtime refactor for create

---

client/starwhale/core/job/cli.py
client/tests/base/test_uri.py

https://github.com/star-whale/starwhale/issues/537

enhance: allow project empty for swcli job create

---

client/starwhale/utils/venv.py
docker/Dockerfile.starwhale

- render `activate.host` script
- update activate show content
- issue: https://github.com/star-whale/starwhale/issues/576

bug: update conda activate text for host environment

---

client/starwhale/core/runtime/model.py
client/starwhale/utils/venv.py
client/tests/core/test_runtime.py

issue: https://github.com/star-whale/starwhale/issues/541

enhance: auto pip install user pip-req file in conda restore process

---

client/starwhale/base/store.py
client/starwhale/core/model/model.py
client/starwhale/core/model/store.py
client/starwhale/core/runtime/model.py
client/starwhale/core/runtime/store.py
client/starwhale/mngt/__init__.py
client/tests/core/test_mngt.py
client/tests/core/test_runtime.py

- remove model/dataset bundle and workdir
- related: https://github.com/star-whale/starwhale/issues/540

enhance: tune runtime/model remove workdir

---

client/starwhale/utils/venv.py

only use major-minor version to rebuild virtualenv.
- [] add unit test

hotfix: fix python verion for virtualenv

---

server/controller/src/main/java/ai/starwhale/mlops/api/DatasetApi.java
server/controller/src/main/java/ai/starwhale/mlops/api/DatasetController.java
server/controller/src/main/java/ai/starwhale/mlops/api/RuntimeController.java
server/controller/src/main/java/ai/starwhale/mlops/api/SWModelPackageController.java
server/controller/src/main/java/ai/starwhale/mlops/domain/runtime/RuntimeManager.java
server/controller/src/main/java/ai/starwhale/mlops/domain/runtime/RuntimeService.java
server/controller/src/main/java/ai/starwhale/mlops/domain/runtime/mapper/RuntimeMapper.java
server/controller/src/main/java/ai/starwhale/mlops/domain/swds/SWDatasetService.java
server/controller/src/main/java/ai/starwhale/mlops/domain/swds/SwdsManager.java
server/controller/src/main/java/ai/starwhale/mlops/domain/swds/mapper/SWDatasetMapper.java
server/controller/src/main/java/ai/starwhale/mlops/domain/swds/upload/SwdsUploader.java
server/controller/src/main/java/ai/starwhale/mlops/domain/swmp/SWModelPackageService.java
server/controller/src/main/java/ai/starwhale/mlops/domain/swmp/SwmpManager.java
server/controller/src/main/java/ai/starwhale/mlops/domain/swmp/mapper/SWModelPackageMapper.java
server/controller/src/main/resources/mapper/RuntimeMapper.xml
server/controller/src/main/resources/mapper/SWDatasetMapper.xml
server/controller/src/main/resources/mapper/SWModelPackageMapper.xml

Allow models/runtimes/datasets with the same name for different projects

---

client/starwhale/core/job/executor.py
client/starwhale/utils/debug.py

fix: standalone job data_loader load first line record twice

---

server/controller/src/main/java/ai/starwhale/mlops/api/ProjectApi.java
server/controller/src/main/java/ai/starwhale/mlops/api/ProjectController.java
server/controller/src/main/java/ai/starwhale/mlops/domain/job/JobManager.java
server/controller/src/main/java/ai/starwhale/mlops/domain/job/JobService.java
server/controller/src/main/java/ai/starwhale/mlops/domain/project/ProjectManager.java
server/controller/src/main/java/ai/starwhale/mlops/domain/project/ProjectService.java

fix: modify project api support project url

---

.github/workflows/docs.yaml

chores: add cname for gh-pages action

---

server/controller/src/main/java/ai/starwhale/mlops/domain/dag/DAGQuerier.java
server/controller/src/main/java/ai/starwhale/mlops/domain/system/agent/AgentConverter.java
server/controller/src/test/java/ai/starwhale/test/ObjectMockHolder.java
server/controller/src/test/java/ai/starwhale/test/common/LocalDateTimeConvertorTest.java
server/controller/src/test/java/ai/starwhale/test/domain/system/AgentCacheTest.java

- add unit test for localDateTImeConvertor

add unit test for localDateTImeConvertor

---

client/starwhale/core/job/cli.py
client/starwhale/core/job/model.py
client/starwhale/core/job/view.py

- related: https://github.com/star-whale/starwhale/issues/596

feat(client): job compare in standalone mode

---

README.md
client/starwhale/core/job/executor.py
docs/docs/quickstart/standalone.md
docs/docs/standalone/installation.md

- add darwin env check
- update doc for mac
- related:  https://github.com/star-whale/starwhale/issues/582

chores(environment): test and update doc for mac

---

client/starwhale/api/_impl/loader.py

hotfix(client): remove pdb typo

---

server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/action/end/ArchivedAction.java
server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/action/normal/Uploading2FinishedAction.java
server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/action/report/ReportAction.java

fix agent log upload error

---

console/src/components/Table/TableTyped.tsx
console/src/components/data-table/column.tsx
console/src/components/data-table/data-custom-table.tsx
console/src/components/data-table/stateful-data-table.tsx
console/src/components/data-table/types.tsx

fix(console): data-table full columns missing  in cases

---

client/starwhale/api/_impl/loader.py
client/starwhale/base/bundle_copy.py
client/starwhale/base/uri.py
client/starwhale/core/instance/model.py
client/starwhale/core/instance/view.py
client/starwhale/core/project/model.py
client/tests/base/test_copy.py
client/tests/base/test_uri.py
client/tests/core/test_instance.py
client/tests/utils/test_common.py
client/tests/utils/test_process.py

ci(client): add client ut

---

server/controller/pom.xml
server/controller/src/main/java/ai/starwhale/mlops/api/EvaluationApi.java
server/controller/src/main/java/ai/starwhale/mlops/api/EvaluationController.java
server/controller/src/main/java/ai/starwhale/mlops/api/protocol/evaluation/ConfigRequest.java
server/controller/src/main/java/ai/starwhale/mlops/domain/evaluation/EvaluationService.java
server/controller/src/main/java/ai/starwhale/mlops/resulting/ResultQuerier.java
server/controller/src/test/java/ai/starwhale/test/resulting/ResultQuerierTest.java
server/pom.xml

Simple implementation of Evaluation Summary list

---

console/src/components/DnD/DnDContainer.tsx
console/src/components/Table/TableTyped.tsx
console/src/components/data-table/column-string.tsx
console/src/components/data-table/config-manage-columns.tsx
console/src/components/data-table/data-custom-table.tsx
console/src/components/data-table/measure-column-widths.tsx
console/src/components/data-table/stateful-data-table.tsx
console/src/components/data-table/types.tsx
console/src/consts/index.ts
console/src/hooks/global.ts
console/src/hooks/useDrawer.ts
console/src/hooks/useSelection.ts
console/src/i18n/locales.ts
console/src/pages/Evaluation/EvaluationListCard.tsx
console/src/pages/Evaluation/EvaluationListCompare.tsx
console/src/pages/Runtime/RuntimeVersionListCard.tsx

1. table fill width canceled
2. table can expanded when drawer opened
3. fixed column manage error state
4. fixed default table with a scrollbar showing
5. fixed error calc resizedWidths

enhance(console) eva compare table

---

docs/docs/quickstart/on-premises.md

doc: fix on premises doc hyper link error

---

client/requirements-dev.txt
client/setup.py
client/starwhale/api/_impl/loader.py
client/starwhale/api/_impl/model.py
client/tests/sdk/test_model.py
example/PennFudanPed/code/ppl.py
example/cifar10/code/ppl.py
example/mnist/mnist/ppl.py
example/nmt/code/ppl.py
example/speech_command/code/ppl.py
example/text_cls_AG_NEWS/code/ppl.py

support serialize and deserialize in PipelineHandler

feat(sdk): support serialize and deserialize in PipelineHandler

---

console/src/hooks/useSelection.ts

fix(console): pined column state error

---

server/controller/src/main/java/ai/starwhale/mlops/api/DatasetApi.java
server/controller/src/main/java/ai/starwhale/mlops/api/RuntimeApi.java
server/controller/src/main/java/ai/starwhale/mlops/domain/swds/SWDSVersionConvertor.java
server/controller/src/main/java/ai/starwhale/mlops/domain/swds/SWDatasetService.java
server/controller/src/main/resources/mapper/RuntimeVersionMapper.xml
server/controller/src/main/resources/mapper/SWDatasetVersionMapper.xml

* dataset/runtime api param names
* get DatasetInfo bug
* DatasetVersion convert NPE

bug(controller):fix bugs in dataset api

---

bootstrap/starwhale_bootstrap/cmd.py
bootstrap/starwhale_bootstrap/default.py
bootstrap/starwhale_bootstrap/playbook/roles/controller/tasks/main.yaml
docker/charts/templates/controller-deployment.yaml
server/controller/src/main/resources/application.yaml

Find the host where the controller is located，copy the compiled front-end code to path：/mnt/data/starwhale/controller/run/static/. 
then restart the service.

mount ui from external dir

---

.github/workflows/release.yml

chores(helm): add private registry for pre deploy

---

client/tests/utils/test_load.py

fix(ut): test_load will fail when user python version is not 3.7

---

bootstrap/starwhale_bootstrap/default.py
bootstrap/starwhale_bootstrap/playbook/roles/controller/tasks/main.yaml
docker/charts/templates/controller-deployment.yaml

only mount ui dir

---

server/controller/src/main/java/ai/starwhale/mlops/api/protocol/evaluation/SummaryVO.java
server/controller/src/main/java/ai/starwhale/mlops/domain/evaluation/EvaluationService.java
server/controller/src/main/java/ai/starwhale/mlops/domain/job/mapper/JobMapper.java
server/controller/src/main/java/ai/starwhale/mlops/resulting/ResultQuerier.java
server/controller/src/main/resources/config/evaluation_attributes
server/controller/src/main/resources/mapper/JobMapper.xml
server/controller/src/test/java/ai/starwhale/test/resulting/ResultQuerierTest.java

* Evaluation list format judgement

---

client/starwhale/utils/__init__.py
client/tests/utils/test_common.py

- support `.`, such as: `v1.0`
- support `a-zA-Z` or `_` as the first char for object name

chores(client): update object name validation

---

client/scripts/sw-docker-entrypoint
docker/compose/README.md
docker/compose/compose.override.yaml
docker/compose/compose.yaml

- add docker compose for cloud instance
- issue: https://github.com/star-whale/starwhale/issues/644
- ![image](https://user-images.githubusercontent.com/590748/175812920-fab968e3-7019-44d3-9508-f521399c6194.png)
- ![image](https://user-images.githubusercontent.com/590748/175813678-96fb20b8-0f3a-4c73-a70d-4736687f454c.png)
-

deploy(cloud): cloud instance docker compose

---

server/agent/src/main/java/ai/starwhale/mlops/agent/configuration/AgentProperties.java
server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/action/normal/Preparing2RunningAction.java
server/agent/src/main/resources/application.yaml

feat:add new env for docker

---

client/scripts/sw-docker-entrypoint

chores(docker): update disable debug env name

---

docker/Dockerfile.server
docker/charts/templates/_helpers.tpl
docker/charts/templates/controller-deployment.yaml

fix(deploy): tune jvm heap size

---

client/scripts/sw-docker-entrypoint

bug(docker): fix pip cache config error in sw-docker-entrypoint

---

server/controller/src/main/java/ai/starwhale/mlops/domain/evaluation/EvaluationService.java
server/controller/src/main/java/ai/starwhale/mlops/resulting/ResultQuerier.java
server/controller/src/test/java/ai/starwhale/test/resulting/ResultQuerierTest.java

Evaluation list: only return the summary in attributes

---

client/starwhale/base/uri.py
client/starwhale/core/project/view.py
client/tests/core/test_project.py
client/tests/data/config.yaml
client/tests/utils/test_config.py

- issue: https://github.com/star-whale/starwhale/issues/632

bug(client): fix project select error

---

bootstrap/setup.py
bootstrap/starwhale_bootstrap/cmd.py
bootstrap/starwhale_bootstrap/default.py
bootstrap/starwhale_bootstrap/playbook/roles/agent/tasks/main.yaml
docker/charts/templates/_helpers.tpl
docker/charts/values.yaml
server/agent/src/main/java/ai/starwhale/mlops/agent/container/impl/DockerContainerClient.java
server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/InferenceTask.java
server/agent/src/main/resources/application.yaml

fix(agent): extension pull image time; add preparing status for report

---

bootstrap/README.md
bootstrap/setup.py
bootstrap/starwhale_bootstrap/cmd.py
bootstrap/starwhale_bootstrap/default.py
bootstrap/starwhale_bootstrap/deploy.py
bootstrap/starwhale_bootstrap/playbook/roles/agent/tasks/main.yaml
bootstrap/starwhale_bootstrap/playbook/roles/controller/tasks/main.yaml
bootstrap/starwhale_bootstrap/playbook/roles/minio/tasks/main.yaml
bootstrap/starwhale_bootstrap/playbook/roles/mysql/tasks/main.yaml
bootstrap/starwhale_bootstrap/playbook/roles/nexus/tasks/main.yaml
server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/action/normal/Preparing2RunningAction.java
server/agent/src/main/resources/application.yaml

fix(bootstrap): change ansible storage image

---

docker/charts/templates/_helpers.tpl

bug(helm): fixchart env value parse error

---

client/starwhale/base/view.py
client/starwhale/cli/__init__.py
client/starwhale/core/dataset/cli.py
client/starwhale/core/dataset/view.py

feat(client): dataset cmd of swcli support output to json

---

docker/charts/values.yaml

- yaml convert big number to Scientific notation;
- jvm heap size unit inconsistent

fix(deploy): change chart number to string

---

docker/compose/compose.override.yaml
docker/compose/compose.yaml

chores(deploy): update compose image version and pypi mirrors

---

client/starwhale/base/view.py
client/starwhale/core/instance/cli.py
client/starwhale/core/instance/view.py
client/starwhale/utils/__init__.py

feat(client): instance cmd of swcli support output to json

---

server/controller/src/main/java/ai/starwhale/mlops/domain/evaluation/EvaluationService.java
server/controller/src/main/java/ai/starwhale/mlops/resulting/ResultQuerier.java
server/controller/src/test/java/ai/starwhale/test/resulting/ResultQuerierTest.java

bug(controller): evaluation list cache

---

client/starwhale/core/runtime/cli.py
client/starwhale/core/runtime/view.py

feat(client): runtime cmd of swcli support output to json

---

client/starwhale/core/job/cli.py
client/starwhale/core/job/view.py
client/tests/core/test_job.py

feat(client): job cmd of swcli support output to json

---

README.md
docs/docusaurus.config.js
docs/sidebars.js

doc: remove some dead links

---

docs/docs/standalone/dataset.md
docs/docs/standalone/model.md
docs/docs/standalone/runtime.md
docs/sidebars.js

- add standalone model/runtime yaml docs

doc(standalone): add standalone model/runtime guide docs

---

.github/file-filter.yml
.github/workflows/client.yaml
scripts/run_demo.sh

feat(standalone): end to end test for client

---

client/starwhale/core/job/model.py
client/starwhale/utils/config.py

fix(client): do not set default project for cloud instance

---

console/package.json
console/src/__generated__/MySuperbApi.ts
console/src/components/Header/Logo.tsx
console/src/components/Table/TableTyped.tsx
console/src/components/data-table/column-numerical.tsx
console/src/components/data-table/config-manage-columns.tsx
console/src/components/data-table/data-custom-table.tsx
console/src/components/data-table/header-cell.tsx
console/src/components/data-table/stateful-data-table.tsx
console/src/domain/evaluation/hooks/useFetchEvaluationAttrs.ts
console/src/domain/evaluation/hooks/useFetchEvaluations.ts
console/src/domain/evaluation/schemas/evaluation.tsx
console/src/domain/evaluation/services/evaluation.ts
console/src/i18n/locales.ts
console/src/pages/Evaluation/EvaluationListCard.tsx
console/src/pages/Evaluation/EvaluationListCompare.tsx
console/src/pages/Evaluation/EvaluationOverviewLayout.tsx
console/src/pages/Job/JobTasks.tsx
console/src/pages/Project/ProjectSidebar.tsx
console/src/routes.tsx
console/src/styles/_global.scss
console/swagger.js
console/swagger.json
console/yarn.lock

1. remove pagination from evaluation list
2. compatible with no json line log

feat(console): support evaluation summary metrics 

---

.github/wip.yaml

ci(github): add wip config

---

docs/docusaurus.config.js
docs/src/pages/index.js

bug(doc): fix docs title and remove useless notes

---

README.md
docs/docs/quickstart/standalone.md
docs/docs/tutorials/ag_news.md
docs/docs/tutorials/cifar10.md
docs/docs/tutorials/mnist.md
docs/docs/tutorials/pfp.md
docs/docs/tutorials/speech.md

Refine docs

---

client/starwhale/core/job/executor.py
client/starwhale/utils/__init__.py
client/tests/core/test_model.py

fix(client): unit test darwin runnable

---

server/controller/src/main/java/ai/starwhale/mlops/domain/bundle/BundleManager.java
server/controller/src/main/java/ai/starwhale/mlops/domain/bundle/recover/RecoverManager.java
server/controller/src/main/java/ai/starwhale/mlops/domain/bundle/remove/RemoveAccessor.java
server/controller/src/main/java/ai/starwhale/mlops/domain/bundle/remove/RemoveException.java
server/controller/src/main/java/ai/starwhale/mlops/domain/bundle/remove/RemoveManager.java
server/controller/src/main/java/ai/starwhale/mlops/domain/bundle/revert/RevertAccessor.java
server/controller/src/main/java/ai/starwhale/mlops/domain/bundle/revert/RevertManager.java
server/controller/src/main/java/ai/starwhale/mlops/domain/bundle/tag/TagAccessor.java
server/controller/src/main/java/ai/starwhale/mlops/domain/bundle/tag/TagManager.java
server/controller/src/main/java/ai/starwhale/mlops/domain/runtime/RuntimeManager.java
server/controller/src/main/java/ai/starwhale/mlops/domain/runtime/RuntimeService.java
server/controller/src/main/java/ai/starwhale/mlops/domain/swds/SWDatasetService.java
server/controller/src/main/java/ai/starwhale/mlops/domain/swds/SwdsManager.java
server/controller/src/main/java/ai/starwhale/mlops/domain/swmp/SWModelPackageService.java
server/controller/src/main/java/ai/starwhale/mlops/domain/swmp/SwmpManager.java

Refactor: Remove Bundle & Normalize Managers and Accessors

---

client/setup.py

add more details for client setup.py

chores(client): tune client setup.py for classifiers and other fields

---

.github/workflows/client.yaml

https://github.com/star-whale/starwhale/runs/7161191515?check_suite_focus=true

bug(ci): enable lfs for client e2e test

---

.gitattributes

chores(git): force to use lf

---

client/starwhale/consts/__init__.py
client/starwhale/utils/config.py
client/tests/utils/test_config.py
scripts/run_demo.sh

ci(standalone): local e2e use separate conf and data dir

---

README.md
docker/charts/Chart.yaml

chores(doc): update logo links by git lfs

---

README.md
docker/charts/Chart.yaml

chores(doc): use offical default link for png

---

.github/workflows/docs.yaml

fix(doc): fix missing images

---

scripts/apitest/pytest/common/httputil.py
scripts/apitest/pytest/conftest.py
scripts/apitest/pytest/requirements.txt
scripts/apitest/pytest/test_project.py
scripts/apitest/pytest/test_user.py

pytest: e2e api test

---

README.md
example/mnist/notebook.ipynb

doc: add notebook for mnist

---

README.md

fix(doc): fix lint issue and colab url

---

client/starwhale/base/bundle.py
client/starwhale/base/store.py
client/starwhale/consts/__init__.py
client/starwhale/core/dataset/model.py
client/starwhale/core/dataset/store.py
client/starwhale/core/model/model.py
client/starwhale/core/runtime/model.py
client/starwhale/mngt/__init__.py
client/tests/core/test_dataset.py

feat(sdk): build datasets and models using tmp dir

---

client/starwhale/base/view.py
client/starwhale/core/job/view.py
client/starwhale/utils/__init__.py

feat(client): ordered cli list output

---

client/starwhale/base/tag.py
client/starwhale/utils/fs.py

fix(client): forgot to close the file

---

client/setup.py
client/starwhale/cli/__init__.py
client/starwhale/cli/board.py
client/starwhale/core/instance/model.py

https://user-images.githubusercontent.com/3217223/178214958-0fc5b14b-6893-4d06-980b-e4a8b47393f2.mp4

feat(client): support terminal based UI (list instances and projects)

---

client/starwhale/cli/board/board.py
client/starwhale/cli/board/widgets.py
client/starwhale/utils/__init__.py

"MDRJ" keys for model, dataset, runtime, job
https://user-images.githubusercontent.com/3217223/178715845-1f888da8-8195-46a7-8ad3-3a88b55d1fc8.mp4

feat(client): board support listing model, dataset, runtime and job

---

client/starwhale/cli/board/board.py
client/starwhale/cli/board/project_tree.py
client/starwhale/cli/board/widgets.py

https://user-images.githubusercontent.com/3217223/178882919-6ce0e034-8361-43e5-aa58-40a76c186a9c.mp4

feat(client): pretty project tree with current project selected

---

client/starwhale/cli/board/widgets.py
client/starwhale/utils/__init__.py

https://user-images.githubusercontent.com/3217223/179206888-e5acbdb1-b688-4f4b-a491-0d82dcd8a143.mp4

feat(client): sw board table sortable

---

.github/release-drafter.yml
.github/workflows/release-drafter.yml

- add [Release-Drafter](https://github.com/marketplace/actions/release-drafter) for release notes. 
- related: https://github.com/star-whale/starwhale/issues/755

ci: init release-drafter

---

client/starwhale/api/_impl/dataset.py
client/starwhale/api/_impl/loader.py
client/starwhale/api/_impl/model.py
client/starwhale/base/bundle.py
client/starwhale/base/cloud.py
client/starwhale/base/store.py
client/starwhale/base/tag.py
client/starwhale/base/uri.py
client/starwhale/core/dataset/dataset.py
client/starwhale/core/dataset/model.py
client/starwhale/core/job/executor.py
client/starwhale/core/job/model.py
client/starwhale/core/model/model.py
client/starwhale/core/project/model.py
client/starwhale/core/runtime/model.py
client/starwhale/utils/config.py
client/starwhale/utils/log.py
client/starwhale/utils/obj.py
example/PennFudanPed/code/ds.py

fix: making abstract base classes actually work

---

.github/workflows/e2e-test.yml

- change e2e test trigger event

ci: change e2e test trigger event from pr to schedule

---

client/requirements-dev.txt

- error: https://github.com/star-whale/starwhale/runs/7441839971?check_suite_focus=true
- bug from:   https://github.com/star-whale/starwhale/pull/718   cc @anda-ren

fix(deps): fix requirements-dev.txt import reqs file typo

---

client/starwhale/core/runtime/model.py
client/starwhale/utils/venv.py

feat(runtime): support conda install to use configs.channels field in the runtime.yaml

---

.editorconfig
console/.editorconfig

- ref: https://editorconfig.org/

ci: config global editorconfig file

---

server/controller/pom.xml
server/controller/src/main/java/ai/starwhale/mlops/api/LogController.java
server/controller/src/main/java/ai/starwhale/mlops/deploy/Kubernetes.java
server/controller/src/main/java/ai/starwhale/mlops/domain/task/TaskService.java
server/controller/src/main/java/ai/starwhale/mlops/reporting/ReportProcessorImp.java
server/controller/src/main/resources/template/job.yaml
server/pom.xml

refactor(k8s): merge k8s code

---

client/starwhale/core/runtime/model.py
client/starwhale/utils/venv.py
client/tests/core/test_runtime.py
client/tests/utils/test_venv.py
example/runtime/pytorch/runtime.yaml

- pip config:
- `index_url`: str
- `extra_index_url`: str or list[str]
- `trusted_host`: str or list[str]
- ![image](https://user-images.githubusercontent.com/590748/180410266-c63d0252-7ffc-4e97-b474-75fad1dcf287.png)
- ![image](https://user-images.githubusercontent.com/590748/180212978-7e97a3c8-840d-4409-930e-b6f378d53524.png)
- #745   https://github.com/star-whale/starwhale/issues/741

feat(runtime): support pip install to use configs.pip field in the runtime.yaml

---

console/src/components/Header/index.tsx
console/src/domain/user/components/PasswordForm.tsx
console/src/domain/user/schemas/user.tsx
console/src/domain/user/services/user.ts
console/src/i18n/locales.ts

feat(console): support changing password

---

console/src/components/Header/index.tsx
console/src/components/data-table/stateful-data-table.tsx
console/src/domain/user/hooks/useUser.ts
console/src/domain/user/schemas/user.tsx
console/src/domain/user/services/user.ts
console/src/i18n/locales.ts
console/src/pages/Admin/AdminLayout.tsx
console/src/pages/Admin/AdminSidebar.tsx
console/src/pages/Admin/UserManagement.tsx
console/src/routes.tsx

* add `Admin Setting` layout and page
* List users
* Change user state
https://user-images.githubusercontent.com/3217223/180939687-be1f243c-f229-40c6-af60-c8a99aebd68b.mp4

feat(console): manage users support listing users and change user state

---

server/controller/src/main/java/ai/starwhale/mlops/reporting/ReportedTask.java
server/controller/src/main/java/ai/starwhale/mlops/reporting/SimpleTaskStatusReceiver.java
server/controller/src/main/java/ai/starwhale/mlops/schedule/k8s/JobEventHandler.java
server/controller/src/main/java/ai/starwhale/mlops/schedule/k8s/K8sClient.java
server/controller/src/test/java/ai/starwhale/test/reporting/TaskStatusReceiverImpTest.java

watch k8s job status

---

console/src/components/BaseSidebar.tsx
console/src/domain/project/components/MemberAddForm.tsx
console/src/domain/project/components/RoleSelector.tsx
console/src/domain/project/components/UserSelector.tsx
console/src/domain/project/hooks/useFetchProjectMembers.ts
console/src/domain/project/hooks/useFetchRoleList.ts
console/src/domain/project/schemas/project.tsx
console/src/domain/project/services/project.ts
console/src/domain/user/schemas/user.tsx
console/src/i18n/locales.ts
console/src/pages/Project/ProjectListCard.tsx
console/src/pages/Project/ProjectMembers.tsx
console/src/routes.tsx

* project member management page
* member list
* add/remove/edit member
https://user-images.githubusercontent.com/3217223/181170943-894ab99d-fe61-4061-997b-3ec63336b7b3.mp4

feat(console): support project member management

---

server/controller/src/main/java/ai/starwhale/mlops/api/LogController.java
server/controller/src/main/java/ai/starwhale/mlops/domain/task/TaskService.java
server/controller/src/main/java/ai/starwhale/mlops/domain/task/log/TaskLogCollector.java
server/controller/src/main/java/ai/starwhale/mlops/domain/task/log/TaskLogK8SCollector.java
server/controller/src/main/java/ai/starwhale/mlops/domain/task/status/WatchableTaskFactory.java
server/controller/src/main/java/ai/starwhale/mlops/domain/task/status/watchers/TaskWatcherForK8SJobClear.java
server/controller/src/main/java/ai/starwhale/mlops/domain/task/status/watchers/TaskWatcherForLogging.java
server/controller/src/main/java/ai/starwhale/mlops/exception/SWProcessException.java
server/controller/src/main/java/ai/starwhale/mlops/schedule/k8s/JobEventHandler.java
server/controller/src/main/java/ai/starwhale/mlops/schedule/k8s/K8sClient.java

- collect offline log from k8s pod
- delete k8s job after it is finished

refactor(controller-k8s): collect log from k8s pod & clear finished k8s job

---

client/starwhale/consts/__init__.py
client/starwhale/core/runtime/model.py
client/tests/core/test_runtime.py
example/runtime/pytorch/runtime.yaml

- add `environment.arch` field in runtime.yaml
- add arch validator
- related: https://github.com/star-whale/starwhale/issues/749

feat(runtime): add arch validator

---

client/starwhale/core/runtime/model.py
client/starwhale/utils/venv.py
client/tests/core/test_runtime.py
example/runtime/pytorch/requirements-sw-lock.txt

- https://github.com/star-whale/starwhale/issues/821
- https://github.com/star-whale/starwhale/issues/751

feat(runtime): auto inject starwhale pkg when restore runtime

---

console/src/domain/user/components/NewUserForm.tsx
console/src/domain/user/schemas/user.tsx
console/src/domain/user/services/user.ts
console/src/i18n/locales.ts
console/src/pages/Admin/UserManagement.tsx
console/src/utils/passwordGenerator.ts

https://user-images.githubusercontent.com/3217223/181407397-2da34479-4594-47e2-b548-8029160fb48c.mp4

feat(console): support adding user in user management page

---

client/starwhale/core/runtime/model.py
client/starwhale/utils/venv.py
client/tests/core/test_runtime.py

- add shell environment validators for runtime lock
- remove runtime build useless validators
- related: 
- https://github.com/star-whale/starwhale/issues/751
- https://github.com/star-whale/starwhale/issues/741

feat(runtime): add shell environment validators for runtime lock

---

console/src/components/Form/validators.ts
console/src/domain/user/components/NewUserForm.tsx
console/src/domain/user/components/PasswordForm.tsx
console/src/domain/user/services/user.ts
console/src/i18n/locales.ts
console/src/pages/Admin/UserManagement.tsx

https://user-images.githubusercontent.com/3217223/181453905-af3b52d8-abc6-42d6-a9ce-c5fac8dd927a.mp4

feat(console): support changing user's password in admin settings page

---

console/src/components/Form/validators.ts
console/src/consts/index.ts
console/src/domain/user/components/NewUserForm.tsx
console/src/domain/user/components/PasswordForm.tsx
console/src/i18n/locales.ts

fix(console): set user's password min length to 8

---

console/src/api/ApiHeader.tsx
console/src/components/Header/index.tsx
console/src/domain/project/schemas/project.tsx
console/src/domain/user/services/user.ts
console/src/hooks/global.ts
console/src/hooks/useCurrentUserRoles.ts

https://user-images.githubusercontent.com/3217223/181698368-858f18b9-7aac-47d4-9fa2-862171628dd6.mp4

fix(console): hide admin menu when user is not admin

---

server/controller/src/main/java/ai/starwhale/mlops/schedule/k8s/K8SSelectorSpec.java
server/controller/src/main/java/ai/starwhale/mlops/schedule/k8s/K8sClient.java
server/controller/src/main/java/ai/starwhale/mlops/schedule/k8s/K8sTaskScheduler.java

- adapt device request to k8s node selector
- close log api mannually or connection will be leak

refactor(controller-k8s): adapt device request to k8s node selector

---

client/starwhale/core/runtime/cli.py
client/starwhale/core/runtime/model.py
client/starwhale/core/runtime/view.py
client/starwhale/utils/__init__.py
client/starwhale/utils/venv.py
scripts/run_demo.sh

- related: https://github.com/star-whale/starwhale/issues/751

feat(runtime): add runtime quickstart from Starwhale Runtime URI

---

server/controller/src/main/java/ai/starwhale/mlops/schedule/k8s/JobEventHandler.java
server/controller/src/main/java/ai/starwhale/mlops/schedule/k8s/K8sClient.java

- fix task update error when controller restart

fix: fix task update error when controller restart

---

console/src/domain/project/components/MemberAddForm.tsx
console/src/domain/project/components/UserSelector.tsx
console/src/pages/Project/ProjectMembers.tsx

fix(console): A user can only have one role in a project

---

server/controller/src/main/java/ai/starwhale/mlops/api/UserController.java
server/controller/src/main/java/ai/starwhale/mlops/api/protocol/user/UserUpdateStateRequest.java

feat(console): password is not required in setting user state api

---

client/starwhale/core/runtime/cli.py
client/starwhale/core/runtime/model.py
client/starwhale/core/runtime/view.py
client/starwhale/utils/error.py

https://github.com/star-whale/starwhale/issues/752

feat(runtime): support runtime activate with runtime uri argument

---

client/setup.py
client/starwhale/cli/mngt.py
client/starwhale/mngt/__init__.py

related: https://github.com/star-whale/starwhale/issues/761

feat: add external dependency software check command

---

console/src/App.tsx
console/src/components/Modal/confirm.tsx
console/src/i18n/locales.ts
console/src/pages/Admin/UserManagement.tsx
console/src/pages/Project/ProjectMembers.tsx

Fixes #811
https://user-images.githubusercontent.com/3217223/182512563-646d17e8-3fbf-4274-a70a-a4cc4f7a27bf.mp4

feat(console): show confirm when disable/enable users and remove user from project members

---

server/controller/src/main/java/ai/starwhale/mlops/api/UserApi.java
server/controller/src/main/java/ai/starwhale/mlops/api/UserController.java

- add 'Get arbitrary user token' api for cloud support

feat: add 'Get arbitrary user token' api for cloud support

---

docker/Makefile

related: https://github.com/star-whale/starwhale/pull/838

chores: remove taskset image build cmd

---

docker/Makefile

```sh
v0.2.0-rc.0
v0.2.0-rc.1
v0.2.1
...
Successfully tagged starwhaleai/server:0.2.1-nightly-20220804-4a124817
Successfully tagged starwhaleai/server:latest
Successfully tagged ghcr.io/star-whale/server:0.2.1-nightly-20220804-4a124817
Successfully tagged ghcr.io/star-whale/server:latest
```

fix(build): use the latest tag as latest release version

---

client/setup.py
client/starwhale/api/_impl/data_store.py
client/starwhale/api/_impl/wrapper.py
client/tests/sdk/test_base.py
client/tests/sdk/test_data_store.py
client/tests/sdk/test_wrapper.py

add the first edition of starwhale sdk

---

console/src/api/ApiHeader.tsx
server/controller/src/main/java/ai/starwhale/mlops/configuration/security/JwtLoginFailureHandler.java
server/controller/src/main/java/ai/starwhale/mlops/configuration/security/JwtTokenFilter.java

Fixes #823 
https://user-images.githubusercontent.com/3217223/182809254-3afb1672-7e9a-415d-8228-8b4c0e6d623e.mp4

fix(console): accessing resource with no access will redirect to the login page

---

client/starwhale/consts/__init__.py
client/starwhale/utils/config.py
client/tests/core/test_project.py
client/tests/utils/test_config.py

enhance(client): change default storage path

---

client/starwhale/core/runtime/model.py
client/tests/core/test_runtime.py
example/runtime/pytorch/runtime.yaml

- related: https://github.com/star-whale/starwhale/issues/747
- dependency pr: https://github.com/star-whale/starwhale/pull/862

feat(runtime): support cuda/cudnn field in runtime.yaml

---

client/scripts/sw-docker-entrypoint

- pre pr for https://github.com/star-whale/starwhale/pull/871

refactor: update sw-docker-entrypoint for command switch

---

.github/workflows/release.yml
docker/Makefile

- https://github.com/star-whale/starwhale/issues/873
- backgroud: serial execution spends [38min](https://github.com/star-whale/starwhale/actions/runs/2803545836).

enhance(ci): parallel build starwhale image

---

client/starwhale/core/runtime/model.py

enhance(runtime): add runtime.yaml python field validator

---

README.md

doc: add e2e status and client support python version badge status

---

client/setup.py
client/starwhale/__init__.py
example/runtime/pytorch/dummy/setup.py

issues in python 3.10
```shell
❯ swcli runtime --help                                                                                                                                                                                           Traceback (most recent call last):                                                                                                                                                                                 File "/home/liutianwei/anaconda3/envs/starwhale310/bin/swcli", line 33, in <module>                                                                                                                                sys.exit(load_entry_point('starwhale', 'console_scripts', 'swcli')()) …
```

bug(client):  fix importlib import and install for python3.8+

---

docker/Dockerfile.starwhale

related change:  https://github.com/star-whale/starwhale/pull/814

chore: use the fixed python(3.8) for starwhale package in starwhale image

---

.github/workflows/client.yaml
.github/workflows/e2e-test.yml
client/Makefile
client/setup.py
client/starwhale/__init__.py
client/starwhale/cli/__init__.py
example/runtime/pytorch/dummy/setup.py

ci(client): make client code test and lint happen on python3.7/3.8/3.9/3.10 versions

---

client/setup.py
client/starwhale/core/runtime/cli.py
client/starwhale/core/runtime/model.py
client/starwhale/core/runtime/template/Dockerfile.tmpl
client/starwhale/core/runtime/view.py
client/starwhale/utils/docker.py
client/starwhale/utils/process.py
example/runtime/pytorch/runtime.yaml

- Generate dockerfile and docker image from Starwhale Runtime URI
- Support arm64/amd64 multi-arch
- related: https://github.com/star-whale/starwhale/issues/750
- depend on pr: https://github.com/star-whale/starwhale/pull/876 
- dry-run command
- Dockerfile example
```Dockerfile
ARG BASE_IMAGE=ghcr.io/star-whale/starwhale:latest
FROM ${BASE_IMAGE}
ARG TARGETARCH
ENTRYPOINT []
WORKDIR /opt/starwhale.user/runtime
LABEL starwhale_runtime_dockerize=1
LABEL starwhale_runtime_name=pytorch
LABEL starwhale_runtime_version=mzrtmmbrmzrdizjyg44tkzjwgyzxu2q
ENV SW_USER_RUNTIME_WORKDIR=/opt/starwhale.user/runtime
COPY . /opt/starwhale.user/runtime
ENV SW_PYPI_INDEX_URL "https://pypi.doubanio.com/simple/"
ENV SW_PYPI_EXTRA_INDEX_URL "https://mirrors.bfsu.edu.cn/pypi/web/simple/"
ENV …
```

feat(runtime): add `runtime dockerize` command

---

console/src/App.tsx
console/src/styles/_global.scss

fix(console): iconfont transform by scss error

---

docker/Dockerfile.starwhale

bug(docker): fix Dockerfile.starwhale env typo

---

client/starwhale/utils/log.py

bug(client): fix log streamwrapper typo

---

.github/release-drafter.yml

chore(release): update releaase drafer config for sort and prelease

---

.github/workflows/console.yml
.github/workflows/release.yml

chore(ci): enable lfs for console build

---

server/controller/src/main/java/ai/starwhale/mlops/schedule/k8s/K8sTaskScheduler.java
server/controller/src/main/resources/template/job.yaml

- make init container compatible with both minio and aliyun oss

enhance(controller): make init container compatible with both minio and aliyun oss

---

console/src/domain/user/components/PasswordForm.tsx
console/src/domain/user/services/user.ts

fix(console): new password input disabled when user changes password

---

client/starwhale/core/instance/cli.py
client/starwhale/core/instance/view.py
client/tests/core/test_instance.py
client/tests/core/test_model.py

feat(client): add --token argument for swcli instance login command

---

console/src/components/Form/form.ts
console/src/domain/project/components/ProjectForm.tsx
console/src/domain/project/schemas/project.tsx
console/src/i18n/locales.ts

https://user-images.githubusercontent.com/3217223/184069811-9138c55d-6d5c-4257-aefd-fb2050e117b0.mp4

feat(console): new version project creating modal

---

server/controller/src/main/java/ai/starwhale/mlops/api/UserApi.java
server/controller/src/main/java/ai/starwhale/mlops/api/UserController.java
server/controller/src/main/java/ai/starwhale/mlops/domain/user/UserService.java

- modify parameter of token getter from userName to userId

refactor(controller): modify parameter of token getter from userName to userId

---

server/controller/src/main/java/ai/starwhale/mlops/common/TarFileUtil.java
server/controller/src/main/java/ai/starwhale/mlops/domain/job/JobService.java
server/controller/src/main/java/ai/starwhale/mlops/domain/job/bo/Job.java
server/controller/src/main/java/ai/starwhale/mlops/domain/job/converter/JobBoConverter.java
server/controller/src/main/java/ai/starwhale/mlops/domain/job/parser/JobParser.java
server/controller/src/main/java/ai/starwhale/mlops/domain/job/parser/StepMetaData.java
server/controller/src/main/java/ai/starwhale/mlops/domain/job/split/JobSpliterator.java
server/controller/src/main/java/ai/starwhale/mlops/domain/job/split/JobSpliteratorEvaluation.java
server/controller/src/main/java/ai/starwhale/mlops/domain/job/step/po/StepEntity.java
server/controller/src/main/java/ai/starwhale/mlops/domain/swmp/SWModelPackageService.java
server/controller/src/main/java/ai/starwhale/mlops/domain/swmp/po/SWModelPackageVersionEntity.java
server/controller/src/main/java/ai/starwhale/mlops/domain/task/bo/Task.java
server/controller/src/main/java/ai/starwhale/mlops/domain/task/converter/TaskBoConverter.java
server/controller/src/main/java/ai/starwhale/mlops/domain/task/po/TaskEntity.java
server/controller/src/main/java/ai/starwhale/mlops/schedule/k8s/K8sTaskScheduler.java
server/controller/src/main/resources/mapper/JobMapper.xml
server/controller/src/main/resources/mapper/SWModelPackageVersionMapper.xml
server/controller/src/main/resources/mapper/StepMapper.xml
server/controller/src/main/resources/mapper/TaskMapper.xml
server/controller/src/test/java/ai/starwhale/mlops/domain/job/JobSpliteratorEvaluationTest.java

feat: add new job impl for controller

---

console/src/components/IconFont/index.tsx
console/src/consts/index.ts
console/src/domain/user/components/CreateAccountForm.tsx
console/src/domain/user/components/ResetPasswordForm.tsx
console/src/domain/user/components/ThirdPartyLoginButton.tsx
console/src/domain/user/schemas/user.tsx
console/src/domain/user/services/user.ts
console/src/i18n/locales.ts
console/src/pages/Home/CreateAccount.tsx
console/src/pages/Home/LoginNew.tsx
console/src/pages/Home/ResetPassword.tsx
console/src/routes.tsx
console/src/setupProxy.js

cc @anda-ren @dreamlandliu
https://user-images.githubusercontent.com/3217223/184625947-256166cb-0602-4f6a-bd0f-a78df49d30e1.mp4

feat(console): support sign up with third-party account

---

server/controller/src/main/java/ai/starwhale/mlops/domain/job/split/JobSpliteratorEvaluation.java
server/controller/src/main/java/ai/starwhale/mlops/domain/task/bo/Task.java
server/controller/src/main/java/ai/starwhale/mlops/domain/task/converter/TaskBoConverter.java
server/controller/src/main/java/ai/starwhale/mlops/domain/task/po/TaskEntity.java
server/controller/src/main/resources/db/migration/V00008__Add_job_dag_field.sql
server/controller/src/main/resources/mapper/SWModelPackageVersionMapper.xml
server/controller/src/main/resources/mapper/TaskMapper.xml

1. fixed some typo
2. add alter script for mysql

fix：add alter script for job

---

client/.flake8
client/starwhale/api/_impl/data_store.py
client/starwhale/api/_impl/wrapper.py
client/tests/sdk/test_data_store.py
client/tests/sdk/test_wrapper.py

feat(datastore): support RemoteDataStore and make LocalDataStore work with multi processing

---

console/src/consts/index.ts
console/src/pages/Home/LoginNew.tsx

https://user-images.githubusercontent.com/3217223/184815891-e91f4c34-c12f-4c54-ac7c-d03218145a71.mp4

feat(console): log in with third-party account

---

client/starwhale/api/_impl/loader.py

- add `SW_OBJECT_STORE_KEY_PREFIX` env

enhance(datastore): support `SW_OBJECT_STORE_KEY_PREFIX` env to unify dataset process

---

client/starwhale/api/_impl/dataset.py
client/starwhale/base/cloud.py
client/starwhale/base/type.py
client/starwhale/core/dataset/cli.py
client/starwhale/core/dataset/dataset.py
client/starwhale/core/dataset/model.py
client/starwhale/core/dataset/view.py
client/starwhale/core/model/model.py
client/starwhale/core/runtime/model.py
client/tests/core/test_dataset.py
client/tests/sdk/test_dataset.py

- related: https://github.com/star-whale/starwhale/issues/756
- support to get dataset summary
- ![image](https://user-images.githubusercontent.com/590748/184868135-56ca7dff-f7b8-4e34-a24b-a0f089773fee.png)
- fix metaclass issue, imported by the pr: https://github.com/star-whale/starwhale/pull/768

feat(dataset): support `swcli dataset summary` command

---

client/starwhale/api/_impl/dataset.py
client/starwhale/api/_impl/loader.py
client/starwhale/api/dataset.py
client/starwhale/base/type.py
client/starwhale/consts/__init__.py
client/starwhale/core/dataset/dataset.py
client/starwhale/core/dataset/model.py
client/starwhale/core/dataset/view.py
client/starwhale/utils/fs.py
client/tests/sdk/test_dataset.py
client/tests/sdk/test_model.py
example/mnist/dataset.yaml
example/mnist/mnist/process.py

- related: https://github.com/star-whale/starwhale/issues/897
- provide `RawBuildExecutor` for raw data format dataset build
- provide `UserRawDataLoader` for raw data format dataset load
- dataset build with user raw data
- dataset loader for mnist example

feat(dataset): support user-raw data format type for dataset

---

client/starwhale/base/bundle_copy.py

related pr:  https://github.com/star-whale/starwhale/pull/922

enhance(dataset): add X-SW-UPLOAD-DATA-URI header for dataset copy

---

console/package.json
console/pnpm-lock.yaml
console/src/components/data-table/store.ts
console/src/pages/Evaluation/EvaluationListCard.tsx

fix(console):  keep state unique without local persist

---

client/starwhale/consts/__init__.py
client/starwhale/core/dataset/cli.py
client/starwhale/core/dataset/model.py
client/starwhale/core/dataset/view.py
client/tests/core/test_dataset.py
docs/docs/reference/cli/dataset.md

chore(dataset): remove useless dataset render-fuse-json command

---

client/starwhale/base/bundle_copy.py
client/starwhale/core/dataset/cli.py
client/starwhale/core/dataset/model.py
client/starwhale/core/dataset/view.py

- related: https://github.com/star-whale/starwhale/issues/952
- dependency pr: https://github.com/star-whale/starwhale/pull/944

feat(dataset): support dataset copy with .auth_env file

---

client/starwhale/api/_impl/dataset.py
client/starwhale/api/_impl/loader.py
client/starwhale/consts/__init__.py
client/tests/core/test_executor.py
client/tests/sdk/test_loader.py
client/tests/sdk/test_model.py
example/cifar10/code/ppl.py
example/text_cls_AG_NEWS/code/ppl.py

refactor(client): change misleading fuse to `LocalFS`

---

server/controller/src/main/java/ai/starwhale/mlops/api/JobController.java
server/controller/src/main/java/ai/starwhale/mlops/api/protocol/job/JobRequest.java
server/controller/src/main/java/ai/starwhale/mlops/api/protocol/job/JobVO.java
server/controller/src/main/java/ai/starwhale/mlops/domain/job/JobService.java
server/controller/src/main/java/ai/starwhale/mlops/domain/job/bo/Job.java
server/controller/src/main/java/ai/starwhale/mlops/domain/job/converter/JobBoConverter.java
server/controller/src/main/java/ai/starwhale/mlops/domain/job/converter/JobConvertor.java
server/controller/src/main/java/ai/starwhale/mlops/domain/job/po/JobEntity.java
server/controller/src/main/java/ai/starwhale/mlops/domain/system/mapper/ResourcePoolMapper.java
server/controller/src/main/java/ai/starwhale/mlops/domain/system/po/ResourcePoolEntity.java
server/controller/src/main/java/ai/starwhale/mlops/domain/system/resourcepool/ResourcePoolCache.java
server/controller/src/main/java/ai/starwhale/mlops/domain/system/resourcepool/ResourcePoolConverter.java
server/controller/src/main/java/ai/starwhale/mlops/domain/system/resourcepool/ResourcePoolManager.java
server/controller/src/main/java/ai/starwhale/mlops/domain/system/resourcepool/bo/ResourcePool.java
server/controller/src/main/java/ai/starwhale/mlops/exception/SWValidationException.java
server/controller/src/main/java/ai/starwhale/mlops/schedule/k8s/K8sResourcePoolConverter.java
server/controller/src/main/java/ai/starwhale/mlops/schedule/k8s/K8sTaskScheduler.java
server/controller/src/main/java/ai/starwhale/mlops/schedule/k8s/NodeEventHandler.java
server/controller/src/main/resources/db/migration/V00011__Add_resource_pool.sql
server/controller/src/main/resources/mapper/JobMapper.xml
server/controller/src/main/resources/mapper/ResourcePoolMapper.xml
server/controller/src/test/java/ai/starwhale/mlops/domain/job/JobBoConverterTest.java
server/controller/src/test/java/ai/starwhale/mlops/domain/system/ResourcePoolConverterTest.java

* use K8s node selector as resource pool implementation
* `pool.starwhale.ai` as the prefix of pool label

feat(controller): support resource pool

---

server/controller/src/main/java/ai/starwhale/mlops/domain/job/split/JobSpliteratorEvaluation.java
server/controller/src/test/java/ai/starwhale/mlops/domain/swds/SwdsUploaderTest.java

fix(controller): fix sql error

---

server/controller/src/main/java/ai/starwhale/mlops/api/SystemApi.java
server/controller/src/main/java/ai/starwhale/mlops/api/SystemController.java
server/controller/src/main/java/ai/starwhale/mlops/api/protocol/system/ResourcePoolVO.java
server/controller/src/main/java/ai/starwhale/mlops/domain/system/SystemService.java
server/controller/src/main/java/ai/starwhale/mlops/domain/system/resourcepool/ResourcePoolConverter.java

Add API:  GET `system/resourcePool`
relates to #961
cc @waynelwz

feat(controller): get resource pools api

---

console/src/domain/job/components/JobForm.tsx
console/src/domain/job/components/ResourcePoolSelector.tsx
console/src/domain/job/hooks/useFetchResourcePools.ts
console/src/domain/job/schemas/job.tsx
console/src/domain/job/schemas/resourcePool.ts
console/src/domain/job/services/job.ts
console/src/i18n/locales.ts

relates to #961 #978 
https://user-images.githubusercontent.com/3217223/186391197-a41c14cb-3a07-4842-9d02-8381dfb9602d.mp4

feat(console): support selecting resource pool when create job

---

scripts/apitest/pytest/test_role.py
server/controller/src/main/java/ai/starwhale/mlops/configuration/security/JwtTokenFilter.java

test(controller): add pytest for management of role

---

README.md
client/starwhale/core/dataset/model.py
client/starwhale/core/dataset/type.py
client/tests/data/dataset.yaml
client/tests/data/dataset/dataset.yaml
docs/docs/tutorials/ag_news.md
docs/docs/tutorials/cifar10.md
docs/docs/tutorials/mnist.md
docs/docs/tutorials/nmt.md
docs/docs/tutorials/pfp.md
docs/docs/tutorials/speech.md
example/PennFudanPed/dataset.yaml
example/cifar10/dataset.yaml
example/mnist/dataset.yaml
example/nmt/dataset.yaml
example/speech_command/dataset.yaml
example/text_cls_AG_NEWS/dataset.yaml

chore(dataset): remove useless mode field in dataset.yaml

---

.github/workflows/release.yml

fix(ci): js heap out of memory

---

server/controller/src/main/java/ai/starwhale/mlops/api/DatasetApi.java
server/controller/src/main/java/ai/starwhale/mlops/api/DatasetController.java
server/controller/src/main/java/ai/starwhale/mlops/api/RuntimeApi.java
server/controller/src/main/java/ai/starwhale/mlops/api/RuntimeController.java
server/controller/src/main/java/ai/starwhale/mlops/api/SWModelPackageApi.java
server/controller/src/main/java/ai/starwhale/mlops/api/SWModelPackageController.java
server/controller/src/main/java/ai/starwhale/mlops/exception/api/StarWhaleApiException.java

chore(controller): catch exception when heading model/dataset/runtime

---

server/controller/pom.xml

fix(controller): flyway not support mysql8.0

---

scripts/apitest/pytest/common/httputil.py
scripts/apitest/pytest/test_role.py
scripts/apitest/pytest/test_role_permission.py

test(controller): pytest for role permission apis

---

server/controller/src/main/java/ai/starwhale/mlops/domain/swmp/SWModelPackageService.java

The original InputStream has the wrong position after getting the `eval_jobs.yaml` file.
And The InputStream from MultipartFile.getInputStream did not implement the mark func.
This PR is just a walk round for the next integration tests, it will use double memory.
cc @tianweidut

fix(controller): prevent losing data after finding the eval_jobs.yaml file

---

client/starwhale/core/dataset/type.py

fix(dataset): add default s3 region for s3 link auth

---

client/starwhale/api/_impl/dataset/builder.py
client/starwhale/base/bundle.py
client/starwhale/consts/__init__.py
client/starwhale/core/dataset/cli.py
client/starwhale/core/dataset/model.py
client/starwhale/core/dataset/tabular.py
client/starwhale/core/dataset/view.py
client/starwhale/core/runtime/model.py
client/starwhale/utils/fs.py

- related: https://github.com/star-whale/starwhale/issues/777
- command: `swcli dataset build --append --append-from ${version}`
-  `swcli dataset build . --append --append-from mnstcntggm3d`
-  `swcli dataset build . --append`
-  `swcli dataset build . --append --append-from latest`
- v1 dataset
- v2 dataset

feat(dataset): support dataset data append only mode

---

server/controller/src/main/java/ai/starwhale/mlops/api/DatasetApi.java
server/controller/src/main/java/ai/starwhale/mlops/api/DatasetController.java
server/controller/src/main/java/ai/starwhale/mlops/domain/swds/SWDatasetService.java
server/controller/src/main/java/ai/starwhale/mlops/domain/swds/index/IndexItem.java
server/controller/src/main/java/ai/starwhale/mlops/domain/swds/objectstore/DSFileGetter.java
server/controller/src/main/java/ai/starwhale/mlops/domain/swds/objectstore/StorageAccessParser.java
server/controller/src/main/java/ai/starwhale/mlops/domain/swds/objectstore/StorageAuths.java
server/controller/src/main/java/ai/starwhale/mlops/domain/swds/upload/SwdsUploader.java
server/controller/src/main/java/ai/starwhale/mlops/domain/task/status/watchers/TaskWatcherForSchedule.java
server/controller/src/test/java/ai/starwhale/mlops/domain/swds/objectstore/TestStorageAuths.java
server/storage-access-layer/src/main/java/ai/starwhale/mlops/storage/StorageAccessService.java
server/storage-access-layer/src/main/java/ai/starwhale/mlops/storage/s3/StorageAccessServiceS3.java

- support empty auth name
- convert auth name to uppercase forcefully
- suppport offset download

fix(controller): fix dataset link auth error

---

client/starwhale/api/_impl/data_store.py
client/starwhale/base/uri.py
client/starwhale/consts/env.py
client/starwhale/utils/config.py

feat(client): add SW_TOKEN env for instance_uri sw_token

---

client/scripts/sw-docker-entrypoint

fix(docker): entrypoint default value format

---

server/controller/src/main/java/ai/starwhale/mlops/schedule/k8s/K8sClient.java

`env` will overwrite `coreEnv` and make `SW_TASK_STEP` ... lost

fix(controller): resolve env overwritten

---

client/starwhale/api/_impl/data_store.py

bug(datastore): fix datastore resp format typo

---

example/PennFudanPed/requirements.txt
example/cifar10/requirements.txt
example/mnist/requirements-sw-lock.txt
example/mnist/requirements.txt
example/runtime/pytorch/runtime.yaml
example/speech_command/requirements.txt
example/text_cls_AG_NEWS/requirements.txt

example: update example for numpy dependencies

---

scripts/apitest/pytest/test_role_permission.py
scripts/apitest/pytest/test_user.py

test(controller): pytest for user api

---

client/tests/sdk/test_data_store.py

related: https://github.com/star-whale/starwhale/pull/1020

ci(datastore): fix datastore test for scantable

---

server/controller/src/main/resources/template/job.yaml

chore(controller): remove useless cmd from job template

---

client/starwhale/api/_impl/dataset/builder.py
client/starwhale/api/_impl/dataset/loader.py
client/starwhale/api/_impl/model.py
client/starwhale/core/dataset/tabular.py
client/starwhale/core/dataset/type.py
client/tests/sdk/test_loader.py
example/mnist/mnist/ppl.py
example/mnist/mnist/process.py
example/mnist/requirements-sw-lock.txt
scripts/run_demo.sh

enhance(sdk): set label str type and update mnist example

---

docker/charts/templates/controller-deployment.yaml

chore(deploy): inject instance url for controller

---

client/scripts/sw-docker-entrypoint

fix(docker): change entrypoint of starwhale from swmp to swmp/src

---

server/controller/src/main/java/ai/starwhale/mlops/api/DatasetApi.java
server/controller/src/main/java/ai/starwhale/mlops/api/DatasetController.java
server/controller/src/main/java/ai/starwhale/mlops/domain/swds/SWDatasetService.java
server/controller/src/main/java/ai/starwhale/mlops/domain/swds/objectstore/DSFileGetter.java
server/controller/src/main/java/ai/starwhale/mlops/domain/swds/objectstore/StorageUri.java

- change offset/size parameter type to string
- adapt to relative uri

fix(controller): fix dataset uri download error

---

client/starwhale/api/_impl/dataset/builder.py
client/starwhale/api/_impl/dataset/mnist.py
client/starwhale/core/dataset/model.py
client/starwhale/core/dataset/type.py
client/tests/sdk/test_dataset.py
example/mnist/dataset.yaml
example/mnist/mnist/process.py

- add `mime_type` for every row
cc @waynelwz

feat(dataset): support dataset mime_type config

---

client/starwhale/api/_impl/dataset/builder.py
client/starwhale/api/_impl/dataset/loader.py
client/starwhale/core/dataset/tabular.py
client/tests/sdk/test_dataset.py
client/tests/sdk/test_loader.py

- dependency pr: https://github.com/star-whale/starwhale/pull/1033

enhance(dataset): tune dataset meta schema fields with swds_bin_offset and swds_bin_size

---

client/starwhale/api/_impl/model.py

WIP bug(dataset): fix ppl loader data encode typo

---

client/starwhale/api/_impl/dataset/loader.py
client/starwhale/core/dataset/store.py
client/tests/sdk/test_loader.py

enhance(dataset): tune s3 file read return type as bytes type

---

server/controller/src/main/java/ai/starwhale/mlops/domain/job/step/trigger/EvalStepTrigger.java

fix(controller): tune step trigger condition

---

client/starwhale/base/mixin.py
client/starwhale/core/dataset/model.py
client/starwhale/core/dataset/tabular.py
client/starwhale/core/dataset/type.py
client/starwhale/core/dataset/view.py
client/starwhale/core/model/model.py
client/starwhale/core/runtime/model.py
client/tests/base/test_mixin.py
client/tests/core/test_dataset.py
client/tests/core/test_runtime.py
client/tests/sdk/test_dataset.py

refactor(client): replace object asdict method with ASDictMixin class

---

server/controller/src/main/java/ai/starwhale/mlops/domain/system/resourcepool/ResourcePoolManager.java
server/controller/src/main/java/ai/starwhale/mlops/domain/system/resourcepool/bo/ResourcePool.java
server/controller/src/main/java/ai/starwhale/mlops/schedule/k8s/K8sTaskScheduler.java
server/controller/src/main/resources/mapper/JobSWDSVersionMapper.xml

- make resource poll not mandatory
- fix storage auth error
- fix eval id to uuid

fix(controller): fix integration test error

---

client/starwhale/api/_impl/model.py
client/starwhale/core/eval/view.py

fix(client):move auc to new table

---

server/controller/src/main/java/ai/starwhale/mlops/domain/bundle/BundleManager.java
server/controller/src/main/java/ai/starwhale/mlops/domain/bundle/BundleVersionAccessor.java
server/controller/src/main/java/ai/starwhale/mlops/domain/project/ProjectManager.java
server/controller/src/main/java/ai/starwhale/mlops/domain/runtime/RuntimeManager.java
server/controller/src/main/java/ai/starwhale/mlops/domain/swds/SwdsManager.java
server/controller/src/main/java/ai/starwhale/mlops/domain/swmp/SwmpManager.java

fix(controller): verify object id when converting object url

---

server/controller/src/main/java/ai/starwhale/mlops/datastore/WalManager.java
server/controller/src/test/java/ai/starwhale/mlops/datastore/WalManagerTest.java

fix(datastore): add retrying to WAL reading

---

server/controller/src/main/java/ai/starwhale/mlops/api/DataStoreController.java
server/controller/src/main/java/ai/starwhale/mlops/api/protocol/datastore/QueryTableRequest.java
server/controller/src/main/java/ai/starwhale/mlops/datastore/DataStore.java
server/controller/src/main/java/ai/starwhale/mlops/datastore/DataStoreQueryRequest.java
server/controller/src/main/java/ai/starwhale/mlops/datastore/MemoryTable.java
server/controller/src/main/java/ai/starwhale/mlops/datastore/impl/MemoryTableImpl.java
server/controller/src/test/java/ai/starwhale/mlops/api/DataStoreControllerTest.java
server/controller/src/test/java/ai/starwhale/mlops/datastore/impl/MemoryTableImplTest.java

enhance(datastore): support keepNone in query

---

docker/Dockerfile.nodejs
docker/Makefile
server/Makefile

* Add `git` for console building @waynelwz 
* Add yarn cache volume for node modules cache @waynelwz 
* Use uid:gid to prevent the owner of the user's directory from becoming root
* Add test cmd for the server's Makefile, it can reproduce the junit Tempdir problem sometimes @goldenxinxing

chore(docker): optimize docker build ppl

---

server/controller/src/main/java/ai/starwhale/mlops/domain/job/split/JobSpliteratorEvaluation.java

- fix : all tasks have the same log

fix(controller): fix log overwrite error

---

server/controller/src/main/java/ai/starwhale/mlops/objectstore/impl/S3ObjectStore.java

fix(controller): fix wal init error

---

client/starwhale/core/dataset/cli.py
client/starwhale/core/dataset/model.py
client/starwhale/core/dataset/tabular.py
client/starwhale/core/dataset/view.py
client/starwhale/utils/__init__.py
client/tests/utils/test_common.py

- related: https://github.com/star-whale/starwhale/issues/964

feat(dataset): add `swcli dataset diff` command

---

client/starwhale/core/dataset/cli.py
client/starwhale/core/dataset/view.py

- related: https://github.com/star-whale/starwhale/issues/925

feat(dataset): support dataset build to use the specific runtime environment with `--runtime` argument

---

client/scripts/sw-docker-entrypoint

fix(docker) :entry point typo

---

client/scripts/sw-docker-entrypoint

enhance(docker): tune sw-docker-entrypoint for debug

---

client/starwhale/api/_impl/data_store.py
client/tests/sdk/test_data_store.py

enhance(datastore): add more log for remote data store table update

---

client/scripts/sw-docker-entrypoint
client/starwhale/api/_impl/model.py

fix data column name pattern error

fix(sdk): task execute at cloud store failed

---

.github/workflows/release-base.yml
client/scripts/sw-docker-entrypoint
docker/Dockerfile.base
docker/Makefile
docker/external/render_sources_list.sh

fix(docker): fix wrong python version string parsed by awk

---

.github/workflows/release-base.yml

fix(ci): fix auth token issue in pull request

---

server/controller/src/main/java/ai/starwhale/mlops/api/protocol/user/UserVO.java
server/controller/src/main/java/ai/starwhale/mlops/domain/user/UserConvertor.java
server/controller/src/main/java/ai/starwhale/mlops/domain/user/po/UserEntity.java
server/controller/src/main/resources/mapper/UserMapper.xml

feat(controller): user info contains email(if exists)

---

scripts/apitest/pytest/common/httputil.py

fix(test): use microsecond as name to create tmp user

---

client/starwhale/api/_impl/data_store.py
client/starwhale/api/_impl/model.py
server/controller/src/main/java/ai/starwhale/mlops/datastore/TableSchema.java
server/controller/src/test/java/ai/starwhale/mlops/datastore/TableSchemaTest.java
server/controller/src/test/java/ai/starwhale/mlops/datastore/impl/MemoryTableImplTest.java

fix(datastore):uniform column name pattern

---

server/controller/src/main/java/ai/starwhale/mlops/api/DataStoreController.java
server/controller/src/main/java/ai/starwhale/mlops/api/protocol/datastore/QueryTableRequest.java
server/controller/src/main/java/ai/starwhale/mlops/api/protocol/datastore/ScanTableRequest.java
server/controller/src/main/java/ai/starwhale/mlops/datastore/ColumnType.java
server/controller/src/main/java/ai/starwhale/mlops/datastore/DataStore.java
server/controller/src/main/java/ai/starwhale/mlops/datastore/DataStoreQueryRequest.java
server/controller/src/main/java/ai/starwhale/mlops/datastore/DataStoreScanRequest.java
server/controller/src/main/java/ai/starwhale/mlops/datastore/MemoryTable.java
server/controller/src/main/java/ai/starwhale/mlops/datastore/impl/MemoryTableImpl.java
server/controller/src/main/java/ai/starwhale/mlops/domain/swds/datastore/IndexWriter.java
server/controller/src/test/java/ai/starwhale/mlops/api/DataStoreControllerTest.java
server/controller/src/test/java/ai/starwhale/mlops/datastore/ColumnTypeTest.java
server/controller/src/test/java/ai/starwhale/mlops/datastore/impl/MemoryTableImplTest.java

enhance(datastore): support raw result output for query and scan

---

server/controller/src/main/java/ai/starwhale/mlops/api/ProjectApi.java

fix(controller): project maintainer/guest can get the role list

---

example/mnist/notebook.ipynb

fix(example): use new version swcli in mnist demo

---

client/starwhale/core/eval/executor.py

fix(client): support docker run mode at standalone

---

client/starwhale/core/job/scheduler.py

fix(sdk): single execute status bug

---

server/controller/src/main/java/ai/starwhale/mlops/api/UserController.java
server/controller/src/main/java/ai/starwhale/mlops/api/protocol/user/UserRequest.java
server/controller/src/main/java/ai/starwhale/mlops/domain/user/UserService.java

feat(controller): create user with password and salt

---

client/starwhale/api/_impl/data_store.py

fix(client): dataset copy error when current instance is not local

---

.github/workflows/client.yaml
client/starwhale/api/_impl/data_store.py
client/tests/sdk/test_base.py

fix(datastore):revert datastore exit logic

---

console/src/pages/Project/Overview.tsx

fix(console): edit project use PUT method in overview page

---

README.md

doc: update cov badge for readme

---

console/src/components/BaseSidebar.tsx
console/src/components/Header/index.tsx

chore(console): fix descendant dom warning

---

console/src/domain/runtime/schemas/runtime.tsx
console/src/domain/runtime/services/runtime.ts
console/src/i18n/locales.ts
console/src/pages/Dataset/DatasetVersionOverviewFiles.tsx
console/src/pages/Runtime/Overview.tsx
console/src/pages/Runtime/RuntimeLayout.tsx
console/src/pages/Runtime/RuntimeVersionListCard.tsx

1. fix dataset preview with wrong link

feat(console): support runtime revert 

---

console/src/components/BaseSidebar.tsx
console/src/components/Header/index.tsx
console/src/components/IconFont/index.tsx
console/src/components/Link/TextLink.tsx
console/src/components/Viewer/ImageGrayscaleViewer.tsx
console/src/domain/dataset/services/datasetVersion.ts
console/src/domain/model/services/modelVersion.ts
console/src/domain/project/hooks/useFetchProject.ts
console/src/domain/runtime/services/runtime.ts
console/src/domain/runtime/services/runtimeVersion.ts
console/src/i18n/locales.ts
console/src/pages/Dataset/DatasetVersionListCard.tsx
console/src/pages/Model/ModelVersionListCard.tsx
console/src/pages/Runtime/Overview.tsx
console/src/pages/Runtime/RuntimeVersionListCard.tsx

fix(console): model/dataset/runtime revert

---

server/controller/src/test/java/ai/starwhale/mlops/datastore/impl/MemoryTableImplTest.java

after WAL UTs are executed, temp dirs are not deleted

fix(controller): try to fix wal ut TempDir not deleted error

---

server/controller/src/main/java/ai/starwhale/mlops/api/DatasetController.java
server/controller/src/main/java/ai/starwhale/mlops/api/RuntimeController.java
server/controller/src/main/java/ai/starwhale/mlops/api/SWModelPackageController.java
server/controller/src/main/java/ai/starwhale/mlops/api/protocol/runtime/RuntimeRevertRequest.java
server/controller/src/main/java/ai/starwhale/mlops/api/protocol/swds/RevertSWDSRequest.java
server/controller/src/main/java/ai/starwhale/mlops/api/protocol/swmp/RevertSWMPVersionRequest.java

refactor(controller): the versionUrl is required for revert requests

---

server/controller/src/main/resources/db/migration/V00017__Add_version_field.sql

fix(controller): fix flyway sql for version order

---

.github/workflows/server-ut-report.yml
README.md
server/Makefile
server/pom.xml

codecov report for java
fork repo test screen shot:

ci(ut-controller): codecov report for java

---

console/src/pages/Project/ProjectListCard.tsx

fix(console): Member button should go to Overview page

---

console/src/components/Input/Input.tsx
console/src/domain/user/components/PasswordForm.tsx

fix(console): password input tabindex to -1

---

server/controller/src/main/resources/mapper/RuntimeVersionMapper.xml
server/controller/src/main/resources/mapper/SWDatasetVersionMapper.xml
server/controller/src/main/resources/mapper/SWModelPackageVersionMapper.xml

fix（controller): fix bug with syntax error in mysql

---

client/starwhale/api/_impl/data_store.py
client/tests/sdk/test_data_store.py
server/controller/src/main/java/ai/starwhale/mlops/datastore/DataStore.java
server/controller/src/main/java/ai/starwhale/mlops/datastore/DataStoreQueryRequest.java
server/controller/src/test/java/ai/starwhale/mlops/datastore/DataStoreTest.java

feat(datastore): support custom object type

---

docker/charts/templates/controller-deployment.yaml
server/controller/src/main/resources/application.yaml
server/controller/src/main/resources/db/migration/V00001__Create_schema.sql

Make database name configurable

chore(controller): make database name configurable

---

server/controller/pom.xml
server/controller/src/main/resources/application.yaml
server/controller/src/test/java/ai/starwhale/mlops/objectstore/impl/FileSystemObjectStoreTest.java
server/pom.xml
server/storage-access-layer/pom.xml
server/storage-access-layer/src/main/java/ai/starwhale/mlops/storage/fs/FileIterator.java
server/storage-access-layer/src/main/java/ai/starwhale/mlops/storage/fs/StorageAccessServiceFile.java
server/storage-access-layer/src/test/java/ai/starwhale/mlops/storage/fs/FileIteratorTest.java
server/storage-access-layer/src/test/java/ai/starwhale/mlops/storage/fs/StorageAccessServiceFileTest.java

feat(controller): add file system support for StorageAccessService

---

server/controller/src/main/java/ai/starwhale/mlops/api/DataStoreApi.java
server/controller/src/main/java/ai/starwhale/mlops/api/DataStoreController.java
server/controller/src/main/java/ai/starwhale/mlops/api/protocol/datastore/ListTablesRequest.java
server/controller/src/main/java/ai/starwhale/mlops/api/protocol/datastore/TableNameListVO.java
server/controller/src/main/java/ai/starwhale/mlops/datastore/DataStore.java
server/controller/src/test/java/ai/starwhale/mlops/api/DataStoreControllerTest.java
server/controller/src/test/java/ai/starwhale/mlops/datastore/DataStoreTest.java

feat(datastore): support list tables

---

console/src/domain/datastore/hooks/useFetchDatastore.ts
console/src/domain/datastore/schemas/datastore.tsx
console/src/pages/Evaluation/EvaluationResults.tsx

chore(console): no error message when no evaluation result

---

console/src/api/ApiHeader.tsx
console/src/pages/Home/ResetPassword.tsx

fix(console): can not reset password

---

docker/Makefile

fix(docker): fix jar building after adding java.header for checkstyle

---

server/controller/src/main/resources/mapper/SwDatasetVersionMapper.xml

fix(controller): mapper name error with Upper case

---

server/controller/src/main/java/ai/starwhale/mlops/domain/task/status/watchers/TaskWatcherForJobStatus.java

fix(controller): try to fix no cmp log bug

---

console/src/pages/Admin/UserManagement.tsx

fix(console): #1140 list not refresh after add

---

server/controller/src/test/java/ai/starwhale/mlops/domain/task/TestTaskWatcherForJobStatus.java

ut(controller): add unit test for bug 1164

---

docker/charts/templates/controller-deployment.yaml
docker/charts/values.yaml

chore(deploy): add storage type in config

---

client/starwhale/core/model/model.py

fix(client):task failed but status is success

---

server/controller/src/main/resources/application.yaml

fix(controller): fix e2e failing

---

console/package.json
console/pnpm-lock.yaml
console/src/components/Button/Button.tsx
console/src/components/Viewer/AudioViewer.tsx
console/src/components/Viewer/DatasetViewer.tsx
console/src/components/Viewer/ImageViewer.tsx
console/src/components/Viewer/utils.ts
console/src/components/data-table/config-manage-columns.tsx
console/src/domain/dataset/sdk.ts
console/src/pages/Dataset/DatasetOverviewLayout.tsx
console/src/pages/Dataset/DatasetVersionOverviewFilePreview.tsx
console/src/pages/Dataset/DatasetVersionOverviewFiles.tsx
console/src/utils/index.ts
console/vite.config.ts

1. add dataset sdk match with client cli
2. audio support waveform
3. coco with segment & bbox

feat(console): viewer with segment/bbox/audio/text

---

client/starwhale/core/dataset/view.py
client/starwhale/core/model/cli.py
client/starwhale/core/model/view.py
client/starwhale/core/runtime/cli.py
client/starwhale/core/runtime/view.py

feat(client):history cmd support json format

---

.github/workflows/e2e-test.yml

chroe(ci): remove e2e condition of filter

---

console/src/components/Accordion/Accordion.tsx
console/src/domain/dataset/sdk.ts
console/src/pages/Dataset/DatasetOverviewLayout.tsx
console/src/pages/Dataset/DatasetVersionOverviewFilePreview.tsx
console/vite.config.ts

1. accordion display optimize
2. match with client as_mask

update(console): match with client as_mask

---

console/src/components/data-table/filter-operate-selector.tsx
console/src/pages/Evaluation/EvaluationListCard.tsx
console/src/pages/Evaluation/EvaluationListCompare.tsx
console/src/utils/index.ts

1. eva operator error
2. summary decimal optimize

fix(console): #1179 #1181

---

client/starwhale/core/model/model.py

fix(client):remove exit logic

---

console/src/domain/runtime/schemas/runtimeVersion.tsx
console/src/pages/Runtime/RuntimeLayout.tsx
console/src/pages/Runtime/RuntimeListCard.tsx
console/src/pages/Runtime/RuntimeVersionLayout.tsx
console/src/pages/Runtime/RuntimeVersionListCard.tsx

update(console): use name as list column

---

console/src/domain/job/schemas/task.tsx
console/src/pages/Evaluation/EvaluationOverviewLayout.tsx
console/src/pages/Job/JobListCard.tsx
console/src/pages/Job/JobTasks.tsx

1. rm realtime log server not support for now
2. #1180

feat(console): add job actions

---

server/controller/src/test/java/ai/starwhale/mlops/domain/graph/GraphTest.java
server/controller/src/test/java/ai/starwhale/mlops/domain/job/JobStatusCalculatorTest.java
server/controller/src/test/java/ai/starwhale/mlops/domain/job/StatusRequirementTest.java
server/controller/src/test/java/ai/starwhale/mlops/domain/job/mapper/JobMapperTest.java
server/controller/src/test/java/ai/starwhale/mlops/domain/swds/datastore/IndexWriterTest.java
server/controller/src/test/java/ai/starwhale/mlops/domain/swds/objectstore/DsFileGetterTest.java
server/controller/src/test/java/ai/starwhale/mlops/domain/swds/objectstore/StorageAccessParserTest.java
server/controller/src/test/java/ai/starwhale/mlops/domain/swds/objectstore/StorageAuthsTest.java
server/controller/src/test/java/ai/starwhale/mlops/domain/swds/objectstore/StorageUriTest.java
server/controller/src/test/java/ai/starwhale/mlops/domain/task/StepHelperTest.java
server/controller/src/test/java/ai/starwhale/mlops/domain/task/TaskServiceTest.java
server/controller/src/test/java/ai/starwhale/mlops/domain/task/TaskWatcherForJobStatusTest.java
server/controller/src/test/java/ai/starwhale/mlops/domain/task/log/TaskLogK8sCollectorTest.java
server/controller/src/test/java/ai/starwhale/mlops/domain/task/mapper/TaskMapperTest.java
server/controller/src/test/java/ai/starwhale/mlops/domain/user/mapper/UserMapperTest.java
server/controller/src/test/java/ai/starwhale/mlops/login/LoginRequestTest.java
server/controller/src/test/java/ai/starwhale/mlops/login/PasswordEncoderTest.java
server/controller/src/test/java/ai/starwhale/mlops/schedule/k8s/JobEventHandlerTest.java
server/controller/src/test/java/ai/starwhale/mlops/schedule/k8s/K8sJobTemplateTest.java
server/controller/src/test/java/ai/starwhale/mlops/schedule/k8s/K8sResourcePoolConverterTest.java
server/controller/src/test/java/ai/starwhale/mlops/schedule/k8s/K8sTaskSchedulerTest.java

chore(controller): rename Test** to **Test

---

client/starwhale/base/bundle.py
client/starwhale/base/bundle_copy.py
client/starwhale/base/tag.py
client/starwhale/core/dataset/model.py
client/starwhale/core/model/model.py
client/starwhale/core/runtime/model.py
client/tests/base/test_copy.py
client/tests/base/test_tag.py

feat(client): support auto-fast-tag for model/dataset/runtime

---

server/storage-access-layer/src/main/java/ai/starwhale/mlops/storage/s3/StorageAccessServiceS3.java
server/storage-access-layer/src/test/java/ai/starwhale/mlops/storage/s3/StorageAccessServiceS3Test.java

Wal log do not exists after updateTable called

fix(controller): can not work with minio when disable the chunkedEncoding config

---

console/src/components/Accordion/Accordion.tsx
console/src/components/Viewer/AudioViewer.tsx
console/src/components/data-table/config-manage-columns.tsx
console/src/components/data-table/config-views.tsx
console/src/components/data-table/stateful-data-table.tsx
console/src/i18n/locales.ts
console/src/pages/Dataset/DatasetListCard.tsx
console/src/pages/Dataset/DatasetOverviewLayout.tsx
console/src/pages/Evaluation/EvaluationListCard.tsx
console/src/pages/Evaluation/EvaluationOverviewLayout.tsx
console/src/pages/Job/JobTasks.tsx
console/vite.config.ts

1. view config with all columns selected
2. fix lazylognot showing
3. viewer layout

feat(console): support default view with all runs

---

server/controller/src/main/java/ai/starwhale/mlops/domain/job/JobService.java
server/controller/src/main/java/ai/starwhale/mlops/domain/job/converter/JobConvertor.java
server/controller/src/test/java/ai/starwhale/mlops/domain/bundle/BundleManagerTest.java
server/controller/src/test/java/ai/starwhale/mlops/domain/job/JobServiceTest.java
server/controller/src/test/java/ai/starwhale/mlops/domain/job/converter/JobConverterTest.java

test(controller): add unit tests

---

client/starwhale/base/cloud.py
client/tests/base/test_cloud.py

fix(client): fix dataset size info in cloud

---

server/storage-access-layer/src/main/java/ai/starwhale/mlops/storage/aliyun/StorageAccessServiceAliyun.java

https://github.com/star-whale/starwhale/blob/f62fac92370ffd82a220ab558a343ab3042e4cf5/server/controller/src/main/java/ai/starwhale/mlops/domain/swds/objectstore/DsFileGetter.java#L50-L60

fix(controller): dataset not show when using aliyun oss

---

console/src/__generated__/MySuperbApi.ts
console/src/domain/datastore/hooks/useFetchDatastore.ts
console/src/domain/datastore/hooks/useParseDatastore.ts
console/src/domain/datastore/schemas/datastore.tsx
console/src/domain/datastore/services/datastore.ts
console/src/domain/datastore/utils.ts
console/src/pages/Evaluation/EvaluationResults.tsx
console/src/utils/datetime.ts
console/src/utils/index.ts
console/swagger.json

enhance(console): evaluation result with all store tables

---

server/controller/src/main/java/ai/starwhale/mlops/schedule/k8s/K8sTaskScheduler.java
server/controller/src/main/java/ai/starwhale/mlops/schedule/k8s/ResourceOverwriteSpec.java
server/controller/src/test/java/ai/starwhale/mlops/schedule/k8s/ResourceOverwriteSpecTest.java

add limit for non overcommitable resources

fix(controller): fix gpu failure

---

console/src/api/ApiHeader.tsx
console/src/api/WithAuth.tsx
console/src/api/const.ts
console/src/domain/dataset/sdk.ts
console/src/domain/project/hooks/useFetchProjectRole.tsx
console/src/domain/project/hooks/useProjectRole.ts
console/src/domain/project/services/project.ts
console/src/hooks/global.ts
console/src/i18n/locales.ts
console/src/pages/Dataset/DatasetVersionListCard.tsx
console/src/pages/Evaluation/EvaluationListCard.tsx
console/src/pages/Evaluation/EvaluationOverviewLayout.tsx
console/src/pages/Model/ModelVersionListCard.tsx
console/src/pages/Project/Overview.tsx
console/src/pages/Project/ProjectListCard.tsx
console/src/pages/Project/ProjectMembers.tsx
console/src/pages/Runtime/RuntimeVersionListCard.tsx

feat(console): #1171 component with privilege

---

server/controller/src/main/resources/mapper/ProjectMapper.xml

fix(controller): the project description cannot be set to empty

---

client/starwhale/core/dataset/type.py
client/tests/sdk/test_dataset.py

bug(dataset): support link type reflect

---

console/src/api/ApiHeader.tsx
console/src/api/WithAuth.tsx
console/src/components/Header/index.tsx
console/src/components/data-table/data-custom-table.tsx
console/src/components/data-table/filter-operate-selector.tsx
console/src/components/data-table/measure-column-widths.tsx
console/src/domain/dataset/sdk.ts
console/src/domain/user/hooks/useUserRoles.ts
console/src/domain/user/schemas/user.tsx
console/src/hooks/global.ts
console/src/hooks/useCurrentUserRoles.ts
console/src/pages/Evaluation/EvaluationListCard.tsx
console/src/pages/Project/ProjectListCard.tsx

1. Measure column duplicate key in cases
2. fix error when filtering by id

refactor(console): combine systemRole & projectRole in current user

---

example/speech_command/dataset.yaml
example/speech_command/sc/dataset.py

- raw data is store in the remote s3
-  ![image](https://user-images.githubusercontent.com/590748/191705086-d6c4eef6-bef9-4b4d-866f-72e962d06acf.png)
- build a remote link dataset
-  ![image](https://user-images.githubusercontent.com/590748/191705270-a47d081c-02f4-4a1b-9b6b-0c2c268c241d.png)
- evaluate model in the controller successfully.
-  ![image](https://user-images.githubusercontent.com/590748/191705668-67f0d73c-8ac3-481d-a5de-1f6c6c94bb61.png)
- ![image](https://user-images.githubusercontent.com/590748/191705740-9b23eeec-040f-4c94-b81e-379a004098c4.png)

example: speech commands dataset support remote link

---

server/controller/src/main/resources/template/job.yaml

fix(controller):split dir for swmp and swrt

---

client/Makefile
client/pyproject.toml
client/requirements-dev.txt
client/starwhale/__init__.py
client/starwhale/api/model.py
example/cifar10/cifar/evaluator.py
example/mnist/mnist/evaluator.py
example/mnist/mnist/model.py
example/mnist/mnist/train.py
example/nmt/nmt/evaluator.py
example/speech_command/sc/evaluator.py

- add basic linters for example
- starwhale package export `PPLResultIterator`

ci(example): add lint for example code

---

server/controller/src/main/resources/template/job.yaml

fix(controller): untar error at job container

---

console/src/components/Header/index.tsx
console/src/domain/dataset/components/DatasetVersionSelector.tsx
console/src/domain/job/components/JobForm.tsx
console/src/domain/model/components/ModelVersionSelector.tsx
console/src/domain/runtime/components/RuntimeVersionSelector.tsx
console/src/domain/user/hooks/useUserRoles.ts
console/src/i18n/locales.ts
console/src/pages/Dataset/DatasetOverviewLayout.tsx
console/src/pages/Evaluation/EvaluationListCard.tsx
console/src/pages/Evaluation/EvaluationListCompare.tsx
console/src/pages/Evaluation/EvaluationOverviewLayout.tsx
console/src/pages/Evaluation/EvaluationResults.tsx
console/src/pages/Job/JobListCard.tsx
console/src/pages/Job/JobOverviewLayout.tsx
console/yarn.lock

enhance(console): version selector with alias/duration locals

---

.github/workflows/client.yaml

chore(ci): force config python3.10 micro version for client ci

---

server/controller/src/main/java/ai/starwhale/mlops/domain/task/status/watchers/log/TaskLogK8sCollector.java
server/controller/src/main/java/ai/starwhale/mlops/schedule/k8s/K8sJobTemplate.java
server/controller/src/test/java/ai/starwhale/mlops/schedule/k8s/K8sJobTemplateTest.java

chore(controller): add dev info to pod label

---

console/src/__generated__/MySuperbApi.ts
console/src/components/Divider.tsx
console/src/domain/job/components/JobForm.tsx
console/src/domain/job/schemas/job.tsx
console/src/domain/model/components/ModelVersionSelector.tsx
console/src/domain/model/schemas/modelVersion.tsx
console/src/domain/setting/components/DeviceSelector.tsx
console/src/i18n/locales.ts
console/src/pages/Evaluation/EvaluationListCard.tsx
console/src/pages/Evaluation/EvaluationOverviewLayout.tsx
console/src/pages/Job/JobOverviewLayout.tsx
console/swagger.json
console/vite.config.ts

feat(console): job run with multi task config & yaml editor

---

console/src/assets/logo_normal_en_blue.png
console/src/components/Header/Logo.tsx
console/src/domain/user/components/ThirdPartyLoginButton.tsx

update(console): logo

---

console/src/components/Header/index.tsx
console/src/pages/Settings/SettingsOverviewLayout.tsx
console/src/pages/Settings/SettingsSidebar.tsx

feat(console): show version / update setting page

---

console/src/pages/Job/JobTasks.tsx
server/controller/pom.xml
server/controller/src/main/java/ai/starwhale/mlops/api/TaskLogWsServer.java
server/controller/src/main/java/ai/starwhale/mlops/domain/task/status/watchers/log/CancellableTaskLogCollector.java
server/controller/src/main/java/ai/starwhale/mlops/domain/task/status/watchers/log/CancellableTaskLogK8sCollector.java
server/controller/src/main/java/ai/starwhale/mlops/domain/task/status/watchers/log/CancellableTaskLogK8sCollectorFactory.java
server/controller/src/main/java/ai/starwhale/mlops/schedule/k8s/K8sClient.java
server/controller/src/test/java/ai/starwhale/mlops/api/TaskLogWsServerTest.java
server/controller/src/test/java/ai/starwhale/mlops/domain/task/log/CancellableTaskLogK8sCollectorFactoryTest.java
server/controller/src/test/java/ai/starwhale/mlops/domain/task/log/CancellableTaskLogK8sCollectorTest.java
server/controller/src/test/java/ai/starwhale/mlops/schedule/k8s/K8sClientTest.java
server/pom.xml

feat(controller): support realtime log

---

console/src/domain/runtime/hooks/useRuntimeVersion.ts
console/src/domain/runtime/services/runtime.ts
console/src/hooks/global.ts
console/src/pages/Runtime/RuntimeOverviewLayout.tsx
console/src/pages/Runtime/RuntimeVersionOverview.tsx
console/src/pages/Runtime/RuntimeVersionOverviewFiles.tsx
console/src/pages/Runtime/RuntimeVersionOverviewMeta.tsx

https://user-images.githubusercontent.com/3217223/193204896-73709cc1-aee1-4cf5-9c02-805b5906aa9b.mp4

fix(console): update runtime info after selection changes

---

console/src/domain/setting/hooks/useSettings.ts
console/src/domain/setting/schemas/system.tsx
console/src/domain/setting/services/system.ts
console/src/i18n/locales.ts
console/src/pages/Admin/AdminSidebar.tsx
console/src/pages/Admin/SystemSettings.tsx
console/src/routes.tsx

feat(console): system settings config

---

Makefile
docs/docs/community/contribute.md
docs/docs/community/dev.md
docs/docs/community/roadmap.md
docs/i18n/zh/docusaurus-plugin-content-docs/current/community/contribute.md
docs/sidebars.js

doc: add contribute docs

---

scripts/client_test/step_spec.yaml

fix(e2e): update task num when run eval on cloud

---

docker/Dockerfile.base
docker/Makefile

https://github.com/star-whale/starwhale/pkgs/container/base/45533198?tag=0.2.3

fix(docker): add python-dev in base image

---

.github/workflows/release-base.yml
docker/cuda/render.py

issue: https://github.com/star-whale/starwhale/actions/runs/3246789884

chore(ci): build and push cuda-base image automatically

---

console/src/domain/job/components/JobForm.tsx
console/src/domain/model/schemas/modelVersion.tsx

fix(console): step cant edit by rm overwriteable

---

client/starwhale/api/_impl/data_store.py
client/tests/sdk/test_data_store.py
server/controller/src/test/java/ai/starwhale/mlops/datastore/DataStoreTest.java
server/controller/src/test/java/ai/starwhale/mlops/datastore/impl/MemoryTableImplTest.java

fix(datastore): hex decode error when value is "0"

---

README.md
docs/Makefile
docs/docs/fundamentals/concepts.md
docs/docs/guides/install/helm-charts.md
docs/docs/guides/install/standalone.md
docs/docs/guides/uri.md
docs/docs/img/concepts-org.jpg
docs/docusaurus.config.js
docs/i18n/zh/docusaurus-plugin-content-docs/current/fundamentals/concepts.md
docs/i18n/zh/docusaurus-plugin-content-docs/current/guides/install/helm-charts.md
docs/i18n/zh/docusaurus-plugin-content-docs/current/guides/install/standalone.md
docs/i18n/zh/docusaurus-plugin-content-docs/current/guides/uri.md
docs/i18n/zh/docusaurus-plugin-content-docs/current/quickstart/on-premises.md
docs/i18n/zh/docusaurus-plugin-content-docs/current/reference/cli/dataset.md
docs/i18n/zh/docusaurus-plugin-content-docs/current/reference/cli/eval.md
docs/i18n/zh/docusaurus-plugin-content-docs/current/reference/cli/instance.md
docs/i18n/zh/docusaurus-plugin-content-docs/current/reference/cli/model.md
docs/i18n/zh/docusaurus-plugin-content-docs/current/reference/cli/project.md
docs/i18n/zh/docusaurus-plugin-content-docs/current/reference/cli/runtime.md
docs/i18n/zh/docusaurus-plugin-content-docs/current/reference/cli/utilities.md
docs/i18n/zh/docusaurus-plugin-content-docs/current/reference/sdk/data_type.md
docs/i18n/zh/docusaurus-plugin-content-docs/current/reference/sdk/dataset.md
docs/i18n/zh/docusaurus-plugin-content-docs/current/reference/sdk/evaluation.md
docs/i18n/zh/docusaurus-plugin-content-docs/current/reference/sdk/other.md
docs/i18n/zh/docusaurus-plugin-content-docs/current/reference/sdk/overview.md
docs/package.json
docs/sidebars.js
docs/yarn.lock

doc: upgrade docusaurus and fix doc typo

---

client/starwhale/api/_impl/data_store.py
client/starwhale/api/_impl/dataset/builder.py
client/starwhale/api/_impl/wrapper.py
client/starwhale/core/dataset/tabular.py
client/tests/sdk/test_data_store.py

feat(sdk): datastore support flush

---

scripts/publish/image_sync.sh

sync images from public registry to self hosted registry

ci: sync images from public registry to self hosted registry

---

README.md
docs/docs/community/contribute.md
docs/docs/quickstart/standalone.md
docs/i18n/zh/docusaurus-plugin-content-docs/current/community/contribute.md
docs/i18n/zh/docusaurus-plugin-content-docs/current/quickstart/standalone.md

doc: update docs for the git-lfs issue

---

console/src/api/ApiHeader.tsx
console/src/domain/job/components/JobForm.tsx
console/src/domain/model/schemas/modelVersion.tsx
console/src/domain/setting/components/DeviceSelector.tsx
console/src/i18n/locales.ts
console/src/pages/Admin/SystemSettings.tsx
console/src/pages/Dataset/DatasetVersionOverview.tsx
console/src/pages/Dataset/DatasetVersionOverviewMeta.tsx

1. fix(console): error when return data is null
2. fix: dataset overview not changed when select version

enhancement(console): refactor job step more user friendly

---

example/cifar10/cifar/evaluator.py

bug(examaple): fix cifar10 model evaluation example typo

---

client/starwhale/api/_impl/dataset/builder.py
client/starwhale/core/dataset/model.py
client/starwhale/core/model/default_handler.py
client/starwhale/utils/load.py
client/tests/core/test_dataset.py
client/tests/core/test_model.py
client/tests/data/dataset/dataset.yaml
client/tests/sdk/test_dataset.py
client/tests/utils/test_load.py
docs/i18n/zh/docusaurus-plugin-content-docs/current/guides/dataset.md
example/mnist/dataset.yaml
example/mnist/mnist/dataset.py

- related issue: https://github.com/star-whale/starwhale/issues/1371
[![asciicast](https://asciinema.org/a/530348.svg)](https://asciinema.org/a/530348)

feat(dataset): support function as dataset build handler

---

server/controller/src/main/resources/mapper/JobMapper.xml

fix list jobs mapper 
relates to https://github.com/star-whale/starwhale/actions/runs/3294139080/jobs/5431357767
cc @tianweidut

fix(controller): fix list jobs mapper

---

client/starwhale/base/bundle.py
client/starwhale/base/view.py
client/starwhale/core/dataset/cli.py
client/starwhale/core/dataset/model.py
client/starwhale/core/dataset/type.py
client/starwhale/core/dataset/view.py
client/starwhale/core/model/model.py
client/starwhale/core/model/view.py
client/starwhale/core/runtime/model.py
client/starwhale/core/runtime/view.py
client/tests/core/test_dataset.py
client/tests/utils/test_fs.py
docs/i18n/zh/docusaurus-plugin-content-docs/current/guides/dataset.md
docs/i18n/zh/docusaurus-plugin-content-docs/current/reference/cli/dataset.md

https://github.com/star-whale/starwhale/issues/1372
[![asciicast](https://asciinema.org/a/530770.svg)](https://asciinema.org/a/530770)

enhace(dataset): remove dataset.yaml/name dependencies

---

server/controller/src/main/resources/db/migration/V00022__Add_test_role.sql

fix(controller): add project role for test user

---

console/playwright/.env
console/playwright/playwright.config.ts
console/playwright/tests/admin.spec.ts
console/playwright/tests/config.ts
console/src/domain/setting/services/system.ts
console/src/domain/user/components/NewUserForm.tsx
console/src/i18n/locales.ts
console/src/pages/Admin/SystemSettings.tsx

e2e(console): add admin cases

---

client/starwhale/core/job/model.py
client/starwhale/core/job/scheduler.py
client/starwhale/core/model/model.py

fix(sdk): support single step override task num

---

docker/charts/templates/controller-deployment.yaml
docker/charts/templates/rolebinding.yaml
docker/charts/values.yaml
docs/docs/guides/install/helm-charts.md
docs/i18n/zh/docusaurus-plugin-content-docs/current/guides/install/helm-charts.md

doc: add serviceaccount doc in helm install

---

server/controller/src/main/java/ai/starwhale/mlops/api/DatasetController.java
server/controller/src/main/java/ai/starwhale/mlops/api/protocol/dataset/dataloader/DataConsumptionRequest.java
server/controller/src/main/java/ai/starwhale/mlops/domain/dataset/dataloader/DataReadManager.java
server/controller/src/main/java/ai/starwhale/mlops/domain/dataset/dataloader/DataReadRequest.java
server/controller/src/main/java/ai/starwhale/mlops/domain/dataset/dataloader/dao/DataReadLogDao.java
server/controller/src/test/java/ai/starwhale/mlops/domain/dataset/dataloader/MultiConsumerTest.java

fix(server): dataset range api timeout error

---

server/controller/src/main/java/ai/starwhale/mlops/api/TrashApi.java
server/controller/src/main/java/ai/starwhale/mlops/api/TrashController.java
server/controller/src/main/java/ai/starwhale/mlops/api/protocol/trash/TrashVo.java
server/controller/src/main/java/ai/starwhale/mlops/domain/bundle/base/BundleEntity.java
server/controller/src/main/java/ai/starwhale/mlops/domain/bundle/base/HasModifiedTime.java
server/controller/src/main/java/ai/starwhale/mlops/domain/bundle/recover/RecoverManager.java
server/controller/src/main/java/ai/starwhale/mlops/domain/dataset/DatasetService.java
server/controller/src/main/java/ai/starwhale/mlops/domain/job/JobManager.java
server/controller/src/main/java/ai/starwhale/mlops/domain/job/JobService.java
server/controller/src/main/java/ai/starwhale/mlops/domain/job/po/JobEntity.java
server/controller/src/main/java/ai/starwhale/mlops/domain/model/ModelService.java
server/controller/src/main/java/ai/starwhale/mlops/domain/runtime/RuntimeService.java
server/controller/src/main/java/ai/starwhale/mlops/domain/trash/Trash.java
server/controller/src/main/java/ai/starwhale/mlops/domain/trash/TrashService.java
server/controller/src/main/java/ai/starwhale/mlops/domain/trash/bo/TrashQuery.java
server/controller/src/main/java/ai/starwhale/mlops/domain/trash/mapper/TrashMapper.java
server/controller/src/main/java/ai/starwhale/mlops/domain/trash/po/TrashPo.java
server/controller/src/main/java/ai/starwhale/mlops/exception/SwValidationException.java
server/controller/src/main/resources/db/migration/V00027__Add_trash.sql
server/controller/src/main/resources/mapper/JobMapper.xml
server/controller/src/test/java/ai/starwhale/mlops/api/TrashControllerTest.java
server/controller/src/test/java/ai/starwhale/mlops/domain/bundle/BundleManagerTest.java
server/controller/src/test/java/ai/starwhale/mlops/domain/dataset/DatasetServiceTest.java
server/controller/src/test/java/ai/starwhale/mlops/domain/job/JobServiceTest.java
server/controller/src/test/java/ai/starwhale/mlops/domain/model/ModelServiceTest.java
server/controller/src/test/java/ai/starwhale/mlops/domain/runtime/RuntimeServiceTest.java
server/controller/src/test/java/ai/starwhale/mlops/domain/trash/TrashServiceTest.java
server/controller/src/test/java/ai/starwhale/mlops/domain/trash/mapper/TrashMapperTest.java

feat(controller): api and unit test for trash management

---

server/storage-access-layer/src/main/java/ai/starwhale/mlops/storage/memory/StorageAccessServiceMemory.java
server/storage-access-layer/src/test/java/ai/starwhale/mlops/storage/StorageAccessServiceTest.java

chore(storage): add a memory implementation for unit test

---

console/src/api/Auth.tsx
console/src/domain/setting/hooks/useSettings.ts

Refine current user info logic

chore(console): refine current user info logic

---

client/starwhale/utils/fs.py
client/starwhale/utils/venv.py
client/tests/core/test_runtime.py
client/tests/utils/test_fs.py

related: https://github.com/star-whale/starwhale/pull/1363 
thanks @TrellixVulnTeam

bug(client): fix python extract insecure bug(cve-2007-4559)

---

server/controller/src/main/java/ai/starwhale/mlops/common/util/TagUtil.java
server/controller/src/test/java/ai/starwhale/mlops/common/util/TagUtilTest.java

feat(controller): add tag validation

---

server/controller/src/main/java/ai/starwhale/mlops/domain/dataset/DatasetService.java
server/controller/src/main/java/ai/starwhale/mlops/domain/dataset/dataloader/DataLoader.java
server/controller/src/main/java/ai/starwhale/mlops/domain/dataset/dataloader/DataReadManager.java
server/controller/src/main/java/ai/starwhale/mlops/domain/dataset/dataloader/dao/DataReadLogDao.java
server/controller/src/main/java/ai/starwhale/mlops/domain/dataset/dataloader/mapper/DataReadLogMapper.java
server/controller/src/main/java/ai/starwhale/mlops/domain/dataset/dataloader/mapper/SessionMapper.java
server/controller/src/main/resources/db/migration/V00026__Add_dataset_reader.sql
server/controller/src/test/java/ai/starwhale/mlops/common/KeyLockTest.java
server/controller/src/test/java/ai/starwhale/mlops/domain/dataset/DatasetServiceTest.java
server/controller/src/test/java/ai/starwhale/mlops/domain/dataset/dataloader/MultiConsumerTest.java
server/controller/src/test/java/ai/starwhale/mlops/domain/dataset/dataloader/ReadRangeTest.java

fix(server): lock ut error & transactional use bug

---

server/controller/src/main/java/ai/starwhale/mlops/datastore/DataStore.java
server/controller/src/main/java/ai/starwhale/mlops/datastore/MemoryTable.java
server/controller/src/main/java/ai/starwhale/mlops/datastore/WalManager.java
server/controller/src/main/java/ai/starwhale/mlops/datastore/impl/MemoryTableImpl.java
server/controller/src/main/java/ai/starwhale/mlops/datastore/parquet/SwOutputFile.java
server/controller/src/main/protobuf/table_meta.proto
server/controller/src/main/protobuf/wal.proto
server/controller/src/main/resources/application.yaml
server/controller/src/test/java/ai/starwhale/mlops/api/DataStoreControllerTest.java
server/controller/src/test/java/ai/starwhale/mlops/datastore/DataStoreTest.java
server/controller/src/test/java/ai/starwhale/mlops/datastore/WalManagerTest.java
server/controller/src/test/java/ai/starwhale/mlops/datastore/impl/MemoryTableImplTest.java

enhance(datastore): memory table support saving and loading data from the storage service

---

server/controller/src/main/java/ai/starwhale/mlops/api/PanelApi.java
server/controller/src/main/java/ai/starwhale/mlops/api/PanelController.java
server/controller/src/main/java/ai/starwhale/mlops/api/protocol/panel/PanelPluginVo.java
server/controller/src/main/java/ai/starwhale/mlops/domain/panel/PanelPluginConvertor.java
server/controller/src/main/java/ai/starwhale/mlops/domain/panel/PanelSettingService.java
server/controller/src/main/java/ai/starwhale/mlops/domain/panel/PluginService.java
server/controller/src/main/java/ai/starwhale/mlops/domain/panel/bo/PanelPlugin.java
server/controller/src/main/java/ai/starwhale/mlops/domain/panel/mapper/PanelPluginMapper.java
server/controller/src/main/java/ai/starwhale/mlops/domain/panel/mapper/PanelSettingMapper.java
server/controller/src/main/java/ai/starwhale/mlops/domain/panel/po/PanelPluginEntity.java
server/controller/src/main/java/ai/starwhale/mlops/domain/storage/StoragePathCoordinator.java
server/controller/src/main/java/ai/starwhale/mlops/exception/SwValidationException.java
server/controller/src/main/resources/db/migration/V00028__Add_panel_plugin.sql
server/controller/src/test/java/ai/starwhale/mlops/api/PanelControllerTest.java
server/controller/src/test/java/ai/starwhale/mlops/domain/panel/PanelSettingServiceTest.java
server/controller/src/test/java/ai/starwhale/mlops/domain/panel/PluginServiceTest.java
server/controller/src/test/java/ai/starwhale/mlops/domain/panel/mapper/PanelPluginMapperTest.java
server/controller/src/test/java/ai/starwhale/mlops/domain/panel/mapper/PanelSettingMapperTest.java

cc @waynelwz 
New APIs are:
| api | method | desc |
|---|---|---|
|/panel/plugin| POST| upload plugin tarball |
| /panel/plugin/{id} | DELETE | remove plugin by id|
| /panel/plugin| GET | list plugins |
| /panel/setting/{project_id}/{key} | GET | get setting by project and key|
| /panel/setting/{project_id}/{key} | GET | save setting by project and key (overwritable)|

feat(controller): support panel api

---

client/starwhale/api/_impl/data_store.py
client/tests/sdk/test_data_store.py
server/controller/src/main/java/ai/starwhale/mlops/api/DataStoreController.java
server/controller/src/main/java/ai/starwhale/mlops/datastore/ColumnSchema.java
server/controller/src/main/java/ai/starwhale/mlops/datastore/ColumnTypeList.java
server/controller/src/main/java/ai/starwhale/mlops/datastore/ColumnTypeObject.java
server/controller/src/main/java/ai/starwhale/mlops/datastore/ColumnTypeScalar.java
server/controller/src/main/java/ai/starwhale/mlops/datastore/impl/MemoryTableImpl.java
server/controller/src/main/java/ai/starwhale/mlops/domain/trash/TrashService.java
server/controller/src/main/java/ai/starwhale/mlops/exception/SwValidationException.java
server/controller/src/test/java/ai/starwhale/mlops/datastore/ColumnTypeListTest.java
server/controller/src/test/java/ai/starwhale/mlops/datastore/ColumnTypeObjectTest.java

fix(sdk): correct object type table schema representation

---

server/Makefile
server/controller/src/main/java/ai/starwhale/mlops/datastore/DataStore.java
server/controller/src/main/java/ai/starwhale/mlops/datastore/ObjectStore.java
server/controller/src/main/java/ai/starwhale/mlops/datastore/WalManager.java
server/controller/src/main/java/ai/starwhale/mlops/datastore/impl/MemoryTableImpl.java
server/controller/src/main/resources/application.yaml
server/controller/src/test/java/ai/starwhale/mlops/api/DataStoreControllerTest.java
server/controller/src/test/java/ai/starwhale/mlops/datastore/DataStoreTest.java
server/controller/src/test/java/ai/starwhale/mlops/datastore/WalManagerTest.java
server/controller/src/test/java/ai/starwhale/mlops/datastore/impl/MemoryTableImplTest.java

feature(datastore): support snapshot

---

server/controller/src/main/java/ai/starwhale/mlops/datastore/ColumnType.java
server/controller/src/main/java/ai/starwhale/mlops/datastore/ColumnTypeList.java
server/controller/src/main/java/ai/starwhale/mlops/datastore/ColumnTypeScalar.java
server/controller/src/main/java/ai/starwhale/mlops/datastore/ColumnTypeTuple.java
server/controller/src/test/java/ai/starwhale/mlops/datastore/ColumnTypeTest.java
server/controller/src/test/java/ai/starwhale/mlops/datastore/ColumnTypeTupleTest.java
server/controller/src/test/java/ai/starwhale/mlops/datastore/DataStoreTest.java
server/controller/src/test/java/ai/starwhale/mlops/datastore/impl/MemoryTableImplTest.java

enhance(datastore): add tuple type support

---

example/datasets/coco/dataset.py

fix(example): fix missing images2dict

---

server/controller/src/main/java/ai/starwhale/mlops/configuration/security/ProjectNameExtractorDataStoreMixed.java
server/controller/src/main/java/ai/starwhale/mlops/domain/project/ProjectManager.java
server/controller/src/main/java/ai/starwhale/mlops/domain/project/mapper/ProjectMapper.java
server/controller/src/main/resources/db/migration/V00029__Mod_project_unique.sql
server/controller/src/main/resources/mapper/ProjectMapper.xml
server/controller/src/test/java/ai/starwhale/mlops/domain/project/ProjectManagerTest.java
server/controller/src/test/java/ai/starwhale/mlops/domain/project/mapper/ProjectMapperTest.java

feat(controller): add namespace to projectUrl

---

console/src/components/Viewer/AudioViewer.tsx
console/src/components/Viewer/DatasetViewer.tsx
console/src/components/Viewer/ImageViewer.tsx
console/src/components/Viewer/TextViewer.tsx
console/src/components/Viewer/VideoViewer.tsx
console/src/domain/dataset/sdk.ts
console/src/pages/Dataset/DatasetVersionOverviewFiles.tsx
console/src/pages/Dataset/DatasetVersionOverviewMeta.tsx

feat(console): add simple video viewer

---

console/src/domain/dataset/sdk.ts
console/src/domain/datastore/utils.ts

bug(console): remove encode for offset/size

---

console/src/pages/Dataset/DatasetVersionOverviewFiles.tsx

1. optimize ui 
2. make layout state local

hotfix(console): layout not work when build

---

server/controller/src/main/java/ai/starwhale/mlops/datastore/ColumnSchemaDesc.java
server/controller/src/main/java/ai/starwhale/mlops/datastore/ColumnType.java
server/controller/src/main/java/ai/starwhale/mlops/datastore/ColumnTypeMap.java
server/controller/src/main/java/ai/starwhale/mlops/datastore/ColumnTypeObject.java
server/controller/src/main/java/ai/starwhale/mlops/datastore/ColumnTypeScalar.java
server/controller/src/main/java/ai/starwhale/mlops/datastore/ColumnTypeTuple.java
server/controller/src/main/java/ai/starwhale/mlops/datastore/RecordList.java
server/controller/src/main/java/ai/starwhale/mlops/datastore/WalManager.java
server/controller/src/main/java/ai/starwhale/mlops/datastore/impl/MemoryTableImpl.java
server/controller/src/main/protobuf/wal.proto
server/controller/src/test/java/ai/starwhale/mlops/datastore/ColumnTypeListTest.java
server/controller/src/test/java/ai/starwhale/mlops/datastore/ColumnTypeMapTest.java
server/controller/src/test/java/ai/starwhale/mlops/datastore/ColumnTypeObjectTest.java
server/controller/src/test/java/ai/starwhale/mlops/datastore/ColumnTypeScalarTest.java
server/controller/src/test/java/ai/starwhale/mlops/datastore/ColumnTypeTest.java
server/controller/src/test/java/ai/starwhale/mlops/datastore/ColumnTypeTupleTest.java
server/controller/src/test/java/ai/starwhale/mlops/datastore/DataStoreTest.java
server/controller/src/test/java/ai/starwhale/mlops/datastore/impl/MemoryTableImplTest.java

enhance(datastore): add map type support

---

server/controller/src/main/resources/template/job.yaml

change init container registry

chore: change init container registry

---

client/starwhale/api/_impl/data_store.py
client/tests/sdk/test_data_store.py

enhance(sdk): add tuple type support

---

server/storage-access-layer/src/main/java/ai/starwhale/mlops/storage/aliyun/StorageAccessServiceAliyun.java
server/storage-access-layer/src/main/java/ai/starwhale/mlops/storage/fs/StorageAccessServiceFile.java
server/storage-access-layer/src/main/java/ai/starwhale/mlops/storage/s3/StorageAccessServiceS3.java
server/storage-access-layer/src/test/java/ai/starwhale/mlops/storage/StorageAccessServiceTest.java

fix(storage): aliyun, s3 and fs put error

---

scripts/client_test/cmds/base/common.py
scripts/client_test/cmds/base/invoke.py

chore(e2e):remove useless mnist dataset train data for e2e test

---

client/starwhale/__init__.py
client/starwhale/api/_impl/dataset/__init__.py
client/starwhale/api/_impl/dataset/builder.py
client/starwhale/api/_impl/dataset/loader.py
client/starwhale/api/dataset.py
client/starwhale/core/dataset/store.py
client/starwhale/core/dataset/type.py
client/tests/core/test_dataset_store.py
client/tests/sdk/test_dataset.py
client/tests/sdk/test_loader.py
example/PennFudanPed/pfp/dataset.py
example/datasets/test_annotations/dataset.py

- related: 
- https://github.com/star-whale/starwhale/issues/942
- https://github.com/star-whale/starwhale/issues/1448 
- features:
- support link in annotations
- fix s3 url bugs from  https://github.com/star-whale/starwhale/pull/1480 and https://github.com/star-whale/starwhale/pull/1443
- demo show:
- [![asciicast](https://asciinema.org/a/537466.svg)](https://asciinema.org/a/537466)

feat(dataset): support link type in dataset annotations

---

scripts/publish/image_sync.sh

tag latest image when push to private docker registry

chore(ci): tag latest image

---

client/scripts/sw-docker-entrypoint

fix(docker): broken python module yq in entrypoint

---

scripts/client_test/cli_test.py
scripts/client_test/cmds/artifacts_cmd.py
scripts/client_test/cmds/base/common.py
scripts/client_test/cmds/base/invoke.py
scripts/client_test/cmds/eval_cmd.py
scripts/client_test/cmds/instance_cmd.py
scripts/client_test/cmds/project_cmd.py

fix(test): subprocess use bug in test

---

server/controller/src/main/java/ai/starwhale/mlops/common/TarFileUtil.java
server/controller/src/main/java/ai/starwhale/mlops/domain/panel/PluginService.java
server/controller/src/test/java/ai/starwhale/mlops/domain/panel/PluginServiceTest.java

Support plugin assets serving
cc @waynelwz

feat(controller): support plugin assets serving

---

example/ucf101/requirements-sw-lock.txt

fix(example): opencv missing libGL bug

---

console/src/domain/project/components/UserSelector.tsx
console/src/pages/Admin/UserManagement.tsx

fix(console): fetch enough users to select

---

client/starwhale/core/dataset/type.py
client/tests/sdk/test_dataset.py
example/PennFudanPed/pfp/dataset.py
example/PennFudanPed/pfp/evaluator.py

- run in standalone
- [![asciicast](https://asciinema.org/a/537739.svg)](https://asciinema.org/a/537739)
- run in server
- http://console.pre.intra.starwhale.ai/projects/22/evaluations/228/tasks
- ![image](https://user-images.githubusercontent.com/590748/201860714-adcd1c6d-6886-4a9f-83c8-f257b116f643.png)
- ![image](https://user-images.githubusercontent.com/590748/201860801-c39014a9-0b65-482a-815b-478ccdd45b7b.png)

example: update pfp example dataset for data_store type

---

server/controller/src/main/java/ai/starwhale/mlops/common/VersionAliasConvertor.java
server/controller/src/main/java/ai/starwhale/mlops/common/util/TagUtil.java
server/controller/src/main/java/ai/starwhale/mlops/domain/bundle/BundleManager.java
server/controller/src/main/java/ai/starwhale/mlops/domain/bundle/BundleVersionAccessor.java
server/controller/src/main/java/ai/starwhale/mlops/domain/bundle/tag/TagManager.java
server/controller/src/main/java/ai/starwhale/mlops/domain/dataset/DatasetManager.java
server/controller/src/main/java/ai/starwhale/mlops/domain/dataset/DatasetService.java
server/controller/src/main/java/ai/starwhale/mlops/domain/dataset/upload/DatasetUploader.java
server/controller/src/main/java/ai/starwhale/mlops/domain/model/ModelManager.java
server/controller/src/main/java/ai/starwhale/mlops/domain/model/ModelService.java
server/controller/src/main/java/ai/starwhale/mlops/domain/runtime/RuntimeManager.java
server/controller/src/main/java/ai/starwhale/mlops/domain/runtime/RuntimeService.java
server/controller/src/test/java/ai/starwhale/mlops/common/VersionAliasConvertorTest.java
server/controller/src/test/java/ai/starwhale/mlops/common/util/TagUtilTest.java
server/controller/src/test/java/ai/starwhale/mlops/domain/bundle/BundleManagerTest.java
server/controller/src/test/java/ai/starwhale/mlops/domain/dataset/DatasetManagerTest.java
server/controller/src/test/java/ai/starwhale/mlops/domain/dataset/DatasetServiceTest.java
server/controller/src/test/java/ai/starwhale/mlops/domain/dataset/DatasetUploaderTest.java
server/controller/src/test/java/ai/starwhale/mlops/domain/model/ModelManagerTest.java
server/controller/src/test/java/ai/starwhale/mlops/domain/model/ModelServiceTest.java
server/controller/src/test/java/ai/starwhale/mlops/domain/runtime/RuntimeManagerTest.java
server/controller/src/test/java/ai/starwhale/mlops/domain/runtime/RuntimeServiceTest.java

feat(controller): version urls support latest

---

client/starwhale/base/uricomponents/resource.py
client/tests/base/uricomponents/test_resource.py

Support console URL from the browser when parsing URI

feat(client): support console URL from the browser when parsing URI

---

client/starwhale/base/uricomponents/resource.py
client/tests/base/uricomponents/test_resource.py

fix(client): support version only copy

---

client/starwhale/base/bundle.py
client/starwhale/core/eval/executor.py
client/starwhale/utils/__init__.py
client/tests/core/test_runtime.py
client/tests/utils/test_common.py

- related: https://github.com/star-whale/starwhale/issues/1375
- drop of common parts:
- time version from uuid1
- node info from uuid1
- resource name

refactor(client): refactor resource version without common string parts

---

client/Makefile
client/tests/base/test_cloud.py
client/tests/sdk/test_metric.py

- fix metric test with setup function
- change test mode from serial to parallel

enhance(ci): make client test to run in parallel mode

---

.github/workflows/e2e-test.yml

chore: reverse e2e tag

---

client/starwhale/api/_impl/dataset/loader.py
client/starwhale/core/dataset/cli.py
client/starwhale/core/dataset/model.py
client/starwhale/core/dataset/view.py
client/tests/core/test_dataset.py
docs/i18n/zh/docusaurus-plugin-content-docs/current/reference/cli/dataset.md
example/datasets/test_annotations/dataset.py

[![asciicast](https://asciinema.org/a/qMu3svvwlNRRFYf1jPau38kpB.svg)](https://asciinema.org/a/qMu3svvwlNRRFYf1jPau38kpB)

feat(dataset): add `swcli dataset head` command

---

server/controller/src/main/java/ai/starwhale/mlops/domain/job/JobService.java

catch any exception when splitting

bug: fix job should fail but ready error

---

server/controller/src/main/java/ai/starwhale/mlops/datastore/ColumnTypeList.java
server/controller/src/main/java/ai/starwhale/mlops/datastore/ColumnTypeMap.java
server/controller/src/test/java/ai/starwhale/mlops/datastore/DataStoreTest.java
server/controller/src/test/java/ai/starwhale/mlops/datastore/parquet/ParquetReadWriteTest.java

fix(datastore): failed to write empty list/map values to parquet files

---

server/controller/src/main/java/ai/starwhale/mlops/api/DataStoreController.java
server/controller/src/main/java/ai/starwhale/mlops/api/protocol/datastore/TableDesc.java
server/controller/src/main/java/ai/starwhale/mlops/datastore/DataStore.java
server/controller/src/main/java/ai/starwhale/mlops/datastore/DataStoreScanRequest.java
server/controller/src/test/java/ai/starwhale/mlops/api/DataStoreControllerTest.java
server/controller/src/test/java/ai/starwhale/mlops/datastore/DataStoreTest.java

enhance(datastore): support column prefix in scan

---

server/controller/src/main/java/ai/starwhale/mlops/datastore/DataStore.java
server/controller/src/main/java/ai/starwhale/mlops/datastore/MemoryTable.java
server/controller/src/main/java/ai/starwhale/mlops/datastore/impl/MemoryTableImpl.java
server/controller/src/test/java/ai/starwhale/mlops/datastore/impl/MemoryTableImplTest.java

chore(datastore): return Iterator in MemoryTable.query

---

server/controller/src/main/java/ai/starwhale/mlops/api/DataStoreApi.java
server/controller/src/main/java/ai/starwhale/mlops/api/DataStoreController.java
server/controller/src/main/java/ai/starwhale/mlops/api/protocol/datastore/FlushRequest.java
server/controller/src/main/java/ai/starwhale/mlops/datastore/DataStore.java
server/controller/src/main/java/ai/starwhale/mlops/datastore/WalManager.java
server/controller/src/test/java/ai/starwhale/mlops/datastore/DataStoreTest.java
server/controller/src/test/java/ai/starwhale/mlops/datastore/TestThread.java
server/controller/src/test/java/ai/starwhale/mlops/datastore/WalManagerTest.java

enhance(datastore): support server side flush

---

scripts/publish/image_sync.sh

chore(ci): replace docker.io with ghcr.io

---

example/PennFudanPed/pfp/evaluator.py

make a workaround for pfp example, later SDK will fix the issue.
related pr: https://github.com/star-whale/starwhale/pull/1502

chore(example): fix pfp example workarount for 0.3.2 sdk id changed issue

---

server/controller/src/main/resources/db/migration/v0_3_2/V0_3_2_003__create_schema.sql
server/controller/src/main/resources/db/migration/v0_3_2/V0_3_2_004__init_data.sql

fix(controller): fix bug in flyway sql

---

scripts/apitest/pytest/test_dataset.py
scripts/apitest/pytest/test_model.py
scripts/apitest/pytest/test_runtime.py

fix(controller): temporarily remove e2e test for the modified api

---

client/starwhale/api/_impl/metric.py

https://scikit-learn.org/stable/modules/model_evaluation.html#multilabel-confusion-matrix

fix(sdk): confusion matrix problem

---

scripts/e2e_test/start_test.sh

chore: rename exit hook function

---

client/starwhale/api/_impl/metric.py
client/tests/sdk/test_metric.py

fix(sdk): metric roc_aoc log error

---

server/controller/src/test/java/ai/starwhale/mlops/common/KeyLockTest.java

fix(server): lock ut error

---

example/PennFudanPed/requirements.txt
example/mnist/Makefile
example/mnist/requirements.txt
example/speech_command/Makefile
example/speech_command/requirements.txt
example/text_cls_AG_NEWS/Makefile
example/text_cls_AG_NEWS/requirements.txt
example/ucf101/requirements.txt
scripts/client_test/cli_test.py

chore: add dependency for example

---

.github/workflows/console.yml
.github/workflows/e2e-test.yml
client/starwhale/core/dataset/store.py
console/src/api/ApiHeader.tsx

chore(ci): remove useless lfs for ci

---

docker/Dockerfile.base
docker/Makefile

related pr: https://github.com/star-whale/starwhale/pull/1584

chore(docker): upgrade docker base image for python3.11

---

docker/Dockerfile.base

error message: https://github.com/star-whale/starwhale/actions/runs/3629485936/jobs/6121742047

chore(ci): fix python3.10-3.11 pip install issue

---

scripts/e2e_test/remove_test_env.sh

chore: add remove e2e test script

---

client/starwhale/core/project/model.py

fix(client): add default value to is_default field which is not required in controller api

---

client/requirements-dev.txt
client/setup.py
client/starwhale/api/_impl/model.py
client/starwhale/api/_impl/service.py
client/starwhale/api/service.py
client/starwhale/base/spec/openapi/components.py
client/starwhale/core/dataset/type.py
client/starwhale/core/model/model.py
client/tests/core/test_model.py
client/tests/data/sdk/service/custom_class.py
client/tests/data/sdk/service/custom_service.py
client/tests/data/sdk/service/default_class.py
client/tests/sdk/test_service.py
example/mnist/mnist/custom_evaluator.py
example/mnist/mnist/evaluator.py

`swcli build model` in mnist demo, it will generate spec in `src/svc.yaml`, the content is:
```yaml
info:
description: StarWhale API
title: StarWhale API
version: 1.0.0
openapi: 3.0.0
paths:
/ppl:
post:
requestBody:
content:
multipart/form-data:
schema:
properties:
data:
format: binary
type: string
required:
- data
type: object
description: starwhale builtin model serving specification for type image
responses:
'200':
content:
application/json:
schema:
properties:
data:
type: string
type: object
description: OK
```
online demo
* [default](https://petstore.swagger.io/?url=https://gist.githubusercontent.com/jialeicui/566d7ebcab2700a5295d965119318684/raw/d1c2d7682e07c37ff710d3b1d2f64c10e615a13b/model-serving-spec-demo.yaml#/)
* [custom](https://petstore.swagger.io/?url=https://gist.githubuser …

feat(sdk): support generating openAPI spec

---

client/starwhale/core/runtime/model.py
client/tests/core/test_runtime.py

chore(client): detect starwhale version when build runtime

---

client/starwhale/consts/__init__.py
client/starwhale/core/model/cli.py
client/starwhale/core/model/model.py
client/starwhale/core/model/view.py
client/starwhale/utils/fs.py
client/tests/core/test_model.py
client/tests/data/model/base_manifest.yaml
client/tests/data/model/compare_manifest.yaml
client/tests/utils/test_fs.py
docs/docs/img/model-diff.png
docs/docs/reference/cli/model.md
docs/i18n/zh/docusaurus-plugin-content-docs/current/guides/model.md
docs/i18n/zh/docusaurus-plugin-content-docs/current/reference/cli/model.md

feat(client): add model diff for client

---

client/setup.py

chore(client): update python require for client

---

client/requirements-dev.txt
client/starwhale/api/_impl/dataset/model.py
client/starwhale/core/dataset/tabular.py
client/starwhale/core/dataset/type.py
client/starwhale/integrations/tensorflow/__init__.py
client/starwhale/integrations/tensorflow/dataset.py
client/tests/sdk/test_dataset.py
client/tests/sdk/test_dataset_sdk.py

- https://github.com/star-whale/starwhale/issues/758

feat(sdk): support to conver starwhale dataset to tensorflow dataset

---

console/src/domain/model/hooks/useFetchModelVersionDiff.ts
console/src/domain/model/hooks/useModelVersion.ts
console/src/domain/model/services/modelVersion.ts
console/src/i18n/locales.ts
console/src/pages/Model/ModelOverviewLayout.tsx
console/src/pages/Model/ModelVersionOverview.tsx
console/src/pages/Model/ModelVersionOverviewFiles.tsx

feat(console): support model diff

---

server/controller/src/main/java/ai/starwhale/mlops/api/RuntimeApi.java
server/controller/src/main/java/ai/starwhale/mlops/api/RuntimeController.java
server/controller/src/main/java/ai/starwhale/mlops/configuration/CommonExceptionHandler.java
server/controller/src/main/java/ai/starwhale/mlops/domain/bundle/BundleManager.java
server/controller/src/main/java/ai/starwhale/mlops/domain/dataset/DatasetDao.java
server/controller/src/main/java/ai/starwhale/mlops/domain/dataset/DatasetService.java
server/controller/src/main/java/ai/starwhale/mlops/domain/model/ModelDao.java
server/controller/src/main/java/ai/starwhale/mlops/domain/model/ModelService.java
server/controller/src/main/java/ai/starwhale/mlops/domain/project/ProjectManager.java
server/controller/src/main/java/ai/starwhale/mlops/domain/project/ProjectService.java
server/controller/src/main/java/ai/starwhale/mlops/domain/runtime/RuntimeDao.java
server/controller/src/main/java/ai/starwhale/mlops/domain/runtime/RuntimeService.java
server/controller/src/main/java/ai/starwhale/mlops/exception/SwNotFoundException.java
server/controller/src/test/java/ai/starwhale/mlops/domain/dataset/DatasetServiceTest.java
server/controller/src/test/java/ai/starwhale/mlops/domain/model/ModelServiceTest.java
server/controller/src/test/java/ai/starwhale/mlops/domain/project/ProjectManagerTest.java
server/controller/src/test/java/ai/starwhale/mlops/domain/project/ProjectServiceTest.java
server/controller/src/test/java/ai/starwhale/mlops/domain/runtime/RuntimeServiceTest.java

fix(controller): return 404 when the resource is not found for all of api

---

client/tests/sdk/test_dataset_sdk.py

- related: https://github.com/star-whale/starwhale/actions/runs/3730765668/jobs/6328204351

chore(test): make dataset sdk test stable for the parallel setitem case

---

example/datasets/caltech_101/README.md
example/datasets/caltech_101/dataset.py
example/datasets/caltech_101/example.py

example(dataset): add caltech-101 dataset

---

client/starwhale/api/_impl/service.py

chore(sdk): add swagger ui for model serving apis

---

client/starwhale/api/_impl/dataset/loader.py
client/starwhale/api/_impl/dataset/model.py
client/starwhale/core/dataset/model.py
client/tests/sdk/test_dataset_sdk.py
client/tests/sdk/test_loader.py
client/tests/sdk/test_service.py

use two queues to tune dataloader iter performance with prefetch

enhance(sdk): tune dataloader performance with data prefetch

---

example/datasets/fer2013/README.md
example/datasets/fer2013/dataset.py
example/datasets/fer2013/example.py

example(dataset): add fer2013 dataset

---

example/datasets/eurosat/README.md
example/datasets/eurosat/dataset.py
example/datasets/eurosat/example.py

example(dataset): add eurosat dataset

---

example/datasets/dtd/README.md
example/datasets/dtd/dataset.py
example/datasets/dtd/example.py

example(dataset): add dtd dataset

---

example/datasets/country211/README.md
example/datasets/country211/dataset.py
example/datasets/country211/example.py

example(dataset): add country211 dataset

---

scripts/apitest/pytest/test_project.py
server/controller/src/main/java/ai/starwhale/mlops/configuration/security/JwtTokenFilter.java
server/controller/src/main/java/ai/starwhale/mlops/domain/project/ProjectManager.java
server/controller/src/main/java/ai/starwhale/mlops/domain/project/ProjectService.java
server/controller/src/main/java/ai/starwhale/mlops/domain/project/mapper/ProjectMapper.java
server/controller/src/test/java/ai/starwhale/mlops/domain/project/ProjectManagerTest.java
server/controller/src/test/java/ai/starwhale/mlops/domain/project/ProjectServiceTest.java

fix(controller): internal exception when the project does not exist

---

example/datasets/flickr8k/README.md
example/datasets/flickr8k/dataset.py
example/datasets/flickr8k/example.py

example(dataset): add flickr8k dataset

---

client/starwhale/core/dataset/type.py
example/datasets/gtsrb/README.md
example/datasets/gtsrb/dataset.py
example/datasets/gtsrb/example.py

example(dataset): add GTSRB dataset

---

example/datasets/lfw/README.md
example/datasets/lfw/dataset.py
example/datasets/lfw/example.py

example(dataset): add LFW dataset

---

example/datasets/iNaturalist/README.md
example/datasets/iNaturalist/dataset.py
example/datasets/iNaturalist/example.py

example(dataset): add iNaturalist dataset

---

example/datasets/oxfordIIITPet/README.md
example/datasets/oxfordIIITPet/dataset.py
example/datasets/oxfordIIITPet/example.py

example(dataset): add oxfordIIITPet dataset

---

example/datasets/stanford_cars/README.md
example/datasets/stanford_cars/dataset.py
example/datasets/stanford_cars/example.py

example(dataset): add stanford_cars dataset

---

server/controller/src/main/java/ai/starwhale/mlops/datastore/DataStore.java

fix(datastore): add limit for datastore query api

---

example/datasets/coco/dataset.py

- make bbox starwhale object
- make mask.as_mask = true

example(dataset): add viewer support for coco dataset

---

example/datasets/wider_face/README.md
example/datasets/wider_face/dataset.py
example/datasets/wider_face/example.py

example(dataset): add wider face dataset

---

example/datasets/citycapes/person_bbox/README.md
example/datasets/citycapes/person_bbox/dataset.py
example/datasets/citycapes/person_bbox/example.py
example/datasets/iNaturalist/dataset.py

example(dataset): add cityscapes_person dataset

---

client/starwhale/api/_impl/dataset/model.py
client/starwhale/api/_impl/model.py
client/tests/sdk/test_dataset_sdk.py
client/tests/sdk/test_model.py
example/mnist/mnist/custom_evaluator.py
example/mnist/mnist/evaluator.py
example/speech_command/sc/evaluator.py
example/text_cls_AG_NEWS/tcan/evaluator.py
example/ucf101/custom_model.yaml
example/ucf101/ucf101/custom_evaluator.py
scripts/example/src/evaluator.py

1. (feature) support ppl batch
2. (fix) Solve the problem that the result of PPL returns more than one dimension under single data

feat(sdk): support batch for ppl

---

example/datasets/sbd/README.md
example/datasets/sbd/dataset.py
example/datasets/sbd/example.py

example(dataset): add sbd dataset

---

example/speech_command/sc/evaluator.py

fix(example): speech example dim bug

---

client/starwhale/__init__.py
client/starwhale/api/_impl/dataset/__init__.py
client/starwhale/api/dataset.py
client/starwhale/core/dataset/type.py
client/tests/core/test_dataset.py
example/datasets/culane/README.md
example/datasets/culane/dataset.py
example/datasets/culane/example.py

- add starwhale.Line type
- use starwhale.Line in culane dataset

chore: add starwhale.Line type; use starwhale.Line in culane dataset

---

example/speech_command/sc/evaluator.py

fix(example): speech error

---

client/tests/sdk/test_dataset_sdk.py

https://github.com/star-whale/starwhale/actions/runs/3799187527/jobs/6461485202

chore(test): fix dataset loader test unstable issue
