star-whale/starwhale

- client/starwhale/api/_impl/loader.py
- example/mnist/test/swds_s3_simple.json
use `memoryview` to tune byte/bytearray split memory copy. `memoryview` is zero-copy.
> use memoryview to tune split performance

- client/README.md
- client/starwhale/api/_impl/loader.py
- client/starwhale/api/_impl/model.py
- client/starwhale/cli/mngt.py
- client/starwhale/cli/model.py
- client/starwhale/consts/env.py
- client/starwhale/swds/dataset.py
- client/starwhale/swmp/model.py
- client/starwhale/swmp/store.py
- client/starwhale/utils/__init__.py
- client/starwhale/utils/load.py
- example/mnist/Makefile
- example/mnist/mnist/ppl.py
- example/mnist/model.yaml
- example/mnist/test/swds_fuse.json
- example/mnist/test/swds_s3_smoke.json
- add `swcli model ppl` command,  which can run ppl from model.yaml
-  EXAMPLE: in example/mnist dir , run `swcli model ppl . --swds-config   test/swds_s3_smoke.json `
- ppl some swmp directly: `swcli model ppl mnist:g4zgimrthfrwcnrtmftdgyjzha2wg2a --swds-config test/swds_s3_smoke.json`
- refactor swmp/swds code
- add `SW_PRODUCTION` env to check dev/prod env
- refactor MNIST Example
- fix swmp build without model/config files bug
> add swmp ppl cmd

- client/starwhale/api/_impl/model.py
- example/mnist/mnist/ppl.py
user can define label handler which can make compare with result easily. default label will output as str type.
In our MNIST example, we define `handle_label` method,
```python
def handle_label(self, label, batch_size, **kw):
return [int(l) for l in label]
```
> add label handle method for PipelineHandler

- client/starwhale/__init__.py
- docker/Dockerfile.base
- docker/Dockerfile.sw
- docker/Makefile
- docker/external/sources.list
support base image, which include basic software, python3.7/3.8/3.9 and conda.
run `docker pull starwhaleai/base:0.1.0-nightly-2022040701` to pull base image in your computer
> add base image dockerfile

- docker/Dockerfile.base
- docker/Dockerfile.taskset
- docker/Makefile
- docker/external/dind-dockerd-entrypoint.sh
- docker/external/docker_daemon.json
`taskset` is dind(docker-in-docker) container, which can be as a sidecar for agent pod. 
support some features:
- gpu allocate
- nvidia-smi cmd
- docker daemon config
- run `taskset` in host: `docker run --rm --name dind -it -v /usr/bin/nvidia-smi:/tmp/nvidia-smi -v /mnt/data/tmp/dind:/var/lib/docker --gpus all --privileged starwhaleai/taskset:0.1.0-nightly-2022041601`
- run a new container in `dind container``
- inspect gpu info in `dind` container
- in `dind` container, we create a new container which use `No. 0` GPU.  cmd is `docker run --rm --gpus 1 nvidia/cuda:11.0-base nvidia-smi` .
> add taskset dockerfile for dind

- docker/Makefile
- docker/external/pip.conf
- remove `aliyun` pypi cache, which will install some wrong package 
- rebuild base image
> upgrade new base image and remove aliyun pypi mirror

- client/scripts/sw-docker-entrypoint
> use _manifest runtime as the first class runtime for python

- client/starwhale/api/_impl/metric.py
- client/starwhale/cluster/view.py
- console/src/components/Indicator/types.d.ts
- console/src/pages/Job/JobResult.tsx
fix typo `mutlilabel` -> `multilabel`
#198
> bug: fix multilabel word typo 

- .github/file-filter.yml
- .github/workflows/client.yaml
- .github/workflows/codeql-analysis.yml
- .github/workflows/console.yml
- .github/workflows/maven-build.yml
- .github/workflows/python.yml
- client/Makefile
- client/requirements-dev.txt
- add codeQL analysis for python/java/js/ts
- add python ci framework
- add path filter for python/java/js, which can reduce useless ci  
- #223 
cc @goldenxinxing  @waynelwz
> ci: add python ci

- .github/workflows/client.yaml
- .gitignore
- README.md
- client/.coveragerc
- client/.flake8
- client/Makefile
- client/requirements-dev.txt
- add pytest coverage
- upload to https://coveralls.io/
- #223
> ci: add coverage for client

- .github/workflows/release.yml
fix `RELEASE_VERSION` typo in release.yaml
> hottfix: fix release_version env typo

- .github/workflows/client.yaml
- client/Makefile
- client/README.md
- client/starwhale/eval/executor.py
use `latest` tag , so we need always pull image for eval local run.
> enhanced: always pull starwhale docker image for latest tag

- client/starwhale/eval/executor.py
- only the newer version(>= 20.10) support `docker run --pull=always` args, so we should use `docker pull` cmd to pull image.
- issue: #345
> fix: use docker pull cmd for prepare phase

- server/controller/src/main/java/ai/starwhale/mlops/domain/swmp/SWModelPackageService.java
- server/storage-access-layer/src/main/java/ai/starwhale/mlops/storage/LargeFileInputStream.java
- server/storage-access-layer/src/main/java/ai/starwhale/mlops/storage/s3/StorageAccessServiceS3.java
- fix swmp push size limited to 2G
> fix swmp push size limited to 2G

- bootstrap/Makefile
- bootstrap/starwhale_bootstrap/cmd.py
- bootstrap/starwhale_bootstrap/default.py
- bootstrap/starwhale_bootstrap/playbook/roles/controller/tasks/main.yaml
- bootstrap/starwhale_bootstrap/playbook/roles/mysql/tasks/main.yaml
- docker/charts/templates/_helpers.tpl
- docker/charts/templates/controller-deployment.yaml
- docker/charts/values.yaml
- server/agent/pom.xml
- server/controller/pom.xml
keep playbook environment variables the same as helm uses
> keep playbook environment variables the same as helm uses

- docker/charts/templates/_helpers.tpl
- docker/charts/templates/controller-deployment.yaml
- docker/charts/values.yaml
- server/agent/pom.xml
- server/controller/pom.xml
Closes #214 
agent and controller will have a default api: /actuator/health, and the response now is:
```
{
"status": "UP"
}
```
> add probe for agent and controller

- client/scripts/sw-docker-entrypoint
- client/starwhale/consts/__init__.py
- client/starwhale/core/job/executor.py
- client/starwhale/utils/venv.py
- client/tests/core/test_executor.py
- support pip cache for standalone job
- add `SW_PIP_CACHE_DIR` env for `sw-docker-entrypoint` to set global pip cache dir. 
related issue: https://github.com/star-whale/starwhale/issues/274
> enhance: add pip cache dir for standalone job

- client/starwhale/core/runtime/cli.py
- client/starwhale/core/runtime/model.py
- client/starwhale/core/runtime/view.py
- client/starwhale/utils/venv.py
- client/tests/core/test_runtime.py
- fix runtime conda create typo
- add `--include-editable` flag for runtime build.
- add conda  include-editable check
- issue: https://github.com/star-whale/starwhale/issues/208
- enable
- ![image](https://user-images.githubusercontent.com/590748/172541337-74172f57-cf1c-49ac-82f7-b8682432bbd9.png)
- disable
-  ![image](https://user-images.githubusercontent.com/590748/172541663-75efc2c5-27f9-4c20-a54c-e26fbac564f3.png)
> support include-editable for runtime build

- client/starwhale/utils/error.py
- client/starwhale/utils/load.py
- client/starwhale/utils/venv.py
- client/tests/utils/test_load.py
- Situation: swcli was installed in global or some indepent venvs, but runtime use another venv/conda.
- feature show: swcli can run ppl/cmp successfully.
- related: https://github.com/star-whale/starwhale/issues/525
> enhance: smart import user venv/conda sys.path

- README.md
- client/starwhale/api/_impl/model.py
- client/starwhale/core/dataset/cli.py
- client/starwhale/core/job/cli.py
- client/starwhale/core/job/executor.py
- client/starwhale/core/job/model.py
- client/starwhale/core/job/view.py
- client/starwhale/core/model/cli.py
- client/starwhale/utils/error.py
- client/starwhale/utils/progress.py
- client/starwhale/utils/venv.py
- client/tests/core/test_executor.py
- docs/docs/quickstart/standalone.md
- related issue: https://github.com/star-whale/starwhale/issues/587
- remove `--docker-verbose` args
- add `--use-docker` to specify whether to use docker
- add `swcli model eval` command
> feat: support  run eval job in standalone instance without docker

- server/controller/src/main/java/ai/starwhale/mlops/domain/dag/DAGQuerier.java
- server/controller/src/test/java/ai/starwhale/test/domain/dag/DAGQuerierTest.java
- response to FE with readable error when uerying dag of job at status of created
> fix issue 633 :response to FE with readable error when uerying dag of job at status of created

- server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/persistence/FileSystemTaskPersistence.java
- server/agent/src/test/java/ai/starwhale/mlops/agent/test/TaskActionTest.java
> Fix: agent log with line separator

- docker/external/pip.conf
> bug(docker): fix trusted host in default pip config

- client/starwhale/api/_impl/loader.py
- client/starwhale/api/_impl/model.py
- client/tests/utils/test_process.py
- json.loads can handle `str`, `bytes` automatically.
- related pr: https://github.com/star-whale/starwhale/pull/631
- ![image](https://user-images.githubusercontent.com/590748/175971606-8cda08c8-84d4-45e6-9cf2-c5c873bd409c.png)
> bug(sdk): fix s3 data loader type

- client/Makefile
* make virtual targets PHONY
* `all-check` can not autocomplete without phony under zsh
> fix(client): make targets phony

- server/agent/src/main/java/ai/starwhale/mlops/agent/configuration/TaskConfiguration.java
- server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/AgentTaskScheduler.java
- server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/InferenceStage.java
- server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/TaskPool.java
- server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/action/ExecuteStage.java
- server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/action/end/ArchivedAction.java
- server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/action/normal/AbsBaseTaskAction.java
- server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/action/normal/Init2PreparingAction.java
- server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/action/normal/MonitoringAction.java
- server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/action/normal/Preparing2RunningAction.java
- server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/action/normal/Uploading2FinishedAction.java
- server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/action/normal/cancel/AbsBaseCancelTaskAction.java
- server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/action/normal/cancel/Preparing2CanceledAction.java
- server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/action/normal/cancel/Running2CanceledAction.java
- server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/action/normal/cancel/Uploading2CanceledAction.java
- server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/action/report/ReportAction.java
- server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/persistence/FileSystemPath.java
- server/agent/src/main/java/ai/starwhale/mlops/agent/task/log/Appender.java
- server/agent/src/main/java/ai/starwhale/mlops/agent/task/log/FileLog.java
- server/agent/src/main/java/ai/starwhale/mlops/agent/task/log/LogConfigurator.java
- server/agent/src/main/java/ai/starwhale/mlops/agent/task/log/LogRecorder.java
- server/agent/src/main/java/ai/starwhale/mlops/agent/task/log/LogRecorderForDocker.java
- server/agent/src/main/java/ai/starwhale/mlops/agent/task/log/LoggingEvent.java
- server/agent/src/main/java/ai/starwhale/mlops/agent/task/log/MemoryLog.java
- server/agent/src/main/java/ai/starwhale/mlops/agent/task/log/Reader.java
- server/agent/src/main/java/ai/starwhale/mlops/agent/utils/FileUtil.java
- server/agent/src/test/java/ai/starwhale/mlops/agent/test/LogRecorderTest.java
> refactor(log): refactor agent log impl

- client/starwhale/core/project/model.py
`.tmp` will be recognized as a project without validation
> fix(client): ignore invalid dir in project list

- client/starwhale/base/uri.py
- client/tests/core/test_model.py
> fix(client): model list cmd works with instance prefix uri

- client/starwhale/base/bundle.py
- client/starwhale/base/bundle_copy.py
- client/starwhale/base/store.py
- client/starwhale/base/tag.py
- client/starwhale/base/view.py
- client/starwhale/core/dataset/dataset.py
- client/starwhale/core/dataset/model.py
- client/starwhale/core/job/model.py
- client/starwhale/core/model/model.py
- client/starwhale/core/runtime/model.py
- client/starwhale/utils/__init__.py
- client/starwhale/utils/config.py
- client/tests/core/test_dataset.py
- client/tests/core/test_executor.py
- client/tests/core/test_model.py
- client/tests/core/test_runtime.py
```sh
/home/foo/work/repos/starwhale/client/starwhale/core/dataset/model.py:201: ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/foo/.cache/starwhale/self/dataset/mnist/gv/gvqtqzdche3wcnrtmftdgyjzon2xena.swds/_manifest.yaml' mode='r' encoding='UTF-8'>
_manifest = yaml.safe_load((_bf.path / DEFAULT_MANIFEST_NAME).open())
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/home/foo/work/repos/starwhale/client/starwhale/core/dataset/model.py:201: ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/foo/.cache/starwhale/self/dataset/mnist/hf/hfrdmyrzhe3wgnrtmftdgyjzonudi6a.swds/_manifest.yaml' mode='r' encoding='UTF-8'>
_manifest = yaml.safe_load((_bf.path / DEFAULT_MANIFEST_NAME).open())
ResourceWarning: Enable tracemalloc to get the object …
```
> fix(sdk): resolve all ResourceWarning: unclosed file of yaml loading

- client/Makefile
- client/starwhale/cli/__init__.py
- client/starwhale/cli/board/board.py
- client/starwhale/cli/board/project_tree.py
https://user-images.githubusercontent.com/3217223/178645613-ed8a2983-ce1a-4f4a-87f0-abe825b3ee56.mp4
> feat(client): board support show project tree and model list

- client/starwhale/utils/process.py
- warning message:
- fixed output:
> fix(client): force to close popen stdout for log_check_call 

- client/scripts/sw-docker-entrypoint
- client/starwhale/core/job/executor.py
- docker/charts/templates/_helpers.tpl
- docker/charts/values.yaml
- docker/external/condarc
- https://github.com/star-whale/starwhale/issues/742
- ref: https://conda-forge.org/
> Anaconda Inc. updated their [terms of service](https://www.anaconda.com/terms-of-service) for anaconda.org channels. Based on the new terms of service you may require a commercial license if you rely on Anaconda’s packaging and distribution. See [Anaconda Commercial Edition FAQ](https://www.anaconda.com/blog/anaconda-commercial-edition-faq) for more information. Your use of any Anaconda channels is governed by their terms of service.
> chore(runtime): use conda-forage as the default conda channels

- docker/Dockerfile.base
- docker/external/pip.conf
- Remove the default pip config for China's mainland. Users can config pip config by the `runtime.yaml` or `SW_PYPI_*` env.
- related: https://github.com/star-whale/starwhale/pull/796
> chore(docker): remove default pip config

- client/starwhale/base/type.py
- client/starwhale/core/runtime/cli.py
- client/starwhale/core/runtime/model.py
- client/starwhale/core/runtime/view.py
- client/starwhale/utils/__init__.py
- client/starwhale/utils/venv.py
- client/tests/core/test_runtime.py
- issues: https://github.com/star-whale/starwhale/issues/741  https://github.com/star-whale/starwhale/issues/764
- support freeze environment: `shell`, `conda env name`, `conda prefix`, `venv dir` 
- current shell + venv
- current shell + conda
- name + conda
- prefix + conda
- prefix + venv
> feat(runtime): add `swcli runtime lock` command

- client/starwhale/core/runtime/cli.py
- client/starwhale/core/runtime/model.py
- client/starwhale/core/runtime/view.py
- client/starwhale/utils/venv.py
- client/tests/core/test_runtime.py
- scripts/run_demo.sh
- add `runtime quickstart` command that renders the runtime.yaml with the interactive shell
- ![image](https://user-images.githubusercontent.com/590748/181572561-1d560efb-e9e1-4dbd-9e2a-bb5ca68fcf88.png)
- remove create command
- related: https://github.com/star-whale/starwhale/issues/751
> feat(runtime): add runtime quickstart command, goodbye to create command

- server/controller/src/main/java/ai/starwhale/mlops/schedule/k8s/K8sTaskScheduler.java
- fix job yaml can't be loaded error
> fix: fix job yaml can't be loaded error

- client/starwhale/api/_impl/model.py
- client/starwhale/core/job/executor.py
- client/starwhale/core/job/model.py
- client/starwhale/core/runtime/process.py
- client/starwhale/utils/process.py
- client/starwhale/utils/venv.py
- client/tests/core/test_runtime_process.py
- add Runtime Process Class: auto activate runtime in another new process
- support runtime-uri argument for job create command in the non-docker environment
- related: https://github.com/star-whale/starwhale/issues/752
>  feat(runtime): support runtime-uri argument for job create command

- console/src/pages/Admin/UserManagement.tsx
> fix(console): admin can not disable itself

- server/controller/src/main/java/ai/starwhale/mlops/schedule/k8s/K8sClient.java
- server/controller/src/main/resources/application.yaml
Support inject `SW_K8S_HOST_PATH_FOR_CACHE` env for configuring job's pip cache host path dir
> feat(controller): support injecting host path config for pip cache

- docker/charts/README.md
- docker/charts/templates/controller-deployment.yaml
- docs/docs/cloud/helm-charts.md
> fix(deploy): agent host path takes effect with job cache data

- client/starwhale/base/bundle_copy.py
- client/tests/base/test_copy.py
> feat(client): migrate to new version server api

- client/starwhale/core/runtime/cli.py
- client/starwhale/core/runtime/model.py
- client/starwhale/core/runtime/view.py
- client/starwhale/utils/venv.py
Fixes #851 
https://user-images.githubusercontent.com/3217223/183001459-0bddaddb-8ddc-4b73-8525-d499bcd70aa9.mp4
> feat(client): auto active env in bash/fish/zsh when executing runtime active cmd

- scripts/run_demo.sh
Use the latest job result instead of the index 0 result
It is useful when executing the script in the dev env
> enhance(ci): make e2e test of standalone work well with the existing job data

- .github/workflows/release.yml
- docker/Makefile
Docker buildx does not support parallel upload of the different arch images.
only one arch image.
> fix(ci): remove starwhale arch matrix build

- client/starwhale/utils/venv.py
in SHLVL 2, the `_bin` is the wrong path.
> bug(runtime): fix runtime activate shell bin path

- client/starwhale/base/bundle_copy.py
- client/tests/base/test_copy.py
> fix(client): fix wrong uri of head request

- client/starwhale/api/_impl/data_store.py
- client/starwhale/utils/config.py
- client/tests/sdk/test_base.py
- client/tests/sdk/test_data_store.py
- client/tests/sdk/test_wrapper.py
- replace `SW_ROOT_PATH` env with `SWCliConfigMixed` class for fetching datastore dir
- patch `atexit` in test
> enhance(datastore): tune datastore storage dir by swcli config

- server/controller/src/main/java/ai/starwhale/mlops/api/ProjectController.java
- server/controller/src/main/java/ai/starwhale/mlops/api/protocol/project/ProjectRequest.java
- server/controller/src/main/java/ai/starwhale/mlops/api/protocol/project/ProjectVO.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/project/ProjectConvertor.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/project/ProjectService.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/project/bo/Project.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/project/po/ProjectEntity.java
- server/controller/src/main/resources/db/migration/V00007__Add_project_des.sql
- server/controller/src/main/resources/mapper/ProjectMapper.xml
> feat(console): owner and description of project

- client/starwhale/api/_impl/data_store.py
> bug(datastore): fix scan table path argument error

- client/starwhale/api/_impl/dataset.py
- client/starwhale/base/bundle_copy.py
- client/starwhale/base/cloud.py
- client/starwhale/consts/__init__.py
- client/starwhale/core/dataset/dataset.py
- client/starwhale/core/dataset/model.py
- client/tests/base/test_copy.py
- related issue: https://github.com/star-whale/starwhale/issues/896
- `_meta.jsonl`  example
```json
{"id": 0, "data_uri": "data_ubyte_0.swds_bin", "data_format": "s", "data_offset": 0, "data_size": 4064, "data_origin": "n", "object_store_type": "l", "label": "\u0007"}
{"id": 1, "data_uri": "data_ubyte_0.swds_bin", "data_format": "s", "data_offset": 4064, "data_size": 4064, "data_origin": "n", "object_store_type": "l", "label": "\u0002"}
```
- dataset upload
- _meta.jsonl file
> feat(dataset): support dataset copy with datastore meta load/dump

- client/starwhale/api/_impl/dataset.py
- client/starwhale/api/_impl/loader.py
- client/starwhale/base/store.py
related: https://github.com/star-whale/starwhale/pull/918#discussion_r948612586
> chore(client): remove deprecated abstractproperty

- server/controller/src/main/java/ai/starwhale/mlops/common/util/JwtTokenUtil.java
- server/controller/src/main/java/ai/starwhale/mlops/configuration/security/JobTokenConfig.java
- server/controller/src/main/java/ai/starwhale/mlops/schedule/k8s/K8sTaskScheduler.java
- server/controller/src/main/resources/application.yaml
- server/storage-access-layer/src/main/java/ai/starwhale/mlops/storage/fs/S3Env.java
- add job token env for job 
- add storage env for job
> feat(controller): add job token & storage env for job 

- client/starwhale/api/_impl/model.py
- client/starwhale/base/bundle.py
- client/starwhale/base/tag.py
- client/starwhale/base/uri.py
- client/starwhale/base/view.py
- client/starwhale/core/eval/executor.py
- client/starwhale/core/project/view.py
- client/starwhale/utils/__init__.py
- client/starwhale/utils/config.py
- client/starwhale/utils/http.py
> chore(client): add typing hint for python lambda

- scripts/apitest/pytest/test_project.py
- server/controller/src/main/java/ai/starwhale/mlops/api/ProjectApi.java
- server/controller/src/main/java/ai/starwhale/mlops/api/ProjectController.java
- server/controller/src/main/java/ai/starwhale/mlops/api/protocol/project/CreateProjectRequest.java
- server/controller/src/main/java/ai/starwhale/mlops/api/protocol/project/UpdateProjectRequest.java
- server/controller/src/main/java/ai/starwhale/mlops/common/util/HttpUtil.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/project/ProjectService.java
- server/controller/src/main/resources/db/migration/V00009__Add_project_privacy.sql
- server/controller/src/main/resources/mapper/ProjectRoleMapper.xml
- server/controller/src/test/java/ai/starwhale/mlops/common/util/HttpUtilTest.java
> fix(console): fix bug & add pytest for project api

- server/controller/src/main/java/ai/starwhale/mlops/domain/job/converter/JobConvertor.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/system/resourcepool/ResourcePoolConverter.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/system/resourcepool/bo/ResourcePool.java
It may get NPE when the new program runs with the old data.
> fix(controller): make resource pool feature compatible with the old data

- server/controller/src/main/resources/template/job.yaml
Use offical awscli to support arm64 arch device
> chore(controller): use offical awscli to support arm64 arch device

- server/controller/src/main/java/ai/starwhale/mlops/datastore/WalManager.java
- server/controller/src/main/java/ai/starwhale/mlops/objectstore/impl/FileSystemObjectStore.java
- server/controller/src/test/java/ai/starwhale/mlops/datastore/WalManagerTest.java
> feat(datastore): do not compress write ahead log file in case compression fails

- server/controller/src/main/java/ai/starwhale/mlops/domain/swds/upload/SwdsUploader.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/swmp/SWModelPackageService.java
- fix dataset/model copy error
> fix(controller): fix dataset/model copy error

- server/controller-sdk/src/main/java/ai/starwhale/mlops/api/protocol/report/resp/TaskRequest.java
- server/controller/src/main/java/ai/starwhale/mlops/configuration/security/JobTokenConfig.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/split/JobSpliteratorEvaluation.java
- server/controller/src/main/java/ai/starwhale/mlops/schedule/k8s/K8sTaskScheduler.java
- fix instance token bug
- fix dataset uri env bug
- fix dataset key prefix bug
> fix(controller): fix integeration test bugs

- client/starwhale/api/_impl/dataset/builder.py
- example/mnist/dataset.yaml
- fix label size for dataset builder
- update mnist example default process
> bug(dataset): fix dataset label size calculate

- server/controller/src/main/java/ai/starwhale/mlops/domain/runtime/RuntimeService.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/swds/upload/SwdsUploader.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/swmp/SWModelPackageService.java
- server/controller/src/main/java/ai/starwhale/mlops/objectstore/impl/S3ObjectStore.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/swds/SwdsUploaderTest.java
- server/storage-access-layer/src/main/java/ai/starwhale/mlops/storage/StorageAccessService.java
- server/storage-access-layer/src/main/java/ai/starwhale/mlops/storage/s3/StorageAccessServiceS3.java
Fix the problem of generating empty WAL files when DataStore uses object storage
The empty WAL file causes a starting problem acting like
```
Caused by: ai.starwhale.mlops.exception.SWProcessException: ERROR occurs while dealing with DATASTORE
at ai.starwhale.mlops.datastore.WalManager$1.getNext(WalManager.java:157) ~[classes!/:0.1.0-SNAPSHOT]
at ai.starwhale.mlops.datastore.WalManager$1.next(WalManager.java:129) ~[classes!/:0.1.0-SNAPSHOT]
at ai.starwhale.mlops.datastore.WalManager$1.next(WalManager.java:113) ~[classes!/:0.1.0-SNAPSHOT]
```
> fix(controller): fix the problem of generating empty WAL files when DataStore uses object storage

- client/starwhale/api/_impl/metric.py
- client/starwhale/api/_impl/model.py
- client/starwhale/api/_impl/wrapper.py
- client/starwhale/core/eval/model.py
- client/starwhale/core/eval/view.py
1. cmp metrics use multi table store
2. solve the cmd `swcli eval info {version}`  display problem
> fix(client): cmp results use multi table in datastore

- server/controller/src/main/java/ai/starwhale/mlops/common/RegExps.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/converter/JobBoConverter.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/runtime/RuntimeService.java
- populate runtime image to task
people could overwirte `runtime_version.manifest` in mysql to do debug
> feat(controller): populate runtime image to task

- server/controller/src/main/java/ai/starwhale/mlops/schedule/k8s/K8sClient.java
- server/controller/src/main/java/ai/starwhale/mlops/schedule/k8s/K8sTaskScheduler.java
- server/controller/src/main/resources/template/job.yaml
Remove useless result-uploader container.
Make the real worker as the main container.
> chore(deploy): remove useless result-uploader container

- server/controller/src/main/java/ai/starwhale/mlops/objectstore/impl/S3ObjectStore.java
Close `InputStream` after using s3.get
> fix(datastore): close inputstream after using s3.get

- server/controller/src/main/java/ai/starwhale/mlops/domain/job/converter/JobBoConverter.java
Use manifest field as the runtime image.
> fix(controller): use manifest field as the runtime image

- server/controller/src/main/java/ai/starwhale/mlops/datastore/WalManager.java
> fix(datastore): keep retrying to write WAL even if terminated

- client/starwhale/core/dataset/cli.py
- client/starwhale/core/dataset/view.py
- client/starwhale/core/eval/cli.py
- client/starwhale/core/eval/model.py
- client/starwhale/core/eval/view.py
- client/starwhale/core/model/cli.py
- client/starwhale/core/model/view.py
- client/starwhale/core/runtime/process.py
- add `--runtime` for the model build, the reason is gen_steps will import user [code](https://github.com/star-whale/starwhale/blob/main/client/starwhale/api/_impl/job.py#L154).
- tune `--runtime-restore` argument, when detecting the venv or conda dir is invalid, the command will restore runtime automatically.
- related: https://github.com/star-whale/starwhale/issues/1063
> feat(model): support `--runtime` argument for model build and auto restore runtime

- server/controller/src/main/java/ai/starwhale/mlops/domain/evaluation/EvaluationService.java
Access the evaluation list when the job is unfinished, the status will be cached, and never update until controller restart.
> fix(controller): do not cache unfinished evaluation

- server/controller/src/main/resources/mapper/ProjectMapper.xml
> fix(controller): evaluation counts include all of jobs

- server/controller/src/main/java/ai/starwhale/mlops/domain/user/UserService.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/user/mapper/UserMapper.java
- server/controller/src/main/resources/mapper/UserMapper.xml
> fix(controller): exception that occurs when the register_info does not exist

- client/starwhale/api/_impl/data_store.py
- client/tests/sdk/test_base.py
> enhance(client): use destructor instead of atexit

- client/starwhale/core/eval/executor.py
- client/starwhale/core/job/scheduler.py
- client/starwhale/core/model/model.py
- client/starwhale/core/model/view.py
> fix(sdk): single task execute status bug again

- .github/workflows/client.yaml
> ci(standalone): replace standalone test coverage viewer with codecov

- client/setup.py
- client/starwhale/api/_impl/data_store.py
- client/starwhale/api/_impl/wrapper.py
- client/tests/sdk/test_data_store.py
- client/tests/sdk/test_wrapper.py
- When the TableWriter runs thread raises an Exception, the main thread can handle it.
- add retry for update_table for remote store
> enhance(datastore): tune TableWriter run thread exception handler

- client/starwhale/api/_impl/data_store.py
- client/starwhale/base/cloud.py
- client/starwhale/utils/retry.py
- client/tests/sdk/test_data_store.py
- client/tests/sdk/test_wrapper.py
- client/tests/utils/test_common.py
> enhance(client): add http_retry decorator

- server/controller/src/main/java/ai/starwhale/mlops/api/protocol/runtime/RuntimeVersionVO.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/converter/JobBoConverter.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/runtime/RuntimeService.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/runtime/RuntimeVersionConvertor.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/runtime/po/RuntimeVersionEntity.java
- server/controller/src/main/resources/db/migration/V00016__alter_manifest_2_image.sql
- server/controller/src/main/resources/mapper/RuntimeVersionMapper.xml
rename `manifest` field of `runtime` to `image` to make the semantic clear
> refactor(controller): rename manifest field of runtime to image

- server/controller/src/main/java/ai/starwhale/mlops/api/protocol/user/UserVO.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/user/UserConvertor.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/user/UserService.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/user/mapper/UserMapper.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/user/po/UserEntity.java
- server/controller/src/main/resources/mapper/UserMapper.xml
in current business context , `email ` info only exists for saas users. Email related code should not be present in community version. The front end should get saas user information using saas API `profile`( pr: https://github.com/star-whale/cloud-registration/pull/38)
> refactor(controller): remove email field of user

- console/src/api/ApiHeader.tsx
- console/src/api/Auth.tsx
- console/src/api/index.ts
- console/src/domain/datastore/hooks/useFetchDatastore.ts
- console/src/pages/Dataset/DatasetVersionOverviewFiles.tsx
- console/src/pages/Home/Login.tsx
- console/src/pages/Project/ProjectSidebar.tsx
- console/src/pages/Runtime/RuntimeVersionListCard.tsx
> fix(console): prevent  extra interceptors in strict mode

- server/controller/src/main/java/ai/starwhale/mlops/api/DataStoreController.java
- server/controller/src/main/java/ai/starwhale/mlops/api/protocol/datastore/QueryTableRequest.java
- server/controller/src/main/java/ai/starwhale/mlops/datastore/DataStore.java
- server/controller/src/main/java/ai/starwhale/mlops/datastore/DataStoreQueryRequest.java
- server/controller/src/main/java/ai/starwhale/mlops/datastore/DataStoreScanRequest.java
- server/controller/src/test/java/ai/starwhale/mlops/datastore/DataStoreTest.java
Allow non existing table when query or scan
cc @tianweidut @waynelwz
> chore(datastore): allow non existing table when query or scan

- server/controller/src/main/java/ai/starwhale/mlops/api/ProjectController.java
- server/controller/src/main/java/ai/starwhale/mlops/api/protocol/user/ProjectRoleVO.java
- server/controller/src/main/java/ai/starwhale/mlops/api/protocol/user/RoleVO.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/project/ProjectConvertor.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/project/ProjectManager.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/project/ProjectRoleConvertor.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/project/ProjectService.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/project/bo/Project.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/project/mapper/ProjectMapper.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/project/mapper/ProjectRoleMapper.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/user/RoleConvertor.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/user/UserConvertor.java
- server/controller/src/test/java/ai/starwhale/mlops/api/ProjectControllerTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/project/ProjectConvertorTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/project/ProjectManagerTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/project/ProjectRoleConvertorTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/project/ProjectServiceTest.java
> test(controller): unit test for project classes and some tiny change

- .github/workflows/e2e-test.yml
- docker/Makefile
- scripts/e2e_test/start_test.sh
- scripts/e2e_test/test_job_run.sh
tested on [forked repo](https://github.com/anda-ren/starwhale/runs/8219783754?check_suite_focus=true) 
- people could trigger e2e test manually if needed
- people could open a debug session when trigger it manually
> ci(e2e): restore broken e2e test

- server/controller/src/main/java/ai/starwhale/mlops/datastore/WalManager.java
- server/controller/src/main/resources/application.yaml
- server/controller/src/test/java/ai/starwhale/mlops/datastore/DataStoreTest.java
- server/controller/src/test/java/ai/starwhale/mlops/datastore/WalManagerTest.java
- server/controller/src/test/java/ai/starwhale/mlops/datastore/impl/MemoryTableImplTest.java
- server/storage-access-layer/src/main/java/ai/starwhale/mlops/storage/s3/StorageAccessServiceS3.java
* disable chunked encoding
* ignore `NoSuchKeyException` when listing files
> enhance(datastore): compatible with ali oss

- client/starwhale/base/uri.py
> chore(client):Remove redundant URI parse logic

- server/pom.xml
- server/storage-access-layer/pom.xml
- server/storage-access-layer/src/test/java/ai/starwhale/mlops/storage/s3/StorageAccessServiceS3Test.java
> chore(controller): add unit test for StorageAccessServiceS3

- server/controller/src/main/java/ai/starwhale/mlops/api/DataStoreController.java
- server/controller/src/main/java/ai/starwhale/mlops/api/protocol/datastore/ScanTableRequest.java
- server/controller/src/test/java/ai/starwhale/mlops/api/DataStoreControllerTest.java
> fix(datastore): add ignoreNonExistingTable option for scan table

- server/controller/src/main/java/ai/starwhale/mlops/api/UserController.java
- server/controller/src/main/java/ai/starwhale/mlops/api/protocol/user/SystemRoleVo.java
- server/controller/src/main/java/ai/starwhale/mlops/api/protocol/user/UserRoleVo.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/user/SystemRoleConvertor.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/user/UserRoleConvertor.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/user/UserService.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/user/mapper/RoleMapper.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/user/mapper/UserMapper.java
- server/controller/src/test/java/ai/starwhale/mlops/api/UserControllerTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/user/RoleConvertorTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/user/SaltGeneratorTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/user/SystemRoleConvertorTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/user/UserConvertorTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/user/UserRoleConvertorTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/user/UserServiceTest.java
> test(controller): unit test for user classes and some tiny change

- console/src/domain/job/schemas/task.tsx
- console/src/pages/Job/TaskListCard.tsx
- server/controller/src/main/java/ai/starwhale/mlops/api/protocol/task/TaskVo.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/system/mapper/ResourcePoolMapper.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/task/TaskService.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/task/converter/TaskConvertor.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/task/mapper/TaskMapper.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/task/TestTaskService.java
> fix: Change the field of task table

- server/controller/src/main/java/ai/starwhale/mlops/domain/swds/objectstore/StorageAccessParser.java
- server/controller/src/main/resources/application.yaml
- server/controller/src/test/java/ai/starwhale/mlops/schedule/k8s/TestK8sTaskScheduler.java
- server/storage-access-layer/pom.xml
- server/storage-access-layer/src/main/java/ai/starwhale/mlops/storage/s3/S3Config.java
- server/storage-access-layer/src/main/java/ai/starwhale/mlops/storage/s3/StorageAccessServiceS3.java
- server/storage-access-layer/src/test/java/ai/starwhale/mlops/storage/s3/StorageAccessServiceS3Test.java
- server/storage-access-layer/src/test/resources/logback-test.xml
> enhance(controller): use s3 multipart upload for huge file

- client/starwhale/core/eval/executor.py
- client/starwhale/core/eval/model.py
- client/tests/core/test_eval.py
- client/tests/core/test_executor.py
> fix(client): add label for container and cancel by label

- server/controller/src/main/java/ai/starwhale/mlops/datastore/ObjectStore.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/swds/objectstore/StorageAccessParser.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/swds/objectstore/StorageAuths.java
- server/controller/src/main/resources/application.yaml
- server/controller/src/test/java/ai/starwhale/mlops/domain/swds/SwdsUploaderTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/swds/objectstore/TestDsFileGetter.java
- server/controller/src/test/java/ai/starwhale/mlops/resulting/ResultQuerierTest.java
- server/pom.xml
- server/storage-access-layer/pom.xml
- server/storage-access-layer/src/main/java/ai/starwhale/mlops/storage/LengthAbleInputStream.java
- server/storage-access-layer/src/main/java/ai/starwhale/mlops/storage/StorageAccessService.java
- server/storage-access-layer/src/main/java/ai/starwhale/mlops/storage/aliyun/StorageAccessServiceAliyun.java
- server/storage-access-layer/src/main/java/ai/starwhale/mlops/storage/configuration/StorageAccessConfig.java
- server/storage-access-layer/src/main/java/ai/starwhale/mlops/storage/fs/FileStorageEnv.java
- server/storage-access-layer/src/main/java/ai/starwhale/mlops/storage/fs/StorageAccessServiceFile.java
- server/storage-access-layer/src/main/java/ai/starwhale/mlops/storage/s3/StorageAccessServiceS3.java
- server/storage-access-layer/src/main/java/ai/starwhale/mlops/storage/util/MetaHelper.java
> feat(controller): support aliyun oss

- client/starwhale/core/dataset/store.py
- server/storage-access-layer/src/main/java/ai/starwhale/mlops/storage/configuration/StorageProperties.java
- server/storage-access-layer/src/main/java/ai/starwhale/mlops/storage/fs/AliyunEnv.java
- server/storage-access-layer/src/main/java/ai/starwhale/mlops/storage/fs/BotoS3Config.java
- server/storage-access-layer/src/main/java/ai/starwhale/mlops/storage/fs/FileStorageEnv.java
- server/storage-access-layer/src/main/java/ai/starwhale/mlops/storage/fs/S3Env.java
- server/storage-access-layer/src/test/java/ai/starwhale/mlops/storage/fs/AliyunEnvTest.java
- server/storage-access-layer/src/test/java/ai/starwhale/mlops/storage/fs/BotoS3ConfigTest.java
- server/storage-access-layer/src/test/java/ai/starwhale/mlops/storage/fs/S3EnvTest.java
Resolve the virtual host issue
ref: https://help.aliyun.com/document_detail/64919.html
Relates to #1157
```
File "/opt/starwhale/swmp/export/venv/lib/python3.8/site-packages/botocore/client.py", line 745, in _make_api_call
raise error_class(parsed_response, operation_name)
│           │                └ 'GetObject'
│           └ {'Error': {'Code': 'SecondLevelDomainForbidden', 'Message': 'Please use virtual hosted style to access.'}, 'ResponseMetadata'...
└ <class 'botocore.exceptions.ClientError'>
botocore.exceptions.ClientError: An error occurred (SecondLevelDomainForbidden) when calling the GetObject operation: Please use virtual hosted style to access.
```
> enhance(controller): support virtual host path configuration

- server/controller/src/main/java/ai/starwhale/mlops/datastore/ColumnSchema.java
- server/controller/src/main/java/ai/starwhale/mlops/datastore/ColumnType.java
- server/controller/src/main/java/ai/starwhale/mlops/datastore/impl/MemoryTableImpl.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/swds/index/datastore/IndexWriter.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/swds/datastore/TestIndexWriter.java
> chore(controller): use static constants instead of enum in order to support future complex types

- server/controller/src/main/java/ai/starwhale/mlops/schedule/k8s/K8sTaskScheduler.java
- server/controller/src/main/resources/template/job.yaml
- server/controller/src/test/java/ai/starwhale/mlops/schedule/k8s/TestK8sTaskScheduler.java
- server/storage-access-layer/src/main/java/ai/starwhale/mlops/storage/configuration/StorageProperties.java
> enhance(controller): data provider in job support virtual host path

- client/starwhale/core/model/model.py
> fix(client):exit error code when failed

- server/controller/src/main/java/ai/starwhale/mlops/api/DataStoreController.java
- server/controller/src/main/java/ai/starwhale/mlops/datastore/ColumnType.java
- server/controller/src/main/java/ai/starwhale/mlops/datastore/TableQueryFilter.java
- server/controller/src/main/java/ai/starwhale/mlops/datastore/impl/MemoryTableImpl.java
- server/controller/src/test/java/ai/starwhale/mlops/api/DataStoreControllerTest.java
- server/controller/src/test/java/ai/starwhale/mlops/datastore/DataStoreTest.java
- server/controller/src/test/java/ai/starwhale/mlops/datastore/impl/MemoryTableImplTest.java
> chore(datastore): use explicit typing in query instead of guessing type from actual column value

- server/controller/src/main/java/ai/starwhale/mlops/api/DataStoreController.java
- server/controller/src/main/java/ai/starwhale/mlops/api/protocol/datastore/RecordListVo.java
- server/controller/src/main/java/ai/starwhale/mlops/datastore/RecordList.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/swds/index/datastore/IndexWriter.java
- server/controller/src/test/java/ai/starwhale/mlops/api/DataStoreControllerTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/swds/datastore/TestIndexWriter.java
> fix(controller): use type string name other than category

- client/starwhale/core/dataset/tabular.py
> bug(dataset): fix dataset rows diff error

- console/src/domain/project/components/ProjectForm.tsx
> fix(console): #1139 owner when editing project

- scripts/e2e_test/start_test.sh
increase minikube memory limit to 4G from 2G
> fix(ci): increase minikube memory limit to 4G

- server/controller/src/main/java/ai/starwhale/mlops/api/JobController.java
- server/controller/src/main/java/ai/starwhale/mlops/api/SystemController.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/BaseImageConvertor.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/JobManager.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/mapper/JobSwdsVersionMapper.java
- server/controller/src/test/java/ai/starwhale/mlops/api/JobControllerTest.java
- server/controller/src/test/java/ai/starwhale/mlops/api/LogControllerTest.java
- server/controller/src/test/java/ai/starwhale/mlops/api/SystemControllerTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/job/BaseImageConvertorTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/job/JobManagerTest.java
> test(controller): add unit tests

- server/controller/src/main/java/ai/starwhale/mlops/schedule/k8s/K8sClient.java
- server/controller/src/main/java/ai/starwhale/mlops/schedule/k8s/K8sClientConfig.java
- server/controller/src/main/java/ai/starwhale/mlops/schedule/k8s/NodeEventHandler.java
- server/controller/src/test/java/ai/starwhale/mlops/schedule/k8s/K8sClientTest.java
- server/controller/src/test/java/ai/starwhale/mlops/schedule/k8s/NodeEventHandlerTest.java
> chore(controller): add UT for K8S related code

- server/controller/src/main/java/ai/starwhale/mlops/configuration/security/SecurityMessageConfig.java
- server/pom.xml
> fix(controller): show security message in English

- client/starwhale/core/dataset/type.py
- client/tests/sdk/test_dataset.py
- example/PennFudanPed/pfp/dataset.py
> feat(dataset): add mask propteries for Dataset Image type

- server/controller/src/main/java/ai/starwhale/mlops/memory/SwBufferInputStream.java
- server/controller/src/test/java/ai/starwhale/mlops/memory/SwBufferInputStreamTest.java
> fix(datastore): can not load wal after restart

- client/starwhale/api/_impl/data_store.py
- client/starwhale/api/_impl/metric.py
- client/starwhale/api/_impl/model.py
- client/starwhale/core/eval/view.py
- client/tests/sdk/test_metric.py
> feat(job): tune eval info classification ui for standalone

- server/controller/src/main/java/ai/starwhale/mlops/datastore/DataStore.java
> fix(datastore): datastore table list out of bound error when invoke scan api

- client/starwhale/api/_impl/data_store.py
- client/starwhale/api/_impl/wrapper.py
- client/starwhale/core/eval/model.py
- client/starwhale/core/eval/view.py
- client/tests/core/test_eval.py
> fix(client):job info error at cloud instance

- server/controller/src/main/java/ai/starwhale/mlops/memory/impl/SwByteBuffer.java
- server/controller/src/test/java/ai/starwhale/mlops/memory/impl/SwByteBufferTest.java
> fix(datastore): fix copyTo/setBytes function of SwByteBuffer

- client/starwhale/core/runtime/process.py
- client/tests/core/test_runtime.py
> chore(client): add ut for client runtime

- client/starwhale/base/bundle.py
- client/starwhale/base/uri.py
- client/starwhale/base/view.py
- client/starwhale/core/dataset/model.py
- client/starwhale/core/dataset/view.py
- client/starwhale/core/model/model.py
- client/starwhale/core/model/view.py
- client/starwhale/core/runtime/model.py
- client/starwhale/core/runtime/view.py
- client/tests/core/test_dataset.py
- client/tests/core/test_model.py
- client/tests/core/test_runtime.py
- related issue: https://github.com/star-whale/starwhale/issues/1141
- model info for standalone
- ![image](https://user-images.githubusercontent.com/590748/190971651-cb45d6c8-4518-4bfb-b729-1dfa9f6731ab.png) 
- model info for cloud
-  ![image](https://user-images.githubusercontent.com/590748/190971913-d265ae0a-016c-45cf-9ec9-7bc648f73f19.png)
- dataset info for standalone
-   ![image](https://user-images.githubusercontent.com/590748/190972045-c2bee308-bb80-4591-939a-99bf4bb227f6.png)
- dataset info for cloud
-  ![image](https://user-images.githubusercontent.com/590748/190983041-a10c8c31-f6ea-40c6-90bb-eb85ccfa807a.png) 
- runtime info for standalone
- ![image](https://user-images.githubusercontent.com/590748/190983512-149251fc-72ab-4a22-af3f-b393ea803999.png) 
- runtime info for cloud
- …
> bug(client): fix model/dataset/runtime info command

- client/tests/core/test_eval.py
- client/tests/core/test_model.py
- client/tests/sdk/test_base.py
- client/tests/sdk/test_wrapper.py
- fix atexit error 
- reset `LocalStore._instance` single instance state which will inject the wrong variable by another test case.
> ci(client): fix datastore atexit dump test error

- server/controller/src/main/java/ai/starwhale/mlops/api/DatasetApi.java
> fix(controller): guest user has permission to see the resource in dataset

- client/starwhale/core/model/model.py
> fix(client): raise exception when error

- client/starwhale/api/_impl/model.py
> fix(client)：remove base64 encode/decode ppl result

- client/starwhale/base/bundle.py
- client/starwhale/base/view.py
- client/starwhale/core/dataset/model.py
- client/starwhale/core/dataset/view.py
- client/starwhale/core/eval/view.py
- client/starwhale/core/model/model.py
- client/starwhale/core/model/view.py
- client/starwhale/core/runtime/model.py
- client/starwhale/core/runtime/view.py
provide more user-friendly output for standalone commands.
> enhance(client): add only_standalone decorator for cli view

- server/storage-access-layer/src/main/java/ai/starwhale/mlops/storage/aliyun/StorageAccessServiceAliyun.java
- server/storage-access-layer/src/main/java/ai/starwhale/mlops/storage/s3/StorageAccessServiceS3.java
- server/storage-access-layer/src/test/java/ai/starwhale/mlops/storage/s3/StorageAccessServiceS3Test.java
**AWS S3**
https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListObjectsV2.html#API_ListObjectsV2_RequestSyntax
>  By default the action returns up to 1,000 key names.
The response might contain fewer keys but will never contain more
**aliyun oss**
https://github.com/aliyun/aliyun-oss-java-sdk/blob/a927e670955350ff78e1d0b58cb21538923ebf83/src/main/java/com/aliyun/oss/model/ListObjectsRequest.java#L158-L170
```java
/**
* Sets the max objects to return. By default it's 100, the max is 1000.
* 
* @param maxKeys
*            The max objects to return. The max value is 1000.
*/
public void setMaxKeys(Integer maxKeys) {
if (maxKeys < 0 || maxKeys > MAX_RETURNED_KEYS_LIMIT) {
throw new IllegalArgumentException(OSSUtils.OSS_RESOURCE_MANAGER.getString("MaxKeysOutOfRange"));
}
this.maxKeys = …
```
> fix(controller): oss list all keys

- server/controller/src/test/resources/template/job.yaml
`IfNotPresent` policy is changed to 'Always'
`IfNotPresent` policy is not well fitted for images like `ghcr.io/star-whale/starwhale:latest-cuda11.4` . [ `The caching semantics of the underlying image provider make even imagePullPolicy: Always efficient, as long as the registry is reliably accessible. Your container runtime can notice that the image layers already exist on the node so that they don't need to be downloaded again.`](https://kubernetes.io/docs/concepts/containers/images/)
> enhance(controller): tune imagePullPolicy for worker container

- client/starwhale/core/runtime/cli.py
- client/starwhale/core/runtime/model.py
- client/starwhale/core/runtime/view.py
- client/tests/core/test_runtime.py
> enhance(runtime): runtime quickstart will create workdir automatically

- client/starwhale/api/_impl/dataset/loader.py
- client/starwhale/api/_impl/model.py
- client/starwhale/base/bundle.py
- client/starwhale/core/dataset/model.py
- client/starwhale/core/dataset/view.py
> enhance(client): tune model/dataset/model not-found info output

- client/starwhale/core/runtime/cli.py
- client/starwhale/core/runtime/model.py
- client/tests/core/test_runtime.py
> bug(runtime): fix dockerize tag tuple typo

- server/controller/src/main/java/ai/starwhale/mlops/api/protocol/user/UserVo.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/user/UserService.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/user/UserServiceTest.java
> feat(controller): add system role and project roles in the response of getting current user

- server/controller/src/main/java/ai/starwhale/mlops/api/protocol/evaluation/SummaryVo.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/evaluation/EvaluationService.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/evaluation/EvaluationServiceTest.java
> feat(controller): add job status to evaluation summary

- client/starwhale/api/_impl/data_store.py
- client/starwhale/api/_impl/wrapper.py
- client/tests/sdk/test_data_store.py
- client/tests/sdk/test_wrapper.py
> refactor(datastore): remove wrapper project and eval_version useless env

- client/starwhale/base/bundle.py
- client/starwhale/base/store.py
- client/starwhale/core/dataset/cli.py
- client/starwhale/core/dataset/model.py
- client/starwhale/core/eval/cli.py
- client/starwhale/core/eval/model.py
- client/starwhale/core/model/cli.py
- client/starwhale/core/model/model.py
- client/starwhale/core/model/store.py
- client/starwhale/core/runtime/cli.py
- client/starwhale/core/runtime/model.py
- client/starwhale/core/runtime/store.py
- client/tests/core/test_dataset.py
- client/tests/core/test_eval.py
- client/tests/core/test_model.py
- client/tests/core/test_runtime.py
use `--force` to remove objects directly which cannot recover.
> feat(client): support force remove for model/dataset/runtime/eval

- example/PennFudanPed/pfp/ppl.py
- example/PennFudanPed/pfp/train.py
- example/PennFudanPed/pfp/utils/coco_eval.py
> enhance(example): tune pfp example ppl results

- client/starwhale/core/dataset/model.py
- client/starwhale/core/dataset/type.py
- client/tests/core/test_dataset.py
- client/tests/data/dataset.yaml
- client/tests/data/dataset/dataset.yaml
- example/PennFudanPed/dataset.yaml
- example/cifar10/dataset.yaml
- example/mnist/dataset.yaml
- example/mnist/mnist/dataset.py
- example/nmt/dataset.yaml
- example/speech_command/dataset.yaml
- example/text_cls_AG_NEWS/dataset.yaml
use the more common name to express dataset processor
> chore(dataset): refactor dataset process name to handler

- server/controller/src/main/java/ai/starwhale/mlops/domain/project/ProjectManager.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/project/ProjectService.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/project/mapper/ProjectMapper.java
- server/controller/src/main/resources/db/migration/V00019__Modify_project_index.sql
- server/controller/src/main/resources/mapper/ProjectMapper.xml
- server/controller/src/test/java/ai/starwhale/mlops/domain/project/ProjectManagerTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/project/ProjectServiceTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/project/mapper/ProjectMapperTest.java
> fix(controller): add unique index on project name

- server/controller/src/main/java/ai/starwhale/mlops/domain/task/status/WatchableTask.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/task/status/watchers/TaskWatcherForSchedule.java
> fix(controller): delay deletion of failed job now works

- server/controller/src/main/java/ai/starwhale/mlops/api/SwModelPackageController.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/swmp/SwmpConvertor.java
- server/controller/src/test/java/ai/starwhale/mlops/api/SwModelPackageControllerTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/swmp/SwmpConvertorTest.java
> test(controller): unit test for swmp controller and convertor

- client/scripts/sw-docker-entrypoint
- client/starwhale/base/type.py
- client/starwhale/core/eval/executor.py
- client/tests/core/test_executor.py
related: https://github.com/star-whale/starwhale/pull/1292
> enhance(job): refactor sw-docker-entrypiont with split swmp and swrt workdir

- server/controller/src/main/java/ai/starwhale/mlops/api/protocol/datastore/QueryTableRequest.java
- server/controller/src/main/java/ai/starwhale/mlops/api/protocol/datastore/ScanTableRequest.java
- server/controller/src/main/java/ai/starwhale/mlops/datastore/DataStore.java
- server/controller/src/test/java/ai/starwhale/mlops/api/DataStoreControllerTest.java
> fix(controller):set datastore api param 'ignoreNonExistingTable'=true

- server/controller/src/main/java/ai/starwhale/mlops/api/DatasetController.java
- server/controller/src/main/java/ai/starwhale/mlops/api/RuntimeController.java
- server/controller/src/main/java/ai/starwhale/mlops/api/protocol/runtime/RuntimeVo.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/runtime/RuntimeConvertor.java
- server/controller/src/test/java/ai/starwhale/mlops/api/DatasetControllerTest.java
- server/controller/src/test/java/ai/starwhale/mlops/api/RuntimeControllerTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/runtime/RuntimeConvertorTest.java
> test(controller): unit test for dataset and runtime controller

- .github/workflows/client.yaml
- https://github.com/python/mypy/issues/13627
- random error: https://github.com/star-whale/starwhale/actions/runs/3111623281/jobs/5044398877
-  ![image](https://user-images.githubusercontent.com/590748/191948489-2219e06a-6d12-4a4d-9be5-ca478f8cdfd8.png)
> ci: set fixed python3.10 version to workaround mypy error

- server/controller/src/main/java/ai/starwhale/mlops/schedule/k8s/K8sJobTemplate.java
- server/controller/src/main/resources/application.yaml
- server/controller/src/test/java/ai/starwhale/mlops/schedule/k8s/K8sJobTemplateTest.java
- server/controller/src/test/java/ai/starwhale/mlops/schedule/k8s/K8sTaskSchedulerTest.java
Make host path for pip cache optional
> chore(controller): make host path for pip cache optional

- scripts/client_test/cli_test.py
- scripts/e2e_test/start_test.sh
> fix(e2e):add memory for e2e

- console/src/components/DAG/DAG.tsx
> enhance(console): make dag layout fitable

- console/package.json
- console/yarn.lock
Fix CI issue
https://github.com/star-whale/starwhale/actions/runs/3209393519/jobs/5246068593
```
yarn lint
yarn run v1.22.19
$ eslint -c .eslintrc.js './src/**/*.{ts,tsx}'
Done in 31.9[5](https://github.com/star-whale/starwhale/actions/runs/3209393519/jobs/5246068593#step:8:6)s.
yarn typecheck
yarn run v1.22.19
$ tsc --noEmit -p ./tsconfig.json
This is not the tsc command you are looking for                
To get access to the TypeScript compiler, tsc, from the command line either:
- Use npm install typescript to first add TypeScript to your project before using npx
- Use yarn to avoid accidentally running code from un-installed packages
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
make: *** …
```
> fix(console): remove tsc from package

- client/Makefile
- client/starwhale/api/_impl/dataset/builder.py
- client/tests/base/test_copy.py
- client/tests/base/test_uri.py
- client/tests/core/test_dataset.py
- client/tests/core/test_eval.py
- client/tests/core/test_executor.py
- client/tests/core/test_instance.py
- client/tests/core/test_job.py
- client/tests/core/test_model.py
- client/tests/core/test_project.py
- client/tests/sdk/test_dataset.py
- client/tests/sdk/test_loader.py
- client/tests/sdk/test_model.py
- client/tests/utils/test_config.py
> chore(client): make client ut stable

- client/starwhale/__init__.py
- client/tests/sdk/test_loader.py
- client/tests/sdk/test_model.py
- docs/docs/reference/sdk/data_type.md
- docs/docs/reference/sdk/dataset.md
- docs/docs/reference/sdk/evaluation.md
- docs/docs/reference/sdk/other.md
- docs/docs/reference/sdk/overview.md
- docs/i18n/zh/docusaurus-plugin-content-docs/current/reference/cli/model.md
- docs/i18n/zh/docusaurus-plugin-content-docs/current/reference/sdk/data_type.md
- docs/i18n/zh/docusaurus-plugin-content-docs/current/reference/sdk/dataset.md
- docs/i18n/zh/docusaurus-plugin-content-docs/current/reference/sdk/evaluation.md
- docs/i18n/zh/docusaurus-plugin-content-docs/current/reference/sdk/other.md
- docs/i18n/zh/docusaurus-plugin-content-docs/current/reference/sdk/overview.md
- docs/sidebars.js
- add sdk doc
- export `URI` and `URIType`
> doc: add python sdk zh-doc

- client/starwhale/core/runtime/model.py
- client/starwhale/utils/venv.py
- client/tests/core/test_runtime.py
- example/runtime/pytorch/runtime.yaml
* Use current python version (swcli) when python version not specified in runtime.yaml 
* Remove python version in pytorch runtime.yaml in example
> chore(client): use sys.ver when python version not specified in runtime.yaml

- client/Makefile
- client/pyproject.toml
- client/starwhale/api/_impl/dataset/builder.py
- client/starwhale/utils/venv.py
- fix mypy exclude typo: ignore some unexpected files
- fix code lint error
> bug(client): fix mypy exclude typo and some code lint error 

- client/starwhale/api/_impl/dataset/builder.py
- client/tests/sdk/test_dataset.py
- add swds-bin build copy_file test
- fix missing_ok argument
> bug(client): fix pathlib.unlink missing_ok argument error in python3.7

- server/controller/src/main/java/ai/starwhale/mlops/api/JobController.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/dag/DagQuerier.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/JobService.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/cache/HotJobsLoader.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/cache/JobLoader.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/converter/JobBoConverter.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/split/JobSpliterator.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/split/JobSpliteratorEvaluation.java
- server/controller/src/main/resources/application.yaml
- server/controller/src/test/java/ai/starwhale/mlops/domain/dag/DagQuerierTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/job/JobBoConverterTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/job/JobLoaderTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/job/JobServiceTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/job/JobSpliteratorEvaluationTest.java
job status become unknown when it's DAG is queried before job is split
- decouple job status update from `JobLoader`
- move step link opt from `JobLoader` to `JobBoConverter`
> fix(controller): fix job status is unknown occasionally

- client/starwhale/core/job/model.py
- client/starwhale/core/job/scheduler.py
1. terminal execute process when step failure
2. add log trace print ![image](https://user-images.githubusercontent.com/24869618/195540182-0ea181fd-0d84-4c45-a82e-0d8f22cb3c59.png)
> fix(client): terminal execute process on failure

- .github/workflows/client.yaml
- client/tests/core/test_runtime.py
- client/tests/core/test_runtime_process.py
- client/tests/sdk/test_dataset.py
- scripts/run_demo.sh
Unit test works with macOS
* symlink can not work with virtualenv (not only in macOS)
* temp dir under macOS is like `/var/folders/xx/xxxxxxxxxxxxxxxx/X/`, not `/tmp/`
* macOS use a symlink temp dir for users
mnist demo can not run under macOS for now, will fix it in further PR.
> fix(client): unit test works with macos

- client/starwhale/api/_impl/data_store.py
- client/tests/sdk/test_data_store.py
> fix(statsotre):  hex str encode/decode error when value miss "0"

- client/starwhale/core/runtime/model.py
- client/tests/core/test_runtime.py
- docs/i18n/zh/docusaurus-plugin-content-docs/current/guides/runtime.md
Support specifying docker image env in runtime.yaml
> chore(client): support specifying docker image env in runtime.yaml

- client/starwhale/consts/__init__.py
- client/starwhale/core/runtime/process.py
- client/starwhale/utils/debug.py
- client/starwhale/utils/process.py
- client/tests/utils/test_process.py
related: https://github.com/star-whale/starwhale/issues/1378
- realtime output
- use the external verbose argument for runtime subprocess
> enhance(client): tune runtime process logger with the external swcli verbose setting

- Makefile
- client/starwhale/cli/__init__.py
- client/starwhale/cli/completion.py
- client/starwhale/core/dataset/cli.py
- client/starwhale/core/eval/cli.py
- client/starwhale/core/instance/cli.py
- client/starwhale/core/model/cli.py
- client/starwhale/core/project/cli.py
- client/starwhale/core/runtime/cli.py
- client/starwhale/utils/cli.py
- client/tests/utils/test_cli.py
- docs/i18n/zh/docusaurus-plugin-content-docs/current/reference/cli/basic.md
- docs/i18n/zh/docusaurus-plugin-content-docs/current/reference/cli/dataset.md
- docs/i18n/zh/docusaurus-plugin-content-docs/current/reference/cli/eval.md
- docs/i18n/zh/docusaurus-plugin-content-docs/current/reference/cli/instance.md
- docs/i18n/zh/docusaurus-plugin-content-docs/current/reference/cli/model.md
- docs/i18n/zh/docusaurus-plugin-content-docs/current/reference/cli/project.md
- docs/i18n/zh/docusaurus-plugin-content-docs/current/reference/cli/runtime.md
https://github.com/star-whale/starwhale/issues/1364
[![asciicast](https://asciinema.org/a/529704.svg)](https://asciinema.org/a/529704)
> enhance(client): add aliases for swcli commands

- scripts/publish/pub.sh
> fix(ci): fix e2e not use pypi repo

- server/controller/src/main/java/ai/starwhale/mlops/schedule/k8s/K8sTaskScheduler.java
- server/controller/src/main/java/ai/starwhale/mlops/schedule/k8s/ResourceOverwriteSpec.java
- server/controller/src/test/java/ai/starwhale/mlops/schedule/k8s/K8sTaskSchedulerTest.java
Do not expose GPU to the job which requires no GPU
https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/user-guide.html#gpu-enumeration
> chore(controller): do not expose GPU to the job which requires no GPU

- client/starwhale/utils/config.py
- client/tests/base/test_uri.py
- client/tests/data/config.yaml
- client/tests/utils/test_config.py
> fix(client): get instance wrong when multi instances has the same uri

- .github/workflows/docs.yaml
- docs/Makefile
- docs/docs/guides/install/docker.md
- docs/i18n/zh/docusaurus-plugin-content-docs/current/guides/install/docker.md
- docs/package.json
- docs/sidebars.js
Starwhale controller deployment with docker
> doc: starwhale controller deployment with docker

- .gitignore
- client/starwhale/core/dataset/type.py
- example/datasets/cifar100/Makefile
- example/datasets/cifar100/README.md
- example/datasets/cifar100/dataset.py
- example/datasets/cifar100/example.py
https://github.com/star-whale/starwhale/issues/760
> example: add cifar100 dataset

- scripts/e2e_test/start_test.sh
allow `SW_PYPI_EXTRA_INDEX_URL` be override by env var
> chore: allow `SW_PYPI_EXTRA_INDEX_URL` be override by env var

- client/Makefile
- example/datasets/emnist/Makefile
- example/datasets/emnist/README.md
- example/datasets/emnist/dataset.py
- example/datasets/emnist/example.py
- example/datasets/emnist/requirements.txt
https://cloud.starwhale.cn/projects/14/datasets/5/versions/22/files
> example: add emnist dataset

- client/starwhale/base/type.py
- client/starwhale/core/runtime/model.py
- client/starwhale/utils/fs.py
- client/starwhale/utils/venv.py
- client/tests/core/test_runtime.py
- client/tests/utils/test_fs.py
- example/runtime/pytorch/runtime.yaml
- related: https://github.com/star-whale/starwhale/issues/780
- [![asciicast](https://asciinema.org/a/534239.svg)](https://asciinema.org/a/534239)
> enhance(runtime): refactor runtime dependencies with user original sequence

- server/controller/pom.xml
- server/controller/src/main/java/ai/starwhale/mlops/datastore/ColumnSchema.java
- server/controller/src/main/java/ai/starwhale/mlops/datastore/ColumnType.java
- server/controller/src/main/java/ai/starwhale/mlops/datastore/ColumnTypeList.java
- server/controller/src/main/java/ai/starwhale/mlops/datastore/ColumnTypeObject.java
- server/controller/src/main/java/ai/starwhale/mlops/datastore/ColumnTypeScalar.java
- server/controller/src/main/java/ai/starwhale/mlops/datastore/ParquetConfig.java
- server/controller/src/main/java/ai/starwhale/mlops/datastore/TableSchema.java
- server/controller/src/main/java/ai/starwhale/mlops/datastore/WalManager.java
- server/controller/src/main/java/ai/starwhale/mlops/datastore/impl/MemoryTableImpl.java
- server/controller/src/main/java/ai/starwhale/mlops/datastore/parquet/SwInputFile.java
- server/controller/src/main/java/ai/starwhale/mlops/datastore/parquet/SwOutputFile.java
- server/controller/src/main/java/ai/starwhale/mlops/datastore/parquet/SwParquetReaderBuilder.java
- server/controller/src/main/java/ai/starwhale/mlops/datastore/parquet/SwParquetWriterBuilder.java
- server/controller/src/main/java/ai/starwhale/mlops/datastore/parquet/SwReadSupport.java
- server/controller/src/main/java/ai/starwhale/mlops/datastore/parquet/SwWriteSupport.java
- server/controller/src/main/java/ai/starwhale/mlops/datastore/parquet/ValueSetter.java
- server/controller/src/main/java/ai/starwhale/mlops/exception/SwProcessException.java
- server/controller/src/test/java/ai/starwhale/mlops/datastore/parquet/ParquetReadWriteTest.java
- server/pom.xml
> enhance(datastore): add parquet read/write support for memory table

- client/starwhale/api/_impl/data_store.py
- client/tests/sdk/test_data_store.py
> enhance(sdk): add map type support

- client/scripts/sw-docker-entrypoint
`yq` in entrypoint can not find after global py version changes
> fix(docker): yq in entrypoint can not find after global py version changes

- client/starwhale/base/bundle_copy.py
- client/starwhale/base/uricomponents/exceptions.py
- client/starwhale/base/uricomponents/instance.py
- client/starwhale/base/uricomponents/project.py
- client/starwhale/base/uricomponents/resource.py
- client/tests/base/uricomponents/test_instance.py
- client/tests/base/uricomponents/test_project.py
- client/tests/base/uricomponents/test_resource.py
- client/tests/sdk/test_dataset.py
* Split URI into several parts
* instance
* project
* resource
> refactor(client): uri refactor

- server/controller/src/main/java/ai/starwhale/mlops/datastore/parquet/SwOutputFile.java
> fix(ut): occasional unit test failure in ParquetReadWriteTest

- client/scripts/sw-docker-entrypoint
- client/starwhale/api/_impl/model.py
- client/starwhale/core/eval/cli.py
- client/starwhale/core/eval/executor.py
- client/starwhale/core/model/cli.py
- scripts/client_test/cli_test.py
- scripts/client_test/cmds/eval_cmd.py
- server/controller/src/main/java/ai/starwhale/mlops/domain/dataset/dataloader/DataLoader.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/dataset/dataloader/DataReadManager.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/dataset/dataloader/bo/DataReadLog.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/dataset/dataloader/converter/SessionConverter.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/dataset/dataloader/dao/DataReadLogDao.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/dataset/dataloader/dao/SessionDao.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/dataset/dataloader/mapper/DataReadLogMapper.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/dataset/dataloader/mapper/SessionMapper.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/dataset/dataloader/po/DataReadLogEntity.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/dataset/dataloader/po/SessionEntity.java
- server/controller/src/main/java/ai/starwhale/mlops/schedule/k8s/K8sTaskScheduler.java
- server/controller/src/main/resources/db/migration/V00031__Mod_dataset_reader.sql
- server/controller/src/test/java/ai/starwhale/mlops/domain/dataset/dataloader/MultiConsumerTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/dataset/dataloader/ReadRangeTest.java
1. sever: Support multi datasets, the model's relation are as below:
session -> consumer -> dataset
1        :         n         :       m
2. client: In order to ensure the uniqueness of data under multiple datasets, add uri as prefix for data id/index
4. client: add multi dataset parm for the cmd  "swcli eval run" and "swcli model eval"
> feat(evaluation): support multi datasets

- server/controller/src/main/java/ai/starwhale/mlops/schedule/k8s/K8sTaskScheduler.java
delete existing k8s jobs before start it
> fix(controller): resuming job sometimes fails

- example/mnist/mnist/custom_evaluator.py
> chore(example):support multiple dataset for custom example

- docs/i18n/zh/docusaurus-plugin-content-docs/current.json
- docs/i18n/zh/docusaurus-plugin-content-docs/current/guides/heterogeneous/node-able.md
- docs/i18n/zh/docusaurus-plugin-content-docs/current/guides/heterogeneous/virtual-node.md
- docs/sidebars.js
Add heterogeneous devices part (zh)
> doc: add heterogeneous devices part

- client/starwhale/api/_impl/dataset/builder.py
- client/starwhale/api/_impl/dataset/loader.py
- client/starwhale/core/dataset/store.py
- client/starwhale/core/dataset/tabular.py
- client/starwhale/core/dataset/type.py
- client/starwhale/core/dataset/view.py
- client/tests/core/test_dataset_store.py
- client/tests/sdk/test_dataset.py
- client/tests/sdk/test_loader.py
- client/tests/sdk/test_model.py
- console/src/domain/dataset/sdk.ts
- example/datasets/coco/dataset.py
- example/datasets/coco/example.py
- server/controller/src/main/java/ai/starwhale/mlops/api/DatasetApi.java
- server/controller/src/main/java/ai/starwhale/mlops/api/DatasetController.java
- server/controller/src/main/java/ai/starwhale/mlops/configuration/RequestLoggingConfig.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/dataset/DatasetService.java
- server/controller/src/main/resources/application.yaml
- server/controller/src/test/java/ai/starwhale/mlops/api/DatasetControllerTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/dataset/DatasetServiceTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/dataset/objectstore/DsFileGetterTest.java
- add batch uri sign api in server
- add logger for server request
- change `data_uri` column type to `Link` and change UI related api call
- yield batch rows when scan datastore
- travel all `Link`s in datastore row including annotations
- batch sign uri and add `signed_uri` to `Link`
- change coco example
http://batch-sign-20221116.pre.intra.starwhale.ai/projects/3/evaluations/3/actions
http://batch-sign-20221116.pre.intra.starwhale.ai/projects/3/evaluations/4/results
**sign-links log**
> feat(dataset): sign data uris in batch

- client/starwhale/api/_impl/dataset/loader.py
- client/starwhale/core/dataset/store.py
- client/starwhale/core/dataset/type.py
- client/tests/core/test_dataset_store.py
- client/tests/sdk/test_loader.py
- example/datasets/test_annotations/dataset.py
- fix unclosed issue for _make_file
- support HttpBufferedFileLike same as `S3BufferedFileLike`
- tune HTTP get file with timeout, stream and buffered.
> enhance(sdk): tune get http file performance with buffer

- server/controller/src/main/java/ai/starwhale/mlops/datastore/DataStore.java
- server/controller/src/main/java/ai/starwhale/mlops/datastore/MemoryTable.java
- server/controller/src/main/java/ai/starwhale/mlops/datastore/impl/MemoryTableImpl.java
- server/controller/src/test/java/ai/starwhale/mlops/datastore/impl/MemoryTableImplTest.java
> chore(datastore): return Iterator in MemoryTable.scan

- client/scripts/sw-docker-entrypoint
- client/starwhale/consts/env.py
- client/starwhale/core/eval/cli.py
- client/starwhale/core/eval/executor.py
- client/starwhale/core/eval/model.py
- client/starwhale/core/eval/view.py
- client/tests/core/test_executor.py
- docker/Dockerfile.starwhale
- scripts/client_test/cli_test.py
- scripts/client_test/cmds/artifacts_cmd.py
- scripts/client_test/cmds/base/invoke.py
- scripts/client_test/cmds/instance_cmd.py
- scripts/e2e_test/check_job.sh
- scripts/example/runtime.yaml
- server/controller/src/main/java/ai/starwhale/mlops/common/ArchiveFileConsumer.java
- server/controller/src/main/java/ai/starwhale/mlops/common/TarFileUtil.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/model/ModelService.java
- server/controller/src/main/java/ai/starwhale/mlops/schedule/k8s/K8sJobTemplate.java
- server/controller/src/main/java/ai/starwhale/mlops/schedule/k8s/K8sTaskScheduler.java
- server/controller/src/main/resources/template/job.yaml
- server/controller/src/test/java/ai/starwhale/mlops/common/util/TarUtilTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/model/ModelServiceTest.java
- server/controller/src/test/java/ai/starwhale/mlops/schedule/k8s/K8sTaskSchedulerTest.java
- replace initContainer(dataProvider) with copy operation
- extract model when store to oss
1. build model at standalone
2. copy to server
3. [valid]copy this version from server to standalone(a new name 's-t')
4. [valid]use list
5. [valid]use the model of 's-t/v4'  to run evaluation
> feat(controller):extract model tar file&remove dataProvider Container

- scripts/e2e_test/start_test.sh
> chore: fix e2e not fail

- scripts/apitest/pytest/test_trash.py
- server/controller/src/main/java/ai/starwhale/mlops/domain/dataset/mapper/DatasetMapper.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/dataset/po/DatasetEntity.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/model/mapper/ModelMapper.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/model/po/ModelEntity.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/runtime/mapper/RuntimeMapper.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/runtime/po/RuntimeEntity.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/dataset/DatasetDaoTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/dataset/mapper/DatasetMapperTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/model/ModelDaoTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/model/mapper/ModelMapperTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/runtime/RuntimeDaoTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/runtime/mapper/RuntimeMapperTest.java
> fix(controller): e2e test for remove/recover trash and fix bug

- .github/workflows/client.yaml
- client/requirements-dev.txt
https://github.com/python/mypy/pull/13500
> chore(ci): upgrade mypy, prevent numpy lint error in python ver 3.10.7+

- client/starwhale/api/_impl/dataset/builder.py
- client/tests/sdk/test_dataset_sdk.py
> chore(sdk): fix dataset sdk test more stable

- .github/workflows/client.yaml
- .gitignore
- related pr: https://github.com/star-whale/starwhale/pull/1552
- `mnist/models/mnist.pth` file has already been removed, so the client e2e test can disable git lfs to reduce github's network brandwith.
> chore(ci): disable useless git lfs config

- client/starwhale/api/_impl/dataset/loader.py
- client/starwhale/core/dataset/store.py
E2E failed with error occasionally:
1. make a model who has 20 tasks
2. restart your computer
3. eval it against a link type dataset locally
4. the same error occurs
> bug: fix E2E fail occasionally with s3 client creation error

- client/Makefile
- client/starwhale/core/dataset/tabular.py
- client/tests/sdk/test_dataset_sdk.py
- add flush for fork_dataset to finish datastore dump
- local test: repeat 100 times for test_create_from_existed
-  ![Screenshot from 2022-12-08 19-12-17](https://user-images.githubusercontent.com/590748/206432716-2aaeb5f2-9342-4e9d-819f-f8e98e9402a4.png)
> bug(sdk): fix dataset create cache issue from existed dataset 

- client/starwhale/utils/fs.py
- client/tests/sdk/test_base.py
- client/tests/sdk/test_dataset_sdk.py
Fix
```FAILED tests/sdk/test_dataset_sdk.py::TestDatasetSDK::test_forbid_handler - OSError: [Errno 39] Directory not empty: '/tmp/sw-test-mock-k6gce_c_' ```
[link](https://github.com/star-whale/starwhale/actions/runs/3644683518/jobs/6154166653)
> fix(ci): make test of dataset stable

- .github/workflows/client.yaml
- .github/workflows/e2e-test.yml
- client/setup.py
- client/starwhale/api/_impl/data_store.py
- client/starwhale/api/_impl/dataset/builder.py
- client/starwhale/core/runtime/model.py
- client/tests/sdk/test_dataset.py
- depend pr: https://github.com/star-whale/starwhale/pull/1588
- upgrade deps:
- boto3: 
-  version: `1.21.0` -> `1.26.0`
-  reason: botocore/utils.py:15: DeprecationWarning: 'cgi' is deprecated and slated for removal in Python 3.13
- dill
-  version: `0.3.5.1` -> `0.3.6`
-  reason: dill==0.3.5.1 does not work for python3.11.
- **known issue**: https://github.com/pytorch/pytorch/issues/86566 , so we skip client ut for macosx system in the python 3.11.
> deps(client): client/sdk supports python3.11

- client/scripts/sw-docker-entrypoint
- client/starwhale/cli/__init__.py
Part of #1603
Install the right starwhale cli before execute the real job
> chore(docker): install the correct starwhale version when startup

- client/scripts/sw-docker-entrypoint
related: https://github.com/star-whale/starwhale/pull/1584
> bug(docker): fix sw-docker-entrypoint typo for python3.11

- client/starwhale/core/model/model.py
- server/controller/src/main/java/ai/starwhale/mlops/api/ModelApi.java
- server/controller/src/main/java/ai/starwhale/mlops/api/ModelController.java
- server/controller/src/main/java/ai/starwhale/mlops/api/protocol/dataset/DatasetInfoVo.java
- server/controller/src/main/java/ai/starwhale/mlops/api/protocol/model/ModelInfoVo.java
- server/controller/src/main/java/ai/starwhale/mlops/api/protocol/runtime/RuntimeInfoVo.java
- server/controller/src/main/java/ai/starwhale/mlops/api/protocol/storage/FileDesc.java
- server/controller/src/main/java/ai/starwhale/mlops/api/protocol/storage/FileNode.java
- server/controller/src/main/java/ai/starwhale/mlops/api/protocol/storage/FlattenFileVo.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/dataset/DatasetService.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/model/ModelService.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/runtime/RuntimeService.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/storage/MetaInfo.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/storage/StorageService.java
- server/controller/src/test/java/ai/starwhale/mlops/api/ModelControllerTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/model/ModelServiceTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/storage/FileNodeTest.java
1. tune the response's structure of model info api from flatten list to node list
2. add model diff api
3. refactor model download api
> feat(model): add model diff api for server

- client/starwhale/core/dataset/tabular.py
- client/tests/sdk/test_dataset.py
- console/src/domain/dataset/sdk.ts
expand first level of annotations
http://ano-expand-20221213.pre.intra.starwhale.ai/
> feat(sdk): expand first level of annotations

- client/starwhale/api/_impl/dataset/builder.py
- client/starwhale/api/_impl/dataset/model.py
- client/starwhale/api/_impl/wrapper.py
- client/starwhale/base/bundle_copy.py
- client/starwhale/core/dataset/copy.py
- client/starwhale/core/dataset/model.py
- client/starwhale/core/dataset/tabular.py
- client/starwhale/core/model/copy.py
- client/tests/sdk/test_dataset_sdk.py
[![asciicast](https://asciinema.org/a/545171.svg)](https://asciinema.org/a/545171)
> feat(sdk): support cloud remote dataset build by dataset sdk

- client/starwhale/base/uri.py
- client/starwhale/cli/board/project_tree.py
- client/starwhale/core/project/view.py
- client/tests/base/test_uri.py
use owner:project instead of project name in swcli
> feat(client): support owner:project instead of project name in uri

- client/starwhale/core/runtime/model.py
- client/starwhale/core/runtime/view.py
- client/tests/core/test_runtime.py
- docs/i18n/zh/docusaurus-plugin-content-docs/current/reference/cli/runtime.md
- related: https://github.com/star-whale/starwhale/issues/1370
[![asciicast](https://asciinema.org/a/545250.svg)](https://asciinema.org/a/545250)
> feat(runtime): support render runtime.yaml in the build runtime progress

- client/starwhale/base/bundle_copy.py
- client/starwhale/consts/__init__.py
- client/starwhale/core/dataset/copy.py
- client/starwhale/core/model/copy.py
- client/starwhale/core/model/model.py
- client/tests/base/test_copy.py
- client/tests/core/test_model.py
- client/tests/data/model/base_manifest.yaml
- client/tests/data/model/compare_manifest.yaml
- server/controller/src/main/java/ai/starwhale/mlops/api/protocol/storage/FileDesc.java
- server/controller/src/main/java/ai/starwhale/mlops/api/protocol/storage/FileNode.java
1. fix typo bug: change resources type from 'type' to 'desc'
2. rename class name
> fix(model): file desc typo

- client/scripts/sw-docker-entrypoint
- client/starwhale/core/model/cli.py
- client/starwhale/core/model/view.py
- client/starwhale/utils/docker.py
- client/tests/core/test_model.py
- client/tests/utils/test_docker.py
- docs/docs/reference/cli/model.md
- docs/i18n/zh/docusaurus-plugin-content-docs/current/reference/cli/model.md
model eval command support use-docker flag
Tested with 4 commands(starwhale==0.3.3.dev1212202632):
1. swcli -vvv model eval --dataset mnist/version/latest mnist/version/latest --image runtime1 --use-docker
2. swcli -vvv model eval --dataset mnist/version/latest . --image runtime1 --use-docker
3. swcli -vvv model eval --dataset mnist/version/latest . --runtime pytorch/version/latest --use-docker
4. swcli -vvv model eval --dataset mnist/version/latest mnist/version/latest --runtime pytorch/version/latest --use-docker
docker file for runtime1, work dir is pytorch runtime code:
```shell
FROM 10.131.0.1:8083/starwhale:0.3.3.dev1212202632
COPY requirements-sw-lock.txt /
RUN python3 -m pip install -r /requirements-sw-lock.txt
RUN python3 -m pip install starwhale==0.3.3.dev1212202632
```
> feat(cli): model eval command support use-docker flag

- client/tests/sdk/test_dataset_sdk.py
related:
- https://github.com/star-whale/starwhale/actions/runs/3729052987/jobs/6324736703
reason:
- the newest numpy version (1.24.0) will raise ValueError for the unequal length array to initialize a ndarray object.
```
In [1]: import numpy
In [2]: numpy.array([[1,2], [1]])
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-2-270a92f7560b> in <cell line: 1>()
----> 1 numpy.array([[1,2], [1]])
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.
```
> chore(test): fix tensoflow ut for numpy 1.24.0 version upgration

- server/controller/src/main/java/ai/starwhale/mlops/api/protocol/dataset/dataloader/DataConsumptionRequest.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/dataset/dataloader/DataReadManager.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/dataset/dataloader/DataReadRequest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/dataset/dataloader/ReadRangeTest.java
> fix(controller):tune consumption default value to false for param 'isSerial'

- server/controller/src/main/java/ai/starwhale/mlops/api/JobApi.java
- server/controller/src/main/java/ai/starwhale/mlops/api/JobController.java
- server/controller/src/main/java/ai/starwhale/mlops/api/protocol/job/ModelServingRequest.java
- server/controller/src/main/java/ai/starwhale/mlops/configuration/security/ModelServingTokenValidator.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/ModelServingService.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/mapper/ModelServingMapper.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/po/ModelServingEntity.java
- server/controller/src/main/java/ai/starwhale/mlops/schedule/k8s/K8sClient.java
- server/controller/src/main/java/ai/starwhale/mlops/schedule/k8s/K8sClientConfig.java
- server/controller/src/main/java/ai/starwhale/mlops/schedule/k8s/K8sJobTemplate.java
- server/controller/src/main/java/ai/starwhale/mlops/schedule/k8s/K8sTaskScheduler.java
- server/controller/src/main/resources/application.yaml
- server/controller/src/main/resources/db/migration/v0_3_2/V0_3_2_006__create_model_serving_info.sql
- server/controller/src/main/resources/template/model-serving.yaml
- server/controller/src/test/java/ai/starwhale/mlops/api/JobControllerTest.java
- server/controller/src/test/java/ai/starwhale/mlops/api/config/ModelServingTokenValidatorTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/job/ModelServingServiceTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/job/mapper/ModelServingMapperTest.java
- server/controller/src/test/java/ai/starwhale/mlops/schedule/k8s/K8sClientTest.java
- server/controller/src/test/java/ai/starwhale/mlops/schedule/k8s/K8sJobTemplateTest.java
- server/controller/src/test/java/ai/starwhale/mlops/schedule/k8s/K8sTaskSchedulerTest.java
- Add api `/api/v1/project/{projectUrl}/serving` for create model serving workload, params are:
- model version
- runtime version
- resource pool
- time to live 
- directly deploy the workload to k8s (for MVP, need to refactor later)
- stateful set
- svc
> feat(controller): support deploying serving model workload

- server/controller/src/main/java/ai/starwhale/mlops/domain/dataset/objectstore/DsFileGetter.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/dataset/objectstore/DsFileGetterTest.java
add support for controller to get http uri content
> feat: add support for controller to get http uri content

- server/controller/src/main/java/ai/starwhale/mlops/common/ProxyServlet.java
- server/controller/src/main/java/ai/starwhale/mlops/configuration/ProxyServletConfiguration.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/ModelServingService.java
- server/controller/src/test/java/ai/starwhale/mlops/common/ProxyServletTest.java
live demo
```bash
[
[
9
],
[
[
3.3270520369869727e-09,
1.2171811490062852e-10,
1.2030677147728627e-09,
1.7674929805337285e-09,
9.05094143771982e-05,
6.260217371438276e-08,
4.5112372466471804e-10,
4.308098875417157e-06,
1.1480706309613537e-05,
0.999893676619871
]
]
]
```
api spec in model
http://jialei.pre.intra.starwhale.ai/gateway/model-serving/20/api-spec
> feat(controller): support proxying to the serving model workload

- client/starwhale/api/_impl/service.py
- server/controller/src/main/java/ai/starwhale/mlops/common/ProxyServlet.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/ModelServingService.java
- server/controller/src/test/java/ai/starwhale/mlops/common/ProxyServletTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/job/ModelServingServiceTest.java
Make swagger ui works well behind the controller
demo:
http://jialei.pre.intra.starwhale.ai/gateway/model-serving/23/doc
> chore(sdk): support base uri for serving behind controller gateway

- example/datasets/citycapes/person_bbox/dataset.py
fix typo in storage path(citycapes -> cityscapes)
> fix: typo in storage path(citycapes -> cityscapes)

- server/controller/src/main/java/ai/starwhale/mlops/common/ProxyServlet.java
```bash
curl -i http://jialei.pre.intra.starwhale.ai/gateway/model-serving/21/
HTTP/1.1 502
Date: Thu, 29 Dec 2022 08:52:10 GMT
Content-Length: 0
Connection: keep-alive
```
> chore(controller): return 502 instead of 500 when online eval service is unavailable

- server/controller/src/main/java/ai/starwhale/mlops/api/DatasetApi.java
- server/controller/src/main/java/ai/starwhale/mlops/api/DatasetController.java
- server/controller/src/main/java/ai/starwhale/mlops/api/ModelApi.java
- server/controller/src/main/java/ai/starwhale/mlops/api/ModelController.java
- server/controller/src/main/java/ai/starwhale/mlops/api/RuntimeApi.java
- server/controller/src/main/java/ai/starwhale/mlops/api/RuntimeController.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/dataset/DatasetService.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/dataset/bo/DatasetQuery.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/dataset/mapper/DatasetMapper.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/model/ModelService.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/model/bo/ModelQuery.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/model/mapper/ModelMapper.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/runtime/RuntimeService.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/runtime/bo/RuntimeQuery.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/runtime/mapper/RuntimeMapper.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/user/UserService.java
- server/controller/src/test/java/ai/starwhale/mlops/api/DatasetControllerTest.java
- server/controller/src/test/java/ai/starwhale/mlops/api/ModelControllerTest.java
- server/controller/src/test/java/ai/starwhale/mlops/api/RuntimeControllerTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/dataset/DatasetServiceTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/dataset/mapper/DatasetMapperTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/model/ModelServiceTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/model/mapper/ModelMapperTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/runtime/RuntimeServiceTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/runtime/mapper/RuntimeMapperTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/user/UserServiceTest.java
> feat(controller): add filter params to controller list apis

- client/starwhale/api/_impl/service.py
- client/tests/data/sdk/service/no_api.py
- client/tests/sdk/test_service.py
> chore(client): optimize model build when no model serving api

- client/starwhale/utils/venv.py
- client/tests/core/test_runtime.py
avoid install pre_version when restore
> fix(client): runtime restore use enable_pre=false by default 

- client/starwhale/api/_impl/service.py
- client/starwhale/core/model/model.py
- client/tests/sdk/test_service.py
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/ModelServingService.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/job/ModelServingServiceTest.java
Call outer `wait()` function when on premises for waiting backend service to ready and getting the predicted result.
cc @waynelwz 
gradio doc ref: https://www.gradio.app/custom_CSS_and_JS/
local dev mode has no effect
https://user-images.githubusercontent.com/3217223/210331418-d3f499bb-d011-4c5e-b911-88a1f962f272.mp4
> chore(sdk): hijack submit on premises

- server/controller/src/main/java/ai/starwhale/mlops/api/JobApi.java
- server/controller/src/main/java/ai/starwhale/mlops/api/JobController.java
- server/controller/src/main/java/ai/starwhale/mlops/api/protocol/job/ModelServingVo.java
- server/controller/src/main/java/ai/starwhale/mlops/common/ProxyServlet.java
- server/controller/src/main/java/ai/starwhale/mlops/configuration/security/ModelServingTokenValidator.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/ModelServingService.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/po/ModelServingEntity.java
- server/controller/src/test/java/ai/starwhale/mlops/api/JobControllerTest.java
- server/controller/src/test/java/ai/starwhale/mlops/api/config/ModelServingTokenValidatorTest.java
- server/controller/src/test/java/ai/starwhale/mlops/common/ProxyServletTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/job/ModelServingServiceTest.java
- create model serving API returns {id, baseUri} instead of returning id only
- deprecate TTL seconds param 
- allow proxy URI without handler
After this pr, console will do the actions as follow:
1. post creation params
2. try getting the base URI returned in the last step
3. retry when getting 502
4. post user data when getting 200 in the last step
> chore(controller): model serving api refactor

- server/controller/src/main/java/ai/starwhale/mlops/domain/job/ModelServingService.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/mapper/ModelServingMapper.java
- server/controller/src/main/resources/db/migration/v0_3_2/V0_3_2_007__update_model_serving_info.sql
- server/controller/src/test/java/ai/starwhale/mlops/domain/job/ModelServingServiceTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/job/mapper/ModelServingMapperTest.java
Reuse model serving entries and workloads
- ignore insertion when entries with the same (project, model, runtime, resource pool) exist
- deploy workload and ignore 409 error (already exists)
> chore(controller): reuse model serving entries and workloads

- server/controller/pom.xml
- server/controller/src/main/java/ai/starwhale/mlops/api/DataStoreController.java
- server/controller/src/main/java/ai/starwhale/mlops/api/DatasetController.java
- server/controller/src/main/java/ai/starwhale/mlops/api/EnvController.java
- server/controller/src/main/java/ai/starwhale/mlops/api/EvaluationController.java
- server/controller/src/main/java/ai/starwhale/mlops/api/JobController.java
- server/controller/src/main/java/ai/starwhale/mlops/api/LogController.java
- server/controller/src/main/java/ai/starwhale/mlops/api/ModelController.java
- server/controller/src/main/java/ai/starwhale/mlops/api/PanelController.java
- server/controller/src/main/java/ai/starwhale/mlops/api/ProjectController.java
- server/controller/src/main/java/ai/starwhale/mlops/api/RuntimeController.java
- server/controller/src/main/java/ai/starwhale/mlops/api/SystemController.java
- server/controller/src/main/java/ai/starwhale/mlops/api/TrashController.java
- server/controller/src/main/java/ai/starwhale/mlops/api/UserController.java
- server/controller/src/main/java/ai/starwhale/mlops/configuration/security/ContentCachingFilter.java
- server/controller/src/main/java/ai/starwhale/mlops/configuration/security/ProjectNameExtractorDataStoreMixed.java
- server/controller/src/main/java/ai/starwhale/mlops/datastore/DataStore.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/task/status/watchers/TaskWatcherForSchedule.java
- server/controller/src/main/java/ai/starwhale/mlops/schedule/k8s/K8sJobTemplate.java
- server/controller/src/main/java/ai/starwhale/mlops/schedule/k8s/K8sTaskScheduler.java
- server/controller/src/main/resources/application.yaml
- server/storage-access-layer/pom.xml
- server/storage-access-layer/src/main/java/ai/starwhale/mlops/storage/configuration/StorageProperties.java
> chore(controller): application configuration use snake case

- server/controller/src/main/java/ai/starwhale/mlops/common/ProxyServlet.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/ModelServingService.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/mapper/ModelServingMapper.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/po/ModelServingEntity.java
- server/controller/src/main/java/ai/starwhale/mlops/schedule/k8s/ContainerOverwriteSpec.java
- server/controller/src/main/java/ai/starwhale/mlops/schedule/k8s/K8sClient.java
- server/controller/src/main/java/ai/starwhale/mlops/schedule/k8s/K8sJobTemplate.java
- server/controller/src/main/resources/application.yaml
- server/controller/src/main/resources/db/migration/v0_3_2/V0_3_2_008__add_last_visit.sql
- server/controller/src/test/java/ai/starwhale/mlops/domain/job/ModelServingServiceTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/job/mapper/ModelServingMapperTest.java
- server/controller/src/test/java/ai/starwhale/mlops/schedule/k8s/K8sClientTest.java
Online eval support garbage collection
- removes the workloads that reached the max TTL
- removes the oldest workload when there are pending workloads
- prevent removing the workloads that not reached the min TTL
> feat(controller): online eval support gc

- client/starwhale/base/bundle.py
- client/starwhale/core/model/model.py
- client/tests/core/test_model.py
We do not specify the config file name when tasks run in the cluster
- The task run will fail if users do not provide the `model.yaml` config file
- The task will use the wrong config file when users use the custom file and the `model.yaml` exists
> chore(client): make sure model.yaml exists when use custom config file

- .github/workflows/console.yml
- console/Makefile
- scripts/client_test/cli_test.py
- scripts/e2e_test/start_test.sh
- scripts/publish/pub.sh
- add `build-all` cmd in console Makefile
- fix gradio building 
- change `yarn build` to `make build-all` in `pub.sh` for e2e building
http://e2e-20230111.pre.intra.starwhale.ai/
> fix(e2e): fix console building issue

- server/controller/src/main/java/ai/starwhale/mlops/api/JobController.java
- server/controller/src/main/java/ai/starwhale/mlops/api/protocol/job/ModelServingRequest.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/ModelServingService.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/mapper/ModelServingMapper.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/po/ModelServingEntity.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/spec/ModelServingSpec.java
- server/controller/src/main/java/ai/starwhale/mlops/exception/SwValidationException.java
- server/controller/src/main/java/ai/starwhale/mlops/schedule/k8s/K8sJobTemplate.java
- server/controller/src/main/java/ai/starwhale/mlops/schedule/k8s/ResourceOverwriteSpec.java
- server/controller/src/main/resources/db/migration/v0_3_2/V0_3_2_009__add_spec.sql
- server/controller/src/test/java/ai/starwhale/mlops/api/JobControllerTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/job/ModelServingServiceTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/job/mapper/ModelServingMapperTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/job/spec/ModelServingSpecTest.java
- server/controller/src/test/java/ai/starwhale/mlops/schedule/k8s/K8sJobTemplateTest.java
Add spec field for the `create serving` api
http://jialei.pre.intra.starwhale.ai/swagger-ui/index.html#/Job/createModelServing
spec string demo
```
resources:
- type: CPU
request: 7
limit: 8
```
> feat(controller): online eval support resource params

- client/starwhale/api/_impl/data_store.py
- client/tests/sdk/test_data_store.py
dataset info returns none when retriving from parquet file.
> fix(datastore): fix end_inclusive error when only one row in parquet file

- client/starwhale/api/_impl/data_store.py
- client/tests/sdk/test_data_store.py
fix #1706 
there will have multi writers on multithreading, so it will lead to race when these writers update the same table. one case is that they all create a table, but only the last would be recorded to the singleton datastore, and then would loss some data which are belongs to the previous table obj.
> fix(client): datastore loss data on multithread

- example/speech_command/sc/evaluator.py
- Support model serving in speech command deom
- Support file uploading or recording from microphone as input
> chore(example): add serve handler for speech command

- example/ucf101/Makefile
- example/ucf101/ucf101/custom_evaluator.py
- example/ucf101/ucf101/evaluator.py
- example/ucf101/ucf101/sampler.py
> chore(example): serving handler for ucf101

- client/starwhale/api/_impl/service.py
gradio will make sure the return value is a list
```js
dependencies.forEach((d) => {
if (d.js) {
try {
d.frontend_fn = new AsyncFunction(
"__fn_args",
`let result = await (${d.js})(...__fn_args);
return ${d.outputs.length} === 1 ? [result] : result;`
);
} catch (e) {
console.error("Could not parse custom js method.");
console.error(e);
}
}
});
```
ref: https://github.com/gradio-app/gradio/blob/v3.15.0/ui/packages/app/src/Blocks.svelte#L67
gradio expands the `payload.data.concat(output_data)` as fn_args
So, when there is only one output, nothing wrong, and when there are multiple outputs, we return the wrong response.
```js
if (frontend_fn !== undefined) {
payload.data = await frontend_fn(payload.data.concat(output_data));
}
```
ref: …
> fix(client): fix js compatible with multi args in online eval

- client/scripts/sw-docker-entrypoint
The problem:
```bash
/path/to/venv/pip config get global.cache-dir
/'root'/.cache/pip
```
The single quote `'` makes:
- /'root'/ dir created
- double cache space usage when installing starwhale (if the global starwhale needs to reinstall)
- cache can not be reused between pods
> fix(client): fix pip cache dir

- client/starwhale/api/_impl/service.py
- scripts/client_test/cli_test.py
- gradio import will slow the starwhale package import speed.
- for example: `swcli --help` command do nothing, but it will cost 3~8s because of radio.
- before:  4s
- ![image](https://user-images.githubusercontent.com/590748/215459745-41811dbf-b96b-4ab5-b36a-80fe49a6d572.png)
- after: 0.9s 
- ![image](https://user-images.githubusercontent.com/590748/215459209-53732c6e-7a42-40c8-ac36-35a440b2685c.png)
> chore(client): tune gradio import to slove slow import issue

- docker/charts/templates/controller-deployment.yaml
- docker/charts/values.yaml
- server/controller/src/main/resources/template/job.yaml
- server/controller/src/main/resources/template/model-serving.yaml
- server/controller/src/test/resources/template/job.yaml
We use the `latest` tag and `IfNotPresent` policy by default, the docker image can not update to the latest version when the image exists in the node the scheduler chooses.
I recommend using k8s default behavior like:
https://kubernetes.io/docs/concepts/containers/images/#imagepullpolicy-defaulting
> When you (or a controller) submit a new Pod to the API server, your cluster sets the imagePullPolicy field when specific conditions are met:
> - if you omit the imagePullPolicy field, and the tag for the container image is :latest, imagePullPolicy is automatically set to Always;
> - if you omit the imagePullPolicy field, and you don't specify the tag for the container image, imagePullPolicy is automatically set to Always;
> - if you omit the imagePullPolicy field, and you specify the tag for …
> chore(deploy): remove image pull policy config

- console/src/pages/Project/OnlineEval.tsx
- server/controller/src/main/java/ai/starwhale/mlops/common/ProxyServlet.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/ModelServingService.java
- server/controller/src/main/java/ai/starwhale/mlops/schedule/k8s/K8sClient.java
- server/controller/src/main/java/ai/starwhale/mlops/schedule/k8s/K8sJobTemplate.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/job/ModelServingServiceTest.java
- server/controller/src/test/java/ai/starwhale/mlops/schedule/k8s/K8sClientTest.java
UI
- Check server status immediately after getting the model serving URI
- Change the checking interval from 2s to 1s
Server
- Add cache for K8s workload list (prevent applying orchestration in every predict request)
- Handle `NoRouteToHostException` in proxy
- Change readiness probe interval from 10s to 1s
> chore(controller): online eval rtt optimization

- server/controller/src/main/java/ai/starwhale/mlops/domain/job/step/mapper/StepMapper.java
> fix(controller):step entity without name

- client/starwhale/api/_impl/dataset/builder.py
- client/tests/sdk/test_dataset.py
when BaseArtifact.fp is user local file path , it is unreliable and should be removed.
- remove BaseArtifact.fp after being built by dataset if it is user local file path
> fix(dataset): fix user local fs data can't be fetched by server instance

- client/starwhale/base/bundle_copy.py
- client/starwhale/core/dataset/copy.py
- client/tests/base/test_copy.py
- client/tests/sdk/test_dataset.py
closes #1731 
1. origin copy:
2. changed:
> fix(client):unified the dataset table name when copy

- server/controller/src/main/java/ai/starwhale/mlops/common/TarFileUtil.java
- server/controller/src/main/java/ai/starwhale/mlops/datastore/impl/MemoryTableImpl.java
- server/storage-access-layer/src/main/java/ai/starwhale/mlops/storage/NopCloserInputStream.java
- server/storage-access-layer/src/main/java/ai/starwhale/mlops/storage/aliyun/StorageAccessServiceAliyun.java
aliyun oss sdk will close the original input stream at the end of the put.
https://github.com/aliyun/aliyun-oss-java-sdk/blob/10727ab9f79efa2a4f2c7fbec348e44c04dd6c42/src/main/java/com/aliyun/oss/common/comm/ServiceClient.java#L89
This makes the uploading of the model fail in this block
```java
TarFileUtil.extract(inputStream, (name, size, in) ->
storageAccessService.put(
String.format(FORMATTER_STORAGE_SRC_FILE_PATH, storagePath, name), in, size
)
);
```
> fix(controller): prevent closing input in aliyun oss

- client/starwhale/base/bundle_copy.py
- client/starwhale/core/dataset/copy.py
- client/tests/base/test_copy.py
- client/tests/sdk/test_dataset.py
- client/tests/sdk/test_dataset_sdk.py
- server/controller/src/main/java/ai/starwhale/mlops/api/DatasetApi.java
- server/controller/src/main/java/ai/starwhale/mlops/api/DatasetController.java
- server/controller/src/main/java/ai/starwhale/mlops/api/ModelApi.java
- server/controller/src/main/java/ai/starwhale/mlops/api/ModelController.java
- server/controller/src/main/java/ai/starwhale/mlops/api/protocol/upload/UploadRequest.java
- server/controller/src/main/java/ai/starwhale/mlops/api/protocol/upload/UploadResult.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/dataset/upload/DatasetUploader.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/dataset/upload/HotDatasetHolder.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/model/ModelService.java
- server/controller/src/test/java/ai/starwhale/mlops/api/DatasetControllerTest.java
- server/controller/src/test/java/ai/starwhale/mlops/api/ModelControllerTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/dataset/DatasetUploaderTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/dataset/HotDatasetHolderTest.java
Unified the upload/download api for model and dataset:
1. dataset
changed param from 'part_name' to 'partName' 
2. model
changed headers from `'X-SW-DOWNLOAD-TYPE','X-SW-DOWNLOAD-OBJECT-NAME','X-SW-DOWNLOAD-OBJECT-PATH','X-SW-DOWNLOAD-OBJECT-HASH'` to `'desc','partName','path','signature' `and the type from header to param.
3. Change upload id from String to Long
> fix(controller): remove headers from model download api

- docs/i18n/zh/docusaurus-plugin-content-docs/current/guides/runtime.md
- example/runtime/pytorch/runtime.yaml
> example(runtime): remove example and doc for the unsupported pre/post runtime hook

- docs/docs/guides/config/server_admin.md
- docs/i18n/zh/docusaurus-plugin-content-docs/current/guides/config/server_admin.md
`docker-registry.starwhale.ai` has an expired certificate. Before returning to normal, we use an available address.
```
❯ curl -I https://docker-registry.starwhale.ai
curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.se/docs/sslcerts.html
```
```
❯ curl -I https://docker-registry.starwhale.cn
HTTP/1.1 200 OK
Server: nginx/1.23.0
Date: Wed, 08 Feb 2023 03:22:40 GMT
Content-Type: text/html
Content-Length: 16975
Last-Modified: Wed, 28 Sep 2022 08:28:11 GMT
Connection: keep-alive
ETag: "6334059b-424f"
Accept-Ranges: bytes
```
> chore(doc): update doc registry with the avaiable address

- client/starwhale/base/bundle_copy.py
- client/starwhale/base/uricomponents/instance.py
- client/starwhale/base/uricomponents/project.py
- client/starwhale/base/uricomponents/resource.py
- client/starwhale/core/dataset/cli.py
- client/starwhale/core/dataset/copy.py
- client/starwhale/core/model/cli.py
- client/starwhale/core/runtime/cli.py
- client/tests/base/test_copy.py
- client/tests/base/uricomponents/test_instance.py
- client/tests/base/uricomponents/test_project.py
- client/tests/base/uricomponents/test_resource.py
we cannot execute `swcli runtime cp pytorch-starwhale-main/version/latest pre-k8s/project/mnist ` command without `cloud:// prefix`, following by the user [doc](https://github.com/star-whale/starwhale/blob/main/docs/i18n/zh/docusaurus-plugin-content-docs/current/guides/uri.md#1-instance-uri). 
- before:
- ![image](https://user-images.githubusercontent.com/590748/217454010-ed92b6ff-2e66-4c34-af6a-d6b5b092afad.png)
- after:
- ![image](https://user-images.githubusercontent.com/590748/217748819-161da2a3-d8eb-471a-8277-17c8d73c030c.png)
> enhance(cli): make copy command compatible with no `cloud://` prefix uri

- server/controller/src/main/java/ai/starwhale/mlops/StarwhaleControllerApplication.java
- server/controller/src/main/java/ai/starwhale/mlops/configuration/DockerSetting.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/system/SystemSetting.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/system/SystemSettingService.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/system/listener/DockerSettingListener.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/system/listener/RunTimePropertiesListener.java
- server/controller/src/main/resources/application.yaml
- server/controller/src/test/java/ai/starwhale/mlops/domain/system/SystemSettingServiceTest.java
populate pypi/docker startup envs to system setting
- pypi setting in startup env is synced to system setting on startup if user doesn't set them
- system setting have higher priority than startup env
- if user delete them in system setting they will be set to empty and also have higher priority than startup env
> feat(controller): populate pypi/docker startup envs to system setting

- server/controller/src/main/java/ai/starwhale/mlops/common/DockerImage.java
- server/controller/src/test/java/ai/starwhale/mlops/common/DockerImageTest.java
fix bug introduced by https://github.com/star-whale/starwhale/pull/1817
> (fix): modify image resolve behavior

- server/controller/src/main/java/ai/starwhale/mlops/datastore/ColumnTypeScalar.java
- server/controller/src/test/java/ai/starwhale/mlops/datastore/DataStoreTest.java
> fix(controller):datastore api return empty results when query multi times for type of bytes

- example/transformer/ag_news/README.md
- example/transformer/ag_news/code/download_model.py
- example/transformer/ag_news/code/evaluator.py
- example/transformer/ag_news/model.yaml
- example/transformer/ag_news/requirements-sw-lock.txt
- example/transformer/ag_news/runtime.yaml
add hugging face transformer example
> (model): add hugging face transformer textattack/albert-base-v2-ag-news example

- client/tests/cli/assistance/test_common.py
> fix(client): improve ut stability by prolonging the time gap

- client/starwhale/core/dataset/store.py
- client/starwhale/core/dataset/type.py
- client/tests/sdk/test_dataset.py
- example/datasets/kitti/lane/README.md
- example/datasets/kitti/lane/dataset.py
- example/datasets/kitti/lane/example.py
- example/datasets/kitti/lane/requirements.txt
- add kitti lane dataset
- fix self.resp.raw.read() can't read whole file
> example(dataset): add kitti lane dataset

- client/starwhale/cli/assistance/remote.py
> fix(client): do not wait for stdin so that the remote side can stop immediately when the command quits

- console/src/domain/model/components/CreateOnlineEvalForm.tsx
- console/src/domain/runtime/hooks/useFetchRuntimeVersionSuggestion.ts
- console/src/domain/runtime/schemas/runtimeVersion.tsx
- console/src/domain/runtime/services/runtimeVersion.ts
Auto fill runtime if possible in online eval page
relates to #1805
> feat(console): auto fill runtime if possible in online eval page

- client/starwhale/api/_impl/data_store.py
- client/starwhale/api/_impl/wrapper.py
- client/tests/sdk/test_data_store.py
- client/tests/sdk/test_wrapper.py
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/storage/JobRepo.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/job/storage/JobRepoTest.java
1. lazy to init table name for eval on the client
2. fix bug: replace name with id for eval summary table name
> fix(datastore): lazy to init table name for eval & replace name with id

- README.md
- docs/docs/quickstart/on-premises.md
- docs/docs/quickstart/standalone.md
- docs/i18n/zh/docusaurus-plugin-content-docs/current/quickstart/on-premises.md
- docs/i18n/zh/docusaurus-plugin-content-docs/current/quickstart/standalone.md
- example/notebooks/dataset-sdk.ipynb
- example/notebooks/quickstart-standalone.ipynb
- depend on: https://github.com/star-whale/starwhale/pull/1841
- colab example: https://colab.research.google.com/drive/1eodNQUMOCC5lsQI-5QJH5A6jGlrJWHoS?usp=sharing
> doc(notebook): update readme and standalone quickstart doc, notebooks

- .github/workflows/client.yaml
- client/Makefile
- client/setup.py
- client/starwhale/__init__.py
- client/starwhale/api/_impl/data_store.py
- client/starwhale/api/_impl/metric.py
- client/starwhale/api/_impl/track/base.py
- client/starwhale/api/_impl/track/collector.py
- client/starwhale/api/_impl/track/handler.py
- client/starwhale/api/_impl/track/hooker.py
- client/starwhale/api/_impl/track/syncer.py
- client/starwhale/api/_impl/track/tracker.py
- client/starwhale/api/track.py
- client/starwhale/cli/__init__.py
- client/starwhale/cli/config.py
- client/starwhale/core/dataset/type.py
- client/starwhale/utils/config.py
- client/starwhale/utils/dict.py
- client/starwhale/utils/fs.py
- client/tests/core/test_dataset.py
- client/tests/sdk/test_dataset.py
- client/tests/sdk/test_track.py
- client/tests/utils/test_dict.py
- basic track SDK code skeleton:
- only supports five core functions: `track.start, track.end, track.metrics, track.artifacts, track.params`.
- only store results in local storage.
- mnist example:
- [![asciicast](https://asciinema.org/a/555472.svg)](https://asciinema.org/a/555472)
> feat(sdk): support track sdk for experiment

- docker/external/config-e2e-pypi-repo.sh
- scripts/publish/pub.sh
enlarge pip timeout in e2e runtime
> chore(e2e): enlarge pip timeout in e2e runtime

- server/controller/src/main/java/ai/starwhale/mlops/domain/task/TaskService.java
explicitlly set charset of offline log
> fix(controller): explicitlly set charset of offline log

- .github/workflows/docs.yaml
when  the [pr](https://github.com/star-whale/starwhale/pull/1862) is merged, we could delete the keep_files flag.
> chore(doc): add a temp flag to keep the first archived versions dir

- docker/charts/templates/controller-deployment.yaml
- docker/charts/values.yaml
- remove the outdated `agentHostPathRoot` description
- provide `devMode.createConsoleHostPathPV` fields to config console debug volume
- provide `controller.job.cacheDirHostPath` field to describe job pod cache volume
> chore(charts): refactor helm values for the hostpath pv

- client/starwhale/api/_impl/service.py
**Add a submit button for online eval**
Users may need this button in some cases, e.g.  translation or inference with multiple inputs
> chore(client): add a submit button for online eval

- server/controller/src/main/java/ai/starwhale/mlops/domain/job/cache/JobLoader.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/task/status/watchers/TaskWatcherForJobStatus.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/job/JobLoaderTest.java
1. job status is  still fail after resuming job
2. cmp step could not be triggered after resumed ppl success
http://e2e-20230221.pre.intra.starwhale.ai/projects/1/evaluations/9/results
> fix(controller): job status is  still fail after resuming job

- console/src/domain/project/components/OnlineEvalLoading.tsx
- console/src/pages/Project/OnlineEval.tsx
- console/src/styles/_global.scss
> update(console): ui optimize for process modal

- console/src/pages/Runtime/RuntimeOverviewLayout.tsx
> update(console): remove accordin panel

- client/starwhale/api/_impl/evaluation.py
> chore(sdk): remove useless single `__exit__` function in the evalution module

- server/controller/src/main/java/ai/starwhale/mlops/domain/job/ModelServingService.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/job/ModelServingServiceTest.java
swcli can not find xxx/version/id after #1870  merged
use the version name instead.
> chore(controller): use version name of resource instead of using version id

- server/controller/src/main/java/ai/starwhale/mlops/domain/job/JobService.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/ModelServingService.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/runtime/RuntimeResource.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/system/resourcepool/bo/Resource.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/system/resourcepool/bo/ResourcePool.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/task/status/WatchableTask.java
- server/controller/src/main/java/ai/starwhale/mlops/schedule/k8s/K8sTaskScheduler.java
- server/controller/src/main/java/ai/starwhale/mlops/schedule/k8s/ResourceOverwriteSpec.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/job/JobServiceTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/job/ModelServingServiceTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/system/resourcepool/bo/ResourcePoolTest.java
- Eval and Online Eval
- Validate resources when creating
- Use the default value in the corresponding resource pool as the default if no resource is specified
- Online Eval
- Use the `default` resource pool if no resource pool is specified (server side)
> chore(controller): validate and patch runtime resource when eval

- client/starwhale/base/bundle_copy.py
- client/starwhale/base/uricomponents/resource.py
Closes #1637
- Show console url for the remote bundle after copy done
- sw xx cp support console url with resource name like `.../projects/starwhale/models/mnist/versions/foobarbaz`
It is convenient for users to open the console by clicking the link.
> chore(client): show console url of the remote bundle after copy done

- .github/workflows/release.yml
- docker/Dockerfile.server
- docker/Makefile
- Docker image of the controller support multi-arch
- refine Makefile in docker dir, use the `build-image` which is based on `buildx` in all the release workflow
> chore(docker): controller support multi-arch and refine Makefile

- docker/Makefile
Fixes: https://github.com/star-whale/starwhale/actions/runs/4350126117/jobs/7600519020
Related to #1922
> fix(docker): restore the missing build-release-base-server target

- docker/Makefile
- scripts/publish/pub.sh
The `buildx` can not support build to local image atm, add `build-server-for-local-usage` target for e2e usage
> fix(e2e): fix server build issue in e2e

- client/starwhale/api/_impl/job.py
- client/starwhale/core/model/model.py
- client/starwhale/core/model/store.py
- client/starwhale/utils/fs.py
- client/tests/core/test_model.py
- console/src/pages/Project/OnlineEval.tsx
- server/controller/src/main/java/ai/starwhale/mlops/domain/model/ModelService.java
Move the auto-generated file to the `.starwhale` dir
- eval_jobs.yaml
- svc.json
The panel settings will be saved to this dir too later
> chore(client): move auto-generated file to the .starwhale dir

- server/controller/src/main/java/ai/starwhale/mlops/domain/model/ModelService.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/model/converter/ModelVersionVoConverter.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/model/mapper/ModelVersionMapper.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/model/po/ModelVersionEntity.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/model/ModelServiceTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/model/ModelVersionConverterTest.java
Do not save the manifest file (may be too large) in the database, use the oss version instead.
> chore(controller): store manifest with oss instead of using db

- client/tests/sdk/test_data_store.py
- client/tests/sdk/test_wrapper.py
- server/controller/src/main/java/ai/starwhale/mlops/datastore/ColumnType.java
- server/controller/src/main/java/ai/starwhale/mlops/datastore/DataStore.java
- server/controller/src/main/java/ai/starwhale/mlops/datastore/MemoryTable.java
- server/controller/src/main/java/ai/starwhale/mlops/datastore/impl/MemoryTableImpl.java
- server/controller/src/main/java/ai/starwhale/mlops/datastore/parquet/SwParquetWriterBuilder.java
- server/controller/src/main/java/ai/starwhale/mlops/datastore/parquet/SwReadSupport.java
- server/controller/src/main/java/ai/starwhale/mlops/datastore/parquet/SwWriteSupport.java
- server/controller/src/main/java/ai/starwhale/mlops/datastore/parquet/SwWriter.java
- server/controller/src/test/java/ai/starwhale/mlops/datastore/impl/MemoryTableImplTest.java
- server/controller/src/test/java/ai/starwhale/mlops/datastore/parquet/ParquetReadWriteTest.java
#1916 
1. [Client] add ut for python sdk(dataset and datastore with data of SwObject)
2. [Server] fix lost data bug when save table with error
3. [Server] fix load data exception when data is null at the step of insertRecords 
4. [Server] add retry logic when load is invalid
> fix(datastore): data lost when save table with error

- .github/workflows/release.yml
tested in https://github.com/star-whale/starwhale/actions/runs/4411841925/jobs/7730733975
> fix(docker): buildx can not work without init in release workflow

- console/src/pages/Model/ModelVersionOverviewFiles.tsx
- Unset the default language `yaml`, and let the editor choose the appropriate language
- scroll to the top when the editor content changes
https://user-images.githubusercontent.com/3217223/224950094-be985198-3f0e-46a0-b589-0741757bcae7.mp4
> chore(console): refine code editor language detection

- .github/workflows/release-base.yml
- docker/Dockerfile.nodejs
- docker/Makefile
- Add `make` cmd in the nodejs image for using the `Makefile`
- build nodejs image automatically
> chore(docker): build nodejs image automatically and add make cmd in the image

- docker/Dockerfile.nodejs
Do not use mirror when building nodejs multi-arch images
related to: #1959
https://github.com/star-whale/starwhale/actions/runs/4414182044/jobs/7735563382
> fix(docker): do not use mirror when building nodejs multi-arch images

- client/starwhale/web/data_store.py
- client/tests/web/test_server.py
Console uses regex `/(^project\/.*?\/.*?\/.*?\/.*?\/)/` to replace the evaluation related info, and the table name with `/` prefix can not match it.
https://github.com/star-whale/starwhale/blob/e1dd759a7803a5879457dc2e272c47de54b1e664/console/packages/starwhale-core/src/widget/utils/replacer.ts#L14-L21
> fix(client): remove the prefix slash when listing tables in the client

- client/starwhale/api/_impl/dataset/loader.py
- client/tests/sdk/test_dataset_sdk.py
- example/mnist/mnist/dataset_read.py
- example/notebooks/dataset-sdk.ipynb
- depend pr: https://github.com/star-whale/starwhale/pull/1943 , please review [015a2c](https://github.com/star-whale/starwhale/pull/1948/commits/015a2ce5c8b8eab656470914f71be9a3ba26a6d3) commit.
- Code Example:
```python
from starwhale import dataset
ds = dataset("mnist/version/latest")
print(ds[0].features.label)
ds[0].features.label = 1
del ds[0].features.label
```
> feat(sdk): support `DataRow.features` attribute-like usage

- console/src/pages/Project/OnlineEval.tsx
- Related to https://github.com/star-whale/starwhale/pull/1936/files#diff-0bb49f51eec0b9cb35d56beb255d80db70c48b935f05b04ddeed8d218db5b29dR155
- Need to refine the pull logic later in the server side #1969
cc @lijing-susan
> fix(console): online eval page can not show

- scripts/e2e_test/remove_test_env.sh
remove e2e namespace 
Closing https://github.com/star-whale/starwhale/issues/1825
> chore(e2e): refine e2e remove logic

- console/packages/starwhale-core/src/store/store.ts
Delete the child widgets when deleting the panel
> fix(console): delete the child widgets when deleting the panel

- client/starwhale/api/_impl/dataset/model.py
- client/tests/sdk/test_dataset_sdk.py
`build_from_handler` may bring confusion for the `Python SDK` style. With Python SDK, users can write in-house code to complete the dataset building and management, the external handler code is not friendly for the users.
In further, `swcli dataset build` command focuses on no-code dataset building. 
related: https://github.com/star-whale/starwhale/issues/1940
> chore(dataset): remove `build_from_handler` interface for dataset python sdk

- client/tests/sdk/test_dataset_sdk.py
related issue: https://github.com/star-whale/starwhale/actions/runs/4434089899/jobs/7779742020
Pytorch 2.0 version was released 8 hours ago.
> chore(test): make dataset sdk torch tests compatible with different pytorch versions

- client/starwhale/api/_impl/dataset/model.py
- client/tests/sdk/test_dataset_sdk.py
- dependent pr: https://github.com/star-whale/starwhale/pull/1964
- changes:
- `create=True` is only for the non-existed dataset.
- loading an existing dataset, then you can read, update, add, and delete rows or features for the dataset.
- `readonly`  is an explicit argument for dataset load.
> chore(dataset): new dataset entrypoint function for create or load in Python SDK

- server/controller/src/main/java/ai/starwhale/mlops/schedule/k8s/ResourceOverwriteSpec.java
- server/controller/src/test/java/ai/starwhale/mlops/schedule/k8s/ResourceOverwriteSpecTest.java
Add limit for no-k8s resources if not specified by default
related to #1335
> fix(controller): jobs from console with GPU requests can not work

- example/PennFudanPed/pfp/utils/coco_eval.py
After torch being upgrade to 2.0, there no `_six` module there
> fix(e2e): torch 2.0 has no _six module

- console/package.json
`console/build/.gitignore` will be deleted by vite, and the whole build dir will be treated as dirty
> fix(console): resolve the gitignore missing issue after yarn building

- client/starwhale/consts/__init__.py
- client/starwhale/core/model/model.py
- client/starwhale/web/panel.py
- client/tests/core/test_model.py
- console/src/domain/model/services/modelVersion.ts
- Add support for the yaml format layout config file
- `sw mp build` will generate the JSON format config from the yaml format if exists
- `sw eval info xx --web` support render from the yaml config file
- refuse to save the panel layout settings from the console when using yaml config
related to #1980
The yaml format config demo:
```yaml
layouts:
- title: model builtin layout
panels:
- title: tables for datastore
charts:
- type: table
table: confusion_matrix/binarylabel
- type: table
table: results
- title: charts
height: 500
charts:
- type: roc_auc
table: roc_auc/1
x: tpr
y: fpr
title: roc auc for label 1
- type: confusion_matrix
table: confusion_matrix/binarylabel
title: confusion matrix
```
> feat(client): model building support eval layout yaml config

- client/starwhale/api/_impl/dataset/builder/__init__.py
- client/starwhale/api/_impl/dataset/builder/iterable_builder.py
- client/starwhale/api/_impl/dataset/builder/mapping_builder.py
- client/tests/sdk/test_dataset.py
- changes: 
- rename BuildExcutor to IterableBuildExecutor
- add MappingDatasetBuilder
- provide `put` and `delete` interfaces to create the dataset. But `IterableBuildExecutor` needs an iterable function.
- sync swds-bin format artifacts for the cloud instance automatically.
- TODO:
- https://github.com/star-whale/starwhale/pull/1973 will use `MappingDatasetBuilder` to update-create-delete dataset.
- `swcli dataset build --from-iter` will use `MappingDatasetBuilder` to build dataset.
- related issue:   https://github.com/star-whale/starwhale/issues/1940
> feat(dataset) support mapping style dataset builder

- client/starwhale/core/eval/view.py
- client/starwhale/web/server.py
- client/tests/web/test_server.py
`sw eval info --web` support remote instance
- serve local assets like the index.html and js 
- serve panel-related API for customizing layout
- proxy all the other APIs with the auth and host header
> feat(client): eval info --web support remote instance

- scripts/client_test/update_controller_setting.sh
` ^M` in request header is legal before https://github.com/star-whale/starwhale/pull/1909
Now it should be trimed or `400` will be raised by server
> fix(e2e): remove possible ^M char in auth header

- client/starwhale/api/_impl/dataset/builder/__init__.py
- client/starwhale/api/_impl/dataset/builder/mapping_builder.py
- client/starwhale/api/_impl/dataset/mapping_builder.py
- client/starwhale/api/_impl/dataset/model.py
- client/starwhale/api/_impl/evaluation.py
- client/starwhale/core/dataset/store.py
- client/starwhale/core/dataset/tabular.py
- client/starwhale/core/dataset/type.py
- client/tests/sdk/test_dataset_sdk.py
- client/tests/sdk/test_evaluation.py
- dependent pr: https://github.com/star-whale/starwhale/pull/1976， please review [86fd0c](https://github.com/star-whale/starwhale/pull/1973/commits/86fd0c561bd2e479fee66f3353903d359715e3eb) commit.
- features:
- remove fork_dataset
- provide `commit` interface: flush and generate a version
- use `MappingDatasetBuilder` to build the dataset
- use dataset one-one datastore table
> feat(dataset): new dataset constructive mechanism with versioning datastore table

- console/src/api/ApiHeader.tsx
- console/src/components/Editor/index.tsx
- console/src/pages/Evaluation/EvaluationListCard.tsx
- console/src/pages/Evaluation/EvaluationWidgetResults.tsx
`listTables` can not works with project name, fix it
> fix(console): eval pages works with project name in uri

- console/packages/starwhale-ui/src/Plotly/utils.ts
> fix(console): set ploty auto layout  when large mount of data

- client/tests/base/test_tag.py
These unit tests use the local config, they report errors when `current instance` sets remote
> FAILED tests/base/test_tag.py::StandaloneTagTestCase::test_auto_fast_tag - starwhale.utils.error.NoSupportError: cloud
FAILED tests/base/test_tag.py::StandaloneTagTestCase::test_tag_workflow - starwhale.utils.error.NoSupportError: cloud
> fix(client): ut without existing local config or default

- client/Makefile
- client/setup.py
> chore(client): add ui assets to pkg data

- client/starwhale/api/_impl/data_store.py
- client/tests/sdk/test_data_store.py
- client/tests/sdk/test_track.py
- The method of data persistence changes from Parquet to JSON
- Support data revision in the scan method
- Table (or row) schema becomes mutable
- Writing to remote datastore from batch to single, the throughput will decrease
- Saving the schema in every updating and use the JSON format, the storage space requirements are greatly increasing
> refactor(client): datastore in standalone support version and mutable schema

- client/starwhale/api/_impl/dataset/builder/mapping_builder.py
- client/tests/sdk/test_dataset.py
- client/tests/sdk/test_dataset_sdk.py
- depends on: https://github.com/star-whale/starwhale/pull/1993
> feat(dataset): `MappingDatasetBuilder` supports to upload swds_bin to cloud instance

- client/starwhale/core/dataset/store.py
- client/tests/core/test_dataset_store.py
> bug(client): fix too large indexed-size number for localFS make_file

- server/controller/src/main/java/ai/starwhale/mlops/api/DataStoreController.java
- server/controller/src/main/java/ai/starwhale/mlops/api/protocol/datastore/QueryTableRequest.java
- server/controller/src/main/java/ai/starwhale/mlops/api/protocol/datastore/TableDesc.java
- server/controller/src/main/java/ai/starwhale/mlops/datastore/DataStore.java
- server/controller/src/main/java/ai/starwhale/mlops/datastore/DataStoreQueryRequest.java
- server/controller/src/main/java/ai/starwhale/mlops/datastore/DataStoreScanRequest.java
- server/controller/src/main/java/ai/starwhale/mlops/datastore/MemoryTable.java
- server/controller/src/main/java/ai/starwhale/mlops/datastore/impl/MemoryTableImpl.java
- server/controller/src/test/java/ai/starwhale/mlops/api/DataStoreControllerTest.java
- Use timestamp ms as revision for scan and query
- Ignore the entry with the key only which does not match the revision when scan
> chore(controller): datastore query and scan api support revision

- client/starwhale/core/dataset/cli.py
- client/starwhale/core/eval/cli.py
- client/starwhale/core/model/cli.py
- docs/i18n/zh/docusaurus-plugin-content-docs/current/evaluation/api/cli.md
- hidden some options in the `--help` output, but they can work, and reduce learning costs for the users.
> chore(client): make the internal options hidden in the `--help` output

- client/starwhale/api/_impl/dataset/builder/mapping_builder.py
- client/starwhale/api/_impl/dataset/model.py
- client/starwhale/core/dataset/cli.py
- client/starwhale/core/dataset/model.py
- client/starwhale/core/dataset/type.py
- client/tests/core/test_dataset.py
- client/tests/sdk/test_dataset.py
- client/tests/sdk/test_dataset_sdk.py
- docs/i18n/zh/docusaurus-plugin-content-docs/current/dataset/concepts.md
- example/mnist/dataset.yaml
- related: #1940 
- changes:
- remove useless data_mime_type for dataset data
- support with_builder_blob_config function for dataset sdk
- support volume_size and alignment_size options for `swcli dataset build` command.
- depends on: 
- https://github.com/star-whale/starwhale/pull/2019
> feat(dataset): support dataset blob attributes

- client/starwhale/api/_impl/dataset/model.py
- client/starwhale/base/cloud.py
- client/starwhale/core/dataset/model.py
- client/starwhale/core/dataset/type.py
- client/starwhale/core/project/view.py
- client/tests/base/test_cloud.py
- client/tests/core/test_dataset.py
- client/tests/sdk/test_dataset_sdk.py
- client/tests/sdk/test_evaluation.py
- client/tests/sdk/test_loader.py
- changes:
- replace dataset_byte_size with blobs_byte_size
- add increased_blobs_byte_size into DatasetSummary
- issue: #1940 
- depends on:
-  https://github.com/star-whale/starwhale/pull/2019
> feat(dataset):add more info into dataset summary

- client/starwhale/api/_impl/dataset/model.py
- client/tests/sdk/test_dataset_sdk.py
- create modes:
- `auto` mode: If the dataset already exists, creation is ignored. If it does not exist, the dataset is created automatically.
- `empty` mode: If the dataset already exists, an Exception is raised; If it does not exist, an empty dataset is created. This mode ensures the creation of a new, empty dataset.
- `forbid` mode: If the dataset already exists, nothing is done.If it does not exist, an Exception is raised. This mode ensures the existence of the dataset.
- create mode can help users to ensure the dataset empty or existence.
- related issue:  #1940
> feat(dataset): add create mode argument for dataset sdk

- client/starwhale/api/_impl/data_store.py
- client/tests/sdk/test_data_store.py
- client/tests/sdk/test_track.py
Compress data store table file
> chore(client): compress data store table file

- server/controller/src/main/java/ai/starwhale/mlops/datastore/parquet/SwOutputFile.java
- server/controller/src/test/java/ai/starwhale/mlops/datastore/parquet/SwOutputFileTest.java
> fix(datastore): check IOException when closing a parquet file

- client/starwhale/api/_impl/data_store.py
- client/tests/sdk/test_data_store.py
Data store support deep copy when scan and insert
- insert : always deep copy
- scan: deep copy by default, can be set to false by setting the `SW_DATASTORE_SCAN_DEEP_COPY` env to any string but "true" (case insensitive)
> chore(client): data store support deep copy when scan and insert

- README.md
- client/starwhale/core/runtime/cli.py
- client/starwhale/core/runtime/model.py
- client/starwhale/core/runtime/process.py
- client/starwhale/core/runtime/view.py
- client/tests/core/test_runtime.py
- docs/docs/examples/ucf101.md
- docs/docs/getting-started/runtime.md
- docs/docs/instances/standalone/getting_started.md
- docs/docs/reference/swcli/runtime.md
- docs/docs/runtime/api/cli.md
- docs/i18n/zh/docusaurus-plugin-content-docs/current/examples/ag_news.md
- docs/i18n/zh/docusaurus-plugin-content-docs/current/examples/cifar10.md
- docs/i18n/zh/docusaurus-plugin-content-docs/current/examples/mnist.md
- docs/i18n/zh/docusaurus-plugin-content-docs/current/examples/nmt.md
- docs/i18n/zh/docusaurus-plugin-content-docs/current/examples/pfp.md
- docs/i18n/zh/docusaurus-plugin-content-docs/current/examples/speech.md
- docs/i18n/zh/docusaurus-plugin-content-docs/current/examples/ucf101.md
- docs/i18n/zh/docusaurus-plugin-content-docs/current/getting-started/runtime.md
- docs/i18n/zh/docusaurus-plugin-content-docs/current/instances/standalone/getting_started.md
- docs/i18n/zh/docusaurus-plugin-content-docs/current/reference/swcli/runtime.md
- docs/i18n/zh/docusaurus-plugin-content-docs/current/runtime/api/cli.md
- example/notebooks/quickstart-standalone.ipynb
- changes:
- hide `swcli runtime restore` command for users in the help output.
- make `swcli runtime activate` command enable to restore runtime automatically. 
- demo:
- ![image](https://user-images.githubusercontent.com/590748/230361395-335f671c-1110-4bde-9220-615cdbc6690f.png)
> feat(runtime): enable runtime activate command restore automatically

- client/starwhale/base/cloud.py
- client/starwhale/core/runtime/cli.py
- client/starwhale/core/runtime/model.py
- client/starwhale/core/runtime/view.py
- client/tests/core/test_runtime.py
- docs/docs/reference/swcli/runtime.md
- docs/i18n/zh/docusaurus-plugin-content-docs/current/reference/swcli/runtime.md
[![asciicast](https://asciinema.org/a/576532.svg)](https://asciinema.org/a/576532)
```shell
❯ swcli runtime info --help
Usage: swcli runtime info [OPTIONS] RUNTIME
Show runtime details
RUNTIME: argument use the `Runtime URI` format. Version is optional for the
Runtime URI. If the version is not specified, the latest version will be
used.
Example:
swcli runtime info pytorch # show basic info from the latest version of runtime
swcli runtime info pytorch/version/v0  # show basic info
swcli runtime info pytorch/version/v0 --output-filter basic  # show basic info
swcli runtime info pytorch/version/v1 -of runtime_yaml  # show runtime.yaml content
swcli runtime info pytorch/version/v1 -of lock # show auto lock file content
swcli runtime info pytorch/version/v1 -of manifest # show _manifest.yaml …
```
> feat(runtime): support output filter for runtime info

- example/datasets/LLM/z_bench/README.md
- example/datasets/LLM/z_bench/dataset.py
- example/datasets/LLM/z_bench/example.py
https://github.com/zhenbench/z-bench
> example(dataset): ds z bench

- client/scripts/sw-docker-entrypoint
> fix(client): extract python version when use runtime info

- server/controller/src/main/java/ai/starwhale/mlops/api/SystemApi.java
- server/controller/src/main/java/ai/starwhale/mlops/api/SystemController.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/system/SystemService.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/upgrade/UpgradeService.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/upgrade/step/BackupDatabase.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/upgrade/step/StepTask.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/upgrade/step/UpdateK8sImage.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/upgrade/step/UpgradeStep.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/upgrade/step/UpgradeStepManager.java
> fix(controller): optimize upgrade/cancel upgrading api and fix some bugs

- client/starwhale/api/_impl/dataset/model.py
- client/tests/core/test_dataset.py
- example/datasets/LLM/GraphQuestions/README.md
- example/datasets/LLM/GraphQuestions/dataset.py
- example/datasets/LLM/GraphQuestions/example.py
- example/datasets/LLM/z_bench/dataset.py
- example/datasets/LLM/z_bench/example.py
1. add graph_questions_testing dataset
2.  add dataset util function `from_dict`
> example(GraphQuestions): add graph_questions_testing dataset

- client/starwhale/core/runtime/cli.py
- client/starwhale/core/runtime/model.py
- client/starwhale/core/runtime/view.py
- client/tests/core/test_runtime.py
- scripts/client_test/cmds/artifacts_cmd.py
- build from multi-sources
- build from conda name or conda_prefix without runtime.yaml
```bash
swcli runtime build -c pytorch # lock pytorch conda environment and use `pytorch` as the runtime name                                                                                                                                                                   
swcli runtime build --conda pytorch --name pytorch-runtime # use `pytorch-runtime` as the runtime name                                                                                                                                                                  
swcli runtime build --conda pytorch --cuda 11.4 # specify the cuda version …
```
> feat(runtime): support `swcli runtime build` from multi sources

- client/starwhale/api/_impl/data_store.py
Fix issue
``` python
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
File "/home/foo/work/repo/starwhale/client/starwhale/api/_impl/data_store.py", line 999, in dump
return self._dump(root, if_dirty)
File "/home/foo/work/repo/starwhale/client/starwhale/api/_impl/data_store.py", line 1031, in _dump
os.rename(compressed, new_dst)
OSError: [Errno 18] Invalid cross-device link: '/tmp/tmpcdimdctd' -> '/home/foo/.starwhale/.datastore/project/self/dataset/mnist/_current/meta.sw-datastore.zip'
```
```bash
df -T
Filesystem     Type     1K-blocks      Used Available Use% Mounted on
dev            devtmpfs  15807652         0  15807652   0% /dev
run            tmpfs     15827352      1948  15825404   1% /run
/dev/nvme0n1p5 ext4     283661824 206080776  63098772  77% /
tmpfs …
```
> fix(datastore): fix rename issue after table file compress

- client/starwhale/core/runtime/model.py
- client/tests/core/test_runtime.py
In the runtime bundle, we use the default runtime.yaml name to store user raw runtime build definitions.
> bug(runtime): fix non-default runtime.yaml name build and info issue

- example/datasets/LLM/MKQA/README.md
- example/datasets/LLM/MKQA/dataset.py
- example/datasets/LLM/MKQA/example.py
- example/datasets/LLM/MKQA/requirements.txt
> example(dataset): add MKQA Dataset

- server/controller/src/main/java/ai/starwhale/mlops/configuration/security/TaskTokenValidator.java
The token may be treated as invalid in this condition:
- Task ready
- Pod start
- Pod failed
- New pod created (pending)
- Task status changed from running to preparing
- The `TaskTokenValidator` treat the token as invalid
> fix(controller): the token may be treated as invalid if the pod is pending in eval

- server/controller/src/main/java/ai/starwhale/mlops/datastore/parquet/SwWriteSupport.java
- server/controller/src/test/java/ai/starwhale/mlops/datastore/parquet/ParquetReadWriteTest.java
> fix(datastore): sort attributes by names when creating parquet types

- server/controller/src/main/java/ai/starwhale/mlops/domain/runtime/RuntimeService.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/system/resourcepool/bo/ResourcePool.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/system/resourcepool/bo/Toleration.java
- server/controller/src/main/java/ai/starwhale/mlops/schedule/k8s/K8sJobTemplate.java
- server/controller/src/main/java/ai/starwhale/mlops/schedule/k8s/K8sTaskScheduler.java
- server/controller/src/test/java/ai/starwhale/mlops/schedule/k8s/K8sJobTemplateTest.java
- server/controller/src/test/java/ai/starwhale/mlops/schedule/k8s/K8sTaskSchedulerTest.java
Demo resource pool settings:
```yaml
resourcePoolSetting:
- name: "default"
nodeSelector:
kubernetes.io/hostname: "starwhale-vk-node"
resources:
- name: "nvidia.com/gpu"
max: 2.0
min: 1.0
defaults: 0.0
- name: "memory"
max: 10240.0
min: 1024.0
defaults: 2048.0
tolerations:
- key: "virtual-kubelet.io/provider"
operator: "Equal"
value: "starwhale"
effect: "NoSchedule"
```
> feat(controller): resource pool support tolerations

- client/starwhale/api/_impl/data_store.py
- client/starwhale/utils/retry.py
- client/tests/utils/test_common.py
Always retry when updating the remote data store even if the exception is raised (such as `socket.timeout`)
> chore(client): always retry when updating remote data store

- client/starwhale/core/model/cli.py
- client/starwhale/core/model/model.py
- client/starwhale/core/model/view.py
- client/starwhale/core/runtime/cli.py
- client/starwhale/core/runtime/model.py
- client/tests/core/test_model.py
- docs/docs/reference/swcli/model.md
- docs/i18n/zh/docusaurus-plugin-content-docs/current/reference/swcli/model.md
- docs/i18n/zh/docusaurus-plugin-content-docs/current/reference/swcli/runtime.md
- changes:
- support `--output-filter` option for `swcli model info` command
- command help:
```console
❯ swcli model info --help
Usage: swcli model info [OPTIONS] MODEL
Show model details.
MODEL: argument use the `Model URI` format. Version is optional for the
Model URI. If the version is not specified, the latest version will be used.
Example:
swcli model info mnist # show basic info from the latest version of model
swcli model info mnist/version/v0 # show basic info from the v0 version of model
swcli model info mnist/version/latest --output-filter=all # show all info
swcli model info mnist -of basic # show basic info
swcli model info mnist -of manifest # show manifest.yaml
swcli model info mnist -of model_yaml  # show model.yaml
swcli model info mnist -of handlers # show model runnable …
```
> feat(client): support swcli model info command for output filter

- .github/workflows/e2e-test.yml
- scripts/client_test/cli_test.py
- scripts/e2e_test/start_test.sh
- changes:    
- add timeout for client test
- ignore kubectl port-forward useless log
- add post run for client test, which will show all jobs log
- add retry for remote job status checking
> enhance(e2e): tune github e2e run logs

- scripts/client_test/cli_test.py
- scripts/client_test/cmds/artifacts_cmd.py
> bug(e2e): fix runtime build for e2e with no cache config

- server/controller/src/main/java/ai/starwhale/mlops/datastore/ColumnSchema.java
- server/controller/src/test/java/ai/starwhale/mlops/datastore/TableSchemaTest.java
- server/controller/src/test/java/ai/starwhale/mlops/datastore/impl/MemoryTableImplTest.java
```bash
[update-table]Table:project/2/dataset/webqsp/_current/meta, resp code:500,                                                                                                          
resp text: {"code":"internalServerError","message":"No enum constant ai.starwhale.mlops.datastore.ColumnType.","data":null},                                                                                        
records: [{'id': 2, 'features/questionid': 'WebQTest-3', 'features/rawquestion': 'who plays ken barlow in coronation street?', 'features/processedquestion': 'who plays ken barlow in coronation street', 'features/
parses': [<starwhale.core.dataset.type.JsonDict object at 0x7f102b4ad7d0>]}] 
```
> fix(datastore): error when update table schema

- client/starwhale/api/_impl/dataset/model.py
- client/starwhale/base/bundle_copy.py
- client/starwhale/base/type.py
- client/starwhale/core/dataset/cli.py
- client/starwhale/core/dataset/copy.py
- client/starwhale/core/dataset/model.py
- client/starwhale/core/dataset/view.py
- client/tests/base/test_copy.py
- client/tests/sdk/test_dataset.py
- client/tests/sdk/test_dataset_sdk.py
- scripts/client_test/cli_test.py
- scripts/client_test/cmds/artifacts_cmd.py
- changes:
- support `--patch`/`--overwrite` options for dataset copy command
- support copy into the remote existed dataset.
- support `--force` option for copy the existed dataset version.
- demo show:
- ![SPdHXm704m](https://user-images.githubusercontent.com/590748/234527648-a6000551-02f6-4ff3-83f8-7c68bcd90d15.jpg)
- ![image](https://user-images.githubusercontent.com/590748/234532377-030913db-fde3-44a2-84c3-8fd09db4fec6.png)
> feat(dataset): support `--patch`/`--overwrite` options for dataset copy command

- server/controller/src/main/java/ai/starwhale/mlops/datastore/WalManager.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/model/ModelService.java
- server/storage-access-layer/src/main/java/ai/starwhale/mlops/storage/aliyun/StorageAccessServiceAliyun.java
The reason: we forgot to close the input stream when reading lots of wal file
Fixes:
- make aliyun client timeout enabled
- close the input streams
> fix(controller): the startup hangs when loading lots of wal files

- .github/workflows/client.yaml
- client/starwhale/api/_impl/job.py
- client/starwhale/api/_impl/model.py
- client/starwhale/base/bundle.py
- client/starwhale/core/model/model.py
- client/starwhale/utils/__init__.py
- client/tests/sdk/test_job.py
- client/tests/sdk/test_model.py
- example/mnist/mnist/plain_evaluator.py
- example/mnist/model2.yaml
- scripts/client_test/cli_test.py
- scripts/client_test/cli_test.sh
- scripts/client_test/cmds/base/invoke.py
- scripts/example/src/sdk_model_build.py
- changes:
- Unwrap decorated functions: @pass_context and other decorators can be added for the @handler functions.
- Ignore the `__main__` module.
- Tune related-rootdir search modules path for the imported modules scenario.
- Allow modle build function to be called at the module level, rather than in a cycle call scenario. See the example: https://asciinema.org/a/582707
- Clarify which modules require explicit arguments and which can be imported implicitly by the model build SDK.
- Update mnist example.
-  [![asciicast](https://asciinema.org/a/582707.svg)](https://asciinema.org/a/582707)
> enhance(sdk): enhance model build sdk for searching modules

- .github/workflows/client.yaml
- client/starwhale/api/_impl/job.py
- client/starwhale/api/_impl/model.py
- client/starwhale/base/bundle.py
- client/starwhale/core/model/model.py
- client/starwhale/utils/__init__.py
- client/tests/sdk/test_job.py
- client/tests/sdk/test_model.py
- example/mnist/mnist/plain_evaluator.py
- example/mnist/model2.yaml
- scripts/client_test/cli_test.py
- scripts/client_test/cli_test.sh
- scripts/client_test/cmds/base/invoke.py
- scripts/example/src/sdk_model_build.py
- changes:
- Unwrap decorated functions: @pass_context and other decorators can be added for the @handler functions.
- Ignore the `__main__` module.
- Tune related-rootdir search modules path for the imported modules scenario.
- Allow modle build function to be called at the module level, rather than in a cycle call scenario. See the example: https://asciinema.org/a/582707
- Clarify which modules require explicit arguments and which can be imported implicitly by the model build SDK.
- Update mnist example and add SDK e2e test.
-  [![asciicast](https://asciinema.org/a/582707.svg)](https://asciinema.org/a/582707)
>  enhance(sdk): enhance model build sdk for searching modules

- client/starwhale/api/_impl/evaluation.py
- client/starwhale/api/_impl/job.py
- client/starwhale/base/scheduler/task.py
- client/starwhale/core/job/view.py
- client/tests/sdk/test_evaluation.py
- client/tests/sdk/test_job.py
- example/cifar10/cifar/evaluator.py
- example/mnist/mnist/evaluator.py
- example/ucf101/ucf101/evaluator.py
- depends on: https://github.com/star-whale/starwhale/pull/2186
- for `PipelineHandler` Class
-  `ppl` -> `predict`, same name as @evaluation.predict decorator
-  `cmp` -> `evaluate`, same name as @evaluation.evaluate decorator
> chore(sdk): PipelineHandler support `predict` and `evaluate` function interface

- client/starwhale/core/model/cli.py
- client/starwhale/core/model/model.py
- client/starwhale/core/model/view.py
- client/tests/core/test_model.py
> bug(client): fix the expired jobs.yaml for workdir mode in the swcli model run command

- client/starwhale/api/_impl/data_store.py
- client/tests/sdk/test_data_store.py
- console/packages/starwhale-core/src/datastore/__tests__/model.test.ts
- console/packages/starwhale-core/src/datastore/model.ts
- server/controller/src/main/java/ai/starwhale/mlops/datastore/type/BaseValue.java
- server/controller/src/main/java/ai/starwhale/mlops/datastore/type/MapValue.java
- server/controller/src/test/java/ai/starwhale/mlops/api/DataStoreControllerTest.java
- server/controller/src/test/java/ai/starwhale/mlops/datastore/DataStoreTest.java
- server/controller/src/test/java/ai/starwhale/mlops/datastore/type/BaseValueTest.java
- Add type `UNKNOWN` for null value
- map encode with type return value layout changed
from 
```json
{
"type": "MAP",
"value":
{
"{type=INT8, value=01}":
{
"type": "INT16",
"value": "0002"
}
}
}
```
to 
```json
{
"type": "MAP",
"value":
[
{
"key":
{
"type": "INT8",
"value": "01"
},
"value":
{
"type": "INT16",
"value": "0002"
}
}
]
}
```
> chore(datastore): change map resp layout and add type for null value

- client/starwhale/utils/venv.py
- client/tests/core/test_runtime.py
> enhance(client): detect shell conda bin path at first

- client/starwhale/core/runtime/model.py
- client/starwhale/utils/venv.py
- client/tests/core/test_runtime.py
related: https://github.com/star-whale/starwhale/issues/2202
Runtime build from the existed env(conda/venv/shell) should make the pip nstalled packages compatible dependencies.
> chore(runtime): add pip compatible dependencies check for runtime build from existed env

- client/starwhale/api/_impl/data_store.py
- client/starwhale/base/bundle_copy.py
- client/starwhale/core/job/view.py
- client/starwhale/web/data_store.py
- client/starwhale/web/project.py
- client/tests/web/test_server.py
- console/src/components/BaseNavTabs.tsx
- console/src/hooks/useRouterActivePath.ts
- console/src/pages/Evaluation/EvaluationWidgetResults.tsx
- Fix generated URI for web browser
- Support `encodeWithType` and `rawResult` param in local fake server
> fix(client): web for job info works

- client/starwhale/base/uri/resource.py
- client/tests/base/test_copy.py
- client/tests/base/uri/test_resource.py
> fix(client): parse full uri with type hint failed

- client/starwhale/api/_impl/dataset/model.py
- client/starwhale/base/bundle_copy.py
- client/starwhale/base/uri/exceptions.py
- client/starwhale/base/uri/resource.py
- client/starwhale/base/view.py
- client/starwhale/core/model/view.py
- client/tests/base/test_copy.py
- client/tests/base/test_tag.py
- client/tests/base/uri/test_resource.py
- client/tests/core/test_dataset.py
- client/tests/core/test_dataset_store.py
- client/tests/core/test_eval.py
- client/tests/core/test_model.py
- client/tests/core/test_runtime.py
- client/tests/core/test_runtime_process.py
- client/tests/sdk/test_dataset.py
- client/tests/sdk/test_dataset_sdk.py
- client/tests/sdk/test_evaluation.py
- client/tests/sdk/test_loader.py
- scripts/client_test/cmds/artifacts_cmd.py
- Suppress the exception when refining the URI
- Do not set the resource version to `latest` when no version specified
> chore(client): do not refine by default when parse uri str

- client/starwhale/api/_impl/data_store.py
- client/tests/sdk/test_data_store.py
- example/PennFudanPed/pfp/evaluator.py
> fix(datastore): fix parsing type list to tuple

- client/starwhale/base/blob/store.py
- client/starwhale/core/model/model.py
- client/starwhale/utils/venv.py
- client/tests/base/test_store.py
- client/tests/core/test_runtime_process.py
> chore(client): ignore conda env by default when building model

- client/starwhale/api/_impl/data_store.py
- client/tests/web/test_server.py
> fix(datastore): fix faking object response of encoded type value

- client/starwhale/base/blob/store.py
- client/starwhale/core/model/model.py
- client/tests/base/test_store.py
- client/tests/core/test_model.py
For speech_command examples:
- previous: 1h
```
[2023-05-16 01:06:02.531850] 🔈 |DEBUG| cmd: ['swcli', 'project', 'select', 'self'], env: None
[2023-05-16 01:06:03.773885] 🔈 |DEBUG| cmd: ['swcli', 'model', 'build', '/starwhale/example/speech_command', '--name', 'speech_command'], env: {'SW_BUILD_BUNDLE_FIXED_VERSION_FOR_TEST': 'jhbt3dz673di6plwrpz5vng6xgmmgm5srjbepmgn'}
[2023-05-16 02:06:06.130374] 🔈 |DEBUG| cmd: ['swcli', 'model', 'copy', 'local/project/self/model/speech_command/version/jhbt3dz673di6plwrpz5vng6xgmmgm5srjbepmgn', 'cloud://server/project/starwhale', '--force'], env: None
```
- current: 14s
```console
❯ time swcli -vvv model build .
[2023-05-16 09:59:28.245063] 👾 verbosity: 3, log level: DEBUG
[2023-05-16 09:59:28.248410] 🚧 start to build ResourceType.model bundle... …
```
> enhance(client): tune copy dir performance without recording ignored files

- scripts/client_test/cli_test.py
> fix(e2e): can't find runtime when test all

- server/controller/src/main/java/ai/starwhale/mlops/domain/task/status/TaskStatusMachine.java
Before this pull request, when a `running` task is set to `canceled` the `TaskStatusMachine` considered it illegal. As a result, the logic that deletes the pod wouldn't be executed. This pull request makes this status transfer legal.
> fix: canceled job is not deleted

- client/starwhale/base/uri/resource.py
- client/starwhale/core/model/copy.py
- client/tests/base/test_copy.py
- client/tests/core/test_model.py
- client/tests/sdk/test_dataset.py
- client/tests/sdk/test_dataset_sdk.py
Determine whether the resource refined, judge whether the remote_info exists.
> fix(client): tune resource numberic limitation when refine

- client/starwhale/api/_impl/evaluation.py
- client/tests/sdk/test_evaluation.py
Tune predict result id from "{dataset_name}-{version}__#@#_{ds_index}" to "{dataset_id or name}__#@#_{ds_index}" in cloud and "{project}/{dataset name}__#@#_{ds_index}" in standalone
> fix(sdk): change the default id format for predict result

- server/controller/src/main/java/ai/starwhale/mlops/datastore/parquet/SwInputFile.java
> fix(datastore): parse parquet file on aliyun oss fail

- client/starwhale/utils/venv.py
- client/tests/core/test_runtime.py
current log for conda:
use conda `--quiet` to ignore the progress bar output.
> chore(client): tune conda log options for the pretty log output

- console/playwright/.env
- console/playwright/playwright.config.ts
- console/playwright/setup/index.ts
- console/playwright/tests/admin.spec.ts
- console/playwright/tests/auth.setup.ts
- console/playwright/tests/config.ts
- console/playwright/tests/guest.spec.ts
- console/playwright/tests/utils.ts
- console/src/domain/job/components/JobForm.tsx
- scripts/e2e_test/start_test.sh
> e2e(console): add ui test to daily e2e sh

- example/LLM/chatglm6b/download_model.py
- example/LLM/chatglm6b/evaluator.py
make chatglm6b model package could start without any model bin
> example: make chatglm6b model small

- console/Makefile
- console/packages/starwhale-ui/src/AutoResizer/GridResizer.tsx
- console/packages/starwhale-ui/src/GridTable/components/Query/ConfigSimpleQuery.tsx
- console/playwright/package.json
- console/playwright/yarn.lock
- console/src/pages/Evaluation/EvaluationListCard.tsx
- scripts/e2e_test/start_test.sh
* right rendered error when mode = 2
* add missing deps
> update(console): run e2e by docker for ci

- console/Makefile
- scripts/e2e_test/start_test.sh
> fix(e2e): resolve mount path when run docker in docker

- console/playwright/.env
- console/playwright/playwright.config.ts
- console/playwright/tests/auth.setup.ts
- console/src/domain/job/components/JobForm.tsx
- scripts/e2e_test/start_test.sh
> update(console): e2e test order, handler auto select

- console/playwright/playwright.config.ts
- console/playwright/tests/admin-project.spec.ts
- console/playwright/tests/admin-setting.spec.ts
- console/playwright/tests/guest-project.spec.ts
> refactor(console): split the e2e test case according to different scenarios

- server/controller/src/main/java/ai/starwhale/mlops/domain/job/JobService.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/ModelServingService.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/system/SystemSettingService.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/system/resourcepool/bo/ResourcePool.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/system/SystemSettingServiceTest.java
Add two fields to the Resource Pool:
- isPrivate (bool) makes the pool private, and can not be listed when `visibleUserIds` is not specified
- visibleUserIds (array of long), used to configure which users can access this pool
> feat(controller): support private resource pool

- client/starwhale/base/type.py
- client/starwhale/core/runtime/cli.py
- client/starwhale/core/runtime/model.py
- client/starwhale/core/runtime/view.py
- client/tests/core/test_runtime.py
- example/LLM/belle-bloom/runtime_conda.yaml
- scripts/example/runtime_conda.yaml
> feat(client): support condarc for runtime yaml

- client/starwhale/core/runtime/model.py
- client/starwhale/utils/venv.py
- client/tests/core/test_runtime.py
- client/tests/utils/test_venv.py
- scripts/example/runtime_conda.yaml
error message:
```
[2023-05-19 14:21:24.408722] 🔈 |DEBUG| conda install: 'cuda-toolkit=11.7.1' 'torch=2.0.1' 'pytorch-cuda=11.7'                                                                                                                                                                    
[2023-05-19 14:21:24.418724] 🔈 |DEBUG| cmd: ['/mnt/data/renyanda/anaconda3/bin/conda', 'install', '--prefix', '/mnt/data/tianwei/code/starwhale/example/LLM/belle-bloom/.starwhale/conda', '--channel', 'conda-forge', '--channel', 'nvidia/label/cuda-11.7.1', '--channel', 'pyt
orch', '--yes', '--override-channels', "'cuda-toolkit=11.7.1' 'torch=2.0.1' 'pytorch-cuda=11.7'"] …
```
> bug(client): fix multi conda pkgs installation error

- client/starwhale/base/cloud.py
- client/starwhale/core/instance/view.py
```
🚧 start to copy https://cloud.starwhale.cn/project/llm/model/mnist/version/6n33l65bniqduhtbm7zz6gxjjweh2ugie6izjdjy -> local/project/self/model/mnist/version/6n33l65bniqduhtbm7zz6gxjjweh2ugie6izjdjy
⬇ _manifest.yaml ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00 1 byte ?
⬇ src.tar        ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00 1 byte ?
⬇ mnist_cnn.pt   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00 1 byte ?
⬇ packaged.swrt  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00 1 byte ?
🍵 console url of the remote bundle: https://cloud.starwhale.cn/projects/llm/models/mnist/versions/6n33l65bniqduhtbm7zz6gxjjweh2ugie6izjdjy/overview
👏 copy done.
/opt/starwhale.venv/lib/python3.8/site-packages/urllib3/connectionpool.py:1045: InsecureRequestWarning: Unverified …
```
> chore(client): ignore urllib3 InsecureRequestWarning for http requests

- client/starwhale/core/model/cli.py
```
❯ swcli -vvv model run -w . --dataset mnist-mini                                                                                                                                                                                                                                  
[2023-05-31 16:41:03.291385] 👾 verbosity: 3, log level: DEBUG                                                                                                                                                                                                                    
[2023-05-31 16:41:03.295316] ✈ change current dir to /home/tianwei/code/starwhale/example/mnist …
```
> chore(client): forbid snapshot mechanism for model run in the workdir mode

- client/starwhale/base/bundle_copy.py
- client/starwhale/core/model/copy.py
> fix(client): wrong file path linked when model file exists in cache

- client/starwhale/consts/__init__.py
- client/starwhale/core/runtime/model.py
- client/tests/core/test_runtime.py
in runtime manifest.yaml
```
'docker': {
'builtin_run_image': {
'fullname': 'docker-registry.starwhale.cn/star-whale/starwhale:latest-cuda11.4',
'name': 'starwhale',
'repo': 'docker-registry.starwhale.cn/star-whale',
'tag': 'latest-cuda11.4'
},
'custom_run_image': ''
},
```
> chore(client): refactor runtime docker image info

- server/controller/src/main/java/ai/starwhale/mlops/StarwhaleControllerApplication.java
- server/controller/src/main/java/ai/starwhale/mlops/api/JobController.java
- server/controller/src/main/java/ai/starwhale/mlops/api/SystemApi.java
- server/controller/src/main/java/ai/starwhale/mlops/api/SystemController.java
- server/controller/src/main/java/ai/starwhale/mlops/api/protocol/system/FeaturesVo.java
- server/controller/src/main/java/ai/starwhale/mlops/api/protocol/system/LatestVersionVo.java
- server/controller/src/main/java/ai/starwhale/mlops/configuration/FeaturesProperties.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/system/SystemService.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/system/SystemSettingService.java
- server/controller/src/main/resources/application.yaml
- server/controller/src/test/java/ai/starwhale/mlops/api/JobControllerTest.java
- Online eval can be disabled with the starting up env
- Add API (/system/features) for querying disabled features for the console, the demo response:
```json
{
"data": {
"disabled": [
"online-eval",
"foo"
]
}
}
```
cc @waynelwz
> feat(controller): online eval can be disabled

- client/starwhale/utils/fs.py
https://github.com/star-whale/starwhale/actions/runs/5140825504/jobs/9252653401?pr=2302#step:8:452
```
_______________________ TestPytorch.test_image_transform _______________________
self = <tests.sdk.test_dataset_sdk.TestPytorch testMethod=test_image_transform>
def setUp(self) -> None:
>       super().setUp()
tests/sdk/test_dataset_sdk.py:47: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
tests/__init__.py:26: in setUp
self.datastore_root = str(sw_config.SWCliConfigMixed().datastore_dir)
starwhale/utils/config.py:111: in __init__
self._config = swcli_config or load_swcli_config()
starwhale/utils/config.py:46: in load_swcli_config
_config = render_default_swcli_config(fpath)
starwhale/utils/config.py:86: in render_default_swcli_config …
```
> fix(client): fix race condition in unit test

- server/controller/src/main/java/ai/starwhale/mlops/domain/task/status/watchers/TaskWatcherForSchedule.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/task/status/watchers/log/CancellableTaskLogK8sCollector.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/task/status/watchers/log/TaskLogK8sCollector.java
- server/controller/src/main/java/ai/starwhale/mlops/schedule/SwTaskScheduler.java
- server/controller/src/main/java/ai/starwhale/mlops/schedule/k8s/K8sClient.java
- server/controller/src/main/java/ai/starwhale/mlops/schedule/k8s/K8sTaskScheduler.java
- server/controller/src/main/java/ai/starwhale/mlops/schedule/k8s/PodEventHandler.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/task/TaskWatcherForScheduleTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/task/log/CancellableTaskLogK8sCollectorFactoryTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/task/log/CancellableTaskLogK8sCollectorTest.java
- server/controller/src/test/java/ai/starwhale/mlops/schedule/k8s/K8sClientTest.java
- server/controller/src/test/java/ai/starwhale/mlops/schedule/k8s/K8sTaskSchedulerTest.java
- Collect the pod log before deleting the job
- Use pod name as log file name (remove the timestamp)
> fix(controller): collect pod log before delete when cancel job

- console/src/api/ApiHeader.tsx
- console/src/api/WithAuth.tsx
- console/src/api/const.ts
- console/src/domain/project/hooks/useFetchProjectRole.tsx
- console/src/domain/setting/hooks/useSettings.ts
- console/src/domain/setting/hooks/useSystemFeatures.ts
- console/src/domain/setting/schemas/system.tsx
- console/src/domain/setting/services/system.ts
- console/src/hooks/global.ts
- console/src/pages/Job/JobListCard.tsx
- console/src/pages/Model/ModelListCard.tsx
- console/src/pages/Model/ModelVersionListCard.tsx
- console/src/pages/Project/ProjectLayout.tsx
- console/src/wdyr.ts
> feat(console): support global auth from system features

- server/controller/src/main/java/ai/starwhale/mlops/domain/task/converter/TaskConverter.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/task/TaskConverterTest.java
> fix(controller): task dev url typo

- example/LLM/bloom/download_model.py
- example/LLM/bloom/mt0xxl.py
add starwhale support for bigscience/mt0  fintune
> example(LLM): fintune bigscience/mt0 

- console/src/domain/job/schemas/task.tsx
- console/src/pages/Job/TaskListCard.tsx
- server/controller/src/main/java/ai/starwhale/mlops/api/protocol/task/TaskVo.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/dag/DagQuerier.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/bo/Job.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/step/bo/Step.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/task/bo/Task.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/task/converter/TaskConverter.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/task/mapper/TaskMapper.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/task/status/WatchableTask.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/task/status/watchers/TaskWatcherForPersist.java
- server/controller/src/main/java/ai/starwhale/mlops/reporting/ReportedTask.java
- server/controller/src/main/java/ai/starwhale/mlops/reporting/SimpleTaskModifyReceiver.java
- server/controller/src/main/java/ai/starwhale/mlops/schedule/k8s/JobEventHandler.java
- server/controller/src/main/java/ai/starwhale/mlops/schedule/k8s/PodEventHandler.java
- server/controller/src/main/java/ai/starwhale/mlops/schedule/k8s/Util.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/task/TaskConverterTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/task/TaskServiceTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/task/TaskWatcherForPersistTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/task/TaskWatcherForScheduleTest.java
- server/controller/src/test/java/ai/starwhale/mlops/reporting/TaskModifyReceiverImpTest.java
- server/controller/src/test/java/ai/starwhale/mlops/schedule/k8s/JobEventHandlerTest.java
- server/controller/src/test/java/ai/starwhale/mlops/schedule/k8s/PodEventHandlerTest.java
- Use the pod start time as the task start time
- User the K8s Job last success time or failed time as the task stop time
- Rename `createdTime` to `startedTime` and `stopTime` to `finishedTime` in TaskVo
- Make task status running when pod running (revert the schedule as running logic)
> chore(controller): use the start and stop time in workload

- console/src/domain/job/components/JobForm.tsx
- console/src/i18n/locales.ts
> chore(console): rename the display of builtin

- client/starwhale/core/runtime/model.py
- client/tests/core/test_runtime.py
- server/controller/src/main/java/ai/starwhale/mlops/common/DockerImage.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/ModelServingService.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/converter/JobBoConverter.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/runtime/RuntimeService.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/runtime/converter/RuntimeVersionConverter.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/runtime/po/RuntimeVersionEntity.java
- server/controller/src/test/java/ai/starwhale/mlops/common/DockerImageTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/job/JobBoConverterTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/job/ModelServingServiceTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/runtime/RuntimeServiceTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/runtime/RuntimeTestConstants.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/runtime/RuntimeVersionConverterTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/runtime/mapper/RuntimeVersionMapperTest.java
related:  #2305 #2306 
1. client: runtime dockerize use new image rule
2. server: runtime version's image support replace registry
> feat(runtime): support runtime replace image registry

- .github/workflows/client.yaml
related: https://github.com/actions/setup-python/issues/682
> chore(ci): workaround unittest raise bz2 import error issue

- client/starwhale/api/_impl/dataset/model.py
- client/starwhale/base/type.py
- client/starwhale/core/dataset/cli.py
- client/starwhale/core/dataset/model.py
- client/starwhale/core/dataset/type.py
- client/starwhale/core/dataset/view.py
- client/starwhale/core/runtime/cli.py
- client/tests/core/test_dataset.py
- client/tests/sdk/test_dataset_sdk.py
- scripts/client_test/cmds/artifacts_cmd.py
- refactor `swcli dataset build` command structure, supports multi building source.
- build from dataset.yaml
```
swcli dataset build
swcli dataset build --yaml /path/to/dataset.yaml
``` 
- build from python handler
```
swcli dataset build -w . --handler mnist.dataset:iter_mnist_item
swcli dataset build --handler mnist.dataset:iter_mnist_item
```
- build from image folder
```
swcli dataset build --image image-metadata-jsonl
```
- build from video folder
```
swcli dataset build --video /path/to/video
```
- build from audio folder 
```
swcli dataset build --audio /path/to/audio
```
- Dataset SDK supports `from_folder` method. 
- image folder build example:
- cloud datasets:
- https://cloud.starwhale.cn/projects/23/datasets/66/versions/94/files
- …
> feat(dataset): support dataset builf from audio/video/image folder

- client/starwhale/api/_impl/dataset/model.py
- client/starwhale/core/dataset/cli.py
- client/starwhale/core/dataset/model.py
- client/starwhale/core/dataset/view.py
- client/tests/core/test_dataset.py
```
❯ swcli -v dataset build --json-file WebQSP.test.json --field-selector Questions
👾 verbosity: 1, log level: WARN
🚧 start to build dataset bundle...
👷 uri local/project/self/dataset/WebQSP/version/veh6xbwpldgalaik7cwywzphny3bd6nsqaipcz7w
🦋 update 1639 records into dataset
🌺 congratulation! dataset build from WebQSP.test.json has been built. You can run  swcli dataset info WebQSP/version/nxvutlja75cs
```
> feat(client): support build dataset cli from json file

- client/starwhale/base/uri/resource.py
- client/tests/sdk/test_dataset_sdk.py
- related error:  create a non-existed dataset by dataset sdk.
> bug(client): fix dataset create for cloud instance error

- server/controller/src/main/java/ai/starwhale/mlops/datastore/type/ListValue.java
- server/controller/src/test/java/ai/starwhale/mlops/datastore/type/BaseValueTest.java
cc @tianweidut 
```
java.lang.NullPointerException: null
at ai.starwhale.mlops.datastore.type.ListValue.compareTo(ListValue.java:43) ~[classes!/:0.1.0-SNAPSHOT]
at ai.starwhale.mlops.datastore.type.ObjectValue.compareTo(ObjectValue.java:72) ~[classes!/:0.1.0-SNAPSHOT]
at ai.starwhale.mlops.datastore.type.BaseValue.compare(BaseValue.java:149) ~[classes!/:0.1.0-SNAPSHOT]
at ai.starwhale.mlops.datastore.impl.MemoryTableImpl.insertRecords(MemoryTableImpl.java:347) ~[classes!/:0.1.0-SNAPSHOT]
at ai.starwhale.mlops.datastore.impl.MemoryTableImpl.update(MemoryTableImpl.java:321) ~[classes!/:0.1.0-SNAPSHOT]
at ai.starwhale.mlops.datastore.DataStore.update(DataStore.java:160) ~[classes!/:0.1.0-SNAPSHOT]
at ai.starwhale.mlops.api.DataStoreController.updateTable(DataStoreController.java:111) …
```
> fix(datastore): list item may be null

- client/starwhale/core/runtime/view.py
- client/starwhale/utils/venv.py
- restore by Runtime URI:
```
❯ swcli runtime restore pytorch
🏌 try to restore python runtime environment: pytorch ...
🧮 setup python(3.9) env with venv...
👏 create venv@/home/tianwei/.starwhale/self/workdir/runtime/pytorch/z7/z7xiow2mwcb4afk2qpg2yvfc3gfm5wktbuy4ry4d/export/venv, python:3.9.13 (main, Oct 13 2022, 21:15:33) 
[GCC 11.2.0]
🍡 installing dependencies for pip_req_file:.starwhale/lock/requirements-sw-lock.txt in the venv environment
👏 activate.sw and activate.host is generated at /home/tianwei/.starwhale/self/workdir/runtime/pytorch/z7/z7xiow2mwcb4afk2qpg2yvfc3gfm5wktbuy4ry4d
6 out of 6 steps finished ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00 0:00:01
🍜 runtime(from uri:local/project/self/runtime/pytorch/version/z7xiow2mwcb4afk2qpg2yvfc3gfm5wktbuy4ry4d) has been …
```
> chore(client): tune runtime restore command output

- client/starwhale/core/dataset/cli.py
- client/starwhale/core/dataset/view.py
- client/tests/core/test_dataset.py
- simplify default output
- support `--show-types` option
- add more helpful info in the client help output
```
❯ swcli dataset head --help
Usage: swcli dataset head [OPTIONS] DATASET
Print the first n rows of the dataset
DATASET: argument use the `Dataset URI` format, so you can remove the whole
dataset or a specified-version dataset.
Examples:
- print the first 5 rows of the mnist dataset
swcli dataset head -n 5 mnist
- print the first 10 rows of the mnist(v0 version) dataset and show raw data
swcli dataset head -n 10 mnist/v0 --show-raw-data
- print the data types of the mnist dataset
swcli dataset head mnist --show-types
- print the remote cloud dataset's first 5 rows
swcli dataset head cloud://cloud-cn/project/test/dataset/mnist -n 5
Options:
-n, --rows INTEGER     Print the first …
```
> enhance(client): tune dataset head cli output

- client/starwhale/core/model/copy.py
> feat(client): add environment variables for model copy timeout and retries

- scripts/client_test/cli_test.py
- scripts/publish/pub.sh
The e2e always failed at code-server download of the docker build phase.
- before error:
- after fixed:
> chore(ci): add http proxy for e2e docker build

- docker/Dockerfile.base_e2e
-  in self-hosted e2e container:
```
root@3500d42c713c:/# echo "127.0.0.1 minio" | sudo tee -a /etc/hosts
bash: sudo: command not found
root@3500d42c713c:/# sudo cat /etc/hosts
bash: sudo: command not found
root@3500d42c713c:/# exot
bash: exot: command not found
```
- build error:
- success build:
> chore(ci): add sudo command for e2e base image

- .github/workflows/client.yaml
- scripts/client_test/cli_test.py
> chore(ci): enable client-e2e for mac osx

- client/starwhale/core/model/copy.py
- client/tests/base/test_copy.py
1. improve compression judgement logics
2. fix a boundary error when dealing with compressed chunks
3. fix FileExistsError when copy model with force
> bugfix(client): model copy compression and fileExisted issue

- .github/workflows/client.yaml
- client/requirements-dev.txt
- client/tests/sdk/test_dataset_sdk.py
pytorch/tensorflow has already supported 3.11:
- https://github.com/tensorflow/tensorflow/issues/58032
- https://github.com/pytorch/pytorch/issues/86566
> chore(ci): remove torch/tensorflow python3.11 unittest skip

- client/starwhale/core/model/copy.py
- server/controller/src/main/java/ai/starwhale/mlops/domain/model/ModelService.java
- server/controller/src/main/resources/application.yaml
- server/storage-access-layer/src/main/java/ai/starwhale/mlops/storage/LengthAbleInputStream.java
- server/storage-access-layer/src/test/java/ai/starwhale/mlops/storage/util/LengthAbleInputStreamTest.java
1. add read limit for LengthAbleInputStream
2. add http request retries for model copy
> bugfix(model): model copy retries and add read limit for LengthAbleInputStream

- server/controller/src/main/java/ai/starwhale/mlops/api/protocol/model/ModelInfoVo.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/model/ModelService.java
> chore(controller): remove unused property in model version

- server/controller/src/main/java/ai/starwhale/mlops/common/ProxyServlet.java
- server/controller/src/main/java/ai/starwhale/mlops/common/proxy/ModelServing.java
- server/controller/src/main/java/ai/starwhale/mlops/common/proxy/Service.java
- server/controller/src/main/java/ai/starwhale/mlops/common/proxy/WebServerInTask.java
- server/controller/src/main/java/ai/starwhale/mlops/configuration/FeaturesProperties.java
- server/controller/src/main/java/ai/starwhale/mlops/configuration/security/ProjectNameExtractorDataStoreMixed.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/ModelServingService.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/converter/JobConverter.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/task/converter/TaskConverter.java
- server/controller/src/test/java/ai/starwhale/mlops/common/ProxyServletTest.java
- server/controller/src/test/java/ai/starwhale/mlops/common/proxy/ModelServingTest.java
- server/controller/src/test/java/ai/starwhale/mlops/common/proxy/WebServerInTaskTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/job/converter/JobConverterTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/task/TaskConverterTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/task/TaskServiceTest.java
- ProxyServlet support proxying task web handler and vscode in dev mode
- Add feature switch `job-proxy`
- JobConverter and TaskConverter render the final URL with the job-proxy setting
https://github.com/star-whale/starwhale/assets/3217223/387f9bc7-0885-4b72-b250-5277683c7313
> enhance(controller): support dev mode proxy

- server/controller/src/main/java/ai/starwhale/mlops/common/proxy/WebServerInTask.java
- server/controller/src/main/java/ai/starwhale/mlops/configuration/security/ProjectNameExtractorDataStoreMixed.java
- server/controller/src/test/java/ai/starwhale/mlops/api/config/ProjectNameExtractorDataStoreMixedTest.java
- server/controller/src/test/java/ai/starwhale/mlops/common/proxy/WebServerInTaskTest.java
> fix(controller): runtime can not upload when user is not system admin

- server/controller/src/main/java/ai/starwhale/mlops/domain/job/JobService.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/status/JobStatus.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/status/JobStatusMachine.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/step/StepHelper.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/task/status/TaskStatus.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/task/status/TaskStatusMachine.java
- server/controller/src/main/java/ai/starwhale/mlops/reporting/SimpleTaskModifyReceiver.java
- server/controller/src/main/java/ai/starwhale/mlops/schedule/k8s/JobEventHandler.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/job/HotJobHolderImplTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/job/StatusRequirementTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/task/StepHelperTest.java
- server/controller/src/test/java/ai/starwhale/mlops/schedule/k8s/JobEventHandlerTest.java
- Use the start time of the pod if exists when the job is in the final state
- Use now as the stop time when cancelled
> refactor(controller): refine job start end time

- server/controller/src/main/java/ai/starwhale/mlops/api/DatasetApi.java
- server/controller/src/main/java/ai/starwhale/mlops/api/DatasetController.java
- server/controller/src/test/java/ai/starwhale/mlops/api/DatasetControllerTest.java
There are HEAD/POST method for endpoint `/project/{projectName}/dataset/{datasetName}/hashedBlob/{hash}` but there is no GET method.
before this por client still depends on legacy `/project/{projectUrl}/dataset/{datasetName}/version/{versionName}/file` endpoint after this PR `/project/{projectName}/dataset/{datasetName}/hashedBlob/{hash}` shall be used
> (controller) add dataset hashedblod download api

- client/starwhale/core/dataset/copy.py
- client/tests/sdk/test_dataset.py
depends on: https://github.com/star-whale/starwhale/pull/2420
```
❯ swcli -vvv dataset cp https://cloud.starwhale.cn/projects/12/datasets/23/versions/125/ . -dlp mnist-download --force
[2023-06-28 15:02:16.429311] 👾 verbosity: 3, log level: DEBUG
[2023-06-28 15:02:25.182327] 🚧 start to copy https://cloud.starwhale.cn/project/12/dataset/mnist/version/dwfma4n3w3pxjdnyjuvumwdtyyiq5hwmnkwtebyf -> local/project/mnist-download/dataset/mnist/version/dwfma4n3w3pxjdnyjuvumwdtyyiq5hwmnkwtebyf
[2023-06-28 15:02:25.184078] 🐦 preprocess artifacts link
[2023-06-28 15:02:40.560309] 🐱 try to download 1 blobs
[2023-06-28 15:02:48.612611] 🐴 dump dataset meta from src to dest
[2023-06-28 15:03:05.525905] 🦘 update dataset info
[2023-06-28 15:03:05.609765] 🐯 make version for dest instance
⬇ 10b228058ae7 …
```
> bug(client): fix dataset blob download api typo

- server/controller/src/main/java/ai/starwhale/mlops/api/DatasetController.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/storage/HashNamedObjectStore.java
- server/controller/src/test/java/ai/starwhale/mlops/api/DatasetControllerTest.java
fix: header is omitted by response stream
> fix(controller): header is omitted by response stream

- server/controller/src/main/java/ai/starwhale/mlops/domain/model/ModelService.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/model/ModelServiceTest.java
- server/storage-access-layer/src/main/java/ai/starwhale/mlops/storage/LengthAbleInputStream.java
```
handleInternalServerError /api/v1/project/starwhale/model/mnist/getFileData
java.io.IOException: closed                                                                                                                                     
at okio.RealBufferedSource$inputStream$1.read(RealBufferedSource.kt:154) ~[okio-2.8.0.jar!/:na]                                               
at java.base/java.io.FilterInputStream.read(FilterInputStream.java:133) ~[na:na]                                                                    
at ai.starwhale.mlops.storage.LengthAbleInputStream.read(LengthAbleInputStream.java:63) ~[storage-access-layer-0.1.0-SNAPSHOT.jar!/:0.1.0-SNAPSHOT]   
at java.base/java.io.SequenceInputStream.read(SequenceInputStream.java:199) ~[na:na] …
```
> fix(controller): read model file without compression fail

- server/controller/src/main/java/ai/starwhale/mlops/api/protocol/task/TaskVo.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/task/converter/TaskConverter.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/task/mapper/TaskMapper.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/task/po/TaskEntity.java
- server/controller/src/main/java/ai/starwhale/mlops/reporting/SimpleTaskModifyReceiver.java
- server/controller/src/main/java/ai/starwhale/mlops/schedule/k8s/JobEventHandler.java
- server/controller/src/main/resources/db/migration/v0_4_0/V0_4_0_008__add_task_fail_reason.sql
- server/controller/src/test/java/ai/starwhale/mlops/domain/task/mapper/TaskMapperTest.java
- server/controller/src/test/java/ai/starwhale/mlops/schedule/k8s/JobEventHandlerTest.java
Add `failedReason` fied in task list resp (may be null), demo:
```json
{
"data": {
"total": 2,
"list": [
{
"id": "78",
"uuid": "f2644658-cb81-46bc-ba22-f29e2ec87029",
"failedReason":  "ProviderFailed, failed to get instance configs"
},
...
```
cc @waynelwz
> chore(controller): add failed reason in task response

- console/packages/starwhale-core/src/datastore/constants.ts
- console/packages/starwhale-core/src/datastore/hooks/useDatastoreQueryParams.tsx
- console/packages/starwhale-core/src/editor/index.tsx
- console/packages/starwhale-core/src/widget/WidgetPlugin.tsx
- console/packages/starwhale-core/src/widget/WidgetRenderer.tsx
- console/packages/starwhale-core/src/widget/hooks/useWidget.tsx
- console/packages/starwhale-core/src/widget/index.tsx
- console/packages/starwhale-ui/src/DynamicSelector/Selector.tsx
- console/packages/starwhale-ui/src/GridTable/GridCombineTable.tsx
- console/packages/starwhale-ui/src/GridTable/components/Query/ConfigSimpleQuery.tsx
- console/packages/starwhale-ui/src/GridTable/components/ToolBar/index.tsx
- console/packages/starwhale-ui/src/GridTable/hooks/useGridQuery.tsx
- console/packages/starwhale-ui/src/GridTable/store/StoreUpdater/index.tsx
- console/packages/starwhale-ui/src/GridTable/store/store.ts
- console/packages/starwhale-ui/src/Search/FilterRenderer.tsx
- console/packages/starwhale-ui/src/Search/Search.tsx
- console/packages/starwhale-ui/src/Search/types.ts
- console/packages/starwhale-ui/src/Select/Select.tsx
- console/src/components/Editor/index.tsx
- console/src/domain/job/components/JobForm.tsx
- console/src/domain/job/components/JobStatusSelector.tsx
- console/src/i18n/locales.ts
- console/src/pages/Evaluation/EvaluationListCard.tsx
- console/src/styles/_global.scss
* Resolve the issue of project grid view configuration not resetting when switching.
* Add a map cache to store the current view of multiple projects.
* Fix the bug where the query component content does not reset.
* Modify the widget component by removing the register logic to prevent hot reload failures.
> feat(console): grid table search with IN by multi status, fix view switch problems

- client/Makefile
- client/requirements-dev.txt
- client/setup.py
- error: https://github.com/star-whale/starwhale/actions/runs/5440233912/jobs/9892964282
- reason:
- trio_typing:  https://github.com/python-trio/trio-typing/blob/master/trio_typing/plugin.py#L41
- trio: 
- https://github.com/python-trio/trio/pull/2478
- 0.22 was released at 2023.7.2
> bug(client): fix trio typing plugin not found error

- console/packages/starwhale-core/src/widget/WidgetFactory.tsx
- console/packages/starwhale-core/src/widget/WidgetModules.tsx
- console/packages/starwhale-core/src/widget/hooks/useWidget.tsx
- console/src/domain/model/services/modelVersion.ts
> fix(console): load widget init missing

- client/scripts/sw-docker-entrypoint
- client/starwhale/utils/debug.py
- client/tests/utils/test_common.py
- scripts/client_test/cmds/artifacts_cmd.py
- only show trackback locals in the trace mode
- provide `ENV_LOG_VERBOSE_COUNT` env to config log verbosity
- update the default level for tests: `trace` -> `debug`
> chore(client): show trackback locals in the trace mode

- client/starwhale/core/model/copy.py
- Show a lots of useless httpx info log
- Example: https://cloud.starwhale.cn/projects/12/evaluations/279/tasks
> chore(client): remove useless httpx verbose log

- server/controller/src/main/java/ai/starwhale/mlops/domain/dataset/DatasetService.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/model/ModelService.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/runtime/RuntimeService.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/dataset/DatasetServiceTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/model/ModelServiceTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/runtime/RuntimeServiceTest.java
> chore(controller): resource in private project can not be shared

- server/controller/src/main/java/ai/starwhale/mlops/domain/job/status/JobUpdateHelper.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/job/JobUpdateHelperTest.java
TaskWatcherForSchedule only listen CANCELLING status now, so it should be changed to CANCELLING
> fix(controller): fix running tasks under failed job is not cancled

- server/controller/src/main/java/ai/starwhale/mlops/common/DockerImage.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/runtime/RuntimeService.java
- server/controller/src/test/java/ai/starwhale/mlops/common/DockerImageTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/runtime/RuntimeVersionConverterTest.java
Replace the built-in image with the repoName(registry/org)
> fix(image): use the same logic with client when resolve image's repo

- server/controller/src/main/java/ai/starwhale/mlops/api/ProjectController.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/dataset/mapper/DatasetVersionMapper.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/dataset/po/DatasetVersionEntity.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/model/mapper/ModelVersionMapper.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/model/po/ModelVersionEntity.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/project/ProjectService.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/project/bo/Project.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/runtime/mapper/RuntimeVersionMapper.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/runtime/po/RuntimeVersionEntity.java
- server/controller/src/test/java/ai/starwhale/mlops/api/ProjectControllerTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/dataset/mapper/DatasetVersionMapperTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/model/mapper/ModelVersionMapperTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/project/ProjectServiceTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/runtime/mapper/RuntimeVersionMapperTest.java
> chore(controller): make all the shared resource unshared when project change to private

- client/starwhale/core/runtime/process.py
- client/tests/core/test_runtime_process.py
- scripts/client_test/cli_test.py
- scripts/e2e_test/start_test.sh
> bug(client): fix builtin runtime run error

- client/setup.py
- error:
- https://github.com/star-whale/starwhale/actions/runs/5503317419/jobs/10028401030
- https://github.com/star-whale/starwhale/actions/runs/5503317419/jobs/10028401966
- reason:pydantic recently was upgraded to 2.0.0, but broker and fastapi lib code only work with pydantic < 2.0.0
> chore(client): force to limit pydantic version < 2.0.0

- server/controller/src/main/java/ai/starwhale/mlops/schedule/k8s/PodEventHandler.java
- server/controller/src/test/java/ai/starwhale/mlops/schedule/k8s/PodEventHandlerTest.java
> fix(controller): task may be running after cancelled

- client/requirements-dev.txt
- client/starwhale/api/_impl/dataset/model.py
- client/starwhale/core/dataset/cli.py
- client/starwhale/core/dataset/model.py
- client/starwhale/core/dataset/view.py
- client/starwhale/integrations/huggingface/__init__.py
- client/starwhale/integrations/huggingface/dataset.py
- client/tests/core/test_dataset.py
- client/tests/sdk/test_dataset_sdk.py
- build mnist from huggingface repo:
- other examples
- https://cloud.starwhale.cn/projects/23/datasets/103/versions/143/files
- squad: 
- https://huggingface.co/datasets/squad  
- https://cloud.starwhale.cn/projects/23/datasets/101/versions/140/files 
- PolyAI/minds14
- https://huggingface.co/datasets/PolyAI/minds14
- https://cloud.starwhale.cn/projects/23/datasets/102/versions/142/files  
- lambdalabs/pokemon-blip-captions
- https://huggingface.co/datasets/lambdalabs/pokemon-blip-captions
- ![image](https://github.com/star-whale/starwhale/assets/590748/f0765346-cc14-4958-a331-e59f43545f28)
- https://cloud.starwhale.cn/projects/tianwei:llm/datasets/104/versions/144/files
> feat(dataset): support dataset build from huggingface dataset

- console/src/api/const.ts
- console/src/i18n/locales.ts
- console/src/pages/Job/JobListCard.tsx
> chore(console): add confirm when cancelling or pausing tasks

- client/starwhale/base/bundle_copy.py
- client/tests/base/test_copy.py
- server/controller/src/main/java/ai/starwhale/mlops/domain/runtime/RuntimeService.java
upload success when copy repeatly:
> fix(client): check if exists when upload built-in runtime in the progress of model copy

- client/starwhale/core/dataset/view.py
- client/starwhale/integrations/huggingface/dataset.py
- client/starwhale/utils/fs.py
- client/tests/sdk/test_dataset_sdk.py
- example/text_cls_AG_NEWS/dataset.yaml
- example/text_cls_AG_NEWS/tcan/dataset.py
- update hash digest size: 64 -> 32
- update text_cls_AG_NEWS dataset to use `starwhale.Text` type
- update huggingface dataset string/binary convert logical
> chore(client): update huggingface dataset string/binary convert logical

- docker/Dockerfile.server
- docker/Makefile
- Reuse the infra layer for the jar to reduce the docker image diff
- Disable the remote debug
- Prevent bundling multiple versions of console
> chore(controller): refine docker image building

- console/src/domain/job/components/ExposedLink.tsx
- console/src/domain/job/schemas/job.tsx
- console/src/pages/Job/JobListCard.tsx
- server/controller/src/main/java/ai/starwhale/mlops/api/protocol/job/ExposedLinkVo.java
- server/controller/src/main/java/ai/starwhale/mlops/api/protocol/job/JobVo.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/converter/JobConverter.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/step/ExposedType.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/job/converter/JobConverterTest.java
cc @xuchuan 
https://github.com/star-whale/starwhale/assets/3217223/5c45406c-9105-4946-aa8a-11790a5fcc15
> chore(controller): refine the exposed links

- docker/charts/templates/controller-deployment.yaml
- docker/charts/values.yaml
- server/controller/pom.xml
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/cache/HotJobHolderImpl.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/spec/JobSpecParser.java
- server/controller/src/main/resources/application.yaml
- server/controller/src/test/java/ai/starwhale/mlops/ObjectMockHolder.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/dataset/DatasetUploaderTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/job/HotJobHolderImplTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/model/ModelServiceTest.java
- server/pom.xml
- Support Prometheus metrics
- Add `job.cache.size` and `task.cache.size` metrics
> enhance(controller): support exporting prometheus metrics

- client/starwhale/api/_impl/data_store.py
- client/tests/core/test_dataset.py
related: https://github.com/star-whale/starwhale/issues/2510
> enhance(sdk): the localstore data will be auto dumpped when close the tablewriter

- client/.flake8
- client/pyproject.toml
- example/LLM/llama2/.gitignore
- example/LLM/llama2/README.md
- example/LLM/llama2/evaluation.py
- example/LLM/llama2/llama/__init__.py
- example/LLM/llama2/llama/generation.py
- example/LLM/llama2/llama/model.py
- example/LLM/llama2/llama/tokenizer.py
- example/LLM/llama2/runtime.yaml
- chat: https://cloud.starwhale.cn/projects/12/jobs/427/tasks
- evaluation:https://cloud.starwhale.cn/projects/12/evaluations/430/results
> example(LLM): support llama2 model evaluation

- server/controller/src/main/java/ai/starwhale/mlops/schedule/k8s/K8sJobTemplate.java
- server/controller/src/test/java/ai/starwhale/mlops/schedule/k8s/K8sJobTemplateTest.java
thanks @jckhang for catching this bug.
> fix(controller): merge annotations with the original in template

- example/notebooks/quickstart-standalone.ipynb
https://colab.research.google.com/github/tianweidut/starwhale/blob/hotfix/notebook/example/notebooks/quickstart-standalone.ipynb
> bug(example): fix quickstart notebook path bug

- server/controller/src/main/java/ai/starwhale/mlops/domain/dataset/DatasetService.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/evaluation/EvaluationService.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/JobDao.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/JobService.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/step/mapper/StepMapper.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/model/ModelService.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/runtime/RuntimeService.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/task/TaskService.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/PageTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/evaluation/EvaluationServiceTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/job/JobServiceTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/task/TaskServiceTest.java
> fix(controller): page not working

- docker/external/base-entrypoint.sh
- example/runtime/pytorch-e2e/requirements.txt
- scripts/client_test/update_controller_setting.sh
Fix the wrong environment in the e2e workflow.
- previous
- after tuned
> chore(e2e): install the correct version in e2e when run job

- server/controller/src/main/java/ai/starwhale/mlops/domain/filestorage/FileStorageService.java
- server/controller/src/main/resources/application.yaml
- server/controller/src/test/java/ai/starwhale/mlops/domain/filestorage/FileStorageServiceTest.java
1. oss object can't prefix with "/"
2. fix the path contains multi "/", such as: a//b/c.log
> fix(controller): oss path typo

- console/index.html
- console/vite.config.ts
> update(console): replace inject html

- server/controller/src/main/java/ai/starwhale/mlops/schedule/k8s/log/CancellableJobLogK8sCollector.java
- server/controller/src/test/java/ai/starwhale/mlops/schedule/k8s/log/CancellableJobLogK8sCollectorFactoryTest.java
- server/controller/src/test/java/ai/starwhale/mlops/schedule/k8s/log/CancellableJobLogK8sCollectorTest.java
> fix(controller): online log with the correct pod

- scripts/publish/image_sync.sh
Use `bash image_sync.sh` only and regctl would skip the tag which has already synced to the target repo.
> chore(script): record sync version to file

- docker/compose/Dockerfile.minikube_starter
- docker/compose/README.md
- docker/compose/compose.override.yaml
- docker/compose/compose.yaml
- docker/compose/start.sh
- docker/compose/stop.sh
- server/controller/src/main/java/ai/starwhale/mlops/StarwhaleControllerApplication.java
- server/controller/src/main/java/ai/starwhale/mlops/schedule/k8s/K8sClient.java
- server/controller/src/test/java/ai/starwhale/mlops/schedule/k8s/K8sClientTest.java
users could set up a server instance in the manner of docker compose
**Example**
```bash
./start.sh --global-ip 192.168.1.20
```
1. GPU is not supported
> feat: add support for setting up a server instance in the manner of docker compose

- console/playwright/tests/admin-project.spec.ts
> fix(console): disable task succeed status for  delay  case

- server/controller/src/main/java/ai/starwhale/mlops/api/protocol/dataset/DatasetInfoVo.java
- server/controller/src/main/java/ai/starwhale/mlops/api/protocol/dataset/DatasetVersionVo.java
- server/controller/src/main/java/ai/starwhale/mlops/api/protocol/model/ModelInfoVo.java
- server/controller/src/main/java/ai/starwhale/mlops/api/protocol/runtime/RuntimeInfoVo.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/dataset/DatasetService.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/dataset/converter/DatasetVersionVoConverter.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/model/ModelService.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/runtime/RuntimeService.java
- server/controller/src/test/java/ai/starwhale/mlops/api/DatasetControllerTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/dataset/DatasetServiceTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/model/ModelServiceTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/runtime/RuntimeServiceTest.java
Deleted the tiled version field in the structure and use the `ResourceVesionVo` instead
And then we can get the alias, latest, tags
> chore(controller): refine resource info vo

- client/starwhale/api/_impl/dataset/model.py
- client/starwhale/core/dataset/cli.py
- client/starwhale/core/dataset/model.py
- client/starwhale/core/dataset/view.py
- client/starwhale/integrations/huggingface/dataset.py
- client/tests/core/test_dataset.py
- client/tests/sdk/test_dataset_sdk.py
- changes:
- Processing all subsets automatically.
- Users can specify multi subsets.
- examples:
```bash
swcli dataset build --name cmmlu -hf haonan-li/cmmlu
```
- hf: https://huggingface.co/datasets/haonan-li/cmmlu
- starwhale: https://cloud.starwhale.cn/projects/12/datasets/132/versions/189/files?pageNum=1&pageSize=10
- ![image](https://github.com/star-whale/starwhale/assets/590748/794c7200-5f73-47ba-8d49-ca7c00774169)
> enhance(client): enhance dataset build from huggingface for subsets

- example/LLM/llama2/README.md
- example/LLM/llama2/build.py
- example/LLM/llama2/evaluation.py
- example/LLM/llama2/utils.py
- build other llama2 models: 7b/7b-chat/13b/13b-chat/70b/70b-chat
> example(LLM): build llama2 other base models

- console/packages/starwhale-ui/src/IconFont/index.tsx
- console/packages/starwhale-ui/src/Input/QueryInput.tsx
- console/src/domain/report/hooks/useReport.ts
- console/src/domain/report/schemas/report.ts
- console/src/domain/report/services/report.ts
- console/src/i18n/locales.ts
- console/src/pages/Project/ProjectSidebar.tsx
- console/src/pages/Report/ReportEdit.tsx
- console/src/pages/Report/ReportListCard.tsx
- console/src/pages/Report/ReportOverviewLayout.tsx
- console/src/routes.tsx
> feat(console): report list card

- server/controller/src/main/java/ai/starwhale/mlops/domain/report/mapper/ReportMapper.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/report/ReportMapperTest.java
> fix(controller): report revert error

- scripts/e2e_test/remove_test_env.sh
Config the whitelist in file: ~/.config/e2e.config, the content like this:
```txt
[default]
white_list=e2e-0810,e2e-0811
```
> chore(e2e): add white list for e2e clean script

- client/starwhale/base/cloud.py
- client/starwhale/base/view.py
- client/starwhale/core/dataset/view.py
- client/tests/base/test_cloud.py
[![asciicast](https://asciinema.org/a/602785.svg)](https://asciinema.org/a/602785)
> enhance(client): refactor model/dataset/runtime list for server and cloud instance

- server/controller/src/main/java/ai/starwhale/mlops/datastore/DataStore.java
- server/controller/src/main/resources/application.yaml
> chore(controller):tune dump period and add more logs

- console/playwright/tests/admin-project.spec.ts
> fix(console): e2e should have model of mnist with multi tag named mnist

- .github/workflows/release.yml
- scripts/publish/image_sync.sh
- server/controller/src/main/resources/application.yaml
The dataset build will install starwhale and it's dependencies at first if use the image of base, so build an image that already installed starwhale which version is the same with server would speed up the build time.
> chore(workflow):add dataset builder to release action

- server/controller/src/main/java/ai/starwhale/mlops/domain/runtime/RuntimeService.java
fix the error in kaniko when image containers Upper case like 'star-whale/Stable-diffusion-v1-4':
`error checking push permissions -- make sure you entered the correct tag name, and that you are authenticated correctly, and try again: getting tag for destination: repository can only contain the characters abcdefghijklmnopqrstuvwxyz0123456789_-./`
> fix(controller): use lower case name in image build

- server/controller/src/main/java/ai/starwhale/mlops/schedule/impl/docker/log/TaskLogStreamingCollectorDocker.java
- server/controller/src/test/java/ai/starwhale/mlops/schedule/impl/docker/log/TaskLogStreamingCollectorDockerTest.java
> fix(controller): prevent readLine quit before read all log lines

- client/Makefile
- client/requirements-dev.txt
- issue:  https://github.com/star-whale/starwhale/actions/runs/5995061241/job/16257541837
- reason:  fastapi upgrade `fastapi-0.101.1` -> `fastapi-0.103.0`
- use the latest mypy version to fix the internal error
> chore(ci): upgrade mypy related libs version

- server/controller/src/main/java/ai/starwhale/mlops/domain/task/status/watchers/TaskWatcherForSchedule.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/task/TaskWatcherForScheduleTest.java
cc @tianweidut 
There occurs an error when create job（scheduled failed because of resource problem）:
```
483360 ^[[2m2023-08-28 15:09:10.851^[[0;39m ^[[31mERROR [star-whale-controller,fe57fd63928c93c9,fe57fd63928c93c9]^[[0;39m ^[[35m7^[[0;39m ^[[2m---^[[0;39m ^[[2m[nio-8082-exec-1]^[[0;39m ^[[36ma.s.m.c.CommonExceptionHandler          ^[[0;39m ^[[2m:^[[0;       39m handleInternalServerError /api/v1/project/349/job
483361
483362
483363 java.lang.NullPointerException: null
483364         at ai.starwhale.mlops.domain.task.status.watchers.TaskWatcherForSchedule.addToDeleteQueue(TaskWatcherForSchedule.java:96) ~[classes/:0.1.0-SNAPSHOT]
483365         at ai.starwhale.mlops.domain.task.status.watchers.TaskWatcherForSchedule.onTaskStatusChange(TaskWatcherForSchedule.java:87) …
```
> fix(controller): save to db failed on the stage of create job

- server/controller/src/main/java/ai/starwhale/mlops/datastore/impl/MemoryTableImpl.java
- server/controller/src/test/java/ai/starwhale/mlops/datastore/impl/MemoryTableImplTest.java
> bugfix(datastore): filter out empty records in query results

- server/controller/src/main/java/ai/starwhale/mlops/domain/job/JobServiceForWeb.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/cache/JobLoader.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/task/bo/Task.java
- server/controller/src/main/java/ai/starwhale/mlops/schedule/impl/docker/ContainerTaskMapper.java
- server/controller/src/main/java/ai/starwhale/mlops/schedule/impl/docker/SwTaskSchedulerDocker.java
- server/controller/src/main/java/ai/starwhale/mlops/schedule/impl/docker/reporting/DockerTaskReporter.java
- server/controller/src/main/java/ai/starwhale/mlops/schedule/impl/k8s/JobEventHandler.java
- server/controller/src/main/java/ai/starwhale/mlops/schedule/impl/k8s/K8sJobTemplate.java
- server/controller/src/main/java/ai/starwhale/mlops/schedule/impl/k8s/K8sSwTaskScheduler.java
- server/controller/src/main/java/ai/starwhale/mlops/schedule/impl/k8s/Util.java
- server/controller/src/main/java/ai/starwhale/mlops/schedule/impl/k8s/reporting/PodEventHandler.java
- server/controller/src/main/java/ai/starwhale/mlops/schedule/reporting/ReportedTask.java
- server/controller/src/main/java/ai/starwhale/mlops/schedule/reporting/SimpleTaskReportReceiver.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/job/JobLoaderTest.java
- server/controller/src/test/java/ai/starwhale/mlops/reporting/TaskReportReceiverImpTest.java
- server/controller/src/test/java/ai/starwhale/mlops/schedule/impl/k8s/K8sSwTaskSchedulerTest.java
Resume a failed job will make the job status become `canceled`
<hr/>
**The Reason**:
before resume:
- Job status is `fail`
- Step status is `fail`
resume action do the following actions:
1. change all the failed (paused, canceled) tasks to the `ready` state
2. deploy the `ready` tasks
the `deploy` will try to delete the existing k8s job and then deploy the task
and then the `JobEventHandler` will receive a k8s job deletion event and change the step status to `canceled` (calc via `StepHelper.desiredStepStatus`)
then `JobStatusCalculator.desiredJobStatus` will return `canceled`
> fix(controller): resume can not work if delay deletion is configured

- server/controller/src/main/resources/application.yaml
1. doc: https://docs.spring.io/spring-boot/docs/2.7.9/reference/html/howto.html#howto.webserver.enable-response-compression
2. default MIME types are:[text/html, text/xml, text/plain, text/css, text/javascript, application/javascript, application/json, application/xml]
3.
> chore(controller): enable compression for web server

- console/packages/starwhale-core/src/datastore/hooks/useDatastorePage.tsx
- console/packages/starwhale-core/src/store/store.ts
- console/packages/starwhale-ui/src/AutoResizer/GridResizerVertical.tsx
- console/packages/starwhale-ui/src/Pagination/Pagination.tsx
- console/packages/starwhale-ui/src/TiptapEditor/index.tsx
- console/packages/starwhale-widgets/src/SectionWidget/component/ChartConfigGroup.tsx
- console/packages/starwhale-widgets/src/SectionWidget/component/ChartConfigPopover.tsx
- console/packages/starwhale-widgets/src/SectionWidget/index.tsx
- console/src/App.tsx
- console/src/api/Auth.tsx
- console/src/api/index.ts
- console/src/i18n/locales.ts
- console/src/main.tsx
- console/src/pages/Evaluation/EvaluationListCard.tsx
1. Fixed scantable paging errors caused by the number of pages that can be modified
2. Optimize grid icon and chart icon to add tooltip
3. Fixed an issue where the tiptap editor default role caused the internal selector to fail
4. Fixed the existing token exception caused by report preview public token and adjusted it to an independent token logic
5. Optimizes translation dev mode and currency decimal when creating job
> chore(console):  tiptap editor default role caused the internal selector  disabled, report preview error, etc

- scripts/e2e_test/start_test.sh
since upgrade feature can't be used boldly, remove it from e2e
> e2e: remove upgrade test from e2e

- client/starwhale/core/runtime/model.py
- client/starwhale/utils/venv.py
- client/tests/core/test_runtime.py
- Support custom starwhale version in yaml.
- Support `git+https...` format with version.
Details:
1. The effective priority is: 
`environment.starwhale_version in yaml > starwhale dependency in requirements > current starwhale.`
2. Build with custom starwhale version
```
api_version: 1.1
configs:
conda:
channels:
- conda-forge
dependencies:
- pip:
- numpy
- requirements-sw-lock.txt
environment:
arch: noarch
os: ubuntu:20.04
starwhale_version: git+https://github.com/star-whale/starwhale.git@main#subdirectory=client&setup_py=client/setup.py#egg=starwhale
mode: venv
name: simple-test
```
[![asciicast](https://asciinema.org/a/g0kgCrcMMW9R7hqrnozNoCFlC.svg)](https://asciinema.org/a/g0kgCrcMMW9R7hqrnozNoCFlC)
3. Restore In Cloud(base entrypoint):
4. Restore In Standalone(venv)
5. Restore In …
> feat(client): support custom starwhale version in runtime yaml

- server/controller/src/main/java/ai/starwhale/mlops/backup/db/MysqlBackupService.java
- server/controller/src/test/java/ai/starwhale/mlops/backup/db/MysqlBackupServiceTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/MySqlContainerHolder.java
There will occur an SQL syntax error when allowMultiQueries=true, the reason is that the content of dump sql script contains semicolon(;) at the line of end.
> fix(controller): restore SQL syntax error with multiQueries is true

- server/controller/src/main/java/ai/starwhale/mlops/api/DatasetController.java
- server/controller/src/main/java/ai/starwhale/mlops/api/protocol/dataset/dataloader/DataConsumptionRequest.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/dataset/dataloader/DataLoader.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/dataset/dataloader/DataReadManager.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/dataset/dataloader/DataReadRequest.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/dataset/dataloader/dao/SessionDao.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/dataset/dataloader/mapper/DataReadLogMapper.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/dataset/dataloader/mapper/SessionMapper.java
- server/controller/src/main/resources/db/migration/v0_4_0/V0_4_0_020__alter_constraint_for_dataset_read_session.sql
- server/controller/src/test/java/ai/starwhale/mlops/domain/dataset/dataloader/MultiConsumerTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/dataset/dataloader/ReadRangeTest.java
1. tune method to public when annotation with transactional
2. tune the constrain of data read log from dataset version to dataset version id
3. remove isSerial param
> fix(controller): tune data read log table constrain

- client/starwhale/api/_impl/data_store.py
- client/starwhale/api/_impl/evaluation.py
- client/starwhale/api/_impl/wrapper.py
- client/tests/sdk/test_data_store.py
for `huge-tasks` example in standalone:
[![asciicast](https://asciinema.org/a/608835.svg)](https://asciinema.org/a/608835)
- changes:
- add `flush_all` for predict phase
- tune `list_tables` in standalone
> bug(sdk): resolve the 'evaluate phase cannot read tables in standalone' issue

- scripts/client_test/cli_test.py
> bug(ci): fix no Makefile example for e2e

- scripts/e2e_test/start_test.sh
```
python -m datamodel_code_generator --allow-population-by-field-name --disable-timestamp --custom-file-header '# Generated by make gen-model. DO NOT EDIT!' --url http://e2e-20230925.pre.intra.starwhale.ai/v3/api-docs/Api --snake-case-field --output starwhale/base/client/models/models.py
The input file type was determined to be: openapi
This can be specificied explicitly with the `--input-file-type` option.
/starwhale/.venv/lib/python3.8/site-packages/pydantic/main.py:309: UserWarning: Pydantic serializer warnings:
Expected `Union[list[definition-ref], definition-ref, bool]` but got `JsonSchemaObject` - serialized value may not be as expected
return self.__pydantic_serializer__.to_python(
/starwhale/.venv/lib/python3.8/site-packages/pydantic/main.py:309: UserWarning: Pydantic serializer …
```
> fix(e2e): can not find pytest after open api test

- server/controller/src/main/java/ai/starwhale/mlops/domain/job/JobServiceForWeb.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/cache/JobLoader.java
`HotJobsLoader` loads jobs when old instance `READY_DOWN`, but `WriteOperationCare` blocks `jobloader.load` until old instance `DOWN`
> fix(controller): fix job load blocked by write operation

- server/controller/src/main/java/ai/starwhale/mlops/api/DataStoreController.java
- server/controller/src/main/java/ai/starwhale/mlops/datastore/DataStore.java
- server/controller/src/main/java/ai/starwhale/mlops/datastore/DataStoreQueryRequest.java
- server/controller/src/main/java/ai/starwhale/mlops/datastore/DataStoreScanRequest.java
- server/controller/src/main/java/ai/starwhale/mlops/datastore/MemoryTable.java
- server/controller/src/main/java/ai/starwhale/mlops/datastore/impl/MemoryRecord.java
- server/controller/src/main/java/ai/starwhale/mlops/datastore/impl/MemoryTableImpl.java
- server/controller/src/main/protobuf/table_meta.proto
- server/controller/src/main/protobuf/wal.proto
- server/controller/src/test/java/ai/starwhale/mlops/datastore/impl/MemoryTableImplTest.java
> chore(datastore): use revison instead of timestamp as record versions

- server/controller/src/main/java/ai/starwhale/mlops/datastore/DataStore.java
- server/controller/src/main/java/ai/starwhale/mlops/datastore/MemoryTable.java
- server/controller/src/main/java/ai/starwhale/mlops/datastore/impl/MemoryTableImpl.java
- server/controller/src/main/java/ai/starwhale/mlops/datastore/wal/WalManager.java
- server/controller/src/main/java/ai/starwhale/mlops/datastore/wal/WalRemoteFileManager.java
- server/controller/src/main/resources/application.yaml
- server/controller/src/test/java/ai/starwhale/mlops/api/DataStoreControllerTest.java
- server/controller/src/test/java/ai/starwhale/mlops/datastore/DataStoreTest.java
- server/controller/src/test/java/ai/starwhale/mlops/datastore/impl/MemoryTableImplTest.java
> enhance(datastore): allow dumping when updating tables

- client/starwhale/base/client/models/models.py
- server/controller/src/main/java/ai/starwhale/mlops/api/JobController.java
- server/controller/src/main/java/ai/starwhale/mlops/api/protocol/run/RunVo.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/run/RunDao.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/run/RunService.java
- server/controller/src/test/java/ai/starwhale/mlops/api/JobControllerTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/run/RunDaoTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/run/RunServiceTest.java
> feat(controller): add list api for run

- client/starwhale/api/_impl/data_store.py
- client/tests/core/test_dataset.py
- client/tests/sdk/test_data_store.py
- client/tests/sdk/test_track.py
> refactor(datastore): use flat structure to avoid too many sub directories

- client/starwhale/api/_impl/data_store.py
- client/tests/sdk/test_data_store.py
> chore(client): rm lock when dumping table

- server/controller/src/main/java/ai/starwhale/mlops/datastore/DataStore.java
- server/controller/src/test/java/ai/starwhale/mlops/datastore/DataStoreTest.java
> fix(datastore): query limit without deleted rows

- client/starwhale/api/_impl/data_store.py
- client/tests/sdk/test_data_store.py
> fix(datastore): remove dup entry in data store manifest

- client/starwhale/core/dataset/copy.py
- client/starwhale/core/runtime/model.py
- client/starwhale/utils/http.py
- client/tests/core/test_runtime.py
- client/tests/sdk/test_dataset_sdk.py
- issue:  When exceptions occur within the dataset copy threads, the main thread may fail to detect them.
[![asciicast](https://asciinema.org/a/612774.svg)](https://asciinema.org/a/612774)
- remove some useless `sys.exit`
> enhance(dataset): expose exceptions from dataset copy threads

- client/starwhale/api/_impl/data_store.py
> fix(datastore): prevent loading manifest in every insert

- client/scripts/sw-docker-entrypoint
- client/starwhale/base/bundle_copy.py
- client/starwhale/base/store.py
- client/starwhale/core/dataset/tabular.py
- client/starwhale/core/model/cli.py
- client/tests/core/test_model.py
- client/tests/sdk/test_dataset.py
- scripts/client_test/cli_test.py
1. Model run and serve's uriArgs can pass remoteUri, such as model-uri: cloud://server/project/simple-test/version/123456, runtime-uri: cloud://server/project/simple-test/version/654321
2. entrypoint use the unify cmd
> feat(client): support auto copy artifact when run or serve

- client/starwhale/api/_impl/dataset/loader.py
- client/tests/sdk/test_loader.py
> bug(SDK): fix loader consumption missing upload issue

- .github/workflows/e2e-test.yml
- client/starwhale/api/_impl/data_store.py
- for github runner disk, we got 29GB free disk space.
- before:
```
Filesystem     Type   Size  Used Avail Use% Mounted on
/dev/root      ext4    84G   68G   17G  81% /
tmpfs          tmpfs  3.4G  172K  3.4G   1% /dev/shm
tmpfs          tmpfs  1.4G  1.1M  1.4G   1% /run
tmpfs          tmpfs  5.0M     0  5.0M   0% /run/lock
/dev/sdb15     vfat   105M  6.1M   99M   6% /boot/efi
/dev/sda1      ext4    14G  4.1G  9.0G  [31](https://github.com/star-whale/starwhale/actions/runs/6494737098/job/17638393083?pr=2854#step:6:32)% /mnt
tmpfs          tmpfs  693M   12K  693M   1% /run/user/1001
```
- after: 
```
Filesystem     Type   Size  Used Avail Use% Mounted on
/dev/root      ext4    84G   56G   29G  67% /
tmpfs          tmpfs  3.4G  172K  3.4G   1% /dev/shm
tmpfs          tmpfs  1.4G  1.1M  1.4G …
```
> chore(ci): fix e2e no disk space and TableWriter close issue

- server/controller/src/main/resources/db/migration/v0_4_0/V0_4_0_023__add_run_for_task.sql
fix when explicit_defaults_for_timestamp is off, run table could not be created
> fix(controller): fix when explicit_defaults_for_timestamp is off, run table could not be created

- server/controller/src/main/java/ai/starwhale/mlops/schedule/impl/k8s/reporting/PodEventHandler.java
- server/controller/src/test/java/ai/starwhale/mlops/schedule/impl/k8s/PodEventHandlerTest.java
fix jobs that run on k8s are always cancelling when cancel operation is commited
Tests have passed in the cases:
1. When pod is pending
2. When container is creating
3. When container is running
> fix(controller): fix jobs that run on k8s are always cancelling when cancel operation is commited

- server/controller/src/main/java/ai/starwhale/mlops/domain/job/cache/JobLoader.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/job/JobLoaderTest.java
> fix(controller): failed task that is resumed have two runs

- client/starwhale/base/scheduler/task.py
> chore(client): prevent showing the :id: emoji in console

- .github/workflows/client.yaml
- FastApi==0.104.0 requires typing-extensions>=4.8.0
- TensorFlow requires typing-extensions<4.6.0
The unit test breaks when loading fastapi
```
/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/fastapi/exceptions.py:6: in <module>
from typing_extensions import Annotated, Doc  # type: ignore [attr-defined]
E   ImportError: cannot import name 'Doc' from 'typing_extensions' (/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/typing_extensions.py)
```
https://typing-extensions.readthedocs.io/en/latest/index.html#Doc
> New in version 4.8.0: See [PEP 727](https://peps.python.org/pep-0727/).
> chore(client): make unit test works after fastapi upgrade

- client/starwhale/api/_impl/data_store.py
- client/starwhale/base/artifact/base.py
- scripts/client_test/cmds/artifacts_cmd.py
- scripts/client_test/cmds/job_cmd.py
https://github.com/star-whale/starwhale/actions/runs/6562310747/job/17823986723?pr=2875
```
│ /home/runner/work/starwhale/starwhale/scripts/client_test/cli_test.py:294 in │
│                                                                              │
│   291 │   │   │   assert job_id                                              │
│   292 │   │   │   assert len(self.job_api.list())                            │
│   293 │   │   │   eval_info = self.job_api.info(job_id)                      │
│ ❱ 294 │   │   │   assert eval_info                                           │
│   295 │   │   │   assert eval_info["manifest"]["status"] in STATUS_SUCCESS   │
│   296 │   │   │   logger.info("finish run evaluation at standalone.")        │
│   297 │   │   │   job_ids.append(job_id) …
```
> fix(client): make sure evaluation log flushed to storage

- client/starwhale/api/_impl/evaluation/log.py
- client/starwhale/base/data_type.py
- client/tests/sdk/test_evaluation_log.py
- For cifar10 example(spend 90s to finish evaluate phase):
> enhance(SDK):  avoid obtaining all artifact content in advance

- client/starwhale/api/_impl/dataset/builder/mapping_builder.py
- client/starwhale/api/_impl/evaluation/log.py
- client/starwhale/api/_impl/evaluation/pipeline.py
- client/starwhale/base/data_type.py
- client/tests/base/test_data_type.py
- client/tests/sdk/test_dataset.py
- client/tests/web/test_server.py
- before change:
- after change:
no `fp`, `__cache_bytes`, `_signed_uri` fields.
> enhance(client): remove `clear_cache` operation for data types

- server/controller/src/main/java/ai/starwhale/mlops/api/DatasetController.java
- server/controller/src/main/java/ai/starwhale/mlops/api/EvaluationController.java
- server/controller/src/main/java/ai/starwhale/mlops/api/FileStorageController.java
> refactor(controller): unify sign link api for dataset and evaluation

- client/setup.py
- issue: https://github.com/star-whale/starwhale/actions/runs/6608203654/job/17946597295
- ![image](https://github.com/star-whale/starwhale/assets/590748/0d71f1a2-208e-4fdf-9e84-5ca334526f06)
> chore(client): workaround email-validator lib version in python3.7

- client/starwhale/base/artifact/base.py
> bug(client): enqueue None to the abs queue after artifact close operation

- server/controller/src/main/java/ai/starwhale/mlops/datastore/DataStore.java
- server/controller/src/main/java/ai/starwhale/mlops/datastore/MemoryTable.java
- server/controller/src/main/java/ai/starwhale/mlops/datastore/impl/MemoryTableImpl.java
Test case(use 200 thread to scan the same table which has 20w data)
Speed up the scan processing on multi scan request case.
> chore(controller): datastore use read-write lock

- scripts/e2e_test/cases/api_test.sh
- scripts/e2e_test/cases/install_swcli.sh
e2e case could be placed into a seperate file and re-run on Jenkins
> chore(e2e): add jenkins e2e test case example

- server/controller/src/main/java/ai/starwhale/mlops/schedule/impl/k8s/reporting/JobEventHandler.java
- server/controller/src/main/java/ai/starwhale/mlops/schedule/reporting/listener/impl/RunUpdateListenerForStatus.java
- server/controller/src/test/java/ai/starwhale/mlops/schedule/impl/k8s/JobEventHandlerTest.java
- server/controller/src/test/java/ai/starwhale/mlops/schedule/reporting/listener/impl/RunUpdateListenerForStatusTest.java
> chore(controller): ignore k8s job fail reason and refine task finish time

- server/controller/src/main/java/ai/starwhale/mlops/schedule/impl/container/ContainerSpecification.java
- server/controller/src/main/java/ai/starwhale/mlops/schedule/impl/container/impl/OnlineEvaluationContainerSpecification.java
- server/controller/src/main/java/ai/starwhale/mlops/schedule/impl/container/impl/SwCliModelHandlerContainerSpecification.java
```
+ compatibility_check
+ '[' -z '' ']'
+ echo '-->[Error] The following variables are missing: SW_PROJECT_URI or SW_MODEL_URI or SW_RUNTIME_URI, possible reason: your server version is lower, please upgrade the server to at least 0.6.0, now will exit.'
+ exit 1
-->[Error] The following variables are missing: SW_PROJECT_URI or SW_MODEL_URI or SW_RUNTIME_URI, possible reason: your server version is lower, please upgrade the server to at least 0.6.0, now will exit.
```
> fix(controller): make online eval runable

- client/starwhale/api/_impl/data_store.py
- client/starwhale/core/dataset/tabular.py
- client/tests/sdk/test_dataset.py
> chore(client): prefer using builtin list when building dataset

- client/starwhale/core/runtime/model.py
- client/tests/core/test_runtime.py
- example/runtime/pytorch-e2e/runtime-3-10.yaml
- example/runtime/pytorch-e2e/runtime-3-7.yaml
- example/runtime/pytorch-e2e/runtime-3-9.yaml
- scripts/example/runtime.yaml
- scripts/example/runtime_conda.yaml
When we remove 'arch' field in the runtime.yaml, we will meet the following issue:
```bash
(starwhale) liutianwei@host005-bj01 ~/workdir/code/starwhale$ swcli runtime restore code-llama/v0                                                                                                                                                             example/code-llama 
🏌 try to restore python runtime environment: code-llama/v0 ...
⠋ validate environment condition... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% -:--:-- 0:00:00
╭───────────────────────────────────────────────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────────────────────────────────────────────╮
│ /home/liutianwei/.conda/envs/starwhale/bin/swcli:8 in <module> …
```
> bug(runtime): fix runtime.yaml arch field empty issue

- server/controller/src/main/resources/db/migration/v0_4_0/V0_4_0_027__update_character_set_for_desc_column.sql
Support save emoji in project desc and report desc/content column(Current character set = utf8mb3).
> chore(db): change desc column's character set to utf8mb4

- client/starwhale/base/scheduler/task.py
related to 
- #2639
```
[2023-10-30 04:14:51.260742] ✈ change current dir to /root/.starwhale/.cache/model/mnist/jb/jbck7jh2lh75nffokiqhfrpvlljgp6kjz7vzz3sc.swmp/src
[2023-10-30 04:14:51.261419] ⏳ start to run model, handler:serving ...
[2023-10-30 04:14:51.271811] 🏦 runnable handlers:
[2023-10-30 04:14:51.272348]        [0]: mnist.evaluator:MNISTInference.evaluate
[2023-10-30 04:14:51.273061]        [1]: mnist.evaluator:MNISTInference.predict
[2023-10-30 04:14:51.273683]     *  [2]: serving
[2023-10-30 04:14:51.274412] 💡 |INFO| start to execute task: context(step:serving, index:0/1) step(Step: handler-starwhale.core.model.model:None.StandaloneModel._serve_handler, {'name': 'serving', 'show_name': 'virtual handler for model serving', 'module_name': 'starwhale.core.model.model', …
```
> fix(client): model serving handler can not run

- client/starwhale/core/instance/cli.py
- client/starwhale/core/instance/view.py
- console/src/i18n/locales.ts
- console/src/pages/Auth/ClientLogin.tsx
- console/src/routes.tsx
https://github.com/star-whale/starwhale/assets/3217223/72d7d247-4560-4d59-9aaa-e11a2de19654
> enhance(client): support login with browser

- client/starwhale/api/_impl/service.py
- server/controller/src/main/java/ai/starwhale/mlops/common/proxy/WebServerInTask.java
- server/controller/src/main/java/ai/starwhale/mlops/schedule/impl/container/impl/SwCliModelHandlerContainerSpecification.java
- server/controller/src/main/java/ai/starwhale/mlops/schedule/impl/container/impl/SwCliModelHandlerSpecificationFactory.java
- server/controller/src/test/java/ai/starwhale/mlops/common/proxy/WebServerInTaskTest.java
- server/controller/src/test/java/ai/starwhale/mlops/schedule/impl/contianer/SwCliModelHandlerContainerSpecificationTest.java
The latest gradio will fetch `root/info` and `root/theme.css`
The service will be broken without the correct root path configured.
https://github.com/gradio-app/gradio/blob/93d28bc088f7154ecc00f79eb98119f6d4858fe3/client/js/src/client.ts#L803-L806
> enhance(client): online serving handler support the latest gradio

- console/src/domain/job/services/job.ts
- console/src/i18n/locales.ts
- console/src/pages/Job/JobOverviewLayout.tsx
- console/src/pages/Job/JobServings.tsx
- console/src/routes.tsx
online demo: http://jialei.pre.intra.starwhale.ai/projects/1/jobs/26/servings
(It does not need the gradio~=3.15.0, any version is ok)
Note that the broken example preview is a bug of gradio, it does not allow the file access with any part starting with dot.
https://github.com/gradio-app/gradio/blob/ba4c6d9e65138c97062d1757d2a588c4fc449daa/gradio/routes.py#L361-L365
The main branch has removed the logic.
cc @tianweidut @lijing-susan @weijie00123
> enhance(console): support embedded online eval page

- client/starwhale/api/_impl/data_store.py
- client/starwhale/base/artifact/base.py
- client/tests/__init__.py
- client/tests/core/test_eval.py
The DatasetMapperBuilder and Evaluation components automatically register atexit handlers to close related resources. This includes calling TableWriter.close() to close any open table writers and forcing a dump of the LocalDatastore before the program exits.
> chore(client): remove redunancy atexit for data_store

- server/controller/src/main/java/ai/starwhale/mlops/datastore/ColumnSchema.java
- server/controller/src/test/java/ai/starwhale/mlops/datastore/ColumnSchemaTest.java
Fixes: https://cloud.starwhale.cn/projects/398/jobs/949/tasks
```
2023-11-01 08:25:29.940 ERROR [star-whale-controller,c7a5c62f919dc0e9,c7a5c62f919dc0e9] 7 --- [nio-8082-exec-4] a.s.m.c.CommonExceptionHandler           : handleInternalServerError /api/v1/datastore/updateTable
java.lang.NullPointerException: null
at ai.starwhale.mlops.datastore.Wal$ColumnSchema$KeyValuePair$Builder.setKey(Wal.java:923) ~[classes/:0.1.0-SNAPSHOT]
at ai.starwhale.mlops.datastore.ColumnSchema.getDiff(ColumnSchema.java:331) ~[classes/:0.1.0-SNAPSHOT]
at ai.starwhale.mlops.datastore.ColumnSchema.getDiff(ColumnSchema.java:274) ~[classes/:0.1.0-SNAPSHOT]
at ai.starwhale.mlops.datastore.TableSchema.getDiff(TableSchema.java:134) ~[classes/:0.1.0-SNAPSHOT]
at …
```
> fix(datastore): prevent npe while deal with map diff

- console/package.json
- console/packages/starwhale-core/src/datastore/constants.ts
- console/packages/starwhale-core/src/datastore/schemas/TableQueryFilter.ts
- console/packages/starwhale-ui/src/Button/Button.tsx
- console/packages/starwhale-ui/src/GridDatastoreTable/hooks/useDatastoreSummaryColumns.tsx
- console/packages/starwhale-ui/src/IconFont/index.tsx
- console/packages/starwhale-ui/src/Search/components/FieldDatetime.tsx
- console/packages/starwhale-ui/src/Search/schema/FilterBuilder.tsx
- console/packages/starwhale-ui/src/Search/types.ts
- console/src/components/LogViewer/LogViewer.tsx
- console/src/domain/job/components/JobActionGroup.tsx
- console/src/domain/job/components/JobStatusSelector.tsx
- console/src/domain/job/schemas/job.tsx
- console/src/domain/job/services/job.ts
- console/src/domain/job/services/task.ts
- console/src/i18n/locales.ts
- console/src/pages/Job/JobTasks.tsx
- console/src/pages/Job/TaskEventListCard.tsx
- console/src/pages/Job/TaskListCard.tsx
- console/yarn.lock
[job-event-list.webm](https://github.com/star-whale/starwhale/assets/100347187/6c2c8dad-84ab-4247-9e85-c3424f7b855e)
[dEqxsEJRpF](https://github.com/star-whale/starwhale/assets/100347187/34b96c92-9619-4630-808e-748b2231c19f)
> feat(console): support job event with filter/download/fullscreen etc

- client/starwhale/base/client/models/models.py
- client/starwhale/base/uri/resource.py
- scripts/client_test/cli_test.py
- server/controller/src/main/java/ai/starwhale/mlops/api/JobController.java
- server/controller/src/main/java/ai/starwhale/mlops/api/protocol/job/JobRequest.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/dataset/DatasetService.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/JobCreator.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/JobServiceForWeb.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/ModelServingService.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/bo/JobCreateRequest.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/bo/UserJobCreateRequest.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/converter/UserJobConverter.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/po/JobFlattenEntity.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/model/ModelDao.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/project/ProjectService.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/runtime/RuntimeDao.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/runtime/RuntimeService.java
- server/controller/src/test/java/ai/starwhale/mlops/api/JobControllerTest.java
- server/controller/src/test/java/ai/starwhale/mlops/api/protocol/job/JobRequestTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/dataset/DatasetServiceTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/job/JobCreatorTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/job/ModelServingServiceTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/job/converter/UserJobConverterTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/runtime/RuntimeServiceTest.java
Deprecate:
- modelVersionUrl
- runtimeVersionUrl
- datasetVersionUrls
Add:
- modelVersionId
- runtimeVersionId
- datasetVersionIds
TODO: change the console and client with the newly added fields. (This PR has not been modified for backward compatibility testing)
> refactor(controller): deprecate resource version url in job request

- server/controller/src/main/java/ai/starwhale/mlops/domain/project/ProjectService.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/project/ProjectServiceTest.java
> fix(controller): project update to private when pass null by api

- client/starwhale/integrations/huggingface/dataset.py
- client/tests/sdk/test_dataset_sdk.py
Reverts star-whale/starwhale#2945
When datasets >= `2.14.5`, the datasets can return the expected features, so we ignore workaround.
> chore(sdk): revert "enhance(SDK): enhance hf datasets to handle abnormal dataset without config class"

- server/controller/src/main/java/ai/starwhale/mlops/api/protocol/event/EventVo.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/event/EventService.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/event/EventServiceTest.java
> chore(controller): prevent collecting duplicate scheduler events after controller restart

- server/controller/src/main/resources/db/migration/v0_4_0/V0_4_0_030__ft_related.sql
> fix(controller): fix desc not null

- server/controller/src/main/java/ai/starwhale/mlops/domain/job/spec/StepSpec.java
> chore(controller): add dataset info for step spec

- server/controller/src/main/java/ai/starwhale/mlops/domain/dataset/DatasetService.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/ft/FineTuneAppService.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/ft/vo/FineTuneVo.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/ft/FineTuneAppServiceTest.java
> feat(controller): fill SFT list fields

- server/pom.xml
- server/storage-access-layer/pom.xml
- server/storage-access-layer/src/main/java/ai/starwhale/mlops/storage/autofit/ksyun/CompatibleStorageAccessServiceBuilderKsyun.java
- server/storage-access-layer/src/main/java/ai/starwhale/mlops/storage/ksyun/StorageAccessServiceKsyun.java
- server/storage-access-layer/src/test/java/ai/starwhale/mlops/storage/StorageAccessServiceTest.java
> feat(storage): support ksyun

- server/controller/src/main/java/ai/starwhale/mlops/schedule/reporting/listener/impl/RunUpdateListenerForGc.java
- server/controller/src/test/java/ai/starwhale/mlops/schedule/reporting/listener/impl/RunUpdateListenerForGcTest.java
1. run log save doesn't break status report
2. add retry for run log saving
> fix(controller): run log save doesn't break status report

- server/controller/src/main/java/ai/starwhale/mlops/schedule/impl/container/impl/SwCliModelHandlerContainerSpecification.java
- server/controller/src/test/java/ai/starwhale/mlops/schedule/impl/contianer/SwCliModelHandlerContainerSpecificationTest.java
> chore(controller): add env for gradio root when web service uses proxy

- client/starwhale/api/_impl/experiment.py
- client/starwhale/api/_impl/job/handler.py
- client/starwhale/base/client/models/models.py
- client/tests/sdk/test_job_handler.py
- server/controller/src/main/java/ai/starwhale/mlops/api/protocol/job/JobVo.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/converter/JobConverter.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/spec/StepSpec.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/job/JobParserTest.java
> chore(controller): rename for finetune info

- server/controller/src/main/java/ai/starwhale/mlops/datastore/DataStore.java
- server/controller/src/main/java/ai/starwhale/mlops/datastore/DataStoreMigrationRequest.java
- server/controller/src/main/java/ai/starwhale/mlops/datastore/MemoryTable.java
- server/controller/src/main/java/ai/starwhale/mlops/datastore/impl/MemoryTableImpl.java
- server/controller/src/test/java/ai/starwhale/mlops/datastore/DataStoreTest.java
- server/controller/src/test/java/ai/starwhale/mlops/datastore/impl/MemoryTableImplTest.java
> feat(datastore): add table migration

- client/starwhale/api/_impl/experiment.py
- client/tests/sdk/test_job_handler.py
- client/tests/utils/test_venv.py
- example/LLM/bloom/bloom/bloom.py
- example/LLM/bloom/mt0.py
- example/LLM/llama/finetune.py
- example/llm-finetune/models/baichuan2/finetune.py
> enhance(SDK): tune finetune decorator for Dataset type arguments

- client/starwhale/base/data_type.py
- client/tests/base/test_data_type.py
- example/image-segmentation/models/segment-anything/sam.py
- example/stable-diffusion/txt2img-ft/finetune_text_to_image_lora.py
> feat(SDK): support image mode convert for `Image` type 

- server/controller/src/main/java/ai/starwhale/mlops/domain/ft/FineTuneAppService.java
> fix(controller): fix multiple same env on console

- server/controller/src/main/java/ai/starwhale/mlops/api/FineTuneController.java
- server/controller/src/main/java/ai/starwhale/mlops/configuration/security/ProjectNameExtractorDataStoreMixed.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/bundle/BundleAccessor.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/ft/FineTuneAppService.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/ft/FineTuneSpaceDao.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/ft/mapper/FineTuneMapper.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/ft/mapper/FineTuneSpaceMapper.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/ft/po/FineTuneSpaceEntity.java
- server/controller/src/test/java/ai/starwhale/mlops/api/config/ProjectNameExtractorDataStoreMixedTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/ft/FineTuneAppServiceTest.java
1. check whether the space belongs to project.
2. add spaceId constraint for ft info.
> fix(controller): add resource validation for ftspace

- client/starwhale/api/_impl/service/service.py
- client/starwhale/core/model/model.py
- client/tests/sdk/test_service.py
- example/mnist/mnist/custom_evaluator.py
- example/mnist/mnist/evaluator.py
- example/mnist/requirements.txt
Fixes:
- No module found
- gradio `Sketchpad` component init param breaking change
- duplicate API entry point when sw mp build
> fix(example): make mnist mp build works

- server/controller/src/main/java/ai/starwhale/mlops/domain/dataset/DatasetService.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/JobCreator.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/ModelServingService.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/bo/JobCreateRequest.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/bo/UserJobCreateRequest.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/converter/UserJobConverter.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/runtime/RuntimeService.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/job/JobCreatorTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/job/ModelServingServiceTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/job/converter/UserJobConverterTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/runtime/RuntimeServiceTest.java
> refactor(controller): move handler to user job request

- client/starwhale/base/client/models/models.py
- server/controller/src/main/java/ai/starwhale/mlops/api/FineTuneController.java
- server/controller/src/main/java/ai/starwhale/mlops/api/protocol/ft/FineTuneMigrationRequest.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/ft/FineTuneAppService.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/ft/bo/MigrationResult.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/mapper/JobMapper.java
- server/controller/src/main/resources/mapper/JobMapper.xml
- server/controller/src/test/java/ai/starwhale/mlops/domain/ft/FineTuneAppServiceTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/job/mapper/JobMapperTest.java
1. add validation for import and export
2. tune request body
> fix(controller): add validation for eval import/export

- client/starwhale/api/_impl/service/service.py
- client/starwhale/api/_impl/service/types/llm.py
- FastAPI uses return type annotation to generate router, the typing system does not support `|`
- Pydantic v2 optional field should specify `= None` if the construct function does not always contain the field.
- Top K to int
> fix(client): make llm chat service works with pydantic v2

- client/starwhale/api/_impl/job/handler.py
- client/starwhale/api/_impl/service/service.py
- client/starwhale/api/_impl/service/types/llm.py
- client/starwhale/api/_impl/service/types/types.py
- client/starwhale/base/client/models/models.py
- client/starwhale/consts/__init__.py
- client/starwhale/core/model/model.py
- client/tests/core/test_model.py
- client/tests/sdk/test_service.py
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/spec/StepSpec.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/spec/svc/ApiSpec.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/spec/svc/ComponentSpec.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/spec/svc/ServiceSpec.java
Generated job spec in `example/web_handler`:
```yaml
serving:
- concurrency: 1
expose: 8080
extra_kwargs:
search_modules:
- main
func_name: StandaloneModel._serve_handler
module_name: starwhale.core.model.model
name: serving
replicas: 1
service_spec:
apis:
- components:
- component_spec_value_type: INT
name: top_k
- component_spec_value_type: LIST
name: history
- component_spec_value_type: INT
name: max_new_tokens
- component_spec_value_type: FLOAT
name: top_p
- component_spec_value_type: STRING
name: user_input
- component_spec_value_type: FLOAT
name: temperature
inference_type: llm_chat
uri: fake_chat_bot
version: 0.0.2
show_name: virtual handler for model serving
virtual: true
```
> enhance(client): embed model serving spec into job spec

- .github/file-filter.yml
- .github/workflows/client.yaml
> chore(ci): reduce client unit test for pydantic versions

- server/controller/src/main/java/ai/starwhale/mlops/schedule/impl/docker/RunExecutorDockerImpl.java
- server/controller/src/test/java/ai/starwhale/mlops/schedule/impl/docker/RunExecutorDockerTest.java
> feat(controller): add docker dispatched container to a network

- server/controller/src/main/java/ai/starwhale/mlops/api/ObjectStoreController.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/dataset/objectstore/StorageAccessParser.java
- server/controller/src/main/resources/application.yaml
- server/controller/src/test/java/ai/starwhale/mlops/api/ObjectStoreControllerTest.java
- server/storage-access-layer/pom.xml
- server/storage-access-layer/src/main/java/ai/starwhale/mlops/storage/fs/FsConfig.java
- server/storage-access-layer/src/main/java/ai/starwhale/mlops/storage/fs/FsStorageSignature.java
- server/storage-access-layer/src/main/java/ai/starwhale/mlops/storage/fs/StorageAccessServiceFile.java
- server/storage-access-layer/src/test/java/ai/starwhale/mlops/storage/StorageAccessServiceTest.java
- server/storage-access-layer/src/test/java/ai/starwhale/mlops/storage/fs/StorageAccessServiceFileTest.java
1. make file type object store support file type
2. server signed url are sourced from request server name
cc @tianweidut
> fix(controller): storage file service support put method

- client/starwhale/api/_impl/service/service.py
- client/starwhale/api/_impl/service/types/llm.py
- client/starwhale/api/_impl/service/types/text_to_img.py
- client/starwhale/api/_impl/service/types/types.py
- client/tests/data/sdk/service/default_class.py
- client/tests/sdk/test_service.py
- client/tests/sdk/test_types.py
- example/web-handler/main.py
- Add `TextToImage` type
- Change `Message.role(str)` to `bot(bool)`
- Support getting arg spec from the func signature
Content of the web-handler's job.yaml:
```
serving:
- concurrency: 1
expose: 8080
extra_kwargs:
search_modules:
- main
func_name: StandaloneModel._serve_handler
module_name: starwhale.core.model.model
name: serving
replicas: 1
service_spec:
apis:
- components:
- component_spec_value_type: STRING
name: user_input
- component_spec_value_type: LIST
name: history
- componentValueSpecFloat:
defaultVal: 0.5
component_spec_value_type: FLOAT
name: temperature
- componentValueSpecFloat:
defaultVal: 0.9
component_spec_value_type: FLOAT
name: top_p
- componentValueSpecInt:
defaultVal: 100
component_spec_value_type: INT
name: max_new_tokens
inference_type: llm_chat
uri: …
```
> enhance(client): support text to img infer type

- client/starwhale/api/_impl/service/types/text_to_img.py
- client/starwhale/api/service.py
- client/tests/sdk/test_types.py
> chore(client): add scale for text-to-image

- scripts/e2e_test/start_test.sh
> fix(e2e): fix client test failure doesn't populate to parent script

- example/ucf101/ucf101/evaluator.py
ucf example fails for gradio version being 4.7.1
> fix(example): fix ucf101 example error

- client/starwhale/web/data_store.py
- client/starwhale/web/server.py
- client/tests/web/test_server.py
- Use data store built-in list table func.
- Support gzipped response when proxy requests.
> fix(client): make job info --web works

- console/packages/starwhale-core/src/datastore/hooks/useFetchDatastoreAllTables.tsx
`react-query` uses deep equal to do the optimization
we can not change the cached data.
ref:  https://github.com/TanStack/query/blob/dd3f2a718bdeea282ae12db15e1733b48309cc62/src/core/query.ts#L241-L247
```ts
// Use prev data if an isDataEqual function is defined and returns `true`
if (this.options.isDataEqual?.(prevData, data)) {
data = prevData as TData
} else if (this.options.structuralSharing !== false) {
// Structurally share data between prev and new data if needed
data = replaceEqualDeep(prevData, data)
}
```
The response contains many status fields we do not need, use `resp.data` as the dependency.
> fix(console): prevent dead loop when list datastore tables

- example/llm-finetune/models/chatglm3/evaluation.py
> example: update chatglm3 api decorator definition

- client/starwhale/api/_impl/dataset/model.py
- client/starwhale/base/data_type.py
- client/starwhale/integrations/huggingface/dataset.py
- client/tests/base/test_data_type.py
- client/tests/core/test_dataset.py
- client/tests/sdk/test_loader.py
- scripts/example/src/util.py
> feat(sdk): support Image type to accept numpy and pillow image types

- server/controller/src/main/java/ai/starwhale/mlops/api/JobController.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/evaluation/EvaluationService.java
- server/controller/src/test/java/ai/starwhale/mlops/api/JobControllerTest.java
- server/controller/src/test/java/ai/starwhale/mlops/domain/evaluation/EvaluationServiceTest.java
add job create function in EvaluationService and use it explicitly in JobCreateController so that the later refactor could be more clear
> refactor(controller): add job create function in EvaluationService

- client/starwhale/api/_impl/experiment.py
- client/starwhale/api/_impl/model.py
- client/starwhale/core/model/cli.py
- client/starwhale/core/model/model.py
- client/starwhale/core/model/view.py
- client/tests/core/test_model.py
- client/tests/sdk/test_job_handler.py
- client/tests/sdk/test_model.py
> enhance(client): support excludes for model build and finetune decorator

- README.md
- README_ZH.md
> chore(doc): update github readme for framework

- client/starwhale/base/data_type.py
- client/tests/base/test_data_type.py
> enhance(sdk): format Image shape with pillow.Image and numpy.ndarray shape

- client/starwhale/api/_impl/data_store.py
- client/starwhale/core/dataset/copy.py
- client/tests/sdk/test_data_store.py
- client/tests/sdk/test_wrapper.py
> bug(client): fix dataset copy block forever when update table meets exception

- client/starwhale/api/_impl/service/service.py
- console/client/ServingPage.tsx
- console/client/index.html
demo: http://jialei.pre.intra.starwhale.ai/projects/1/jobs/8/servings
Bug reason:  the front end can not access the assets and the APIs if the server is behind the proxy sub-path
I have implemented a simple string replacement on the client side to achieve the effects of injecting global variables and modifying asset paths. 
I did not use templates like Jinja2 because once templates are used, the client/index.html file can no longer be used for debugging and packaging with Vite.
> fix(client): the online evaluation is accessible behind the proxy sub-path

- console/package.json
- console/src/assets/docs/QuickStartNewModelEN.md.ejs
- console/src/assets/docs/QuickStartNewModelZH.md.ejs
- console/src/consts/index.ts
- console/src/utils/index.ts
- console/yarn.lock
> chore(console): use current web host in quickstart for model

- client/starwhale/core/runtime/cli.py
- client/starwhale/core/runtime/process.py
- client/starwhale/utils/process.py
- client/tests/core/test_runtime.py
- client/tests/core/test_runtime_process.py
- client/tests/utils/test_process.py
`swcli runtime activate` + `run command` + `deactivate` three commands -->  `swcli runtime run` 
```bash
❯ swcli runtime run --help
Usage: swcli runtime run [OPTIONS] URI
Run a command in the Starwhale Runtime environment.
For an existed Starwhale runtime, the command will restore and activate the
runtime automatically.
Positional arguments:
URI: Starwhale Runtime URI in the standalone instance
CMD: Executable command name, with additional arguments if needed.
Examples:
swcli runtime run pytorch python -c "import torch;print(torch.__version__)"
swcli -vvv runtime run --cwd example/helloworld helloworld python3 dataset.py
swcli runtime run pytorch --live-stream ipython3
Options:
--cwd TEXT     Working directory
--live-stream  Do not capture stdout/stderr, when the is an interactive cmd, …
```
> feat(client): support `swcli runtime run` command

- client/starwhale/api/_impl/service/types/llm.py
- client/starwhale/api/_impl/service/types/text_to_img.py
- client/starwhale/api/_impl/service/types/types.py
- client/tests/sdk/test_types.py
> refactor(client): use auto generated arg_types

- client/starwhale/core/dataset/cli.py
- client/starwhale/core/dataset/view.py
- client/starwhale/core/model/cli.py
- client/starwhale/core/model/view.py
- client/starwhale/core/runtime/cli.py
- client/starwhale/core/runtime/view.py
```bash
❯ swcli model build . --name helloworld -m evaluation --push http://e2e-20231219.pre.intra.starwhale.ai/project/starwhale
🚧 start to build model bundle...
👷 uri local/project/self/model/helloworld/version/5owht6nm44ftxnf5a7dd65fl4hwp2ywukw2zqd46
📁 workdir: /home/tianwei/.starwhale/.tmp/tmpdbcw6x8f
🦚 copy source code files: . -> /home/tianwei/.starwhale/.tmp/tmpdbcw6x8f/src
📁 source code files size: 237.98KiB
🚀 generate jobs yaml from modules: ('evaluation',) , package rootdir: .
9 out of 9 steps finished ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00 0:00:01
💯 finish gen resource @ /home/tianwei/.starwhale/self/model/helloworld/5o/5owht6nm44ftxnf5a7dd65fl4hwp2ywukw2zqd46.swmp
🚧 start to copy local/project/self/model/helloworld/version/5owht6nm44ftxnf5a7dd65fl4hwp2ywukw2zqd46 …
```
> feat(client): add `--push` argument for model/runtime/dataset build

- server/controller/src/main/java/ai/starwhale/mlops/datastore/ColumnSchema.java
- server/controller/src/main/java/ai/starwhale/mlops/datastore/DataStore.java
- server/controller/src/main/java/ai/starwhale/mlops/datastore/TableSchema.java
- server/controller/src/main/java/ai/starwhale/mlops/datastore/impl/MemoryTableImpl.java
- server/controller/src/main/java/ai/starwhale/mlops/datastore/impl/WalRecordDecoder.java
- server/controller/src/main/java/ai/starwhale/mlops/datastore/impl/WalRecordEncoder.java
- server/controller/src/main/java/ai/starwhale/mlops/datastore/parquet/SwReadSupport.java
- server/controller/src/test/java/ai/starwhale/mlops/api/DataStoreControllerTest.java
- server/controller/src/test/java/ai/starwhale/mlops/datastore/DataStoreTest.java
- server/controller/src/test/java/ai/starwhale/mlops/datastore/TableSchemaTest.java
- server/controller/src/test/java/ai/starwhale/mlops/datastore/impl/MemoryTableImplTest.java
`columnSchemaMap` in the `RecordList` is the latest version of the data
but the query or scan supports the old version of the data,
so the columnSchemaMap is meaningless except for names
we remove the column schema info from the result and other getting function calls except for parquet dump and load
> refactor(controller): remove column schemas dependency

- server/controller/src/main/java/ai/starwhale/mlops/api/protocol/event/EventRequest.java
- server/controller/src/test/java/ai/starwhale/mlops/api/protocol/event/EventRequestTest.java
> fix(controller): the event request could not be deserialized

- client/scripts/sw-docker-entrypoint
- client/starwhale/core/runtime/model.py
- client/starwhale/core/runtime/process.py
- client/starwhale/core/runtime/view.py
- client/starwhale/utils/venv.py
- client/tests/core/test_model.py
- client/tests/core/test_runtime.py
> enhance(client): add env file for restored runtime

- server/controller/src/main/java/ai/starwhale/mlops/schedule/SwTaskSchedulerImpl.java
- server/controller/src/test/java/ai/starwhale/mlops/schedule/SwTaskSchedulerImplTest.java
> chore(controller): add run info to pod env

- client/starwhale/api/_impl/evaluation/pipeline.py
- client/starwhale/api/_impl/experiment.py
- client/starwhale/api/_impl/model.py
- client/starwhale/base/client/api/event.py
- client/starwhale/base/uri/instance.py
- client/starwhale/consts/env.py
- client/starwhale/core/model/model.py
- client/starwhale/core/runtime/model.py
- client/starwhale/core/runtime/process.py
- client/starwhale/utils/event.py
- client/tests/utils/test_event.py
depends on: https://github.com/star-whale/starwhale/pull/3092
> feat(client): support for reporting client events to server/cloud instance

- client/starwhale/web/server.py
https://github.com/star-whale/starwhale/actions/runs/7334596840/job/19971841957?pr=3093
```
mypy . ../example/mnist ../scripts/client_test --show-traceback
starwhale/web/server.py:37:28: error: Argument 2 to "add_route" of "Starlette" has incompatible type "Callable[[], FileResponse]"; expected "Callable[[Request], Union[Awaitable[Response], Response]]"  [arg-type]
starwhale/web/server.py:45:40: error: Argument 2 to "add_exception_handler" of "Starlette" has incompatible type "Callable[[Request, HTTPException], FileResponse]"; expected "Union[Callable[[Request, Exception], Union[Response, Awaitable[Response]]], Callable[[WebSocket, Exception], Awaitable[None]]]"  [arg-type]
Found 2 errors in 1 file (checked 201 source files)
make: *** [Makefile:52: ci-mypy] Error 1
```
> chore(client): fix mypy lint

- client/starwhale/__init__.py
- client/starwhale/api/_impl/argument.py
- client/starwhale/api/_impl/evaluation/__init__.py
- client/starwhale/api/_impl/experiment.py
- client/starwhale/api/_impl/job/handler.py
- client/starwhale/api/job.py
- client/starwhale/base/scheduler/__init__.py
- client/starwhale/base/scheduler/step.py
- client/starwhale/base/scheduler/task.py
- client/starwhale/core/model/cli.py
- client/starwhale/core/model/model.py
- client/starwhale/core/model/view.py
- client/tests/sdk/test_job_handler.py
- client/tests/sdk/test_model.py
- scripts/client_test/cli_test.py
- scripts/example/src/evaluator.py
depends on: https://github.com/star-whale/starwhale/pull/3095
Changes:
- Replace `IntInput, BoolInput...` with Python [typing hint](https://docs.python.org/3/library/typing.html)
- Expand the capability to customize argument mechanisms across all functions, as currently only the @handler decorator supports external arguments.
- Employ dataclasses for bundling arguments, leveraging a feature that is widely adopted in machine learning libraries.
> refactor(client): refactor handler args with `@starwhale.argument` decorator

- client/starwhale/api/_impl/argument.py
- client/starwhale/core/model/cli.py
- client/starwhale/core/model/view.py
- client/tests/sdk/test_argument.py
> feat(client): support echo `@starwhale.argument` help text

- client/starwhale/api/_impl/argument.py
- client/starwhale/consts/__init__.py
- client/starwhale/core/model/model.py
- client/tests/core/test_model.py
- client/tests/sdk/test_argument.py
depends on:  https://github.com/star-whale/starwhale/pull/3101
argument json example:
```json
{
"evaluation:predict_image": {
"evaluation:EvaluationArguments": {
"reshape": {
"name": "reshape",
"opts": [
"--reshape"
],
"type": {
"name": "integer",
"param_type": "INT",
"choices": null,
"case_sensitive": false
},
"required": false,
"multiple": false,
"default": 64,
"help": "reshape image size",
"is_flag": false,
"hidden": false
}
}
}
}
```
> feat(client): dump arguments to json file when model building

- server/controller/src/main/java/ai/starwhale/mlops/configuration/security/JwtTokenFilter.java
- server/controller/src/test/java/ai/starwhale/mlops/configuration/security/JwtTokenFilterTest.java
> chore(controller): prevent access to deleted projects

- server/controller/src/main/java/ai/starwhale/mlops/configuration/security/JwtTokenFilter.java
- server/controller/src/test/java/ai/starwhale/mlops/configuration/security/JwtTokenFilterTest.java
> fix(controller): allow recovering project if project is deleted

- client/starwhale/api/_impl/argument.py
- client/tests/sdk/test_argument.py
> enhance(sdk): support new typing hint example for transformers 4.36.0+

- console/packages/starwhale-ui/src/GridTable/components/TableActions.tsx
- console/packages/starwhale-ui/src/TiptapEditor/index.tsx
> update(console): editor bubble menu invalid when readonly & header dropdown zindex

- server/controller/src/main/java/ai/starwhale/mlops/configuration/security/JwtTokenFilter.java
- server/controller/src/main/java/ai/starwhale/mlops/domain/project/mapper/ProjectMapper.java
> fix(controller): 500 when get deleted project by name

- .github/workflows/e2e-test.yml
- client/starwhale/api/_impl/argument.py
- client/starwhale/api/_impl/job/handler.py
- client/starwhale/base/client/models/models.py
- client/starwhale/base/models/model.py
- client/starwhale/consts/__init__.py
- client/starwhale/core/model/model.py
- client/tests/core/test_model.py
- client/tests/sdk/test_argument.py
- client/tests/sdk/test_job_handler.py
- console/src/api/server/data-contracts.ts
- server/controller/src/main/java/ai/starwhale/mlops/domain/job/spec/StepSpec.java
- server/controller/src/main/java/ai/starwhale/mlops/schedule/impl/container/impl/SwCliModelHandlerContainerSpecification.java
- server/controller/src/test/java/ai/starwhale/mlops/schedule/impl/contianer/SwCliModelHandlerContainerSpecificationTest.java
1. write arguments spec to job.yaml
2. support parse arguments in server side
3. output the failed log in githua action
> feat: add custom args

- console/packages/starwhale-core/src/form/WidgetForm.tsx
- console/packages/starwhale-ui/src/RJSFForm/widgets/CheckboxWidget.tsx
- console/packages/starwhale-ui/src/RJSFForm/widgets/index.ts
- console/src/api/server/data-contracts.ts
- console/src/domain/job/components/FormFieldModel.tsx
- console/src/domain/job/utils.ts
- console/src/i18n/locales.ts
[Screencast from 2024年01月10日 17时03分49秒.webm](https://github.com/star-whale/starwhale/assets/100347187/2027ba8c-438e-4f1e-be98-0dec560fa1de)
> feat(console): support model argument schema

- server/controller/src/main/resources/db/migration/v0_4_0/V0_4_0_034__alter_jobs_type_for_model_version.sql
> chore(controller):update jobs column to longtext which belong to model version 

- client/starwhale/base/view.py
- sort history output
- remove useless code
> enhance(client): sort model/runtime/dataset history list by created_at field

- client/starwhale/base/bundle.py
- client/starwhale/base/models/runtime.py
- client/starwhale/core/dataset/model.py
- client/starwhale/core/model/model.py
- client/starwhale/core/runtime/model.py
- client/tests/core/test_runtime.py
https://github.com/star-whale/starwhale/issues/3104
> enhance(client): make the list(model/runtime/dataset) output of standalone instance consitent with cloud/server style

- example/llm-finetune/models/chatglm3/finetune.py
> example(LLM): change chatglm3 generation_config field type for command line arguments

- client/starwhale/api/_impl/evaluation/pipeline.py
- client/tests/sdk/test_evaluation_pipeline.py
> bug(SDK): fix pipeline batch size return error

- example/llm-leaderboard/leaderboard.md
- example/llm-leaderboard/requirements.txt
- example/llm-leaderboard/src/benchmark/cmmlu.py
- example/llm-leaderboard/src/evaluation.py
- example/llm-leaderboard/src/llm/__init__.py
- example/llm-leaderboard/src/llm/base.py
- example/llm-leaderboard/src/llm/mistral.py
example for some new areas:
- using `vLLM`
- using predict batch
example: http://e2e-20240201.pre.intra.starwhale.ai/projects/1/jobs/21/tasks
> example(LLM): add mistral 7b+vllm example for llm-leaderboard

- .github/workflows/client.yml
> chore(ci): back to macos-13 for client test passed

- .github/workflows/client.yml
- client/setup.py
- client/starwhale/api/_impl/data_store.py
- client/starwhale/mngt/__init__.py
- client/tests/sdk/test_evaluation_pipeline.py
> bug(client): fix tenacity version for ModuleNotFoundError issue
